### ISSUE TITLE
Handle new unformatted HDD

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#10]
Currently you have to use a partition manager to format your disk (erase all data) to create at least one partition with ext4 filesystem.
Having just filesystem without partition table will not work.
It is a Linux file system, so you need to use Linux based tools. GParted Live USB is a good option for that.
https://github.com/syncloud/platform/wiki/External-Disk
Always check what you are erasing/formatting to not erase your primary disk!

**Comment by cyberb** [comment]
New format button added for each inactive disk on storage screen with corresponding confirmation dialog.

![storage](https://user-images.githubusercontent.com/885528/44622959-0f122c00-a8bb-11e8-8085-80ef27a57244.png)

![format-dialog](https://user-images.githubusercontent.com/885528/44622964-336e0880-a8bb-11e8-802e-b368eaeb1570.png)
