### ISSUE TITLE
Device send logs doesn't work before activation

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#104]
1. Plug in device
2. Go to IP:81 web page
3. Click Send logs

No logs sent - redirected to Error page

**Comment by cyberb** [comment]
Right, I thought about it as well.
Maybe we should change send logs button to 'send logs if fails' checkbox?
Then there will be no confusion.

**Comment by vsapronov** [comment]
It's not about confusion. It just doesn't work.

Try steps and try to get logs any way.

I guess it's because the device is not activated, and there's no token...

On Saturday, January 16, 2016, Boris Rybalkin <notifications@github.com>
wrote:

> Right, I thought about it as well.
> Maybe we should change send logs button to 'send logs if fails' checkbox?
> Then there will be no confusion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/104#issuecomment-172263082>.
>


-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
Yes, it is not working, because I am stupid.
So I am offering different implementation.
Otherwise I will have to force user to specify all fields or just redirect login/pass for send logs button.

**Comment by vsapronov** [comment]
May be we need a form for sending logs where we ask for user email/password only if we don't have them.
Otherwise it's better not to show button at all if we don't have credentials...

**Comment by cyberb** [comment]
![tmp_5047-screenshot_2016-02-11-22-09-43-480x8531875360136](https://cloud.githubusercontent.com/assets/885528/12992552/08c32f62-d10d-11e5-94dc-71d8a96e9258.png)

![tmp_5047-screenshot_2016-02-11-22-09-59-480x854305718204](https://cloud.githubusercontent.com/assets/885528/12992565/1a71d8ee-d10d-11e5-9e1a-5e510c757f2e.png)
