### ISSUE TITLE
Add apps logs to report

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#110]
We need some systematic way to add log files to the  device log report.

We already had some case when we weren't able to understand a user's issue because we don't receive ownCloud logs in report.

One option would be:
1. Store file with list of log file paths in platform. All files from the list will be sent in logs report from device.
2. Expose platform API call to add log files to the list, like: add_log(path).
3. Each app adds its logs to the list in post_instal. It's not needed to remove them - they can stay forever - more logs is always better then less logs.

**Comment by cyberb** [comment]
What is wrong with /opt/data/platform/log/*.log
Maybe also /opt/app/[app]/log/*.log
And /var/log/sam.log

**Comment by vsapronov** [comment]
Nothing is wrong. Does it work already? I haven't checked latest releases...

**Comment by cyberb** [comment]
I would just fix locations of all needed logs to be in data/app/logs/*.log

Another reason is we could than manage log rotation centrally.
