### ISSUE TITLE
ownCloud install issue

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#115]
Platform v152

internal rest log:

socket/fd (probably the client disconnected) !!!
Sat Feb  6 21:51:45 2016 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 296] during GET /server/rest/app?app_id=owncloud (192.168.1.55)
IOError: write error

**Comment by vsapronov** [comment]
Is this reproducable on latest platform versions? v152 is pretty old...

**Comment by cyberb** [comment]
That came from a user who never replied, this is I think was coming from 0.9 release, never seen it myself. Not sure we need to do anything without feed back.

**Comment by cyberb** [comment]
feedback never arrived, closing
