### ISSUE TITLE
Opening https devices doesn't work

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#118]
Android client v1.38 hangs when refreshing the list of devices by pulling down the list. It does that not every time, try severely refreshes.
After that even device open hangs.
Maybe it is related to https devices.

**Comment by vsapronov** [comment]
Could it be related to your network? Send Android logs please anyways. Who complains without logs at all?!

**Comment by cyberb** [comment]
I will send logs, I cannot reproduce outside of my home network and also I think it is related to issue #119 I am having right now, as cannot even open device from mobile.

**Comment by vsapronov** [comment]
When you say "it hangs" what exactly do you mean? Is progress circle
spinning during that "hang"?

We have one minute timeout for all web requests. So if your phone is unable
to get response in one minute you will see spinning progress for a minute.
Is it what's happening?

On Tuesday, February 16, 2016, Boris Rybalkin <notifications@github.com>
wrote:

> I will send logs, I cannot reproduce outside of my home network and also I
> think it is related to issue #119
> <https://github.com/syncloud/platform/issues/119> I am having right now,
> as cannot even open device from mobile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/118#issuecomment-184818753>.
>


-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
Yes, 1 minute timeout is happening.

**Comment by vsapronov** [comment]
Is progress spinning?

On Tuesday, February 16, 2016, Boris Rybalkin <notifications@github.com>
wrote:

> Yes, 1 minute timeout is happening.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/118#issuecomment-184846746>.
>


-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
Yes

**Comment by vsapronov** [comment]
OK, then it's not a "hang". And I doubt that it is something to do with
Android unless you think otherwise. I was worried that Android App is
broken... Let's investigate though, send longs...

On Tuesday, February 16, 2016, Boris Rybalkin <notifications@github.com>
wrote:

> Yes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/118#issuecomment-184850172>.
>


-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
After fixing #119 cannot reproduce 1min timeout.
But now I cannot open device, looks like https is not trusted by default.
Sent logs.

**Comment by cyberb** [comment]
I have probably forgotten they we are not allowing to connect to device when it is in internal mode as android message says. Reactivation is actually switches it to internal mode (confused me a little)

After enabling external mode works as expected.

We can close this for now.

**Comment by vsapronov** [comment]
OK, nobody checked opening https devices on both iOS and Android. This is certainly a bug.
