### ISSUE TITLE
Two devices take the same external port mapping

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#119]
Potentially port list/add bug. 
Probably port probe should not just check for 200/OK but also make sure it connects to itself and not some other Syncloud device. We could use some unique id in ping reply for validation.

**Comment by vsapronov** [comment]
Improving probe is a good idea. However I'm sure there's a bug in how we select ports:
See this line: https://github.com/syncloud/platform/blob/master/src/syncloud_platform/insider/upnpc.py#L100
There we get existing_ports (external) to exclude them from new port mapping trials. The problems is that those method returns only external ports related to the device IP, therefore it won't return port that is used by other device. And thefore it won't filtered during new mapping port selection.

**Comment by cyberb** [comment]
Should be fixed by https://github.com/syncloud/platform/commit/f488175812115350414630dfe3b5e6d1ba2da577
