### ISSUE TITLE
Delayed sync after http/https change

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#122]
Steps to reproduce:
Open activated device
Change access http/https
Check redirect web or smartphone client
There's old access still shown till the next sync which is 5 mins away...

**Comment by cyberb** [comment]
Redirect is full of errors.
Also on platform side we are not properly handling 200 codes but with json success false, potentially recent switch from 500 to 200 for errors on redirect side.

Probably requests are different cron sync and from ad-hoc sync, but we are making redirect call on protocol change.

**Comment by vsapronov** [comment]
Do you mean redirect logs are full of errors? .info or .it? In any case
that's fine - we have non-backward compatible version of redirect to
release and it's deployed already on .info. When old device syncs to new
redirect or new device syncs to old redirect the error will happen...

Requests from cron and ad-hoc can't be different - it's the same code,
isn't it? If something is wrong then it's more likelly wrong with ad-hoc
call, cause in max 5 mins after access change update will be done on
redirect. That means cron sync works. I guess ad-hoc sync is easier to
log/debug.

On Thu, Feb 18, 2016 at 1:38 PM, Boris Rybalkin <notifications@github.com>
wrote:

> Redirect is full of errors.
> Also on platform side we are not properly handling 200 codes but with json
> success false, potentially recent switch from 500 to 200 for errors on
> redirect side.
>
> Probably requests are different cron sync and from ad-hoc sync, but we are
> making redirect call on protocol change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/122#issuecomment-185852082>.
>



-- 

Vladimir Sapronov
