### ISSUE TITLE
Setup rootfs build on home server

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#13]
_From @vsapronov on March 31, 2015 15:50_

null

_Copied from original issue: syncloud/image-ci#7_

**Comment by vsapronov** [comment]
@cyberb Should I start from trying this: https://github.com/syncloud/rootfs?

**Comment by vsapronov** [comment]
@cyberb So building rootfs using qemu is very slow. About 10 hours on our server and even longer on ARM (checked on cubitruck). Can we try this approach on arm with chroot?

**Comment by cyberb** [comment]
Right, I am thinking about docker now. chroot has some problems as it is
not properly isolated from the host. But docjer is not even available in
Jessie. So I am trying Ubuntu core again as they have it packaged for some
time already.

**Comment by vsapronov** [comment]
Let me know if you'll need to do anything on the home server. I'm assigning
this to none, since I'm not working on this anymore...

On Wed, Apr 15, 2015 at 9:39 AM, Boris Rybalkin <notifications@github.com>
wrote:

> Right, I am thinking about docker now. chroot has some problems as it is
> not properly isolated from the host. But docjer is not even available in
> Jessie. So I am trying Ubuntu core again as they have it packaged for some
> time already.
> On Apr 15, 2015 13:46, "Vladimir Sapronov" <notifications@github.com>
> wrote:
>
> > @cyberb <https://github.com/cyberb> So building rootfs using qemu is
> very
> > slow. About 10 hours on our server and even longer on ARM (checked on
> > cubitruck). Can we try this approach on arm with chroot?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/syncloud/platform/issues/13#issuecomment-93377070>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/13#issuecomment-93404547>.
>



-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
I was able to produce cubietruck ubuntu core base image and it boots fine!
It takes truck base image and merges-in ubuntu core rootfs
https://github.com/syncloud/rootfs/blob/master/ubuntu-core/merge.sh

So far I am not able to create image from scratch (parted/mkfs) and merge-in truck kernel/modules. It does not boot. I think parted is not good at this :) probably I should try fdisk.

So we can change our build procedure to:
1. Take official ubuntu core rootfs
2. Build syncloud on it using our chroot approach
3. Merge rootfs into board image

Ideally one arm builds rootfs others just merge it into their images, but that requires some board synchronization (which would be really cool! using some zookeeper tool) 

There is one more problem, rpi 1 (arm v6) is not compatible with ubuntu core (arm v7) so we can also add debian rootfs for example.

**Comment by cyberb** [comment]
Ubuntu core 15.04 also worked fine, it has systemd enabled by default.
15.04 should be released on April 23rd.
Will try install syncloud on it.

**Comment by vsapronov** [comment]
Cool!

The parted tool is junk. This is why I changed it to fdisk even for resize...

It sounds that we need to merge rootfs with kernel/modules on the particular board. But why? If these are just partitions operations and copy files here and there then it seems to be possible to do just on PC...

RPi: Well having build for 2 images is anyway much better then 5 (and potentially more).

**Comment by cyberb** [comment]
Right, merge can happen on any arch, I am just still testing the result, so it does more then it should.
Also bad news on Ubuntu core, looks like some apt installs brings systemd updates which brake it. Tried daily rootfs, does not even boot. Maybe we should wait for the release and try again.
Meanwhile I will try Debian rootfs.

**Comment by cyberb** [comment]
Good news! Debian armhf rootfs worked fine and I even integrated new cubietruck debian base image into the build (complete test).
Tested the build, all is good, (activation, owncloud, image-ci).
So it is time to split building into rootfs manipulation and board specific image creation (fdisk, kernel, modules, board specific settings).
Maybe we should extract boot partitions (kernel/bootloaders) + kernel modules (from base rootfs) and keep them separate so we can merge them.
Also I am not sure if we can use same partition layout for all the boards.

**Comment by vsapronov** [comment]
Let's script extraction of boot partition and kernel modules. And upload
these extracted parts to S3.

All boards have the same partitions layout for now: 1 - boot, 2 - rootfs.

**Comment by cyberb** [comment]
Layout is a bit more complex than this :)
http://linux-sunxi.org/Bootable_SD_card#SD_Card_Layout

That is why it does not boot if you just copy files from first partition.
Playing with dd now.

**Comment by cyberb** [comment]
Was able to create image and boot using fdisk, bootloader, boot partition and kernel modules.
https://github.com/syncloud/rootfs/blob/master/debian/create.sh

Next step is to create extractor and try this approach on RPi.

**Comment by cyberb** [comment]
Have fully working extract, rootfs, merge scripts.
Cubietruck us good.

Raspberry pi 1 as predicted is a mess, was fooled by package names armhf (looks like Debian arm v7), but it appeared that they took them and ported to arm v6 without changing arch name.
Looks like their port is faster than official Debian arm v6 duild.
So I can extract rootfs from rasbian and have separate rootfs build for rpi1.
Rpi2 should work from current build, could you try on home server /syncloud/image/syncloud - raspberry.img?
