### ISSUE TITLE
VoIP

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#133]
I want to have personal telephony so people can call me from my device web page (social page/diaspora) and not to depend on isolated networks like Skype/Viber/Hangouts/WatsApp 

Features:
1. Making call to user from users device web page with a browser, probably not restricted in the beginning (call me button).
2. Receiving calls with an app (sipdroid)
3. Receiving calls through land-line (if connected) to mobile
4. Receiving calls through GSM (if connected) to mobile
5. Installing pre-configured mobile voice app from the device web.
6. Making calls to other users (device to device calls)
7. Making calls to another networks (Skype, Viber, ...) if possible.

I think it is possible with Asterisk server + Sip clients

**Comment by cyberb** [comment]
I want to have personal telephony so people can call me from my device web page (social page/diaspora) and not to depend on isolated networks like Skype/Viber/Hangouts/WatsApp 

Features:
1. Making call to user from users device web page with a browser, probably not restricted in the beginning (call me button).
2. Receiving calls with an app (sipdroid)
3. Receiving calls through land-line (if connected) to mobile
4. Receiving calls through GSM (if connected) to mobile
5. Installing pre-configured mobile voice app from the device web.
6. Making calls to other users (device to device calls)
7. Making calls to another networks (Skype, Viber, ...) if possible.

I think it is possible with Asterisk server + Sip clients

**Comment by cyberb** [comment]
There are existing solutions like, rocket chat, should start there.

**Comment by klmhsb42** [comment]
#446

**Comment by klmhsb42** [comment]
Alternatives to Asterisk:

- http://www.sipfoundry.org/
- http://www.yate.ro/
- https://freeswitch.com/
- https://www.gnu.org/software/bayonne/bayonne.html
