### ISSUE TITLE
Supprt ODROID C2

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#136]

**Comment by vsapronov** [comment]
ODROID-C2 works great. A bit slow compared to XU models, but faster than RPis. And C2 doesn't have fan which makes it my favorite choice and I would like to move our prebuilt dev boards on it. The selection of cases is a bit disappointing, but we can live with it.

Here's one general issue not specific to ODROID-C2.
For every new board support we need to modify platform code. The change is to make platform code to detect name of the device and provide it for discovery and also for redirect. It seems to me that writing file with the board name during image build still makes sense. 
If you are strongly against building 2 different images for XU3 and XU4. We could just have a family name instead of detailed name, smth like "ODROID-XU" and "Raspberry Pi" - without saying is it XU3 or XU4 or RPi2 or RPi3. 
Just writing such file would make our platform code significantly cleaner:  almost the whole syncloud_platform.board namespace will go away and there's no need in lsusb then...

What do you think?

**Comment by cyberb** [comment]
I like family names!
sure lets remove the code.

On Wed, May 4, 2016 at 9:00 PM, Vladimir Sapronov <notifications@github.com>
wrote:

> ODROID-C2 works great. A bit slow compared to XU models, but faster than
> RPis. And C2 doesn't have fan which makes it my favorite choice and I would
> like to move our prebuilt dev boards on it. The selection of cases is a bit
> disappointing, but we can live with it.
>
> Here's one general issue not specific to ODROID-C2.
> For every new board support we need to modify platform code. The change is
> to make platform code to detect name of the device and provide it for
> discovery and also for redirect. It seems to me that writing file with the
> board name during image build still makes sense.
> If you are strongly against building 2 different images for XU3 and XU4.
> We could just have a family name instead of detailed name, smth like
> "ODROID-XU" and "Raspberry Pi" - without saying is it XU3 or XU4 or RPi2 or
> RPi3.
> Just writing such file would make our platform code significantly cleaner:
> almost the whole syncloud_platform.board namespace will go away and there's
> no need in lsusb then...
>
> What do you think?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/136#issuecomment-216984154>
>



-- 
Boris Rybalkin
ribalkin@gmail.com
