### ISSUE TITLE
sometimes unable to open settings, shows error page

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#137]
Platform: v541
Image: 16.04

Found in /opt/data/platform/log/uwsgi_public.log

````
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1475, in full_dispatch_request
[pid: 1273|app: 0|req: 55/235] 192.168.0.106 () {50 vars in 993 bytes} [Sat Apr  2 22:41:45 2016] GET /server/rest/user => generated 75 bytes in 13 msecs (HTTP/1.1 200) 3 headers in 343 bytes (1 switches on core 1)
    rv = self.dispatch_request()
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1461, in dispatch_request
[pid: 1281|app: 0|req: 109/236] 192.168.0.106 () {50 vars in 1019 bytes} [Sat Apr  2 22:41:45 2016] GET /server/rest/settings/protocol => generated 20 bytes in 21 msecs (HTTP/1.1 200) 3 headers in 343 bytes (1 switches on core 1)
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/platform/lib/Flask-Login-0.2.11/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/opt/app/platform/lib/syncloud-platform-541/syncloud_platform/rest/public.py", line 146, in external_access
    return jsonify(external_access=public.external_access()), 200
  File "/opt/app/platform/lib/syncloud-platform-541/syncloud_platform/rest/facade/public.py", line 54, in external_access
    return self.user_platform_config.get_external_access()
  File "/opt/app/platform/lib/syncloud-platform-541/syncloud_platform/config/config.py", line 194, in get_external_access
    external_access = self.parser.getboolean('platform', 'external_access')
  File "/opt/app/platform/python/lib/python2.7/ConfigParser.py", line 369, in getboolean
    if v.lower() not in self._boolean_states:
AttributeError: 'list' object has no attribute 'lower'
------------------------------------------------------------
````

**Comment by vsapronov** [comment]
Need more logs

**Comment by vsapronov** [comment]
Need to check value of external_access (every time it's retrieved the value is logged).
Also need to check if cron sync is working at the same time (may be it's writing config).
The config file itself would be useful.

**Comment by cyberb** [comment]
I think we will need to do synchronisation around critical sections between processes, either by using some cross process locks (not really available out of box in Python SDK) or by extracting a worker process and sending it tasks so it will have a queue and will be single threaded. It would also simplify app installation tasks as well. 
Something like Twisted is really popular in Python world. I think it is not a lot of code change, just instead of calling some function you need to send a  signal. Same code will be used on the worker side.

**Comment by cyberb** [comment]
Maybe Twisted is too much for us (after reading) and something simpler like Redis would be easier. Clients creating records, worker reading and doing the work. Clients can also check Redis if their task is running to inform UI and not send new one for example.

**Comment by vsapronov** [comment]
Can we confirm first that it's sync? Give me logs...

I'm not even sure that sync is writing that config at all. Also don't you
think that if we move config that is concurrently written/read to some
lightweight db then it solve all problems with concurrency (again if this
is concurrency at all).

On Sunday, April 3, 2016, Boris Rybalkin <notifications@github.com> wrote:

> I think we will need to do synchronisation around critical sections
> between processes, either by using some cross process locks (not really
> available out of box in Python SDK) or by extracting a worker process and
> sending it tasks so it will have a queue and will be single threaded. It
> would also simplify app installation tasks as well.
> Something like Twisted is really popular in Python world. I think it is
> not a lot of code change, just instead of calling some function you need to
> send a signal. Same code will be used on the worker side.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/137#issuecomment-204934391>
>


-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
I am not talking about moving this config to db, I am talking to move
concurrent work to a single worker process. we should discuss this.

On Sun, Apr 3, 2016 at 1:26 PM, Vladimir Sapronov <notifications@github.com>
wrote:

> Can we confirm first that it's sync? Give me logs...
>
> I'm not even sure that sync is writing that config at all. Also don't you
> think that if we move config that is concurrently written/read to some
> lightweight db then it solve all problems with concurrency (again if this
> is concurrency at all).
>
> On Sunday, April 3, 2016, Boris Rybalkin <notifications@github.com> wrote:
>
> > I think we will need to do synchronisation around critical sections
> > between processes, either by using some cross process locks (not really
> > available out of box in Python SDK) or by extracting a worker process and
> > sending it tasks so it will have a queue and will be single threaded. It
> > would also simplify app installation tasks as well.
> > Something like Twisted is really popular in Python world. I think it is
> > not a lot of code change, just instead of calling some function you need
> to
> > send a signal. Same code will be used on the worker side.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/syncloud/platform/issues/137#issuecomment-204934391>
> >
>
>
> --
>
> Vladimir Sapronov
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/137#issuecomment-204958728>
>



-- 
Boris Rybalkin
ribalkin@gmail.com

**Comment by cyberb** [comment]
I care less about proving that this issue was because of cron writing a
file at the same time, but think about this in general. Cron may sync ports
at the same time as you are changing ports from UI by installing/removing
apps or enabling disabling external access. Another thing you can break
things by installing apps in parallel from UI. I think "worker process" is
a solution. Redis may be just one of the ways to implement a queue for the
worker. Then if queue is more or less easy to read it is possible to inform
UI on what is going on right now, why you cannot install new app while
another is being installed. Cron is also may just check if sync is running
then no need to run another one.

On Sun, Apr 3, 2016 at 1:36 PM, Boris Rybalkin <ribalkin@gmail.com> wrote:

> I am not talking about moving this config to db, I am talking to move
> concurrent work to a single worker process. we should discuss this.
>
> On Sun, Apr 3, 2016 at 1:26 PM, Vladimir Sapronov <
> notifications@github.com> wrote:
>
>> Can we confirm first that it's sync? Give me logs...
>>
>> I'm not even sure that sync is writing that config at all. Also don't you
>> think that if we move config that is concurrently written/read to some
>> lightweight db then it solve all problems with concurrency (again if this
>> is concurrency at all).
>>
>> On Sunday, April 3, 2016, Boris Rybalkin <notifications@github.com>
>> wrote:
>>
>> > I think we will need to do synchronisation around critical sections
>> > between processes, either by using some cross process locks (not really
>> > available out of box in Python SDK) or by extracting a worker process
>> and
>> > sending it tasks so it will have a queue and will be single threaded. It
>> > would also simplify app installation tasks as well.
>> > Something like Twisted is really popular in Python world. I think it is
>> > not a lot of code change, just instead of calling some function you
>> need to
>> > send a signal. Same code will be used on the worker side.
>> >
>> > —
>> > You are receiving this because you commented.
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/syncloud/platform/issues/137#issuecomment-204934391
>> >
>> >
>>
>>
>> --
>>
>> Vladimir Sapronov
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/syncloud/platform/issues/137#issuecomment-204958728>
>>
>
>
>
> --
> Boris Rybalkin
> ribalkin@gmail.com
>



-- 
Boris Rybalkin
ribalkin@gmail.com

**Comment by vsapronov** [comment]
In general I agree with you.

Though implementing working processes to solve issue that we don't fully
understand is classics of overengeneering.

I think concurrent storage for configs is much easier to implement and
support.

Let's think more and discuss on the phone.

On Sunday, April 3, 2016, Boris Rybalkin <notifications@github.com> wrote:

> I care less about proving that this issue was because of cron writing a
> file at the same time, but think about this in general. Cron may sync ports
> at the same time as you are changing ports from UI by installing/removing
> apps or enabling disabling external access. Another thing you can break
> things by installing apps in parallel from UI. I think "worker process" is
> a solution. Redis may be just one of the ways to implement a queue for the
> worker. Then if queue is more or less easy to read it is possible to inform
> UI on what is going on right now, why you cannot install new app while
> another is being installed. Cron is also may just check if sync is running
> then no need to run another one.
>
> On Sun, Apr 3, 2016 at 1:36 PM, Boris Rybalkin <ribalkin@gmail.com
> <javascript:_e(%7B%7D,'cvml','ribalkin@gmail.com');>> wrote:
>
> > I am not talking about moving this config to db, I am talking to move
> > concurrent work to a single worker process. we should discuss this.
> >
> > On Sun, Apr 3, 2016 at 1:26 PM, Vladimir Sapronov <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> >> Can we confirm first that it's sync? Give me logs...
> >>
> >> I'm not even sure that sync is writing that config at all. Also don't
> you
> >> think that if we move config that is concurrently written/read to some
> >> lightweight db then it solve all problems with concurrency (again if
> this
> >> is concurrency at all).
> >>
> >> On Sunday, April 3, 2016, Boris Rybalkin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> >> wrote:
> >>
> >> > I think we will need to do synchronisation around critical sections
> >> > between processes, either by using some cross process locks (not
> really
> >> > available out of box in Python SDK) or by extracting a worker process
> >> and
> >> > sending it tasks so it will have a queue and will be single threaded.
> It
> >> > would also simplify app installation tasks as well.
> >> > Something like Twisted is really popular in Python world. I think it
> is
> >> > not a lot of code change, just instead of calling some function you
> >> need to
> >> > send a signal. Same code will be used on the worker side.
> >> >
> >> > —
> >> > You are receiving this because you commented.
> >> > Reply to this email directly or view it on GitHub
> >> > <
> https://github.com/syncloud/platform/issues/137#issuecomment-204934391
> >> >
> >> >
> >>
> >>
> >> --
> >>
> >> Vladimir Sapronov
> >>
> >> —
> >> You are receiving this because you authored the thread.
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/syncloud/platform/issues/137#issuecomment-204958728
> >
> >>
> >
> >
> >
> > --
> > Boris Rybalkin
> > ribalkin@gmail.com <javascript:_e(%7B%7D,'cvml','ribalkin@gmail.com');>
> >
>
>
>
> --
> Boris Rybalkin
> ribalkin@gmail.com <javascript:_e(%7B%7D,'cvml','ribalkin@gmail.com');>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/137#issuecomment-204966595>
>


-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
Looks like that was simply trying to call ajax callback after navigating away from the page (xhr.status = 0)

Fix is to add status === 0 handler to our error handler:
````
function onError(xhr, textStatus, errorThrown) {
    if (xhr.status === 401) {
        window.location.href = "/login.html";
    } else if (xhr.status === 0) { // <---------------------------------- FIX IS HERE
        console.log('user has navigated away from the page');
    } else {
        console.log('onError xhr: ' + xhr);
        window.location.href = "/error.html";
    }
}

function on_error(status, error) {
    if (status === 401) {
        window.location.href = "/login.html";
    } else if (status === 0) { // <-------------------------------------- FIX IS HERE
        console.log('user has navigated away from the page'); 
    } else {
        console.log('on_error status: ' + status + ', error: ' + error);
        window.location.href = "/error.html";
    }
}
````
