### ISSUE TITLE
Better build server

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#14]
_From @cyberb on March 27, 2015 21:30_

For example:
http://docs.buildbot.net/current/tutorial/firstrun.html

_Copied from original issue: syncloud/image-ci#6_

**Comment by vsapronov** [comment]
_From @cyberb on March 30, 2015 23:15_

[IDEA]
Ideally we have network of independent builders, each shows all builds in the network.
Distributed coordination can be done with kazoo/zookeeper

**Comment by cyberb** [comment]
We have TC and it is fine, closing this one.
