### ISSUE TITLE
Domain delete

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#15]
_From @vsapronov on March 17, 2015 11:49_

There should be a way to delete domain from web UI.

_Copied from original issue: syncloud/redirect#19_

**Comment by vsapronov** [comment]
@cyberb I have done this feature. Could you please check it quickly at .info. I want to push it to .it right away, since there're no big changes - just a front-end.

**Comment by cyberb** [comment]
Works fine in prod! :)
