### ISSUE TITLE
Android TV is reconized as UPnP router

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#156]
This prevents UPnP port drilling.

**Comment by vsapronov** [comment]
vsapronov@XPS13-Ubuntu:~$ upnpc -l
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.99.35:8008/ssdp/device-desc.xml
 st: upnp:rootdevice

UPnP device found. Is it an IGD ? : http://192.168.99.35:8008/
Trying to continue anyway
Local LAN ip address : 192.168.99.58
GetConnectionTypeInfo failed.
GetStatusInfo failed.
  Time started : Tue Jun 28 12:47:57 2016
GetLinkLayerMaxBitRates failed.
GetExternalIPAddress failed. (errorcode=-3)
 i protocol exPort->inAddr:inPort description remoteHost leaseTime
GetGenericPortMappingEntry() returned -3 (UnknownError)

**Comment by vsapronov** [comment]
Happens only if UPnP on router doesn't work (by any reason). Hard to reproduce.

**Comment by cyberb** [comment]
Similar issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=725288

**Comment by cyberb** [comment]
There is a manual port mapping option which should help in this kind of situation.
Reopen if needed.
