### ISSUE TITLE
Turn off HTTPS doesn't work

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#158]
Steps to reproduce:
1. Switch device to HTTPS
2. Switch device back to HTTP

All http url requests to device redirected to https.

Logs from device odroid-c2 sent on July 8th 13:29 (US Eastern time)

**Comment by cyberb** [comment]
Strange, worked fine on my docker, will test on a device after getting more sd cards.

**Comment by cyberb** [comment]
Got it:
https://github.com/syncloud/platform/blob/master/config/nginx/https.conf#L6

It is a feature we have enabled, probably we can disable it for now.
https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
