### ISSUE TITLE
Optimize app install time

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#166]
Downloading and unpacking takes significant part of app installation time. This could be done ahead of time (before user clicks upgrade) by some schedule. Files could be stored in some cache on the device.

**Comment by vsapronov** [comment]
I've got new idea. When we do release we can put all apps into sam cache somewhere. This cache will be used if there were no updates of the app (99.9%). We can provide both images: no apps (smaller size of the image), popular apps (bigger size of the image).
This should improve first experience dramatically.

**Comment by cyberb** [comment]
I am not sure why we are discussing this, has anyone complained about the
speed?
In my view progress bar and other correctness fixes have higher pririty
than performance.

**Comment by vsapronov** [comment]
I complain about this all the time. Install takes long-long-long time.
We are discussing this because discussing is free and may be we'll find some cheap way to improve it without too much coding.
We need to look at Waffle to see what has higher priority. This task is just in the backlog somewhere. It's not planned for any milestone.

**Comment by cyberb** [comment]
After Snapd.
