### ISSUE TITLE
Check available disk space before sam actions

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#168]
If we run out of space during platform upgrade then nothing will work. It seems that we need to ensure that there's enough of space before upgrading platform.

**Comment by vsapronov** [comment]
Let's think first about sam server and then address all issues with current sam there...

**Comment by vsapronov** [comment]
I reopened this. It seems like this is done in platform now! Why not in sam?

**Comment by cyberb** [comment]
We will keep on both sides until we have proper sam server.
