### ISSUE TITLE
Web activate is broken

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#173]
:81/ (not :81/activate.html) doesn't load css and js
redirect to login.html doesn't work

**Comment by cyberb** [comment]
I do not see any css issue, need more info if there is any issue.

**Comment by vsapronov** [comment]
Try clicking Activate from device Settings page. The Activate page that was
displayed to me was completely broken...

**Comment by cyberb** [comment]
![tmp_19455-screenshot_2016-09-16-00-10-461767829650](https://cloud.githubusercontent.com/assets/885528/18576690/c1d24a6e-7bdb-11e6-8b39-3b5252b542a6.png)

**Comment by vsapronov** [comment]
What is the address of this page. Could you please let me see it from the
browser.

**Comment by cyberb** [comment]
![tmp_5381-screenshot_2016-09-16-18-28-491767829650](https://cloud.githubusercontent.com/assets/885528/18595229/b4129bee-7c3b-11e6-9bcf-10cb767f066d.png)

**Comment by vsapronov** [comment]
Let me test it more. So far looks good from your comments...

**Comment by vsapronov** [comment]
OK, everything seems to be fixed
