### ISSUE TITLE
External access check should be more reliable

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#175]
The fact that external ip is responding doesn't mean anything. It could be router admin web page. We need to make sure that we really reached the Syncloud device.

**Comment by cyberb** [comment]
Do you mean /probe/port check?
It checks the body as well.

https://github.com/syncloud/platform/blob/master/src/syncloud_platform/insider/port_prober.py#L20

**Comment by vsapronov** [comment]
This is very strange then. I was able to activate device but I see router web-panel on external address... May be this is because I'm going to it from INSIDE of my network. I'll test it more. Do you remember we had the bug with some routers before: router didn't route properly by external address of itself...

**Comment by vsapronov** [comment]
We just have got confirmation from user that failed port mapping doesn't stop enabling external access. Weird thing. It looks like we actually check for the device availability through redirect. Something doesn't work as we wanted.
Related to https://github.com/syncloud/platform/issues/192
This should be fixed first.
We should have 3 different scenarios:
Everything is working - awesome!
IP is external, but port map failes - give option to map port manually
Nothing works - sorry can't help

**Comment by cyberb** [comment]
Apart from fixing the code to be consistent should we also restore our 'problem diagnosis' page with usual pass/fail checks (external ip, port mapping, ...)

**Comment by cyberb** [comment]
Apart from fixing the code to be consistent should we also restore our 'problem diagnosis' page with usual pass/fail checks (external ip, port mapping, ...)

**Comment by cyberb** [comment]
Apart from fixing the code to be consistent should we also restore our 'problem diagnosis' page with usual pass/fail checks (external ip, port mapping, ...)

**Comment by vsapronov** [comment]
Yes, it would make sense to have the page on the device.
Though let's think through user experience of it. What does user see, what he/she clicks, etc... It should be super user-friendly.
May be we need to move the whole External Access/HTTPS into new page and make these diagnosis checks on that page.

**Comment by cyberb** [comment]
We have access page now which does more checks.
https://github.com/syncloud/platform/issues/199
