### ISSUE TITLE
python code is not working

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#177]
root@cubietruck:~# /opt/app/platform/bin/insider sync_all
    invalid section len 1073741874, max remaining 50
    invalid subsection length 2147500649, max allowed 40
/opt/app/platform/python/bin/python: line 4:   376 Illegal instruction     ${DIR}/bin/python.bin $@

Python itsself seems to be fine:

root@cubietruck:~# /opt/app/platform/python/bin/python --version
Python 2.7.10

**Comment by vsapronov** [comment]
Can you reproduce it?

**Comment by cyberb** [comment]
Give me some time, I will test one more time.

**Comment by cyberb** [comment]
new sd copy fixed the problem.
We should really stop using sd and switch to eMMC modules at least!
