### ISSUE TITLE
Device connection using Tor hidden service

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#19]
_From @cyberb on August 26, 2014 22:16_

The main advantage is secure phisical location of a device.
Ultimate device location security requires all its services to be accessd through tor.

One of the java libs:
https://github.com/hoijui/JTor

_Copied from original issue: syncloud/android#4_

**Comment by vsapronov** [comment]
Do you think this is Android related? Where we'll be doing development/setup? In what project? Tasks should be reported to projects where they will be implemented mostly...

**Comment by vsapronov** [comment]
_From @cyberb on August 28, 2014 22:22_

First version is probably for our own communication between android and device.

**Comment by cyberb** [comment]
Not enough resources at the moment.
