### ISSUE TITLE
Rely on user port mapping

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#192]
There should be a way to say: "I mapped port myself, it's 80 from outside, use it". Such option would be useful for people with broken routers that can't add mapping through UPnP. We just can make a backdoor for manual mapping and from insider assume that we created them through PortDrill or whatever.
We need to analyse external mode errors better to make such UI useful...

**Comment by vsapronov** [comment]
This issue is for the error analysis part: https://github.com/syncloud/platform/issues/175

**Comment by cyberb** [comment]
We can detect well known even without user intervention, if mapping fails we can check it is visible through redirect still.

**Comment by vsapronov** [comment]
Related to https://github.com/syncloud/platform/issues/199
This should be done on that separate Access page

**Comment by vsapronov** [comment]
I guess this is done already, is it?
