### ISSUE TITLE
Blog on our site

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#193]
Looks like we can make a blog right on our website. Posts that we make to Facebook + release notes seems to be frequent enough for a blog.
Need to investigate how to do this in that way that there's no double work to publish both blog and facebook. There should be some crosspost  tools.

For now it's very hard to say that our project is active without going to Facebook...

**Comment by vsapronov** [comment]
Testing http://everypost.me now. It seems they can post to Facebook, this is something.
Will check what else they can...

**Comment by cyberb** [comment]
not enough resources at the moment.
