### ISSUE TITLE
New setup demo video

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#194]
People watching our youtube setup video. UI is lod there, and some things have changed already.
Need to update it and make it prettier if possible.

**Comment by klmhsb42** [comment]
I'm working on a step-by-step video. Just a content question: Must be UPnP enabled in the router settings?

![video](https://user-images.githubusercontent.com/44033489/73556577-fd3d9c80-444f-11ea-8e25-17b44702923e.PNG)

**Comment by cyberb** [comment]
UPnP allows device to automatically open ports but in reality it is not enabled and not very reliable if enabled. So it is better to open ports manually and not rely on UPnP.

**Comment by klmhsb42** [comment]
I'm getting better with git commands :) 

You can see progress here https://github.com/klmhsb42/syncloud.org/tree/add-manual2/manual

**Comment by klmhsb42** [comment]
It's drawn by myself so you don't have to worry about copyright

**Comment by cyberb** [comment]
Android Firefox cannot show it, should I open SVG file?
Can you post a picture here?

**Comment by klmhsb42** [comment]
I've drawn “frames“ with Inkscape (svg file) and exported each frame into frame/ folder as png file. I've written a text for each frame into txt file. I will create for each text an audio file and set then everything together as video. I will create a LaTeX file to create a manual out of frames and text as pdf. If there will be changes in future, frames can be easily changed. To get first idea, you can go into frames/ folder an click through png files...

**Comment by klmhsb42** [comment]
Frames are 1920 x 1080 full hd but can be exported with any resolution as svg uses vectors

**Comment by cyberb** [comment]
I see, great, looking forward!

**Comment by klmhsb42** [comment]
Download link of first video version to support per mail

**Comment by cyberb** [comment]
There should be open source music out there like this: https://freemusicarchive.org.

Or this: https://www.bensound.com
> You are free to use this music in your multimedia project (online videos(YouTube,...), websites, animations, etc.) as long as you credit Bensound.com, For example: "Music: www.bensound.com" or "Royalty Free Music from Bensound"

**Comment by klmhsb42** [comment]
OK, cool. So, I would just write "Music: www.bensound.com" on the first video frame and then we should be safe. You can also put it in the youtube video description, too.

**Comment by klmhsb42** [comment]
https://github.com/syncloud/stuff/commit/9105ae271c006734d00e2abf5706737c0e0cf250

**Comment by klmhsb42** [comment]
I used https://www.openshot.org/de/ as video editor, but I tested https://shotcut.org/ for another project and found this one better. Or https://kdenlive.org/de/ as you suggested.

**Comment by klmhsb42** [comment]
> syncloud/stuff@9105ae2

Download link of video sent per mail to support. Can you download? Do you want me to do some changes or is it ok to publish?

**Comment by cyberb** [comment]
Did you send me new video with no 81, new music and louder voice?

**Comment by klmhsb42** [comment]
Yes, I can send again...

**Comment by klmhsb42** [comment]
done, see mail

**Comment by cyberb** [comment]
Pushed to artifacts: https://github.com/syncloud/stuff/releases/download/20.04/syncloud-20200415.mp4

**Comment by klmhsb42** [comment]
If you publish to YouTube, I can update the link on syncloud.org repo with the next pull request...

**Comment by cyberb** [comment]
Ok, let me create a company account.

**Comment by klmhsb42** [comment]
> create a company account.

There is _google my business_, which you can also use for _youtube for business_, I guess https://www.google.com/intl/en/business/

**Comment by cyberb** [comment]
Looks like there is not business account, but there is a branded channel, so I created Syncloud channel and uploaded the video:

https://youtu.be/xI_I8yNOzNE

**Comment by klmhsb42** [comment]
https://github.com/syncloud/syncloud.org/pull/44

**Comment by klmhsb42** [comment]
Could you add the Syncloud _logo_ and URL https://syncloud.org to youtube channel?

**Comment by klmhsb42** [comment]
And maybe "background music is from https://www.bensound.com/royalty-free-music/track/sunny" under the video description

**Comment by klmhsb42** [comment]
#507

**Comment by klmhsb42** [comment]
> 
> 
> [syncloud/syncloud.org#44](https://github.com/syncloud/syncloud.org/pull/44)



> 
> 
> Could you add the Syncloud _logo_ and URL https://syncloud.org to youtube channel?



> 
> 
> And maybe "background music is from https://www.bensound.com/royalty-free-music/track/sunny" under the video description


You can close this issue after those steps are done.

**Comment by cyberb** [comment]
done
