### ISSUE TITLE
Resize sd card button in settings

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#195]
Existing workaround is to run the following command on a device using ssh:

/opt/app/platform/bin/resize-sd-partition.sh

Then reboot device.

**Comment by vsapronov** [comment]
Is reboot really needed?
It seems to work for me without reboot...

**Comment by cyberb** [comment]
90% will work but 100%.
I had cases when it did not.

**Comment by cyberb** [comment]
![selection_004](https://cloud.githubusercontent.com/assets/885528/19890292/b2e86a40-a031-11e6-933a-e256563125c9.png)

**Comment by vsapronov** [comment]
Very cool!
Does progress spin when you click button?
Also, is it possible to check when extend makes sense and when it doesn't?
If we extended already it would be better not show it again.

**Comment by cyberb** [comment]
Progress spins, actually waits for the extension.
Will try to hide when not needed.
