### ISSUE TITLE
Sam server

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#197]
We have several issues like:
1. No information what is happening right now (if you navigated away)
2. Not possible to stop installation
3. No installation progress.
4. Ability to run parallel installations
5. Out of disk space issue

I think they are connected and related to the lack of proper back-end.
Currently we are mixing web server and ssh server to run various tasks.

Web server cannot run long running tasks as browser times out after some time and we do not really want to hold that connection.
SSH Server is not perfect as we have very complex control over what job is running, what it is doing and how to stop it and not stop something else by accident.

Prober back-end should be able to solve these issues.

It should have the following features:
1. Scheduling a task
2. Cancelling a task
3. Listing currently running tasks
4. Getting task info (name, progress ... )
5. Ability to limit amount of currently running tasks (I think 1 is a good start)
6. Notification of completed tasks (successful or failed)

Possible implementations:
- Try ubuntu core + snappy installer.
- http://docs.celeryproject.org
- http://python-rq.org
- We could implement similar thing by saving some state about running "process" and having python worker which checks state and does what it says.

**Comment by vsapronov** [comment]
Let's discuss this.

**Comment by cyberb** [comment]
We will try snapd (https://github.com/syncloud/platform/issues/263)
