### ISSUE TITLE
UPnP has to be enabled on router

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#199]
As of now Syncloud relies heavily on UPnP being enabled on router.
UPnP allows device to open needed ports (80/443 or others if these are taken) automatically.

Unfortunately in case UPnP is not enabled or not available at all users cannot easily setup manually external access as device will not update DNS ([user].syncloud.it) with external IP.

We need separate page for enabling external access and HTTPS which will allow step by step setup with fallback to entry of manually mapped external ports and possibly external IP (while this can be guessed by our DNS server).

For now users should try to enable UPnP or use appropriate router.

**Comment by jsfrederick** [comment]
Another vote for fixing this ASAP!  I really need to ability to access my Syncloud instance outside the home.  I will NOT enable UPNP !  I am available to test if needed.

Also, help me make sure I understand this.

Syncloud has the ability to know the public IP address if an instance, it just does not support manual port forwarding at this time.  So, that means that I don't have to worry about Dynamic DNS to update the public IP address, correct?

Once Manual port forwarding is available, we will have the ability to access the instance outside the home network, correct?

**Comment by cyberb** [comment]
Syncloud gets public IP from either UPnP (disabled in your case) or by checking the source IP when pinging our DDNS service (syncloud.it).
If your provider gives you public IP it should be fine.

Otherwise your are right when we add ability to tell Syncloud not use UPnP and manually enter port info it should work the same way.

**Comment by cyberb** [comment]
This is how access page will like like to allow disabling automatic port mapping.
![tmp_7500-psx_20170227_222342-1874840457](https://cloud.githubusercontent.com/assets/885528/23382829/9ae293e6-fd3b-11e6-951d-c3df3db49e69.jpg)

**Comment by jsfrederick** [comment]
That would work for me!  I like it.

**Comment by BenoitSvB** [comment]
Waiting for the release of this feature to start my Syncloud trial!

**Comment by cyberb** [comment]
This is our top priority and we are doing final testing. It is a little bit delayed as we have a temporary instability with our build infrastructure.

**Comment by jsfrederick** [comment]
Any updates?

**Comment by cyberb** [comment]
Look like we are going to release 17.03 this weekend.

**Comment by BenoitSvB** [comment]
What will happen if my ISP assigns at some moment a public ip address, different from the ip address I specified at the moment I activated my syncloud device?

**Comment by cyberb** [comment]
Try entering 0 into IP it should trigger server side (ddns) ip detection and it will be automatically update it every five minutes.

**Comment by BenoitSvB** [comment]
ddns is the function I had hoped for but could not guess/find...
