### ISSUE TITLE
Helios4 board support

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#201]
We need to build good relationship with Helios3 developer. This partnership could give us some good exposure.

**Comment by vsapronov** [comment]
I guess this is kind of done?

**Comment by cyberb** [comment]
Yes :)

**Comment by g-provost** [comment]
Hi guys, could you use the latest Armbian image for Helios4 to build your syncloud image ?

**Comment by g-provost** [comment]
Thanks for the build. It works ;-)
I registered the device and installed Next Cloud. Looks good.

However, not sure how your build flow works, it seems you are not keeping the tweaks made in the Armbian base system. For instance in the case of Helios4 we need to install 'fancontrol' dpkg and add some udev rules + fancontrol config files. You can find those file here : 
https://github.com/armbian/build/tree/master/packages/bsp/helios4

So somewhere in your build script, we need to add something like 
```
chroot $FILESYSTEM /bin/bash -c "apt-get -y -qq install fancontrol >/dev/null 2>&1"
patch $FILESYSTEM /usr/sbin/fancontrol $INCLUDES/helios4/fancontrol.patch

cp -R $INCLUDES/helios4/90-helios4-hwmon.rules $FILESYSTEM/etc/udev/rules.d/
cp -R $INCLUDES/helios4/fancontrol_pwm-fan-mvebu-next.conf $FILESYSTEM/etc/fancontrol
```

**Comment by cyberb** [comment]
@g-provost I will include these fixes and let you know.
On a side note, why do you need to patch fancontrol itself?

**Comment by g-provost** [comment]
@cyberb you can find the commit message here that explains why :

https://github.com/armbian/build/commit/5abd71d6b6b6fc601419c3c59495e9009ac78708

**Comment by g-provost** [comment]
Hi again @cyberb, I just checked and actually it seems that the 'too many arguments' issue with fancontrol has been fixed in latest fancontrol version available in Debian Stretch (issue [727731](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=727731)).
As for the other fancontrol little tweak that set the pwm value to 0 when exiting, it is not a must.
**Therefore you can just ignore the patch ;-)**

**Comment by g-provost** [comment]
_/etc/fancontrol_ is the config file for fancontrol, not a directory containing some config file.
_fancontrol_pwm-fan-mvebu-next.conf_ should be rename as _/etc/fancontrol_

Thanks.

```
root@helios4:~# systemctl status fancontrol.service
● fancontrol.service - fan speed regulator
   Loaded: loaded (/lib/systemd/system/fancontrol.service; enabled)
   Active: failed (Result: exit-code) since Thu 1970-01-01 00:01:05 UTC; 2min 30s ago
     Docs: man:fancontrol(8)
           man:pwmconfig(8)
  Process: 353 ExecStartPre=/usr/sbin/fancontrol --check (code=exited, status=1/FAILURE)

Jan 01 00:01:04 helios4 fancontrol[353]: Loading configuration from /etc/fan....
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: grep: /etc/fancontrol: Is a directory
Jan 01 00:01:05 helios4 fancontrol[353]: Some mandatory settings missing, pl...!
Jan 01 00:01:05 helios4 systemd[1]: fancontrol.service: control process exi...=1
Jan 01 00:01:05 helios4 systemd[1]: Failed to start fan speed regulator.
Jan 01 00:01:05 helios4 systemd[1]: Unit fancontrol.service entered failed ...e.
Hint: Some lines were ellipsized, use -l to show in full.
root@helios4:~# 
root@helios4:~# ls -la /etc/fancontrol 
total 12
drwxr-xr-x  2 root root 4096 Sep 24  2018 .
drwxr-xr-x 68 root root 4096 Sep 24  2018 ..
-rw-r--r--  1 root root  437 Sep 24  2018 fancontrol_pwm-fan-mvebu-next.conf
root@helios4:~# 
```

**Comment by cyberb** [comment]
My bad, can you try this:
http://artifact.syncloud.org/image/syncloud-helios4-18.09.img.xz

**Comment by g-provost** [comment]
Looks pretty good :-)

But few comments :

1. I didn't realized the base system was Jessie. Is it correct ? I mean Jessie is kinda EOL even though still under LTS. You guys plan to move to Stretch at some points ?

2. Many config files are missing a carriage return at the end.

Example udev-rules :

```
Jan 01 00:00:02 helios4 systemd[1]: Starting udev Kernel Device Manager...
Jan 01 00:00:02 helios4 systemd[1]: Started udev Kernel Device Manager.
Jan 01 00:00:02 helios4 systemd-udevd[217]: invalid key/value pair in file /etc/udev/rules.d/75-persistent-net-generator.rules on line 1,starting at character 114 ('')
Jan 01 00:00:02 helios4 systemd-udevd[217]: invalid key/value pair in file /etc/udev/rules.d/90-syncloud.rules on line 3,starting at character 91 ('')
```

Also /etc/apt/sources.list, and i guess many others.

3. Talking about APT source.
I feel it's a bit of a pity that you are scrapping the whole Armbian rootfs. There are some tweaks for reliability and performance improvements that are quite recommended for all the board that you guys actually also support. But the bigger problem is that now there is no source for Helios4 to keep it's kernel and u-boot up to date. You could add the armbian one, but in order to be the latest kernel it should point to Stretch distrib.

```
$> cat /etc/apt/sources.list.d/armbian.list 
deb http://apt.armbian.com stretch main stretch-utils stretch-desktop
```

Even though this build is already quite good, I'm not sure we can use it yet as a first official Syncloud release for Helios4.

**Comment by cyberb** [comment]
1. Let me explain. Syncloud image is not general purpose linux OS, we try to keep base system is very limited and it is not updated between image release at the moment (it probably will in futire using ubuntu core mechanism). All Syncloid packaged apps bring their dependencies with them and have very limited dependency on base OS itself.

Kernel and kernel modules are coming from device specific distributions.

To answer your question we eventually upgrade base OS to Stretch or Ubuntu Core for example.

2. Thanks for brining that warning to my attention, few config files had no EOF line ending, this is fixed and reuploaded to 
http://artifact.syncloud.org/image/syncloud-helios4-18.09.img.xz

3. Regarding apt, as i said users are not supposed to upgrade packages as it will potentially break things. So apt will be disabled by default and eventually removed. We are using snapd to bring Syncloud packaged apps down.

Can you point me at some of those useful performance tweaks so we can think how to integrate them?

**Comment by cyberb** [comment]
We are maintaining our version of snapd with Syncloud store support (simple http file system) at https://github.com/syncloud/snapd

I think it is based on 2.31. We plan to rebase our version on the latest releases as needed. Right now there is no need, it is perfect :)

I will check these tweaks, thanks.

Sd card optimization is good, but again our main device Odroid HC1 is actually using SSD disk as an internal memory and we are super happy with it.

**Comment by g-provost** [comment]
Here the link : https://cdn.kobol.io/files/Armbian_5.61_Helios4_Debian_stretch_next_4.14.72.7z

> Sd card optimization is good, but again our main device Odroid HC1 is actually using SSD disk as an internal memory and we are super happy with it.

Well I'm pretty sure many of your users are using board that rely on SDcards to host the rootfs. BTW Odroid HC1 not even listed on you Hardware page. I hope Helios4 will make it back to this page soon ;-)

**Comment by cyberb** [comment]
You are right many users are on sd card, which is not ideal.

Sorry forgot about helios 4 hardware page, added both.

Also latest image is here:
http://artifact.syncloud.org/image/syncloud-helios4-18.09.img.xz

**Comment by g-provost** [comment]
Ok tested. It works.

Some issue I realized in this build and also in previous builds : On first boot, after I register the device with syncloud backend, I get redirected to the https://<ip-machine> (not the <device_name>.syncloud.it), I got a 500 error. Once I access the https://<device_name>.syncloud.it, I can see the login page but after login I would get a 'Oops error' (don't remember exactly the error message). The only way to make it works is to reboot, and then all will be ok.

Can you also amend the following for Helios4 info on your Hardware page :
- Cores / Frequency : 2 / 1.6 GHz
- Memory RAM : 2GB ECC

BTW here an image with proper white background.
![helios4_board_only](https://user-images.githubusercontent.com/26227460/46269189-0bd12680-c572-11e8-8132-610ecdde7646.jpg)

**Comment by cyberb** [comment]
Fixed the specs and the image.

For the error, could you send us logs to see what is the problem? You can do this from Settings - Support.

**Comment by g-provost** [comment]
Ok I don't seem to be able to reproduce it now :/ Well that's good.

So i guess we can define this build as the first official release for Helios4 ;-) Can you make it available on your [download page](https://github.com/syncloud/platform/wiki) ?

Thanks for the support ;-) I know need to send you guys a board.

**Comment by cyberb** [comment]
Fixed the download page.

**Comment by g-provost** [comment]
@cyberb could you re-generate the syncloud image based on our latest build : https://cdn.kobol.io/files/Armbian_5.68_Helios4_Debian_stretch_next_4.14.88.img.xz

If you want i can test it first before you publish it.

**Comment by cyberb** [comment]
Done: http://artifact.syncloud.org/image/syncloud-helios4-18.12.img.xz

Could you test it please? We do not have a board yet :)

**Comment by g-provost** [comment]
Ok I will test and keep you updated.

Can you contact on gauthier@kobol.io and provide me an address where i can send the board.

**Comment by cyberb** [comment]
Sent

**Comment by g-provost** [comment]
Ok I tested the image all good, you can please publish.

**Comment by cyberb** [comment]
Updated existing image: https://github.com/syncloud/platform/releases/download/18.11/syncloud-helios4-18.11.img.xz

**Comment by g-provost** [comment]
Hi guys, FYI we are going to release soon major release update for Armbian.

- Kernel 4.19 + Uboot 2019 + Debian Buster (Armbian Next)
- Kernel 4.14 + Uboot 2018 + Debian Stretch (Armbian Default)

So maybe you guys should consider building a new Syncloud version for Helios4 based on one of the new upcoming images above ;-)

**Comment by cyberb** [comment]
Sure, let us know when it is ready, image itself.

**Comment by g-provost** [comment]
@cyberb Not sure which base OS version you are using now, Stretch or Buster ?
Now we have both available with updated kernel and u-boot, check our download page : https://wiki.kobol.io/download/
