### ISSUE TITLE
Unable to login to owncloud app

### ISSUE THREAD

**Issue by apefrog** [syncloud/platform#207]
Using raspberry pi 3
Login credentials don't work.

Is there a way I can manually edit admin user login details?

Owncloud login works fine.

**Comment by apefrog** [comment]
NEXTCLOUD login fails, not owncloud as the title says. MY bad.

**Comment by cyberb** [comment]
Probably you are running out of space or something like that, could you create fresh syncloud sd card and try again?

Please find this script after starting on fresh image:
/opt/app/platform/bin/resize-sd-partition.sh

Soon we will have a button on the UI to extend sd card file system to take the whole space of the card.

Also we have 'send logs' button which gives us more info about the state of your device.

**Comment by apefrog** [comment]
Ok thanks. I'll give that a try.

**Comment by apefrog** [comment]
Worked.
