### ISSUE TITLE
Lets Encrypt cert restrictions

### ISSUE THREAD

**Issue by apefrog** [syncloud/platform#209]
Not able to automate this process.

Any ideas on how this is manually done?

**Comment by cyberb** [comment]
When external access is enabled and https mode is set it will try to get you a real certificate.

There are some conditions:

1. Your router should allow opening port 80 and 443, that is where let's encrypt service will look.

2. DNS propagation may take up to 10 minutes so give it some time and it will work after some time if all conditions are met.

You can check this log file:
/opt/data/platform/log/letsencrypt.log

Or just use 'send logs' button.

**Comment by cyberb** [comment]
Forgot to mention while not all conditions are met Syncloud you will still have https but with self signed certificate.

**Comment by apefrog** [comment]
UPnP is enabled on my router. Does this allow syncloud to open thise ports ?

**Comment by cyberb** [comment]
It should. Ports (80/443) should not be used or taken on the router.

**Comment by cyberb** [comment]
Is this still an issue?

**Comment by marxistvegan** [comment]
I am still having this issue with the log below

```
==> /var/snap/platform/common/log/letsencrypt.log <==
    response = self.net.post(self.directory.new_authz, new_authz)
  File "/snap/platform/181109762/python/lib/python2.7/site-packages/acme/client.py", line 682, in post
    return self._post_once(*args, **kwargs)
  File "/snap/platform/181109762/python/lib/python2.7/site-packages/acme/client.py", line 695, in _post_once
    return self._check_response(response, content_type=content_type)
  File "/snap/platform/181109762/python/lib/python2.7/site-packages/acme/client.py", line 582, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new authz :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/
2018-12-13 03:31:09,475:ERROR:certbot.log:An unexpected error occurred:
2018-12-13 03:31:09,475:ERROR:certbot.log:There were too many requests of a given type :: Error creating new authz :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/
root@syncloud:~# 

```

**Comment by cyberb** [comment]
Do you have port 80 on your piblic IP mapped to your device?

If it became available recently then it will take some time for Let's Encrypt to start working again as they limit the amount of failed attempts you can make at a certain period of time.

Can you send logs or at least your domain name to support so we can tell you exactly what is the issue?

**Comment by marxistvegan** [comment]
Port 80 is open from my router, as well as 443 and the site [is here ](dialectica.red)

**Comment by cyberb** [comment]
How long do you have port 80 open?
It may take time for them to start allowing requests again.

**Comment by marxistvegan** [comment]
It's been open since the start

**Comment by cyberb** [comment]
Can you send us logs from setting - support page?

**Comment by marxistvegan** [comment]
Yep, I sent them, twice the second one by mistake.

**Comment by cyberb** [comment]
Ok, your problem is that you do not seem to have a wildcard cname dns record for your domain like this:

````
CNAME *.example.com example.com
````

Can you add one, instead a few individual domain names?

**Comment by marxistvegan** [comment]
Ahh ok freends dynamic dns i am using does not offer that with its free services. Hmmm i will have to consider my options.

**Comment by marxistvegan** [comment]
> Currently you need to have these domains if you cannot have a wildcard:
> 
> ```
>  example.com
>  diaspora.example.com
>  files.example.com
>  gogs.example.com
>  mail.example.com
>  nextcloud.example.com
>  platform.example.com
>  rocketchat.example.com
>  sam.example.com
>  syncthing.example.com
> ```

Got it and I just added the missing ones

**Comment by cyberb** [comment]
Still does not work, could you send another logs?

**Comment by marxistvegan** [comment]
Still not working, new logs just sent.

**Comment by cyberb** [comment]
It says mail. is still missing

**Comment by marxistvegan** [comment]
Ohh ok I changed the IP for it to be to freedns it was sent to gandi but I am not sure if that was necessary though it is where the email is.

**Comment by cyberb** [comment]
It is green now!

**Comment by marxistvegan** [comment]
W00t!

**Comment by cyberb** [comment]
Obviously it should work untill we add another app to the list, so you can fix it the same way.

We are planning to add wildcard certificates, but it is only possible if we control dns (syncloud.it in this case) and custom domains will continue to use non wildcard certificates.

https://github.com/syncloud/platform/issues/360

**Comment by mikini** [comment]
For people fighting for green padlocks on their own domain;

New location for letsenxrypt.log: **/var/snap/platform/common/log/letsencrypt.log**

Current, as of v21.01, list of (sub)domains that has to be in DNS for the certificate to be generated (taken from log on actual system, unable to locate these in source):

* `<no subdomain>`
* diaspora
* files
* gogs
* installer
* mail
* nextcloud
* notes 
* openvpn
* pihole
* platform
* plex
* rocketchat
* syncthing
* users
* wordpress

**Comment by cyberb** [comment]
One of the features coming soon is that we will start offering DNS management to any domain, but unfortunately we canmot do it for free as it requires us to pay for it, would you use such an option?

**Comment by mikini** [comment]
Personally I am technically advanced enough to do my own DNS setup and don't find much value in paying for that.

For the above I just setup an A record for the base domain that is dynamically updated at my usual DNS provider (local to Denmark [GratisDNS](https://web.gratisdns.dk/)) and created a CNAME wildcard to that for subddomains.

I can see that instructions for doing exactly that is in [the source](https://github.com/syncloud/platform/blob/master/www/src/views/Activate.vue#L92). I did not see that message during installation of 21.01, though.

**Comment by cyberb** [comment]
Agree, many oeople do that.
Another useful feature of a managed DNS for a device is that you do not need port 80 open for incoming DNS validation calls from Let's Encrypt as it will use DNS record validation by creating short lived TXT eecords for you.

**Comment by mikini** [comment]
Yeah, that could definitely be an added bonus for some. But doesn't [certbot with DNS plugins](https://certbot.eff.org/docs/using.html?highlight=dns#dns-plugins) do that for sufficiently sophisticated users already? (haven't use that approach myself)

Looking at [acme.sh there are even more API integrations](https://github.com/acmesh-official/acme.sh/tree/master/dnsapi) towards DNS providers. Even for [GratisDNS](https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_gdnsdk.sh).

I think a solution where you'd require the DNS to be hosted at your/your partners DNS solution would only cater to non-technical people that is ignorant to DNS anyway. I think a solution where users could choose between providers supported by the chosen tool would be more accepted and appreciated. But this could of course also go hand in hand with an option to choose an easy solution with a provider dictated by you.

I guess what I was mostly missing here was some documentation telling me that I needed to have more than the few domains of the installed applications in DNS for the certificate to be generated. Is that present anywhere? (besides the above mentioned [info in the Activate.vue page](https://github.com/syncloud/platform/blob/master/www/src/views/Activate.vue#L92) that I never saw during installation of 21.01)

**Comment by cyberb** [comment]
We have two places with the info.
1. Activation screen custom "Device Name" question mark
![Screenshot_2021-03-08-10-37-02-869_org mozilla firefox](https://user-images.githubusercontent.com/885528/110310437-75cf3f00-7ffa-11eb-8fca-c1c1a46dd3f9.jpg)
![Screenshot_2021-03-08-10-37-11-668_org mozilla firefox](https://user-images.githubusercontent.com/885528/110310451-7962c600-7ffa-11eb-8e8e-8a70949c4ab4.jpg)

2. Wiki: https://github.com/syncloud/platform/wiki/Custom-domain
