### ISSUE TITLE
[UI] Unable to handle platform upgrade progress complete from settings

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#210]
When upgrading platform everything is restarted and we lose browser user sessions so update progress cannot complete as it starts getting 401 unauthorised but we are waiting 200.

Probably after platform upgrade we should handle 401 and treat it as upgrade finish and redirect to login page (our regular 401 handler)

**Comment by vsapronov** [comment]
It seems that this is fixed already by handling 401 as complete
