### ISSUE TITLE
Let's encrypt certificate is not working when apps are installed

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#213]
App installation breaks Let's encrypt.

It was already fixed and will be released some time after v16.09.

Workaround:
1. Uninstall all apps
2. Disable HTTPS
3. Change this file on device: /opt/app/platform/config/nginx/app.server
According to this commit: https://github.com/syncloud/platform/commit/379a69ccbf0096a7aac4cec95f167383e694af77
4. Enable HTTPS
5. Install needed apps

**Comment by taschenlampe** [comment]
Hi!
The workaround seems not to be working here. Not sure where to find the correct logs for this.
I suppose that the logs should be related to ngnix, all I see is "raspberrypi3 nginx[297]: nginx: [alert] could not open error log file: open() "/nonexistent/path/nginx/logs/error.log" failed ".
Where should I look for more information? 
Cheers.

**Comment by cyberb** [comment]
All the logs are in /opt/data/platform/log

What exactly is not working?

**Comment by taschenlampe** [comment]
I guess this is the relevant log entry, in platform.log I found this:
`main.py: error: argument -m/--email: expected one argument
2016-12-17 12:09:18,137 - tls - WARNING - unable to generate real certificate: Command '/opt/app/platform/bin/certbot --logs-dir=/opt/data/platform/log --config-dir=/opt/data/platform/certbot --agree-tos --email  certonly  --webroot --webroot-path /opt/app/platform/www/public/_site -d blackflag.syncloud.it -d files.blackflag.syncloud.it -d mail.blackflag.syncloud.it -d diaspora.blackflag.syncloud.it -d nextcloud.blackflag.syncloud.it -d owncloud.blackflag.syncloud.it -d sam.blackflag.syncloud.it -d platform.blackflag.syncloud.it ' returned non-zero exit status `

**Comment by cyberb** [comment]
Do you have user_email setting in your /opt/data/platform/user_platform.cfg ? Should be under [redirect] section.

**Comment by taschenlampe** [comment]
Yes indeed, the missing email address was the troublemaker. Now all is "green", nice! 
Is there already a better working solutions for end users in the pipeline? The email could be entered in that conf.file when the login into the UI is established. Would have saved me a little time. ;-)

**Comment by cyberb** [comment]
Actually device activation should set this automatically, I will make sure this is working in the next release.
https://github.com/syncloud/platform/blob/master/src/syncloud_platform/device.py#L35
