### ISSUE TITLE
Clarify device account usage

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#214]
1. Add FAQ entry for device account and it's usage for app login.
2. Maybe add Activations notes, a note under Syncloud Account 'used to maintain domain name' and a note under Device Account 'used for device web and app access'

**Comment by vsapronov** [comment]
I think 1. is done here: http://syncloud.org/faq.html#credentials
2. Yes, seems makes sense to add explanation popup on device login form

**Comment by cyberb** [comment]
Enough for now.
