### ISSUE TITLE
Allow sending logs only to user.

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#215]
Some people use that to learn more about their device, we should allow them to select where to send that info.

For example add selected by default 'include Syncloud support' checkbox.

**Comment by taschenlampe** [comment]
Agreeing here. As  a user it would be nice to have access to the logs. Now users are sending the logs to "got no clue where to" + to their registration email. 
I'd suggest:
* adding a way to view the logs -> like send logs to Developers  -> send logs to my email address
* give an info to whom the email is actually send to
