### ISSUE TITLE
Add a FTP app

### ISSUE THREAD

**Issue by taschenlampe** [syncloud/platform#218]
I think that a FTP(s) app could make sense. 
Where users can decide either to have a ftp server  with a guest access (no password) and/or a password protected access.

**Comment by lil5** [comment]
Why support such and old protocol isn't webDAV (`davs://`) and SFTP (using `ssh`) enough?

**Comment by cyberb** [comment]
I guess you are right, http based protocols are much simpler to maintain (routers, DNS based app separation...)
This is why no one is really working on this issue.
Nextcloud does the job right now.
Reopen if you have a better reason and you want to maintain it.
