### ISSUE TITLE
Show mount point of mounted disk(s) in Settings

### ISSUE THREAD

**Issue by taschenlampe** [syncloud/platform#219]
Currently I can only see that a disk got mounted, unfortunately the UI lacks the info where the disk is actually mounted.

**Comment by cyberb** [comment]
Disk is always mounted under /data.

![storage](https://user-images.githubusercontent.com/885528/44622982-91025500-a8bb-11e8-9880-1e38748c68de.png)

![disk-info](https://user-images.githubusercontent.com/885528/44622984-9495dc00-a8bb-11e8-81ed-8fa80ca608dd.png)
