### ISSUE TITLE
Installing Diaspora failes

### ISSUE THREAD

**Issue by taschenlampe** [syncloud/platform#221]
Hi!
Could someone please take a look at the logs. 
[log.zip](https://github.com/syncloud/platform/files/656982/log.zip)

**Comment by taschenlampe** [comment]
"No space left on device" I guess that's the problem

**Comment by cyberb** [comment]
This should be handled better in the next release.
Resize manually for now: https://github.com/syncloud/platform/issues/195

**Comment by taschenlampe** [comment]
Yes indeed, expanding the size worked and the installation was successful.
