### ISSUE TITLE
File Browser shows an 404 when trying to access files in /data

### ISSUE THREAD

**Issue by taschenlampe** [syncloud/platform#224]
File Brower is unable to open files in /data. Files that are mounted as /data/Video are visible in Nextcloud though. Maybe logs can help 
[log2.zip](https://github.com/syncloud/platform/files/657092/log2.zip).

**Comment by vsapronov** [comment]
Seems to be because of the same reason as https://github.com/syncloud/platform/issues/206

**Comment by BenoitSvB** [comment]
I have only root as device user

**Comment by cyberb** [comment]
@BenoitSvB could you upgrade files and try again?

**Comment by BenoitSvB** [comment]
Syncloud will not be my device for some time to come. Thank you for your 
trouble.


Op 6-4-2017 om 23:59 schreef Boris Rybalkin:
