### ISSUE TITLE
External Access -> failes with no information

### ISSUE THREAD

**Issue by taschenlampe** [syncloud/platform#226]
I am currently trying to configure the external access. In the UI I can enable the "ext. acceess" after a while the controller goes from grey to green, what made me thing that all is fine. But after reloading the setting page the slider is grey again. This is confusing and led me to wrong assumptions why I could not reach my nextcloud from the internet. 
What would be nice to have would be
* a working slider 
* an info that shows my external IP -if I have one.

**Comment by coffeeforcoffins** [comment]
Syncloud supposes that you haven't blocked port 5351 from LAN to your Local network devices, so it can't get a response. I'm in a rush right now but I think it's the Plug N Play aspect of networking. Follow the other thread on this issue, it has a lot more posts. https://github.com/syncloud/platform/issues/230

**Comment by cyberb** [comment]
Please follow this issue https://github.com/syncloud/platform/issues/199 and add more details if you want.
Closing this one.
