### ISSUE TITLE
Wi-Fi support for RPi 3

### ISSUE THREAD

**Issue by taschenlampe** [syncloud/platform#228]
This is not an important feature wish, but wifi support would be pretty nice.

**Comment by daN4cat** [comment]
Agree, why is not supported?

**Comment by cyberb** [comment]
Apart from simply not having time to implement various features :) we need to understand what exactly you expect Syncloud to do, could you explain do you want device to be a WiFi client or WiFi access point for other devices?

**Comment by daN4cat** [comment]
Indeed you are correct.
I would say that at least would be nice to have the WiFi client, in the current distribution WiFi drive is not supported.

**Comment by cyberb** [comment]
When you say it is not supported do you mean there is no UI for it?
Have you tried setting it up with command line:
https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md

**Comment by taschenlampe** [comment]
If I may add my thoughts to this topic. I would like to have a simple interface for the network-devices, there the user could choose how s/he want to connect to the network: DHCP/static/wifi..etc.

The main idea would be that I power my RP3 on and if I find myself in a know wifi network, synloud goes online and all my services are running. So in the end I just need usb-power for my RP3 and that's it. That would make syncloud a super easy portable server.  

Syncloud as an access point...hmm...not sure about that. Could be useful -maybe- but I would not expect syncloud to host anything like that.

**Comment by daN4cat** [comment]
I'm under the impression that the current rapsberry pi image of syncloud doesn't contain the WiFi driver. I don't see any with lsmod.

**Comment by cyberb** [comment]
Actually driver should be there.
````
apt-get install wireless-tools
ifconfig wlan0 up
iwlist wlan0 scan
````
Should give you the list of networks.

**Comment by cyberb** [comment]
Looks like there are few web based management UIs for WiFi:

1. https://github.com/billz/raspap-webgui
2. https://github.com/mk-fg/NetworkManager-WiFi-WebUI

In think in the beginning it would be great to have one as an app to see how it goes.

**Comment by cyberb** [comment]
Here is another WiFi app:

**Comment by cyberb** [comment]
Here is another app: https://github.com/resin-io/resin-wifi-connect

**Comment by cyberb** [comment]
WiFi app issue: https://github.com/syncloud/platform/issues/296

Closing this as all the support to do it from command line is there now.
