### ISSUE TITLE
I don't manage to have my external drive recognized

### ISSUE THREAD

**Issue by fBedecarrats** [syncloud/platform#231]
Hello,
Installation on RPi3 ran smoothly, but I don't manage to have my external drive recognized (230 ssd usb hard drive). It was initially in Fat32, so when I tried to activate it, I got an error message from the Setting menu telling me it had to be in ext 2, 3 or 4. I connected in SSH to the RPi, unmounted the drive and formated it in ext4. Now, in SSH, `<sudo fdisk -l>` indicates that I have : 
> Disk /dev/sda: 223.6 GiB, 240057409536 bytes, 468862128 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

As it didn't appear in the Syncloud Settings menu, so I created a mounting point with `<sudo mkdir -p /mnt/disque1>` and mounted with `<sudo mount -t ext4 /dev/sda /mnt/disque1>`. It seems correctly mounted, as `<df -h>` indicates that I have a:
> Filesystem      Size  Used Avail Use% Mounted on
/dev/root       1.9G  796M  1.1G  44% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           463M     0  463M   0% /dev/shm
tmpfs           463M   12M  451M   3% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           463M     0  463M   0% /sys/fs/cgroup
tmpfs            93M     0   93M   0% /run/user/0
**/dev/sda        220G   60M  209G   1% /mnt/disque1**

But it is still not detected by the Settings menu. Can someone please tell me what I did wrong and how to have the external drive detected by the syncloud app?
Best regards,
FB

**Comment by cyberb** [comment]
Disk should have at least one partition with ext filesystem to be recognised.

**Comment by cyberb** [comment]
root@cubietruck:~# fdisk -l /dev/sda


Disk /dev/sda: 1.8 TiB, 2000398933504 bytes, 3907029167 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x81617ebb

Device     Boot Start        End    Sectors  Size Id Type
/dev/sda1        2048 3907028991 3907026944  1.8T 83 Linu

**Comment by fBedecarrats** [comment]
Thanks you ! Indeed I was missing this : 
Creating a partition `<sudo fdisk /dev/sda>`
and then formatting it `<sudo mkfs.ext4 -b 4096 /dev/sda1>`
It works fine now. Thanks a lot !
Maybe it could be useful to add a few instruction on how to prepare the external drive in the "Build your device" webpage?

**Comment by cyberb** [comment]
We have this issue and at some point we will implement it: https://github.com/syncloud/platform/issues/10
