### ISSUE TITLE
raspberrypi3 login after Calling CRDA to update world regulatory domain

### ISSUE THREAD

**Issue by IBastionI** [syncloud/platform#233]
Hey,

im getting this right after booting (just 30sec). I tested Username: pi and password: raspberry but it doesn´t work. Whats the problem here?
![img_20170211_131306](https://cloud.githubusercontent.com/assets/25284376/22853663/dca02f5a-f05c-11e6-9fff-b471fabb27fb.jpg)

Please help me :)

**Comment by cyberb** [comment]
Accounting to the instruction (https://github.com/syncloud/doc/wiki/Build-Syncloud-Device) ssh login is root and password is syncloud. After activating ssh password will be changed to device password. Ssh login is always root.

Regarding crda message it is probably coming from wireless driver and should be harmless.

If it continues to appear try this command:
''''
apt-get install wireless-regdb iw crda
''''
and reboot

Found this error here: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=122067

Let us know if that fixes the problem, we will try to fix it in the next release.

**Comment by IBastionI** [comment]
Hello,

thank you for your quick answer.

it was my fault. I typed in root and syncloud with a qwertz keyboard. So i have to type z instead of y to write syncloud :). Ok thank you!

What should i do now? it doesn´t do something, just waiting for an order. Sry im very nooby :)
![img_20170211_140601](https://cloud.githubusercontent.com/assets/25284376/22853994/c96c35c6-f063-11e6-878b-77621b3418a2.jpg)

**Comment by cyberb** [comment]
I see, actually you do not need to login that way, all you need is to activate the device using one of our apps: http://syncloud.org/setup.html
App should find the device and let you activate it and install apps.

**Comment by IBastionI** [comment]
Thank you. You´re doing a great job!

**Comment by cyberb** [comment]
You can like us and share your experience on Facebook if you want: facebook.com/thesyncloud
:)

**Comment by IBastionI** [comment]
Ok :)

I´ve got another little question. If i want to use your VM using Virtualbox, what i have to do to keep it running. Can you give me a little step by step instruction please?

Thank you 👍

**Comment by cyberb** [comment]
You will need to install Virtual Box on a PC (connected to your home router) and run our VM, then discover and activate it using one of the mobile apps. There is nothing special just leave PC on.
Please create separate github issue for more questions if that does not work.
