### ISSUE TITLE
Running Syncloud on VirtualBox

### ISSUE THREAD

**Issue by IBastionI** [syncloud/platform#234]
Hi,

which distribution i have to use to inject the syncloud HDD build. Do i have to make any further adjustements in Virtual Box?

If i choose debian 32 bit, my smartphone app doesn´t shows syncloud in my home network.

**Comment by cyberb** [comment]
Let me check, I think there is a problem with vbox build.

**Comment by jpma89** [comment]
@IBastionI, have you also tried "Debian (64-bit)"? This worked for me.

**Comment by IBastionI** [comment]
y Debian 64 bit is working. Thank you! But can you see your device at your smartphone? Do i have to make some adjustements in the virtual box network options?

**Comment by jpma89** [comment]
I changed my network adapter settings from NAT to Bridge which worked fine for me.

**Comment by IBastionI** [comment]
Thank you so much, it works 👍 .
