### ISSUE TITLE
Access NAS, which are under NAT

### ISSUE THREAD

**Issue by denis4net** [syncloud/platform#238]
Dear development team,
If I understand correctly, now I have to assign public IP address to my device, if I want to access it from global network (Internet). Do you plan to develop some kind of public available "proxy" for the NAS devices under the NAT? Let me imagine webdav JS client that accesses files on the device over webrtc...

**Comment by cyberb** [comment]
At the moment we rely on UPnP/NAT-PMP to allow access behind NAT.
It automatically detects external IP on the router and adds needed port mappings.
Please follow this issue for improvements in this area: https://github.com/syncloud/platform/issues/199

**Comment by denis4net** [comment]
So, what about cases where ISP doesn't dedicate global IP for users?

**Comment by cyberb** [comment]
Also your ISP to provide one or try changing ISP.
Otherwise you will not be able to make services available from the Internet.
