### ISSUE TITLE
Translate Syncloud.org into Simplified Chinese 

### ISSUE THREAD

**Issue by getnas** [syncloud/platform#240]

**Comment by cyberb** [comment]
I will try to use some i18n library like https://github.com/airbnb/polyglot.js and get back to you.

**Comment by getnas** [comment]
Should I need to wait for you to confirm it?

**Comment by cyberb** [comment]
We will need some form of translation file anyway, so you can start doing it if you want.
It will be easy to change its format to meet the library needs later.
It may take few weeks before I can start adding language switch work as I need to finish other tasks.
If you know HTML and JavaScript you can try adding language switch support yourself in the fork.

**Comment by getnas** [comment]
Look at this project https://github.com/WeblateOrg/weblate
It is a web based translation platform maybe can help us for multi-language purpose.

**Comment by cyberb** [comment]
Some progress is here: http://test.syncloud.org/buy.html

Only buy and hardware pages are translated so far.
Also language switch is introduced in non-mobile view.

Work is happening here: https://github.com/syncloud/syncloud.org/tree/translation

**Comment by cyberb** [comment]
I have pushed translation to syncloud.org.
There is a switch now to English, Chinese and Russian.
I have included your name and github link to Chinese translation file, let me know if you need this changed in any way.
