### ISSUE TITLE
Add hdparm support for RasPi3

### ISSUE THREAD

**Issue by Yury-MonZon** [syncloud/platform#241]
Could be useful to have hdparm installed and setup to spin down. Also, some users would prefer using acoustic mode.

sudo apt-get install hdparm -y
sudo cat >/etc/hdparm.conf<<EOF
/dev/sda {
write_cache = on
spindown_time = 120
}

EOF

**Comment by cyberb** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you have more info.
Thank you!
