### ISSUE TITLE
Device web admin: Autocomplete suggests wrong credentials in login form

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#245]
When logging into the device web admin autocomplete (at least in Chrome) suggests login password from syncloud.it account. That might be the root cause of all these "what login password to use?" complains.

**Comment by cyberb** [comment]
This must be smart browsers as we are not using any 'remember me' features in flask login https://github.com/syncloud/redirect/blob/master/redirect/www.py#L62

Need to check if it is possible to restrict browsers to exact list of domains, like syncloud.it and www.syncloud.it and no other subdomains.
Or we can move www (not rest) part of syncloud.it to syncloud.org.

**Comment by cyberb** [comment]
Or we can force login only from www.syncloud.it by redirecting browsers from syncloud.it to www.syncloud.it. I think that should help.

**Comment by cyberb** [comment]
This was actually done some tine ago.
