### ISSUE TITLE
Manual port mapping does not support more then one port mapping

### ISSUE THREAD

**Issue by BenoitSvB** [syncloud/platform#248]
Boris Rybalkin answered my device error report as follows:

> Mail wants to open few ports automatically and it does not work with new manual port mapping 
mode. Mail is not pure http application like nextcloud unfortunately. Could you open bug under platform "umbrella" bug tracker: https://github.com/syncloud/platform/issues so we can discuss options on fixing this as it is not simple bug.

So here is the issue.

**Comment by vsapronov** [comment]
May be we should introduce app requirements concept. Then each app would have:
1. Disk size required for installation (related to https://github.com/syncloud/platform/issues/200).
2. Ports needed for application functioning. Each port could have option "hardwired", for example Diaspora requires 443 regardless if you can open it or not. Then these ports we can show for user manual mapping in the Settings form depends on what apps user has installed.

**Comment by BenoitSvB** [comment]
I am just starting to discover Syncloud Personal Server,so I have no idea if the introduction of the concept "app requirements" is a good solution. For the moment I would appreciate a workaround to get Mail app installed without allowing UPnP. I prefer to manually setup port redirects on my router. Would it help if I did so before installing Mail?

**Comment by cyberb** [comment]
You could try mapping these ports: 25,110, 143, 587.

**Comment by cyberb** [comment]
We will concentrate on a single web port mapping at the moment (80, 443).
More complex setup like mail users should have all ports manually mapped or have public IP on device itself.
