### ISSUE TITLE
Implement backup for the device

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#250]
Could be simple: take the whole disk into archive, encrypt and put to the storage. Obviously it's storage space sensitive.

It also correlates to our ideas of migrating physical device into/from cloud.

**Comment by cyberb** [comment]
I was thinking about something like glusterfs to be able to attach syncloud devices and care less if they die.

http://gluster.readthedocs.io/en/latest/Quick-Start-Guide/Architecture/

**Comment by coffeehabit** [comment]
I was thinking that SyncThing might be able to be used - It uses a web interface for control. Install on each device you want to back up, and each device to back up to each other, pick your master/parent folders and choose your backup method - it supports simple, staggered, and external versioning techniques.

**Comment by cyberb** [comment]
Good idea, another option is to organise raid array with more than one usb drive.

**Comment by cyberb** [comment]
Syncthing is actually available on master channel:
https://github.com/syncloud/platform/issues/315
