### ISSUE TITLE
Community support forum

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#251]
We need to run something like discourse.org to allow users to share their experience. Currently we are using private support by mail which is useful but we cannot share it.

**Comment by muneebali** [comment]
Perhaps can have forum.syncloud.org

https://vanillaforums.com/en/

**Comment by klmhsb42** [comment]
you could use your own product and run it as syncloud app #452

**Comment by cyberb** [comment]
done: https://syncloud.discourse.group
