### ISSUE TITLE
ODROID-XU4 loses external disk /dev/sda1 during Nextcloud sync

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#252]
Hi Syncloud team,

on my ODROID XU-4, I recently replaced my old Syncloud 16.02 image with a fresh 17.03 image.

Since then, I noticed Debian loses the entry for my external drive (/dev/sda1) entirely after some time of normal operation (syncing data via Nextcloud).

`root@odroid-xu3and4:~# mount /dev/sda1 /opt/disk/external`
`mount: special device /dev/sda1 does not exist`

After rebooting the ODROID /dev/sda1 is available again and I have to reactivate the drive via Syncloud settings page. This solves the issue for maybe an hour, till the same behavior shows up again.

With Syncloud 16.02 (other Debian release?) everything was just fine.

Any ideas what might be wrong here?

Thanks,
jpma89

**Comment by cyberb** [comment]
Could you post dmesg output?

**Comment by cyberb** [comment]
Usual problem would be the lack of dedicated power supply, do you have one?

**Comment by jpma89** [comment]
dmesg indicated an issue with the file system of the external drive. fsck solved it. Thanks for your help.

**Comment by cyberb** [comment]
Maybe we need to offer users disk check feature and notification.
