### ISSUE TITLE
Device communication performance

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#26]
_From @cyberb on November 28, 2014 20:28_

We need to improve connection performance as I was told it is slow by random user.
I personally think it is.

Maybe http rpc would be faster, need to try.

_Copied from original issue: syncloud/apps#16_

**Comment by cyberb** [comment]
I think this is ok now, right?

**Comment by vsapronov** [comment]
Yes, let's close...

On Saturday, September 19, 2015, Boris Rybalkin <notifications@github.com>
wrote:

> I think this is ok now, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/26#issuecomment-141708908>.
>


-- 

Vladimir Sapronov
