### ISSUE TITLE
gogs: unable to commit from web and init repo

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#262]
Any web operation which involves git commits is not working.

Edit a file error:
Failed to update/create file 'README.md' with error: CommitChanges: exit status 128 - fatal: --author ''Boris' is not 'Name ' and matches no existing author 

Similar error on repo creation with init commit.

**Comment by vsapronov** [comment]
Could be missing git user problem. I'll take a look.

**Comment by cyberb** [comment]
Fixed, it was git bash wrapped swallowing parts of author CLI parameter.
