### ISSUE TITLE
Custom DNS

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#264]
Currently we use syncloud.it as our main DNS for all the devices and we have ddns service api.syncloud.it to maintain public device IP changes.

Some users would like to have their own DNS name to be used like example.com.

Currently if you create:
2. A record with your device public IP address for example.com
2. CNAME *.example.com for example.com

It should allow you to open apps like:
nextcloud.example.com
Or device itself: example.com

It will not allow you to get real SSL certificate from letsencrypt as device does not know that it needs to use example.com.

What we can do is to add a setting somewhere on access page to override main DNS name to allow real SSL certificates to work.

Also as we are not maintaining example.com it will not update public IP address changes as there is no ddns service (unless user allows example.com to Syncloud to manage, not sure if anyone wants this)

**Comment by chegeiser** [comment]
This is a big help! A setting to allow override of the main DNS name to change example.syncloud.it to example.com would be fantastic.

Thank you

**Comment by chegeiser** [comment]
Hi,

This works in getting me to the Syncloud login page - is there a way to do the same thing but point to the applications within Syncloud - like Nextcloud. Ideally something like nextcloud.example.com should take me to the nextcloud login page.

Thanks!

**Comment by cyberb** [comment]
I am working on this feature right now and I am planning to add custom domain option on activation page. It may take few weeks before I can do proper release with this feature.

**Comment by chegeiser** [comment]
That's great news! Thank you

**Comment by cyberb** [comment]
It will look like this:
<img src="https://user-images.githubusercontent.com/885528/30580145-749863dc-9d13-11e7-885b-fd14412e2c51.png" width="300">

**Comment by chegeiser** [comment]
That looks perfect. Does this mean the latest version has this up and running or is it still to come?

Also, will there be any way to convert a project from *.syncloud.it to *.com?

Thanks!

**Comment by cyberb** [comment]
I am still working on this, few other things have to be done.
It will be in the next release.
It is always possible to reactivate a device to another domain from settings.

**Comment by cyberb** [comment]
Will be available as part of 17.10 release
