### ISSUE TITLE
rocket chat

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#268]
We need to investigate https://rocket.chat/

**Comment by maedla** [comment]
yes, please!

**Comment by cyberb** [comment]
App will be published in the next release.

**Comment by maedla** [comment]
Very cool, Boris!


But unfortunately my Syncloud has stopped to work for more than a month.


________________________________

**Comment by cyberb** [comment]
You can send us logs from settings so we can check what happened or tell us what exactly is not working by email support@syncloud.it

**Comment by maedla** [comment]
Done... in a separeted email.

See also picture below. "Send logs" button doesn't work.


[Image]




Sent from my cellphone (+49 1522 1522110)

________________________________

**Comment by cyberb** [comment]
Sorry there is no image, could you send it directly to our support email?
Do not reply to github notification with your personal info.

**Comment by cyberb** [comment]
Cannot reply to your email, your mail service says:

    535 5.7.0 Incorrect username or password.

As to the device error you sent me, umfortunately I would suggest reflashing the image.

**Comment by maedla** [comment]
Apparently I have no email problem. Alternatively you can use marcelo.lang@gmail.com


How to reflash my image?


thanks!

________________________________
