### ISSUE TITLE
Wi-Fi Access Point app

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#27]
_From @vsapronov on December 29, 2014 22:24_

Any board with Wi-Fi could be a Wi-Fi access point. It's very useful when travelling to some random places. You can just plug Syncloud into Ethernet and have Wi-Fi and your local server all-in-one!

_Copied from original issue: syncloud/apps#18_

**Comment by cyberb** [comment]
Duplicate: https://github.com/syncloud/platform/issues/296
