### ISSUE TITLE
Nginx with http2

### ISSUE THREAD

**Issue by whitelake-city** [syncloud/platform#270]
It would be nice to have nginx running with http2. It doesn't need much to do. Nginx has to be compiled with the http2 module and it has to be enabled in the nginx config. 

http2 would increase of the pi due to less requests - at least when using a client that supports it.

**Comment by LeoGerber** [comment]
The raspbian now supports booting directly from usb devices - eg flash drives. It would be really awesome to support this.

**Comment by cyberb** [comment]
Should be fixed by https://github.com/syncloud/platform/commit/db74376532fc25200c42b4668415c44c0ee617b8
