### ISSUE TITLE
Boot from usb

### ISSUE THREAD

**Issue by whitelake-city** [syncloud/platform#271]
The raspbian distribution now supports booting directly from usb devices - eg flash drives. To do so a bit has to be programmed on the pie ([see raspberrypi.org docs] https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md) It would be really awesome to support this.

**Comment by cyberb** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you want to implement the feature.
Thank you!
