### ISSUE TITLE
RPi3 use multiple drives

### ISSUE THREAD

**Issue by diretix** [syncloud/platform#275]
Hello i have raspberry pi 3 fully configured. and 2 hdds connected via usb. bouth ext4, one of them is 1tb and another 300gb. when i try to switch the on in settings i can swith on only one drive ither 1tb or 300gb how can i connect them bouth to get 1300 gb? i also planned to add storage in future up to 4tb+ with multiple drives.

**Comment by cyberb** [comment]
As a first step for multiple disk management, we will try to implement some raid mirroring mode (https://github.com/syncloud/platform/issues/250).
As a next step we can probably implement more raid features like combine disks into bigger virtual disk drives.

**Comment by diretix** [comment]
what about if i want to connect ntfs hdd like my most used one and share some files from it, is it possible right now?

**Comment by cyberb** [comment]
ntfs is not supported and I do not think will ever be.

**Comment by diretix** [comment]
okay, thanks for help!
