### ISSUE TITLE
Question regarding privacy

### ISSUE THREAD

**Issue by MoeSattler** [syncloud/platform#277]
Is the data that I store on this device, and that uses the syncloud domain, in anyway or form accessible or stored by syncloud? Is it encrypted?

**Comment by cyberb** [comment]
Data is stored on device and no one has access to it except the owner who activated device and assigned it a password. Login and password is stored on device.

There is only one piece of information which is stored outside, DNS record for your device. So you or other people (if you enable external access mode) can can find your device.

At the moment data is not encrypted. Feel free to create an issue. We are accepting help from other people and eventually we will add this option.

**Comment by MoeSattler** [comment]
@cyberb meaning data is not encrypted on the device or in transport?

**Comment by cyberb** [comment]
Not encrypted on device.

Transport (channel between you and device) depends on access HTTP(S) mode.
HTTP is plain, but HtTPS is encrypted.

**Comment by MoeSattler** [comment]
Thank you @cyberb
