### ISSUE TITLE
Calendar/contacts app

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#281]
Currently people use Nextcloud calendar app but it is not very convenient as it is dependent on nextcloud and breaks sometimes because of nextcloud updates.

Something independent and potentially better is needed.
For example:
Web cloents: http://agendav.org/, https://www.inf-it.com/open-source/clients/caldavzap/
Servers: http://sabre.io/baikal/, http://www.davical.org/

**Comment by lil5** [comment]
@cyberb Strange I find it very convenient, if there are stability issues why not take it up with nextcloud
heres a link: https://github.com/nextcloud/contacts#readme

**Comment by cyberb** [comment]
Actually you may be right as we fixed recently nextcloud calendar/contacts issue and it was due to our problems not their. So I guess we can close this for now and live with what people actually like :)
