### ISSUE TITLE
Support for RasPi 3B+

### ISSUE THREAD

**Issue by veritas06** [syncloud/platform#285]
Any chance of support for the new 3B+?

Or if not support for the new model, it would be great if we could install SynCloud on top of a base image. That way we wouldn't have to wait for image support.

**Comment by cyberb** [comment]
Have you tried existing rpi3 image on rpi3b+ ?

**Comment by veritas06** [comment]
Yes, I tried the 3 image but no luck booting. I didn't get a chance to
check the hardware specs on each, but I'm guessing there's some different
hardware with the B+.

**Comment by veritas06** [comment]
Thanks cyberb. I'm now able to boot from that image you provided.
