### ISSUE TITLE
Unable to login in apps

### ISSUE THREAD

**Issue by osuiowq** [syncloud/platform#288]
Hello, after installing nextcloud it is unable to login or to reset the password. Is there any Default-Login or any configuration for Apps?

**Comment by osuiowq** [comment]
ok, with filebrowser and gogs login is working, but not with nextcloud.

**Comment by cyberb** [comment]
Do you have any special symbols in your login name like exclamation mark?
You could send us (or yourself first) logs from settings page to see what is the problem.

**Comment by osuiowq** [comment]
No, no special Symbols in my loginname, but in my PW. I send you the logfile.

**Comment by cyberb** [comment]
Everything seems alright in the logs.
Can you check what response you get from Nextcloud in browser network log (F12 )?

Do you even see Nextcloud login screen?

I would try to reactivate the device from settings to see if simpler login/password helps or it it just nextcloud failed to install properly.

**Comment by osuiowq** [comment]
I see the login Screen i can type my Logindata and get a wrong password at login and wrong user message on the pw-reset screen.

Networklog says: 200 GET login 
303 POST login

**Comment by cyberb** [comment]
Ok I see what is the problem, did you try to install two times? Looks like either simultaneous install happened or something similar. We are migrating to a new installer called snapd from Canonical which will prevent from such issues. The only solution right now is to reflash.

**Comment by osuiowq** [comment]
Thank you! Thats the Problem.
