### ISSUE TITLE
RPI 3 B+ No network

### ISSUE THREAD

**Issue by tmm72** [syncloud/platform#290]
I have a RPI 3 B+ device and imaged the syncloud. It boots to the login screen but never gets a DHCP address and tried to static the eth0 with no change in network status.
I am using image syncloud-raspberrypi3-18.03.01-sam.img

**Comment by cyberb** [comment]
Could you flash it again and then show dmesg output?

**Comment by cyberb** [comment]
Could you run:
dmesg | grep eth

Also do you have properly working ethernet cable, network led is green on device?
Do you get network working if you flash official raspberry pi image?

**Comment by cyberb** [comment]
What aboit:
dmesg | grep netw

**Comment by tmm72** [comment]
That is unfortunately blank also

**Comment by cyberb** [comment]
Hmm, hard to say, I do not have B+ yet, but other people have said mage is fine. Could take screenshots of every dmesg page by running dmesg | less and then using page down to skip pages ?

**Comment by tmm72** [comment]
I have attached the screen shots

![img_20180412_062957468_burst000_cover_top - copy](https://user-images.githubusercontent.com/29409290/38675371-173efd58-3e1d-11e8-9345-950d1ee602cd.jpg)
![img_20180412_063003822_burst000_cover_top - copy](https://user-images.githubusercontent.com/29409290/38675372-1758e8c6-3e1d-11e8-8f39-45a1d45ca2d6.jpg)
![img_20180412_063007961 - copy](https://user-images.githubusercontent.com/29409290/38675373-177038aa-3e1d-11e8-80c7-f62dc243e2b2.jpg)
![img_20180412_063014744 - copy](https://user-images.githubusercontent.com/29409290/38675374-178b7f0c-3e1d-11e8-9d7b-026b534571ac.jpg)
![img_20180412_063024930_burst000_cover_top - copy](https://user-images.githubusercontent.com/29409290/38675375-17b58fc2-3e1d-11e8-9bcc-dfb01646f754.jpg)
![img_20180412_063029875_burst000_cover_top - copy](https://user-images.githubusercontent.com/29409290/38675378-1838bbf4-3e1d-11e8-9548-c37cb7fbc205.jpg)
![img_20180412_062934284 - copy](https://user-images.githubusercontent.com/29409290/38675380-1853e424-3e1d-11e8-8d4f-ef35a20332b1.jpg)
![img_20180412_062942026 - copy](https://user-images.githubusercontent.com/29409290/38675381-187afbae-3e1d-11e8-9a07-86b9fa3bc4ed.jpg)
![img_20180412_062946874 - copy](https://user-images.githubusercontent.com/29409290/38675382-19059b06-3e1d-11e8-9a59-001e35fac7a2.jpg)
![img_20180412_062953362_burst000_cover_top - copy](https://user-images.githubusercontent.com/29409290/38675383-191ea128-3e1d-11e8-9915-20fd93a818ad.jpg)

**Comment by cyberb** [comment]
Thanks for the log.
Starnge there is no network error log. Looks like network driver either not present or cannot detect the device.
Probably it is a problem between Syncloud Jessie image and Raspbian Stretch kernel + drivers we merge together.
Maybe it is related to this question;
https://raspberrypi.stackexchange.com/questions/81725/raspbian-8-on-raspberry-pi-3-b
Could you post dmesg log from working raspbian?

**Comment by cyberb** [comment]
Thanks!
Could you try this image it is based on lite (not desktop) raspberry pi image.
http://artifact.syncloud.org/image/syncloud-raspberrypi3-18.04-sam.img.xz

**Comment by lil5** [comment]
@cyberb a bit off topic but why is the default build built with raspbian desktop?

Seems a little overkill as there's `raspbian-lite`.

**Comment by cyberb** [comment]
Agree, no reason just a mistake.
We are not really using any rootfs contents from these images, just extracting kernel, drivers and firmware:
https://github.com/syncloud/image/blob/master/tools/extract.sh

**Comment by tmm72** [comment]
cyberb I tried the 18.04 image and it doesn't even boot so not sure but something is missing

**Comment by tmm72** [comment]
Flashed with Raspbian Lite and it booted

**Comment by tmm72** [comment]
Here is the lite dmesg log
[puttylite.log](https://github.com/syncloud/platform/files/1915183/puttylite.log)

**Comment by cyberb** [comment]
Right, kernel command line is a bit different on lite, fixed (boot, not the network) and re-uploaded.
Could you try one more time?
http://artifact.syncloud.org/image/syncloud-raspberrypi3-18.04-sam.img.xz

My RPi3B+ is on the way so I hope to test myself in few days.

**Comment by cyberb** [comment]
Tested on my new 3B+ and it works fine, network is there. Could you test please?

**Comment by tmm72** [comment]
Well I am having no luck on my end. 
The network is still not working.
It is weird that the network works with the raspbian image but not yours.

**Comment by cyberb** [comment]
Could you run ifconfig on raspbian?

**Comment by tmm72** [comment]
Yes and that only returns the "lo" interface

**Comment by cyberb** [comment]
Could you post it?
If it has only lo, how can you connect to it?
We are talking about raspbian (non Syncloud)

**Comment by tmm72** [comment]
Here is from the raspbian image

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.88.249  netmask 255.255.255.0  broadcast 192.168.88.255
        inet6 fe80::a072:25d3:a41e:5004  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:ce:0e:24  txqueuelen 1000  (Ethernet)
        RX packets 144865  bytes 210455556 (200.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 91814  bytes 8027642 (7.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by cyberb** [comment]
Just in case, what are you using to write an image?
Could you try Etcher with verify mode enabled?

**Comment by cyberb** [comment]
Is it possible to attach dmesg one more time as a text file from Syncloud image?
You can run these commands:

    dmesg > /dmesg.log
    sync

Then shutdown the board and take SD card to a PC with network and mount its second partition to get this file.
I will diff it with my dmesg.

**Comment by cyberb** [comment]
Here is my dmesg with working network:
[syncloud.rpib3plus.good.dmesg.log](https://github.com/syncloud/platform/files/1933669/syncloud.rpib3plus.good.dmesg.log)

**Comment by tmm72** [comment]
Well I think after messing around on another network it is something on my network that is having issues I will have to look into more later

**Comment by tmm72** [comment]
Narrowed it down to my PiHole on the network blocking web access once I figured. Also I put it on a PI 3 not a plus version. So still haven't figured out my issue with Plus box yet

**Comment by Lenny5156** [comment]
Will you fix this bug, so it will run on a Raspberry Pi 3B+?

**Comment by cyberb** [comment]
There is no issue with RPi 3B+, I am sure as use one and we sell as well.

If you have a problem please open a new issue and add more details.
