### ISSUE TITLE
RPi 2B Not found with SyncloudApp

### ISSUE THREAD

**Issue by carlos3dx** [syncloud/platform#291]
I've followed the instructions for setup Syncloud on my RPi 2B, but when I try to activate it through the iOS app it says "No devices discovered".

The mobile and the RPi are in the same network, also I'm able to connect through ssh to the RPi.

**Comment by cyberb** [comment]
Can you access http://[device_ip]:81
This is device activation URL.
Discovery may not work on some networks, but all it does it uses this URL.
Also this may be a sign of incomplete flash or other issues.

**Comment by carlos3dx** [comment]
When I try to acess through URL the browser shows the following error.

> This site can’t be reached
> 192.168.1.112 refused to connect.
> Search Google for 192 168 112
> ERR_CONNECTION_REFUSED

I've downloaded the image again and flashed it a couple of times (with Ubuntu image writer and Etcher, both have a verification step) and never worked.

The micro sd has a capacity of 8GB and before flashing syncloud it had arch running on the pi.

**Comment by cyberb** [comment]
You said you can SSH to it with Syncloud image. Can you run the following command:

systemctl status platform.nginx-public

**Comment by carlos3dx** [comment]
Thanks @cyberb, the problem was that it was trying to resolve "localhost" it wasn't present at the hosts file. After editing the hosts file, syncloud starts without problem.

**Comment by cyberb** [comment]
I would like to fix the problem in our image so it does not happen again, could you post your new hosts file?

Here is how hosts file should look on the image: https://github.com/syncloud/rootfs/blob/master/bootstrap/armhf/etc/hosts

**Comment by carlos3dx** [comment]
127.0.0.1 raspberrypi2
127.0.0.1 localhost
::1 raspberrypi2
