### ISSUE TITLE
Mastodon App

### ISSUE THREAD

**Issue by celesteh** [syncloud/platform#292]
It's fantastic that this platform includes a Diaspora pod! Would you be willing to consider also including a Mastodon (or pleroma) instance and a ssb pub?

**Comment by cyberb** [comment]
There are some rules I am following for adding new apps:

1. It must be open source
2. It must be active and very popular (many github stars)

Also I want to cover basic set of tools first. One for each: social, files, music, messaging, mail ...

Apart from that I am open to any contributions.

**Comment by cyberb** [comment]
I must say Mastodon (https://github.com/tootsuite/mastodon) looks even better than Diaspora. Very active development, LDAP integration (missing in Diaspora) and many mobile clients. So I am thinking now that we should add it or even replace Diaspora.

**Comment by zhangzhengedu** [comment]
wordpress mattermost  i want

**Comment by marxistvegan** [comment]
Just to note the NextCloud social app is mastodon compatible but it still in alpha stage, but moving to beta from what I hear, unfortunately still no luck with it working correctly.

**Comment by cyberb** [comment]
Done
