### ISSUE TITLE
OpenVPN

### ISSUE THREAD

**Issue by michawer** [syncloud/platform#298]
Hi,

since the Syncloud already makes external access to the data and services on it possible, wouldn't it be an easy step to also offer an OpenVPN server service as a new out of the box capability of Syncloud?
It would be really nice to have the Syncloud serving as a VPN Server. So one could use one's own private VPN connection to the home network e.g. when being connected to a "unsafe" public Wifi network...
Thank you :)

**Comment by cyberb** [comment]
Yes, I will add this at some point.
At the moment I am concentrating on pure http based solutions as it does not envolve any additional port mapping requirements for non technical users.
It appears that nginx can tunnel VPN traffic through the same port but I need to read more to understand how it works.

**Comment by cyberb** [comment]
There is some web ui for managing client certificates and openvpn config itself:
https://github.com/adamwalach/openvpn-web-ui

**Comment by cyberb** [comment]
done
