### ISSUE TITLE
Proxy app

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#30]
_From @cyberb on September 23, 2014 8:38_

_Copied from original issue: syncloud/apps#10_

**Comment by vsapronov** [comment]
How about Tinyproxy: https://tinyproxy.github.io/
I need this app - friends in Russia suffer from Internet censorship...

**Comment by cyberb** [comment]
I have a lot of experience with haproxy.

**Comment by vsapronov** [comment]
Cool, haproxy seems to be copy deployable and already built into tar.gz.
Will start from it!

On Monday, April 4, 2016, Boris Rybalkin <notifications@github.com> wrote:

> I have a lot of experience with haproxy.
> On 4 Apr 2016 16:58, "Vladimir Sapronov" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > How about Tinyproxy: https://tinyproxy.github.io/
> > I need this app - friends in Russia suffer from Internet censorship...
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/syncloud/platform/issues/30#issuecomment-205366680>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/30#issuecomment-205397884>
>


-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
I guess this ticket is about forward proxy so probably squid is more like it.

**Comment by cyberb** [comment]
OpenVPN app fixed that problem tested on linkedin.com from Russia.
