### ISSUE TITLE
[nextcloud] unable to login

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#307]
````
Jun 20 17:00:10 odroid-xu3and4 ownCloud[1894]: {user_ldap} Configuration Error (prefix s01): login filter does not contain %uid place holder.
Jun 20 17:00:10 odroid-xu3and4 ownCloud[1894]: {user_ldap} Configuration Error (prefix s01): login filter does not contain %uid place holder.
Jun 20 17:00:10 odroid-xu3and4 ownCloud[1894]: {user_ldap} Configuration Error (prefix s01): login filter does not contain %uid place holder.
Jun 20 17:00:10 odroid-xu3and4 ownCloud[1894]: {user_ldap} Configuration Error (prefix s01): login filter does not contain %uid place holder.
Jun 20 17:00:10 odroid-xu3and4 ownCloud[1894]: {user_ldap} Configuration is invalid, cannot connect
Jun 20 17:00:10 odroid-xu3and4 ownCloud[1894]: {user_ldap} No LDAP Connection to server ldap://localhost
Jun 20 17:00:10 odroid-xu3and4 ownCloud[1894]: {index} Exception:
{"Exception":"OC\\ServerNotAvailableException","Message":"Connection to
LDAP server could not be established","Code":0,"Trace":"#0
````

**Comment by cyberb** [comment]
Looks like this happens when app is failing to install the first and users install it again over corrupted config.

Here is the workaround: https://github.com/syncloud/platform/wiki/Clean-app-configs-from-previous-install

**Comment by burij** [comment]
hi, sorry to barg you and thanks for amazing work. the workaround doesn't work for me. also after a clean install of syncloud and nextcloud i'm not able to login. first visit of nextcloud brings me to the login page (not the setup wizard). i also tryed the workaround and any possible combination of default credentials and credentials syncloud could alredy know. any idea?

**Comment by cyberb** [comment]
Syncloud configures nextcloud for users automatically on install, postgresql dB, local LDAP, trusted domain...
So you actually should see just login page after the install.

All the apps except

**Comment by burij** [comment]
ok, thx for the feedback. after third (!) clean install i manged to login with my normal login. it work with an older version of syncloud, not with the current one. somehow the current stable build fails to create the right user.

**Comment by cyberb** [comment]
I assume by clean install you mean image writing.
Did you change anything during those three attempts like different (simpler) login, waiting for Nextcloud install to finish?

Did it take three attempts using current (18.05) image or the old (18.03.01) one?

**Comment by burij** [comment]
no, i din't do anything special. first time i was in settings during the installation of nextcloud und changed ports, external drive etc. login failded. so i deleted nextcloud with the software center, deleted through ssh nextcloud folders, reinstalled nextcloud, login failed. then i wrote a knew image with the same current build, didn't during the installation anything, login failed. then i took older image, did the installation, login succeed.

**Comment by cyberb** [comment]
What board are you using?
I will do more testing.

**Comment by burij** [comment]
I'm using Raspberry Pi 3B

**Comment by ik0api** [comment]
I do have the same symptoms after a date-time issue with mi RPI4 with internal boot SD card and external USB disk.

Every app works except Nextcloud: when I reach the login page and insert the right login/px combinations of 3 different admin and user accounts I get the login mask appearing again. I'm sure about the 3 combinations.

My questions:

1 - can I recover or change admin password via SSH?

2 - What if I remove the Nextcloud app and reinstall it? Will I be able to see my files on the external disk If I use the same admin/pw combination of the old faulty installation?

Any other hints for this issue?

Thank you so much.

Marco
