### ISSUE TITLE
Diaspora app

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#31]
_From @cyberb on September 23, 2014 8:37_

_Copied from original issue: syncloud/apps#9_

**Comment by cyberb** [comment]
Initial preview implementation is complete.

Preferred access protocol is https, make sure to set it before installing it.

Some restrictions:
1. Install is very slow as it precompiles web static resources like js or css. Which also precompiles absolute URL (we may talk to diaspora people about it)
2. Domain or protocol change breaks diaspora and it has to be reinstalled.
3. Diaspora removed LDAP so users have to create separate account inside diaspora. We may try to maintain LDAP support for diaspora as there are some outdated branches with the code.
