### ISSUE TITLE
'module' object has no attribute 'prepare_storage'

### ISSUE THREAD

**Issue by zblev1** [syncloud/platform#312]
Trying to configure an external drive. I am getting the following error: 'module' object has no attribute 'prepare_storage' I have forwarded my logs.

**Comment by cyberb** [comment]
We did not get any error report, could you include support and send logs from feedback screen again?

**Comment by cyberb** [comment]
Log shows you have disk errors:

````
[ 3512.600583] blk_update_request: I/O error, dev sda, sector 3907028992
````

It may happen because you have no dedicated power for the hard drive or drive is actually bad.

**Comment by cyberb** [comment]
Reopen if you need more help.
