### ISSUE TITLE
Syncthing app

### ISSUE THREAD

**Issue by KovalevArtem** [syncloud/platform#315]
Было бы замечательно увидеть интеграцию с Resilio Sync и Syncthing

**Comment by KovalevArtem** [comment]
Замечательно что вы собираетесь интегрировать Syncthing... 

Resilio Sync - Freemium (платные только Premium функции)... По принципу как и в BitTorrent и μTorrent. Его вполне возможно использовать и бесплатно... Resilio Sync гораздо удобнее Syncthing. И еще (как не странно) более кроссплатформенный.

**Comment by KovalevArtem** [comment]
Yes, but not as active as Resilio Sync

**Comment by cyberb** [comment]
There is an alpha master channel, feel free to try.
Use you device login/password for its UI.

snap install syncthing --channel=master

**Comment by cyberb** [comment]
Suncthing app has been released.
