### ISSUE TITLE
Standard Notes notetaking app?

### ISSUE THREAD

**Issue by chegeiser** [syncloud/platform#316]
Standard Notes is a really nice open source encrypted notetaking app. It requires installation of Standard File (also open source). It allows fully sync of notes between multiple devices - all encrypted.

Desktop app: https://github.com/standardnotes/desktop
Web app: https://github.com/standardnotes/web
There are also Android and iOS apps on Github

Standard File: https://github.com/standardfile

Development is quite active. There's also an active Slack channel.

Thank you!

**Comment by cyberb** [comment]
Looks interesting, I guess you asking for an app based on their production-ready reference implementation of the standardfile protocol which all these clients use: 
https://github.com/standardfile/ruby-server

I guess this not what they are using behind their default cloud offering:

**Comment by chegeiser** [comment]
Hi,

There are two pieces to getting Standard Notes to work. First, StandardFile must be set up as the backend for the encrypted data. Then StandardNotes can be set up to serve up the web app. The mobile app can be downloaded free and should connect directly to the SF server.

**Comment by chegeiser** [comment]
This would be fantastic if you can integrate Standard Notes! 
Thank you,

**Comment by cyberb** [comment]
Are you using Syncloud already?
Have you tried to setup standard file server using their instruction?
Have you tried standard notes app to see how it works?

**Comment by cyberb** [comment]
Looks like they have no plans to add LDAP or any other external authentication mechanism. Which will force users to create an account inside standart notes in addition to a default devixe user account, similar to diaspora.

https://github.com/standardfile/ruby-server/issues/79

**Comment by chegeiser** [comment]
I’ve got it set up on a RPi now. Detailed installation instructions are attached.  
[Install SF RPi.txt](https://github.com/syncloud/platform/files/2898394/Install.SF.RPi.txt)

**Comment by cyberb** [comment]
Interesting, you are not using the official standard file server implementation.

Let me ask them if fhey have plans to do an ldap authentication.

**Comment by cyberb** [comment]
https://github.com/tectiv3/standardfile/issues/14

**Comment by cyberb** [comment]
There is no ldap there but they are at least open to pull requests. I can try adding it as I did similar thing for syncthing already.

So at this moment I whould create Syncloid package it as is to see how it

**Comment by cyberb** [comment]
I am busy at the moment adding app backup/restore support.
Do you want to try to package it for Syncloud?
You will get nginx/ssl for free.
I can create notes app repo

**Comment by chegeiser** [comment]
I’m pretty novice at this and don’t know how to package something. Slowly learning. Wish I could help. If I get up to speed on package I will certainly help out in this.

**Comment by cyberb** [comment]
I have a package ready.
Could you try this command:

snap install notes --channel master

**Comment by cyberb** [comment]
It may take some time for Let's encrypt to invlude this app into yoir certificate (took 5 minutes for me).

StandardNotes app should use server irl: https://notes.[name].syncloud.it/api

**Comment by chegeiser** [comment]
Is this set up to work on my personal domain? If so, i'll try that, otherwise I'll try the syncloud domain. Thanks!

**Comment by cyberb** [comment]
It should work on any type of domain.
https://notes.[your_domain]/api

**Comment by chegeiser** [comment]
This does spin up the Standard File server. I’ve got it running running at https://notes.[name].syncloud.it/api. For some reason it’s not allowing me to connect to it from Standard Notes. Will have to do some more digging.

**Comment by chegeiser** [comment]
Could it be that we need cors set to true in
/snap/notes/current/config.templates/standardfile.json
```
{
 "foreground": true,
"debug": false,
"socket": "{{ snap_common }}/web.socket",
"noreg": false,
"cors": false,
"db": "{{ snap_data }}/database.sqlite"
}
```

**Comment by cyberb** [comment]
It worked for me.

Can you open https://notes.[name].syncloud.it
You should see version and no certificate warning.

**Comment by chegeiser** [comment]
I do get the server at that address, with this message that indicates the server is up and running: Dashboard. Server version: v0.4.1-2-g0865706. 

The page does show an SSL certificate, but it says it is not a trusted certificate.  Were you able to actually access the SF server at register an account through Standard Notes?

**Comment by cyberb** [comment]
I was able to register and sync notes with android app after adding /api to the url.

**Comment by cyberb** [comment]
Probably certoficate is the problem.
Do you have a valid sertificate for your domain without notes?

**Comment by chegeiser** [comment]
It does seem to be a certificate issue, it's giving this error `NET::ERR_CERT_AUTHORITY_INVALID`. When after a day the SSL cert was still throwing this error I reactivated to my domain, and still get the same `NET::ERR_CERT_AUTHORITY_INVALID` error. 

This is true for https://notes.mydomain.syncloud.it as well as https://mydomain.syncloud.it (same is true when activated on my own domain).

Any thoughts on how to resolve this?

**Comment by cyberb** [comment]
Do you have port 80 open?
Network page should warn about this.
That is the requirement to get Lets Encrypt certificate at the moment. Port 80 is only used for certificate validation by Lets Encrypt .

**Comment by cyberb** [comment]
Did you fix the certificate issue?

**Comment by chegeiser** [comment]
I am still getting a cert error. On Firefox when I this when I view the certificate: "Could not verify this certificate because the issuer is unknown". The cert is listed as:
Issued To
Common Name (CN)          mydomain.com
Organization (O)                 Syncloud
Organizational Unit (OU)    Syncloud

I tried using https://www.sslshopper.com/ssl-checker.html and got this:
> The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error. The fastest way to fix this problem is to contact your SSL provider.

I do have port 80 open, and 443.

**Comment by cyberb** [comment]
You can send us logs from support page so I can check what letsencrypt log says.

**Comment by chegeiser** [comment]
Logs just sent. Thank you

**Comment by cyberb** [comment]
Did you include support?

**Comment by chegeiser** [comment]
I did include support.

**Comment by cyberb** [comment]
Got it.
So you are using a custom domain, but you do not have a wildcard dns record (A or CNAME).

A *.example.com [ip]

CNAME *.example.com example.com

Depending on what your dns provider supports, one is enough.

**Comment by chegeiser** [comment]
I've added the CNAME and it is now working!
Since I have another RPi running another domain 'this.mydomain.com' I should edit the nginx.conf at /var/snap/platform/common/config.runtime/nginx/ in order to add a proxy redirect to this other domain?

Standard Notes now connects to my SF server on Syncloud!

Thank you!

**Comment by cyberb** [comment]
Why do you need a redirect?
Why cannot you connect directly to the other device?

**Comment by chegeiser** [comment]
Got it working. Still learning my way around linux.

I can log in via the desktop StandardNotes app and the iOS app, but using the webapp (https://app.standardnotes.org) still throws a CORS error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://notes.cebaxo.com/api/auth/sign_in. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).[Learn More]`

I tried adding this to the server section of the nginx.conf: `add_header "Access-Control-Allow-Origin" *;` and I still get the error. I also tried editing the public.conf from `/var/snap/platform/common/config/nginx/public.conf` - no luck here either. I've attached the files (changed to .txt files so they can be attached)

[public.txt](https://github.com/syncloud/platform/files/2943927/public.txt)
[nginx.txt](https://github.com/syncloud/platform/files/2943928/nginx.txt)

**Comment by cyberb** [comment]
I guess this is cors flag in standardfile.json

Ideally standard notes web app should be part of our notes app so there is no cross origin problem. Let me check if I can add it.

**Comment by chegeiser** [comment]
This has all been working great now. I actually didn’t realize you included both the StandardNotes browser and the StandardFile db in the build. I have it all running at https://notes.mydomain.com and can also use the iOS app connecting to my db at https://notes.mydomain.com/api

Will this roll out as one of the standard apps offered through Syncloud?

Fantastic! Thank you!

**Comment by cyberb** [comment]
I am still fixing few things like extensions.
I will publish to the stable channel as soon as I fix them.

**Comment by viscropst** [comment]
Anyone else to upgrade the standardfiles to stable channel please. The stable version of server was outdated,and can't sign in with standardnotes app.

**Comment by cyberb** [comment]
What Syncloud app are you using, notes or standardnotes?

Notes was the first app and we had to decomission it as it did not support v2 of database format.

New app is called Standardnotes.

Latest Android app v3.125.0 is working ok with it for me.

**Comment by viscropst** [comment]
It's standardnotes. The Syncloud system was 1746,installer version was 312. I'm trying to signing in by standardnotes windows desktop version,but the dekstop app always shows "Invalid login credentials." . Then I just test the 0.9.0 and latest version of standardfile,It's working normally. After testing I checked out the standardnotes version of my Syncloud Server(hardware was Jetson Nano 2GB I newlly created image with 22.09) it's 0.6.8(as 168 in appcenter). Now I just download and install the standardnotes snap manually from the infomation of the latest ci,and finally working with standardnotes desktop version.
