### ISSUE TITLE
[Feature Request] Mailpile

### ISSUE THREAD

**Issue by marxistvegan** [syncloud/platform#321]
Hey all,

I think it would be great to offer [Mailpile](https://www.mailpile.is/) as an application for the Syncloud project. Mailpile is in development but one of the only applications I have found that offers a great web interface and encrypting emails from the start. If anyone is familiar with using GPG (aka PGP) email encryption Mailpile seeks to solve and the way they do it is before opening the mail client one has to enter their passphrase and then they can have access to their accounts. With a web interface the rest is really easy to follow and encrypting emails is more a natural easy step, something that i have found Enigmail and Thunderbird do an ok to confusing job with. Nonetheless I would like to propose to include it. 

Their development is being done [here](https://github.com/mailpile/Mailpile).

**Comment by cyberb** [comment]
Have you tried our mail app based on roundcube?
Can you compare them?

**Comment by marxistvegan** [comment]
> Have you tried our mail app based on roundcube?
I have not, mostly cause I am running on a beaglebone black and nextcloud consumes most of the resources, so I have been hesitant to add a new piece until I upgrade the device. But I could try it, however I have used roundcube before on other platforms and I do find the interface better than most, though often runs heavy and in my experience of running mailpile locally to test it, it is quite responsive and runs lightly. 

> Can you compare them?

I am going to try installing the roundcube in the coming days to test it out, but the gpg part is why I feel mailpile has a leg up on roundcube.

**Comment by marxistvegan** [comment]
Closing cause Mailpile development is not consistent enough for this to be considered at the moment, if and when it does then maybe reopen.
