### ISSUE TITLE
Torrent app

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#322]
rTorrent: https://github.com/rakshasa/rtorrent
Flood web UI: https://github.com/jfurrow/flood

Android client: http://www.transdroid.org/

**Comment by cyberb** [comment]
Transmission is the best candidate: https://github.com/transmission/transmission
Backend is written in c (ideal!) with web.

**Comment by ik0api** [comment]
> 
> 
> Transmission is the best candidate: https://github.com/transmission/transmission
> Backend is written in c (ideal!) with web.

Trasmission is a very light client but powerful and reliable, I totally sponsor it

**Comment by ik0api** [comment]
Ditto, it's a great, light and reliable app

**Comment by Drasila** [comment]
A torrent app is exactly what I need now.

**Comment by cyberb** [comment]
Transmission does not support unix socket and ldap, I qm not sure it supports any authentication. C lang does not make it easy to add :(

**Comment by cyberb** [comment]
While https://github.com/jesec/flood can use various torrent backends like transmission and it has some authentication mechanism. Written in js which is much easier to add ldap and unix socket mode. Of course nodejs is a resource hungry beast.

**Comment by cyberb** [comment]
Transmission has unix support now.
Will try to add ldap support: https://github.com/transmission/transmission/issues/6412

**Comment by cyberb** [comment]
Transmission app is out!
