### ISSUE TITLE
Interal Server Error

### ISSUE THREAD

**Issue by marxistvegan** [syncloud/platform#325]
Hey all, 
Oddly Nextcloud runs without error, but the syncloud core software page throws this error. This happened after a failed install attempt of the Mail (roundcube). The error was not seen in the GUI, I see this in the platform log. I have tried rebooting but to no avail, nextcloud continues to work but not able to install other Syncloud apps. What other logs would help? FYI I can ssh in. 
```
`23.225.30", "platform_version": "180729", "token": "***", "web_local_port": 443, "web_protocol": "https", "map_local_address": false}
{
  "message": "unable to run /opt/app/platform/bin/run_hook_action /opt/app mail post-install", 
  "data": {
    "py/reduce": [
      {
        "py/type": "__builtin__.Exception"
      }, 
      [
        "unable to run /opt/app/platform/bin/run_hook_action /opt/app mail post-install"
      ], 
      {}, 
      null, 
      null
    ]
  }, 
  "success": false
}
2018-09-20 14:56:30,474 - port_mapper_factory - WARNING - NAT-PMP mapper failed, message: NATPMPUnsupportedError(-11, 'The gateway does not support NAT-PMP'), {}
````

**Comment by cyberb** [comment]
That is just a warning that mail coild not add ports for you as yoi have no UPnP enabled.

I see you are usinf pre snap image, 
Could you try latest image from https://github.com/syncloud/platform/wiki

**Comment by marxistvegan** [comment]
> That is just a warning that mail coild not add ports for you as yoi have no UPnP enabled.
> 
> I see you are using pre snap image,
> could you try latest image from https://github.com/syncloud/platform/wiki

I could but i am more concerned as I am running beaglebone black and the microSD is where the OS is installed and the data directory. What is the best way to maintain data and upgrade?

**Comment by cyberb** [comment]
First of all do not write new image onto your existing sd card and use another one.

If you just want to preserve /data you need to copy all the contents into the new card after writing the image.

Why are you not using external usb drive foe data?

If you want to preserve all app settings (users, shares...) this is much more difficult and you will need to copy db files from correspoding app.

**Comment by marxistvegan** [comment]
> First of all do not write new image onto your existing sd card and use another one.
Noted

> Why are you not using external usb drive for data?

In all honesty, never really thought of it since the microSD has 32gigs of space. I will certainly explore it now.

> 
> If you want to preserve all app settings (users, shares...) this is much more difficult and you will need to copy db files from correspoding app.

The only app is nextcloud so I could prepare for a new instance instead of the backup process.

**Comment by cyberb** [comment]
All your files should be under /data/nextcloud/[user]/files/

You copy them to your new sd or external drive and run the following command so nextcloud knows about new files:

````
DATA_DIR=/var/snap/nextcloud/common /snap/nextcloud/current/bin/occ-runner files:scan
````

**Comment by marxistvegan** [comment]
> Did it help?

Sorry I have not had the chance to work on this. I would prefer to upgrade the device so I can use more of the tools. In the mean time can close this as unresolved.
