### ISSUE TITLE
Rock64 device support

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#329]
Image: https://dl.armbian.com/rock64/Debian_stretch_default_desktop.7z

**Comment by cyberb** [comment]
Image for testing is here: http://artifact.syncloud.org/image/syncloud-rock64-18.09.img.xz

**Comment by jungfred** [comment]
Image for testing Link is dead.
Or do i need to install the first link?

Is it planned to get this officially stable on rock64?

**Comment by cyberb** [comment]
It is on the download page now: https://github.com/syncloud/platform/wiki

**Comment by jungfred** [comment]
The image is'nt booting..
I tried it twice and flashed it with etcher

**Comment by cyberb** [comment]
Does this image boots for you?

https://dl.armbian.com/rock64/Debian_stretch_default_desktop.7z

**Comment by jungfred** [comment]
Yes, this one is booting fine

**Comment by cyberb** [comment]
Yes, we use it to convert to Sybcloud.
Do you have an hdmi output to see what Syncloud image says on the screen?

**Comment by jungfred** [comment]
If I try to boot up with syncloud-image I only see a blackscreen.

**Comment by cyberb** [comment]
Can you try this one: http://artifact.syncloud.org/image/syncloud-rock64-18.12.img.xz

Unfortunately I do not have a board to test it myself.

Also hdmi output would help if shows any error.

**Comment by jungfred** [comment]
With 18.12.img i'm getting bootloop:

Please see the following hdmi-output in two pictures:

Picture 1 - https://ibb.co/SPJ63cK
Picture 2 - https://ibb.co/4VGvt0q

After picture 2 its rebooting and shows the same again.

**Comment by cyberb** [comment]
Ok, one more fix for partition uuid.
Can you re-download this image: http://artifact.syncloud.org/image/syncloud-rock64-18.12.img.xz

**Comment by jungfred** [comment]
Now it shows this while booting:
https://ibb.co/2Khvr0B

Then it changes to login screen.
After I'm typing the login It shows this:
https://ibb.co/NSsC7rx

(The device is not found via App or ip-adress)

**Comment by cyberb** [comment]
Ok, can you run this command after it boots?

````
systemctl status snap-platform-181109762.mount
````

**Comment by jungfred** [comment]
This is the output after the command:
https://ibb.co/sWRcvJH

**Comment by cyberb** [comment]
Could you one more time latest image from:
http://artifact.syncloud.org/image/syncloud-rock64-18.12.img.xz

Also if it does not work run this:

````
zcat /proc/config.gz | grep SQUASHFS
````

**Comment by jungfred** [comment]
Its still not working. See the HDMI output here: 
https://ibb.co/BZb7mrV

After I typed again:
"systemctl status snap-platform-181109762.mount"
See the HDMI output here:
https://ibb.co/RSLVkHV

**Comment by cyberb** [comment]
Finally got new base image from Armbian with my kernel flag to support squash fs with xz.

Coukd you try http://artifact.syncloud.org/image/syncloud-rock64-18.12.img.xz

**Comment by cyberb** [comment]
Reopen if this image is not working.
