### ISSUE TITLE
Root password seems different from device password

### ISSUE THREAD

**Issue by raphraph** [syncloud/platform#332]
After activating device (through Syncloud app) the root password is supposed to be set to the password chosen when activating the device, but entering the newly set password when logging as root into the device (not with the browser but connecting a screen + keyboard) does not work, error message is 'Login incorrect'.

My keyboard is azerty, but device is set to qwerty, so when I type the password I have to refer to a qwerty layout. But I know that I'm typing the password correctly since I can test the keyboard layout in the login field.

Furthermore I can correctly login into Syncloud account from the browser using the login/password set on activation, so it is not a typo when typing password during activation...

Password is made of letters, numbers and special characters.
It sounds like I'm doing something very stupid, but it's kind of driving me crazy, I've made numerous tests and reactivated device a second time before writing this issue...

**Comment by raphraph** [comment]
OK so I made a few other tests and figured it out.
It seems that as soon as there is a $ in the set password then I can't login as root.

I did not try with other special characters so I can't say if it's only doing this with this character.
For the moment with passwords containing only letters and numbers it is working fine.

**Comment by cyberb** [comment]
Thanks for reporting 
This is fixed and released, check system updates (v181008701 and above)
