### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#334]
As we are using snapd it is possible now to enable auto updates of system (platform app) and apps.

Update process brings down updated app for a period of time from few seconds to few minutes depending on the app.

So I would start with explicit autoupdate checkbox which is off by default.

**Comment by Tizona1** [comment]
Hi Cyberb,
Please can you let me know how to enable the auto update?
Thanks
Chris

**Comment by cyberb** [comment]
Looks like our snapd package does not include auto refresh mode. I will spend some time understanding how it works and what is missing.

Probably it is due to exclusion of core snap.

**Comment by cyberb** [comment]
What did not work? Auto-update?
As I said auto-update is not working inside installer service itself (snapd) and reinstalling Nextcloud app cannot help.
This will require some work and new version of installer.
There is no ETA at the moment.

**Comment by Tizona1** [comment]
Sorry Boris, the mix-up is mine.
I had confused "auto-update" with the "external storage" issue that I am
facing.
I have inserted and formatted a 32 GB USB drive into the device USB port,
but I do not see external storage GUI in my App page.
[screen shots attached]
Is there any way that I can resolve this issue?
Thank you
Chris

**Comment by cyberb** [comment]
Please do not put unrelated comments into issue.

Disks appear in settings - storage.

**Comment by Tizona1** [comment]
Apologies Boris, the mistake is due to my confusion.
Regards
Chris

"sent from my mobile device"

**Comment by cyberb** [comment]
Automatic updates are now enables by default in the latest installer update.
It checks for updates daily around midnight and installs if there is any.
