### ISSUE TITLE
Multiple external disks raid support

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#335]
Currently we have no boards with more than one SATA connection in which case it should be possible to implement RAID mode selection (backup, performance...)

**Comment by klmhsb42** [comment]
- Following might be interesting for testing https://pchelp.ricmedia.com/build-raspberry-pi3-raid-nas-server/ 
- As the Odroid-N1 was announced to have two SATA connections http://linuxgizmos.com/rk3399-based-odroid-n1-sbc-doubles-up-on-sata-iii/ maybe the N2 is comming soon with two https://forum.odroid.com/viewtopic.php?t=31277
- This solution would be better then issue #336

**Comment by cyberb** [comment]
There are more options with intel cpu, for example:

1. Shuttle XH270, 4 disks (available as barebone)
2. Asus VM65N, 2 disks (not available as barebone)
3. Gigabyte BRIX Gaming BNi7HG4-950 (available as barebpne, expensive)

**Comment by klmhsb42** [comment]
Issue #399

**Comment by cyberb** [comment]
One more should be good even for gaming:
NUK8i7HVK: https://www.intel.co.uk/content/www/uk/en/products/boards-kits/nuc/kits/nuc8i7hvk.html
2 x M2 SSD disks.
Probably I should try packaging Steam.

**Comment by simoneburalli** [comment]
Odroid HC4 and its "toast" layout is apparently an interesting solution for RAID with mdadm:
https://www.hardkernel.com/shop/odroid-hc4/
Are you going to support this system? Thanks

**Comment by cyberb** [comment]
It should be difficult to support hc4: https://github.com/syncloud/platform/issues/566

**Comment by simoneburalli** [comment]
It seems like this is the link of a Ubuntu image for that system. What do you need to carry out a Syncloud image, usually? Thanks a lot

**Comment by cyberb** [comment]
Please comment under the corresponding issue.
We will build the image for hc4 so you do not need to do anything at this time unless you want to know how to to it yourself and help us :)

**Comment by cyberb** [comment]
hc4 is now supported.

**Comment by simoneburalli** [comment]
Hi Boris,
I would like to thank all the team and being that I cannot buy the HC4
directly from your shop yet, I'll compensate through a contribution for the
SW development.
Thanks a lot.

Simone

p.s. during these days I've played with Syncloud and Nextcloud, including
external access, Nextcloud Windows and Android clients and that's really
COOOOOOOOOOOOOL.


Il giorno dom 17 gen 2021 alle ore 16:45 Boris Rybalkin <
notifications@github.com> ha scritto:

**Comment by cyberb** [comment]
Closing this as RAID support is covered by this issue: https://github.com/syncloud/platform/issues/571
