### ISSUE TITLE
Custom case design

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#336]
Specification: https://www.zotac.com/us/product/mini_pcs/ri323#spec

This device has raid 0,1 support with 2 sata disks.

Currently cannot find where to buy in UK to test it.

**Comment by klmhsb42** [comment]
It seems, that it's not offered anymore. This could be an alternative https://www.asus.com/de/Mini-PCs/VivoMini-VC65R/ but I think it's not offered neither...

**Comment by klmhsb42** [comment]
I know, this issue has no high priority, but I think the design of your devices has the same importance as the functionality. And the less the user has to setup the hardware, the easier it is to do so. I think your devices should come directly with storage (with size selection options) as this could seem to the user as a hidden cost factor to buy an external one. A nice design could be realized by a self-made case. You could offer a Syncloud S, M and L.

In a first run, you could start with Syncloud S, which would include RPi, two USB flash drives (128 or 265 GB if it’s possible? and RAID), one USB Wifi dongle and one short USB extension cable. You could design the case in that way, that the USB flash drives and Wifi dongle are hidden by it and that there is just one USB connection open to get a real backup with a third USB flash drive. The case could also have your logo in a subtle way. And no transparent plastic, maybe just black rectangular shape. So, you would only need funding for a case, which should be the cheapest part. I don’t know, if you will need an own registration, if you sell it in such a modified way?

In future you could start with Snycloud M with an Odroid-N2 (which could be offered this year) with two SATA ports with two SSDs (500 GB or 1TB) and then later with Snycloud L with a Helios4 with four SSDs. In all ways, you could start with designing a case.

In general, it would be nice to have a backup and a shutdown/restart button on the hardware and maybe a small battery to bridge a power outage and to shutdown the device automatically in a save way. Maybe a LED or small display would be good, to see its status. I think you could rename this issue as designing own devices/cases. This are just ideas, let me know what you think…

**Comment by cyberb** [comment]
Sounds great.
Do you think we need different cases per board or it is possible to design one which can fit any board from Raspberry Pi to Helios4?
Like a small Alienware case.
It may have usb, power, network connectors which will be conected internally to a board.

Do you want to be more involved and investigate how much it may cost (design, production) for example in Germany?

**Comment by klmhsb42** [comment]
Thanks for your trust. I could certainly learn a lot from you, but I'm currently working in research and got my own time-consuming projects. Therefore, I wouldn't be a reliable partner. Anyway, I've drawn a simple scheme about my ideas, so maybe this could help you at least to get an estimate of costs by a manufacturer. Next step could be drawing it with a CAD software including more detail and exact proportion, but therefore you need the final hardware...

![syncloud](https://user-images.githubusercontent.com/44033489/47258191-fa57ac00-d497-11e8-8407-2d14f3f3243f.png)

Other question from my side. There is an wifi app issue. But, if the user wants to activate its device already with only wifi, then this wifi connectivity function must be embedded in the smartphone app as first activation step. The app must be also communicate with the server without connection to the local network. Will that be on any way possible or is there another way? I didn't want to create a new issue, but I think my question is not the same as the existing wifi app issue...

**Comment by cyberb** [comment]
I think Shuttle solved this problem long time ago :)
http://www.shuttle.eu/products/
