### ISSUE TITLE
PeerTube app

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#337]
Code: https://github.com/Chocobozzz/PeerTube

**Comment by klmhsb42** [comment]
it seems that this software can cause some serious cases regarding copyright as it's using BitTorrent protocol 
https://github.com/Chocobozzz/PeerTube/issues/713 

https://avideo.tube/ would be an alternative https://github.com/WWBN/AVideo

**Comment by cyberb** [comment]
Done
