### ISSUE TITLE
Nextcloud postgres dies sometimes

### ISSUE THREAD

**Issue by raphraph** [syncloud/platform#348]
After applying fix proposed in issue #347 , the generation of the LetsEncrypt certificate seems to have broken the Nextcloud app. Only two apps were installed (Nextcloud and Rocket.chat) and only Nextcloud app is broken.

Now when accessing Nextcloud I land on a blank page.

In debugger I only find this :
`Erreur lors du chargement de cet URI : Could not load the source for https://nextcloud.mydomain.com/.
[Exception... "Component returned failure code: 0x80470002 (NS_BASE_STREAM_CLOSED) [nsIInputStream.available]"  nsresult: "0x80470002 (NS_BASE_STREAM_CLOSED)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js :: onResponse :: line 569"  data: no]
Stack: onResponse@resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js:569:25
onStopRequest@resource://gre/modules/NetUtil.jsm:126:17
Line: 569, column: 0`

It's not the first time this happens to me, when I was playing around trying to generate a certificate of my own using certbot it also happened.
Rebooting does not solve the problem.

**Comment by cyberb** [comment]
Can you send logs to us or yourself to see if there is anything in syslog file?

**Comment by raphraph** [comment]
Not sure if sending logs is working (at least I'm not receiving anything...).
Should I send file to contact@syncloud.org ?

**Comment by raphraph** [comment]
Physical reboot did not solve the problem.

**Comment by cyberb** [comment]
Can you send logs one more time?

**Comment by cyberb** [comment]
Can you login using ssh and run this:
````
systemctl status snap.nextcloud.postgresql
````

Also try to start:
````
systemctl start snap.nextcloud.postgresql
````

And then status again

**Comment by raphraph** [comment]
Thanks !

Status was 'failed'.
But Nextcloud is up and running again after running `systemctl start snap.nextcloud.postgresql`

**Comment by cyberb** [comment]
Logs are sent to your email address you used to register an account on syncloud it.

Can you check your spam?

**Comment by raphraph** [comment]
Device is not linked to syncloud.it since I'm using custom domain. But maybe the link was created at activation ?
Spam folder is empty...

**Comment by cyberb** [comment]
Good point, you right if you have not created an account you still should be able to send us logs if needed, we need another issue for that.
Have you created and account before trying custom domain?

**Comment by cyberb** [comment]
Nextcloud postgres shows this in your syslog:

````
nextcloud.postgresql[288]: pg_ctl.bin: another server might be running; trying to start server anyway
````

Probably it was not stopped cleanly.
Still not sure why service start helped but device reboot which should start all the starts did not.

Will try to investigate that

**Comment by raphraph** [comment]
> Have you created an account before trying custom domain?

Yes, I first created an account to test with syncloud domain service. Then reactivated with custom domain.
But later I wrote a new image on the SD card, and when activating the device I used the app and I don't remember if it was linked to the syncloud.it account already or not...

**Comment by cyberb** [comment]
We have migrated to postgres 10, please reopen if this happens again.
