### ISSUE TITLE
First login for apps - credentials?

### ISSUE THREAD

**Issue by chegeiser** [syncloud/platform#353]
I added 4 apps (Nextcloud, Syncthing, GOGS and Diaspora) - for the first two the Syncloud login credentials got me logged in, for GOGS and Diaspora I'm not able to log in with those same credentials. Are there default credentials for GOGS and Diaspora?

Thank you!

**Comment by cyberb** [comment]
You need to use exactly the same username/passowrd as eas user for device credentials.

What format of username are you using, username or username@domain.com?

Can you uninstall all other apps and try again?

Can you reflash the image, activate and just install gogs?

**Comment by cyberb** [comment]
Juat tried custom domain and used test/test1234 activation credentials.

Installed only gogs and was able to login.

Could you try the same to check if is related to login password incompatible symbols or not?

**Comment by chegeiser** [comment]
I tried with a fresh flash using the test/test1234 activation credentials and Gogs worked. Then I tried again with my credentials and it wouldn’t work. I finally figured out that a username of ‘admin’ is the problem. Changing to a different username fixed the issue. Then I retried with a password that does have a symbol and that worked. So the issue was that ‘admin’ can’t be used as a username.

**Comment by cyberb** [comment]
Missed your diaspora roles question, check this instruction: https://github.com/syncloud/platform/wiki/Diaspora

Let me check why admin is not allowed in Gogs.

**Comment by cyberb** [comment]
admin is reserved name in gogs: https://github.com/gogs/gogs/issues/2040

**Comment by cyberb** [comment]
Should we close this issue?

**Comment by chegeiser** [comment]
This has resolved the issue: don't use 'admin' as the username for Gogs.
