### ISSUE TITLE
Nextcloud admin user unable to update email in settings

### ISSUE THREAD

**Issue by marxistvegan** [syncloud/platform#355]
Hey all I am going to add a screen shot so one can see what I am looking at, this is on the Personal Settings page.
![screenshot from 2018-11-08 16 08 14](https://user-images.githubusercontent.com/6064303/48227515-8e6ab400-e370-11e8-9399-1664de2bc798.png)

This happened on my previous syncloud setup too but i was not using it as thoroughly. Note that the phone number section can be updated but the email and name cannot be altered.

**Comment by cyberb** [comment]
I am working on "users" app which will allow to modify/add/remove users on a device: https://github.com/syncloud/platform/issues/148

**Comment by marxistvegan** [comment]
I can close this, I was able to add the email address which was necessary for inviting attendees to a calendar event, by going to the user section and adding it there.
