### ISSUE TITLE
Can't commit file on Gogs: permission denied

### ISSUE THREAD

**Issue by chegeiser** [syncloud/platform#357]
The error shown below is what I get when I try to create and then commit a new file in Gogs. I've not been able to upload files, or to create files - they all give this permission denied error. This is with the admin account and with another user account.

Failed to update/create file 'index.html' with error: UpdateLocalCopyBranch [branch: master]: git clone master: mkdir data: permission denied

This is with Syncloud version 181109762 running on my own domain.

**Comment by cyberb** [comment]
New gogs version with the fix was released, could you upgrade it from app center?
