### ISSUE TITLE
Nextcloud Dashboard install error

### ISSUE THREAD

**Issue by marxistvegan** [syncloud/platform#358]
Hey all, 
Nextcloud is running well, but i am not able to add the Dashboard app, i get this error

```
An error occured during the request. Unable to proceed.
An exception occurred while executing 'INSERT INTO "oc_dashboard_settings"("id","key","value") VALUES(?,?,?)' with params [1, "show_activity", 1]: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "oc_dashboard_settings_pkey" DETAIL: Key (id)=(1) already exists.
```
Which makes it seem I had it installed but I am not sure how to resolve it.

**Comment by cyberb** [comment]
I guess you need to contact dashboard app devs with this question first.

**Comment by marxistvegan** [comment]
I see an approach to solving this, https://github.com/nextcloud/dashboard/issues/40, but I am not sure how to access the nextcloud database.

**Comment by cyberb** [comment]
You can enter the database shell using the following command:

````
/snap/nextcloud/current/postgresql/bin/psql -U nextcloud -h /var/snap/nextcloud/common/database -p 5436
````

**Comment by cyberb** [comment]
Then you can execute their truncate command

**Comment by marxistvegan** [comment]
OK the truncate command worked, but another issue arose, I am going to close this as it does appear to be an issue upstream.
