### ISSUE TITLE
Links from website into Wiki content 

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#359]
It’s not a high priority issue, but one idea how you could make your website more user-friendly would be to integrate more links from the website into the pages of the github-Wiki. For example:

On https://syncloud.org/setup.html you say “Setting up Syncloud device is easy as one-two-three” but you could link to https://github.com/syncloud/platform/wiki/Things-to-know-before-buying-a-device 

Or in `[device name].syncloud.it` you could link to https://github.com/syncloud/platform/wiki/Unable-to-access-device-from-local-network and https://github.com/syncloud/platform/wiki/External-access to avoid same user questions

Under “Storage” link to https://github.com/syncloud/platform/wiki/Backup-SD-Card 

Or in the FAQs you could set links. E.g. under “Can I access my device from anywhere through Internet?” same link to https://github.com/syncloud/platform/wiki/Things-to-know-before-buying-a-device and https://github.com/syncloud/platform/wiki/External-access

**Comment by cyberb** [comment]
Sounds good, do you want to publish pull requests with the changes to corresponding projects?

syncloud.org => https://github.com/syncloud/syncloud.org

syncloud.it => https://github.com/syncloud/redirect

**Comment by klmhsb42** [comment]
I cloned the master branch and edit the files in my local repository. I've pressed commit to master and then tried to push origin, but an error occurs. Do I have rights to do that or which branch should I clone and push? What's the difference to pull request? Sorry, I'm a github beginner...

**Comment by cyberb** [comment]
You should fork the repo into your personal repo, make the changes on your repo and then create a pull request.

https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by cyberb** [comment]
Changes are pushed to https://syncloud.org
For now I will not wait for cn/fr translations as it may take some time (they will show english version)

**Comment by klmhsb42** [comment]
My first pull request motivated me to continue. Thanks for merging so quickly. I'm trying to open https://github.com/syncloud/platform/tree/master/www/public in browser. I've installed NodeJS and npm. But I got some error 

"ERROR in multi ./node_modules/webpack-dev-server/client?http://localhost:8888 ./src
Module not found: Error: Can't resolve './src' in '/var/www/html/platform/www/public'
 @ multi ./node_modules/webpack-dev-server/client?http://localhost:8888 ./src main[1]
ℹ ｢wdm｣: Failed to compile"

And the browser shows "Cannot GET /platform/www/public". Do I've to set some index.html in the webpack.config.js ? I don't get it...

**Comment by cyberb** [comment]
Did you npm install ?
What OS are you using?

**Comment by klmhsb42** [comment]
Yes, npm install. Using debian... I've to read more about it... Just thought maybe you have direct idea... I don't need tomcat, right?

**Comment by cyberb** [comment]
No, webpa k will use its own webserver.
What exact command gives you this error?

**Comment by klmhsb42** [comment]
Ok, I tested on Windows and getting to the same as on Debian (forget the error message from above, I messed it up yesterday). I just simply did:

(1) Download (.msi file) and install Node.js here https://nodejs.org/en/ (Download for Windows (x64) - 10.16.0 LTS Recommended For Most Users)
(2) npm install http-server -g
(3) http-server "C:\platform\www\public"

When I open IP:Port/index.html there is no error message and it loads even the favicon (so it had to load the /template/meta.html) but "<%= require('html-loader!./template/meta.html') %>" is still written as html text... See screenshot...
![screenshot](https://user-images.githubusercontent.com/44033489/62156758-eafd6d00-b30b-11e9-86b2-c7b899fa1009.png)

**Comment by cyberb** [comment]
Where did you get these commands?
Did you follow these steps?
https://github.com/syncloud/platform/blob/master/README.md#web-ui-development

**Comment by klmhsb42** [comment]
Ok, I followed at the beginning, but then I was lost. I tried just your steps again, now it's working :) sorry for stealing time. I will let you know when I've some new pull request...

**Comment by klmhsb42** [comment]
I played around with some ideas https://github.com/klmhsb42/platform/tree/master/www/public
Let me know what you think... Also I've never worked with nodejs, so I've to read more about it to do final working implementation... But, if you think it's good, I would keep working on it...

**Comment by cyberb** [comment]
@klmhsb42 I am happy that you want to help us! Is this work related to this issue, if not let's close it and open more specific one?
I have checked the UI changes and so I would really like to understand what are you trying to achieve?  Nicer UI, new features, ... I do not want to waste your time.

I hope we can discuss those changes in an appropriate issue, but for me the general rule is:
1. We try to keep minimalistic approach in UI design, kind of how Apple does UI. Less buttons less problems for users (sub menu idea). I guess Google's material design is all about it.
2. Same for platform UI features (system/security idea), at the moment we look for good existing open source web app to implement various useful features. I beleive there are many good system monitor and security tools out there, so I would encourage people to concentrate on app packaging. 

![Screenshot from 2019-08-01 22-09-40](https://user-images.githubusercontent.com/885528/62327668-1ff2f680-b4a9-11e9-8e90-e78ef975553a.png)
