### ISSUE TITLE
Wildcard certificates

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#360]
We need to implement certbot's wildcard certificate support.

This will remove the need for http port 80 availability as it uses txt dns record verification mode.
It will be only available for syncloud.it domains as we control the dns.

Custom domains will still have to use http verification mode as we do not control the dns.

**Comment by Tizona1** [comment]
Hi Cyberb, is there an ETA for this implementation?
After it is implemented,  can I disable the port forward rule for "80".
Thanks
Chris

**Comment by Tizona1** [comment]
Thank you!
Had I the expertise you would have had a volunteer.

**Comment by cyberb** [comment]
Implementation is done just testing various cases.

**Comment by cyberb** [comment]
Released

**Comment by dumblob** [comment]
>It will be only available for syncloud.it domains as we control the dns.

Hm, why? Everybody who sets up their custom domain (buys it) has by definition control over their DNS.

This is actually the second biggest reason to run own email/... server. Namely to have full control over DNS.

Is the wildcard support really only available (hard-coded so to say) for syncloud.it domains?

**Comment by cyberb** [comment]
wildcard support is available for personal domain on premium yes, the original comment was made on 2018 :)

**Comment by cyberb** [comment]
https://github.com/syncloud/platform/wiki/Premium

**Comment by dumblob** [comment]
Please refer to https://github.com/syncloud/platform/issues/583#issuecomment-1407090332 for explanation why this should not be part of premium if one wants an email server (with non-email services this is OK and can stay premium).
