### ISSUE TITLE
Beaglebone black image

### ISSUE THREAD

**Issue by Danieliko** [syncloud/platform#362]
Hi!

I has trying to install Syncloud in a Beaglebone Black board. I have not do work it. Board runs fine with BB Debian image. May be Syncloud BBB image is broken?

PD: Installing nextCloud's snap in BBB Debian image works, but performance is very very... very poor. I think it's not a good idea to maintain an image for a board with not enough performance. People can get wrong thinking Syncloud is a heavy and slow solution.

**Comment by cyberb** [comment]
Let me check the image.

**Comment by cyberb** [comment]
Right there was a problem with single partition base images and I have reuploaded it.
Could you download again and try?

**Comment by Danieliko** [comment]
Ok.
The new image works perfectly.
I've installed and configured it using Android app.
NextCloud still being so heavy to beaglebone black, but I'm testing
syncthing and promise to work fine.
Thanks and congrats!

**Comment by cyberb** [comment]
Good.

Regarding performance I agree this board is not powerful for Nextcloud, but Nextcloud is not the only app. Also there are other reasons like testing.

Should we close this issue if image is working?

**Comment by Danieliko** [comment]
Yes, please.
