### ISSUE TITLE
The external is not working he settings page.

### ISSUE THREAD

**Issue by Tizona1** [syncloud/platform#363]
Hello,
The external is not working and always resets to OFF when I switch it ON after refreshing the settings.
Opening up UPnP, is a security risk [the solution for #230], please can you provide an alternate?
The ISP's modem is in bridge mode and my router is an Asus RT-AC68U with firmware at 3.0.0.4.384_45149.
Thank you
Chris

**Comment by cyberb** [comment]
If you press question mark it will tell you what to do in case you have no upnp you can open two ports (80, 443) manually.
Have you tried that?
Also do you have external ipv6 or ipv4?

**Comment by Tizona1** [comment]
Hello,
With Boris's help, this issue has been resolved.
What was done:
1. Port Forwarding for HTTP -> <device IP> 80
2. Port Forwarding for HTTPS -> <device IP> 443
3. IPV6 disabled
