### ISSUE TITLE
Attach a NAS with virtual partitions to the Syncloud device

### ISSUE THREAD

**Issue by Tizona1** [syncloud/platform#365]
Dear Development Team,
I am excited to be able to use Syncloud as my "personal" cloud - thank you!
Is there a method whereby I can attach a NAS to the Syncloud device as my Cloud?
Currently, this NAS is accessible as a shared drive to any computer on my local network.
This is a RAID2, 1TB,Synology DS216 with four virtual partitions and would like to be able to access the data and/or give selective access to other Users, when we are away from the home network.
Thank you,
Chris

**Comment by cyberb** [comment]
Nextcloud app has external storage support: https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/external_storage_configuration_gui.html

**Comment by Tizona1** [comment]
Please can you let me know from where I can download and install the "External Storage Support" ?
The screen shot below shows that this App is not available to me from "App Center".
![app_center](https://user-images.githubusercontent.com/47007120/51935143-3bcef000-23d3-11e9-8d6c-7d3c90159141.jpg)

For reference, I have attached a screen shots of the USB storage that has been plugged into the USB port of the device and the Apps that I have currently been able to download

![my_apps](https://user-images.githubusercontent.com/47007120/51935293-95371f00-23d3-11e9-9f5c-f07fd1348e32.jpg)
![external_disk](https://user-images.githubusercontent.com/47007120/51935304-9b2d0000-23d3-11e9-9400-701a846bae6e.jpg)

**Comment by cyberb** [comment]
External storage support is a feature of Nextcloud app.
Open Nextcloid app and follow the instruction mentioned above.

I understand it is a little bit confusing, Syncloud, Nextcloud ... ;)

Syncloud is an easy to use app store and that is pretty much it.

**Comment by Tizona1** [comment]
Here is what I see when I open the Nextcloud app, please correct me if I am not opening the right menu.
![nextcloud_menu](https://user-images.githubusercontent.com/47007120/51941181-f36afe80-23e1-11e9-91f8-2cd0b4b1e03f.jpg)

**Comment by Tizona1** [comment]
I have carefully read the document.
The problem is that the external storage app in Nextcloud is not visible.
I have uninstalled and re-installed the Nextcloud app, but the "external storage" app, is not available or visible.
When I log in to Nextcloud, I get the screen as shown in the post above.
The options as documented in the weblink are not available.
Please help.
Thanks
Chris

**Comment by cyberb** [comment]
Nextcloud -> add apps -> scroll down -> enable "External storage support"

**Comment by Tizona1** [comment]
Thank you for your patience with my issues.
The have the "External Storage Support" enabled.
![external storage support](https://user-images.githubusercontent.com/47007120/52066429-858c1780-2546-11e9-94aa-5fe31c0ffb45.jpg)
I am not able to see or access this.
![configuring external storage gui nextcloud 15 administration manual 15](https://user-images.githubusercontent.com/47007120/52066544-c7b55900-2546-11e9-9fff-d2566c4e5aff.jpg)
This is My App page.
![my app page](https://user-images.githubusercontent.com/47007120/52066579-d69c0b80-2546-11e9-8305-c6940136b249.jpg)
This is the menu I get when I log into Nextcloud
![nextcloud_menu](https://user-images.githubusercontent.com/47007120/52066638-f59a9d80-2546-11e9-90e3-c8bb2de47b14.jpg)
I have enabled external storage
![external usb drive](https://user-images.githubusercontent.com/47007120/52066706-14992f80-2547-11e9-9c32-02ec03ba901d.jpg)

Please help!

**Comment by Tizona1** [comment]
![external storage permission](https://user-images.githubusercontent.com/47007120/52066952-81142e80-2547-11e9-874b-6e0d584ebca2.jpg)

**Comment by cyberb** [comment]
You need to use google a little bit :)

https://help.nextcloud.com/t/no-permissions-to-configure-external-storage/29411

This is user view.
You need to go to Profile - Settings - Administration - External storage

**Comment by cyberb** [comment]
And to your previous question, Syncloud storage will tell Nextloud to store all its data to that diak (see question mark)

Nextcloud external storage allows you to connect additional network drives.

**Comment by Tizona1** [comment]
Thanks for pointing out that I need to go to the Admin settings [all the while I was looking at the User settings!]. In connection with this, one more request - how do I configure the attached USB drive in here
![configure_external_strorage](https://user-images.githubusercontent.com/47007120/52072166-74490800-2552-11e9-8650-ea81db9cff1a.jpg)

**Comment by Tizona1** [comment]
https://www.youtube.com/watch?v=pcAvknt53vs

This problem solved, 
[Actually it was not a problem, the information is there and I just needed to see it]
Thank you
Chris
