### ISSUE TITLE
Access to the External Drive

### ISSUE THREAD

**Issue by Tizona1** [syncloud/platform#366]
Hello!
With your help and the instructions here:
https://docs.nextcloud.com/server/14/admin_manual/configuration_files/external_storage_configuration_gui.html
I was able to create the external storage.
The problem is that I do not have the "permissions", even though I am the creator of the drive and have assigned the permissions.
Please let me know what it is that I am missing?

Screen print of the External Storage

![external_storage](https://user-images.githubusercontent.com/47007120/52226161-3150a280-287a-11e9-8124-6e3d70857911.jpg)

Screen print of the "no permissions"

![no_permissions](https://user-images.githubusercontent.com/47007120/52226197-504f3480-287a-11e9-9235-b6f15f418ee1.jpg)

Screen print of my  "identity"

![tizona_identity](https://user-images.githubusercontent.com/47007120/52226231-5e9d5080-287a-11e9-9fbf-152f26bb37ab.jpg)

I have also referred to these instructions:
https://docs.nextcloud.com/server/14/admin_manual/configuration_files/external_storage_configuration_gui.html#user-and-group-permissions

**Comment by cyberb** [comment]
Are you trying to use a local usb disk as an external disk from nextcloud?
This is not the right way to use it.
External storage support in nextcloud is for NAS devices and other network disks.

If you have local disk attached all you need to do is activate it in Syncloud disks and all your apps will automatically store their data on it.

**Comment by Tizona1** [comment]
Thank you for correcting me.
Now, I have plugged in my Synology NAS to the USB port on the device.
The Synology NAS has a fixed IP and is accessible to computers on my home network.
I would like to be able to use Nextcloud to access the Synology NAS from external Networks/Internet.
This is the Synology NAS:
https://global.download.synology.com/download/Document/DataSheet/DiskStation/16-year/DS216/Synology_DS216_Data_Sheet_enu.pdf

Which of these options should I select:

![configuring external storage gui nextcloud 15 administration manual 15 docum](https://user-images.githubusercontent.com/47007120/52368005-621c0d80-2a1b-11e9-933d-11ad1fcfd16c.jpg)

Please suggest - thank you.
Chris

**Comment by Tizona1** [comment]
![externalstorageoption](https://user-images.githubusercontent.com/47007120/52368311-17e75c00-2a1c-11e9-8798-9eac52b8cfb7.png)

Apologies, this is the correct screen shot of the options that I have [the previous screen shot was taken from the Nextcloud documentation]

**Comment by cyberb** [comment]
> Now, I have plugged in my Synology NAS to the USB port on the device.

I hope Synology Nas is not plugged to Syncloud device USB port as ot will not work.
Nas should have independent power amd network.

> Which of these options should I select:

It really depends on what NAS supports, I would read their docs. 
Probably one of the last four.

**Comment by cyberb** [comment]
Stale
