### ISSUE TITLE
Nextcloud internal server error

### ISSUE THREAD

**Issue by Tizona1** [syncloud/platform#367]
Am able to log in to Syncloud, but clicking on the Nextcloud icon results in a screen with the "internal server error" message. The logs have been sent
Powering off the system and powering it on again did not resolve the issue.
[This may not be relevant but the only change that was made is that I have unplugged the USB drive from the device USB port and plugged in a 2 RAID NAS drive, please refer to issue #366]

![nextcloud internal server error](https://user-images.githubusercontent.com/47007120/52311475-07c87180-2975-11e9-9d35-91cd02740c81.jpg)

**Comment by cyberb** [comment]
Did you dectivate this disk in Suncloud first?
You cannot just take disk out of it is activated in settings.

What Syncloud -  settings -disks shows?

**Comment by Tizona1** [comment]
Hi,
To answer the question, the disk [USB drive] was deactivated first and then disconnected.
I was able to work around the issue by un-installing and re-installing the Nextcloud App.
Thank you for your help.
Best,
Chris
