### ISSUE TITLE
Can't use encrypted SATA driver as external storage

### ISSUE THREAD

**Issue by elsalanzo** [syncloud/platform#368]
I'd like to use my encrypted and mounted SATA disk but I get this error. 

<img width="599" alt="error message" src="https://user-images.githubusercontent.com/46665255/52320882-1bc3b000-2a15-11e9-8295-71c4fcbe15cc.png">
<img width="598" alt="confirmation" src="https://user-images.githubusercontent.com/46665255/52320883-1bc3b000-2a15-11e9-9069-dfd1e946ecb6.png">
<img width="554" alt="storage list" src="https://user-images.githubusercontent.com/46665255/52320884-1c5c4680-2a15-11e9-9f2e-340f29aaa037.png">

**Comment by cyberb** [comment]
Do you need encryption on that disk?

Just curious why do you need it? Is it not safe where device is located?

**Comment by elsalanzo** [comment]
The disk is already encrypted and yes it's not safe since it's located in a share house. I just don't want someone unplug the driver and access my datas.

**Comment by cyberb** [comment]
I see.
At the moment we do not support activating anything other than ext* filesystems as we depend on linux filesystem features like permissions.
Probably we can add disk encryption at some point as Syncloud feature.

### Workaround (hacky):
1. Move contents of /opt/disk/internal to /opt/disk/internal_backup
````
mv /opt/disk/internal /opt/disk/internal_backup
````
2. Mount you disk under /opt/disk/internal

3. Copy contents /opt/disk/internal_backup to /opt/disk/internal
````
cp -R /opt/disk/internal_backup/.  /opt/disk/internal
````
It should look like this in the end:
````
root@helios4:~# ls -la /opt/disk/internal/
total 16
drwxr-xr-x 4 root      root      4096 Jan 14 19:11 .
drwxr-xr-x 3 root      root      4096 Nov 14 22:12 ..
drwxrwx--- 6 nextcloud nextcloud 4096 Jan  9 16:05 nextcloud
drwxr-xr-x 3 root      root      4096 Jan 14 19:11 platform
````

**Comment by elsalanzo** [comment]
That's cool! I did it. It seems okay no problem. Thanks for the workaround! 

I'm looking forward to see the support for encrypted disk feature. 

Happy coding!
