### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#37]
Users reported having public IPv6 from their ISP (WAN) and still having IPv4 on LAN

**Comment by cyberb** [comment]
We would like to gather different use cases here to understand how different ipv6 configurations look like.

Syncloud device should be listening on both ipv4 and ipv6 assigned addresses.

1. Do you have ipv6 assigned to Syncloud device?
2. Can you access that IP from other ipv6 networks (mobile)?
3. Do you have a mix of ipv4 and ipv6?

You can use this any 'ipv6 test' websites to get more info about your setup.

We may add ipv6 section in settings to give you more info.

**Comment by jpma89** [comment]
I tested Nginx with IPv6 on my BeagleBoneBlack with a standard Debian image. The Nginx of the Syncloud image is lacking the "--with-ipv6" option as far as I could see. 

Direct access via IPv6 address as well as access via type AAAA DNS worked fine for me after applying proper port filter settings on my router. However external access only worked with IPv6 enabled devices/networks. This also prevents customers from being able to use VPN.

Most mobile networks (at least in Germany) and some public WiFis are not yet IPv6 ready unfortunately. To overcome this issue, some NAS providers offer some kind of relay service to their customers (e.g. Synology QuickConnect).

The "DS lite" method most cable ISPs in Germany use for their non-business customers, offers a large range of external IPv6 addresses but the external IPv4 address is shared across multiple customers and cannot be forwarded to in internal device. However most IPv6 test websites indicate that DS lite customers have both an IPv6 and an IPv4 address.

**Comment by jpma89** [comment]
Any plans to include an Nginx binary including "--with-ipv6" option in one of the next releases?

**Comment by cyberb** [comment]
Here is the latest build of nginx which will be used in the next release: http://artifact.syncloud.org/3rdparty/nginx-armv7l.tar.gz
Could you try it's binary?

We are still a little bit busy with migrating our build infrastructure (from TeamCity to drone.io) so the next release may be delayed by a month or two.

**Comment by jpma89** [comment]
This binary looks good from good from parameter point of view:

```
debian@beaglebone:~/nginx/sbin$ ./nginx -V
nginx version: nginx/1.8.0
built by gcc 4.9.2 (Debian 4.9.2-10)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --prefix=/nonexistent/path/nginx --with-cpu-opt=generic --with-cc-opt='-static -static-libgcc' --with-ld-opt=-static --with-http_ssl_module --with-http_gzip_static_module --with-http_spdy_module --with-openssl=../openssl-1.0.2g --with-pcre=../pcre-8.40 **--with-ipv6**
```

**Comment by cyberb** [comment]
Closing this in preparation for Release 17.08
