### ISSUE TITLE
apu board support (x86)

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#372]
https://pcengines.ch/apu.htm

**Comment by maichai** [comment]
Thanks for preparing the amd64 image and activating the serial console.
The APU4 is a killer platform for syncloud. I tested it successfully.

**Comment by cyberb** [comment]
Did you juat copy the image to sd card and boot?

They only support msata which is twice as expensive as regular 2.5 sata ssd disks.

Can you boot directly from msata?

Otherwise it looks good, maybe I should buy one :)

**Comment by maichai** [comment]
I out it on a USB flash drive and booted that. I did not copy it to the internal mSATA SSD, but that should be easy enough. Just make sure that you include (g)parted and resize2fs in your image so that after dd'ing the image to the SSD the partition and filesystem can be extended.

**Comment by cyberb** [comment]
Ok, closing
