### ISSUE TITLE
Nextcloud Social App

### ISSUE THREAD

**Issue by marxistvegan** [syncloud/platform#373]
Hey all, great work, somehow i missed how upgrade are done, but I updated Nextcloud and install the Nextcloud Social, but it comes up with an issue with the following 

> 
> .well-known/webfinger isn't properly set up!
> 
> Social needs the .well-known automatic discovery to be properly set up. If Nextcloud is not installed in the root of the domain, it is often the case that Nextcloud can't configure this automatically. To use Social, the admin of this Nextcloud instance needs to manually configure the .well-known redirects: [Open documentation](https://docs.nextcloud.com/server/15/go.php?to=admin-setup-well-known-URL)

**Comment by cyberb** [comment]
I have added the needed configuration and pushed to the store.

I think Social app is not very syable yet.
They have this bug open: https://github.com/nextcloud/social/issues/294

Looks like it requires manual url configuration on the device:

````
snap run nextcloud.occ social:reset
````

**Comment by marxistvegan** [comment]
Ah i see and thanks for the update, the webfinger is fixed. 

> 
> Looks like it requires manual url configuration on the device:
> 
> ```
> snap run nextcloud.occ social:reset
> ```

Do I need to run this myself?

**Comment by cyberb** [comment]
Yes, after nextcloud upgrade and tell it your nextcloud url.
To me that has to happen automatically and developers of Social app have to implement automatic nextcloud url detection.
I guess that is why their issue is still open.

**Comment by marxistvegan** [comment]
OK thanks, I know i asked this but forgot to note it down, how do I become the nextcloud user to run that?

**Comment by cyberb** [comment]
You should run this under root and it will do everything for you

**Comment by marxistvegan** [comment]
Thanks for the response!
