### ISSUE TITLE
[image] odroid u3 support

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#374]
Device seems to be discontinued.
There is some debian image available here:
https://forum.odroid.com/viewtopic.php?f=79&t=12604

**Comment by maichai** [comment]
Not sure what you are implying. 
Will there be a syncloud image be maintained that will run on Odroid U3 in the future, or not?

Some people may also have such a device lying around and may want to put it to good use. It is not a big financial loss if the U3 is not supported in the future, but it is a decent device, worth still being put to use.

I have been running ArkOS (the project is end-of-life) on the U3 for years and it was a stable, reliable platform for mail and owncloud with very low power consumption.

I would love to see syncloud on the U3, but I do not have the technical skills to make it happen.

**Comment by cyberb** [comment]
All I need to have is any working linux image, I tried downloading the image mentioned above on the forum, but mega download hosting asks for an account.

Do you have a link to arkos image?

**Comment by maichai** [comment]
I will make it available to you. It is just old: 2014

**Comment by cyberb** [comment]
Could yoi try this one: http://artifact.syncloud.org/image/syncloud-odroid-u3-19.02.img.xz

**Comment by cyberb** [comment]
Did it work?

**Comment by cyberb** [comment]
Reopen if needed.

**Comment by maichai** [comment]
Sorry I just got the time to test the Odroid U3+, but I skipped the versin you made available back then and went straight for syncloud-odroid-u3-19.08.img.xz

There is a problem and i opened a new issue: 
https://github.com/syncloud/platform/issues/422
"Odroid U3+ image problem #422"
