### ISSUE TITLE
Alternative methods to access apps

### ISSUE THREAD

**Issue by maichai** [syncloud/platform#375]
Currently to be able to acces sthe syncloud apps one has to register the app names as DNS sub domains of the own domain. This is feasible, but I consider it unnecessary effort.

It would be good, if the apps could also be accessed via defined or configurable paths, such as: mydomain/nextcloud, mdomain/mail, etc.

**Comment by cyberb** [comment]
It was loke this in the begining, domain/app.

The problem with this approach is that not every app supports that, for example diaspora: https://github.com/diaspora/diaspora/issues/1989

Domain names are simpler and more stable.

All you need to have is one additional woldcard record in your dns:

CNAME *.example.com example.com

Syncloud.it domains do that by default.

Also to run your personal server on your custom domain you will need difgerent kinds of dns records anyway, like MX for mail and probably others.

**Comment by maichai** [comment]
As I said, it is not prohibitive to have the app names in DNS, its just additional effort.
The web server that you are using on syncloud could do the mapping in cases where you couldn't just put a path in front of what the app is doing in the URL?

**Comment by cyberb** [comment]
Again, if diaspora cannot do it how can we?
I understand it sounds simple but it is not and our past experiance showed that.

iI someone is willing to prove that wrong by testing diaspora and propose a pull request we can discuss it.

Closing untill such time.
