### ISSUE TITLE
UI to configure mail server functionality

### ISSUE THREAD

**Issue by maichai** [syncloud/platform#376]
Currently it is possible to acces the mail client app UI of RoundCube, but I did not find a way to access some UI to configure the mail server app.

As an example: Synology DSM offers some configurability on the DSM Web UI.

I do not know what are open source projects that provide such functionality, sorry for that.
Maybe some other use may jump in?

**Comment by cyberb** [comment]
What kind of configuration you are looking for?

**Comment by maichai** [comment]
I gave an example. Not sure if you know Synology DSM. If you want I can attach some screenshots.

**Comment by cyberb** [comment]
Yes please.

**Comment by cyberb** [comment]
If you can find any popular open source project that does this I will consider integrating it.

**Comment by cyberb** [comment]
Unfortunately we have no plans at the moment to implement mail server configuration UI.
Personally I do not even know half of those mail configs in Synology so I doubt any non-technical user will have any idea what to do with them.
