### ISSUE TITLE
Configurable location for app data, including network shares

### ISSUE THREAD

**Issue by maichai** [syncloud/platform#378]
Since some platforms have very limited storage, syncloud supports external storage devices that are directly connected to take the app data.
I think this is a half-way solution in some aspects (reliability of e.g. SD-Cards, cluttering the house with external drives attached to some small IoT boxes - the dog trips over the usb cable, additional power consumption). 

I consider a network share a better consolidated and more reliable solution as it utilizes existing stable solutions: storage is consolidated on 1 filer host that has availability and reliability mechanisms such as RAID and multi-tiered backup concept with versioning. Also such a consolidated solution will use less power, since only the files drives need to be powered and not a number of drives conencted to a number of small boxes.

It would be great if the functionality to locate app data on external directly attached storage will be extended to network shares, such as using NFS or SMB. Many/(most?) users do have a NAS available at home that already offers good speed, error correction, backup, monitoring and less power consumption.

I know that nextcloud has some similar functionality. This feature request is directed towards the storage location of _all_ apps on syncloud - no fixed storage location, make it configurable to some good options and make it easy on the UI to migrate from one storage location to another. The mechanisms should clearly be below the apps, the apps do not need to be aware of the fact that the storage location has changed, by "virtualizing" the location.

Ideally, since there are existing syncloud installations, if changing the app data storage location, syncloud would cleanly migrate the app data to the new location and clean the old location (optionally securely selecting the app data at the old location by overwriting, according solutions exist).

**Comment by cyberb** [comment]
Currently what you configure in settings - storage as external disk becomes a crucial part of the apps.  Apps like Nextcloud store more then just user files there.
They will stop functioning if disk dissapers or does not have required permissions set.

That is why these disks requirements are strict and have to be attached to the device.

May be we should not use 'external disk' term here and use something like 'local app storage location'.

I think you are right and we need a proper external storage configuration section so these external storages are automatically attached to all the apps and apps do not really depend on them if they dissapear.

**Comment by maichai** [comment]
I think it is ok to support my request for network drives also for files that must be accessible and with proper permissions. 
If you use a reasonable NAS it doesn’t just go away. 

I have been doing this (holding config files and app storage data on NFS) with arkOS and ownCloud for several years. That was stable. 
Alas, arkOS is not maintained any more. 

I hope you consider also offering this for syncloud.

**Comment by maichai** [comment]
I would not consider this issue closed.

**Comment by cyberb** [comment]
Stale, feel free to open a PR if you have an idea how to implement this.
