### ISSUE TITLE
Nextcloud -> add SMB2/3 support

### ISSUE THREAD

**Issue by szaimen** [syncloud/platform#379]
Please add SMB2/3 support. 
Since Wannacry it is not longer recommended to use SMB1 and also disabled in Windows by default.

When I activate the SMB1-Server functionality on my Windows Server, I can acces my Windows network shares over the Nextcloud "External Storage" App. If I disable SMB1-Server-functionality, I cannot. 
That is the reason I am thinking SMB2/3 support is missing in Syncloud.

**Comment by cyberb** [comment]
Could you try changing smb level as adviced here: https://help.nextcloud.com/t/issues-with-nextcloud-13-and-smb-share

If that works we can fix it.

**Comment by szaimen** [comment]
I would like to do that but the file /etc/samba/smb.conf does not exist on my stock syncloud installation. What can I do now?

**Comment by szaimen** [comment]
It works now. I had to create the /etc/samba directory and have written the following into the smb.conf file:

_[global]
max protocol = SMB3
client max protocol = SMB3_

It was nice if you could integrate that into the Syncloud images.

**Comment by szaimen** [comment]
I was wrong: When I want to write to the SMB-Share over Nextcloud it says "An unknown error occurs" even though i can write with the same credentials from another PC to the network share.
How can I fix that?

**Comment by cyberb** [comment]
Can you send us logs from settings so I can see what exactly nextcloud does not like?

Also they mentioned setting:
````
client min protocol = SMB2
````

**Comment by szaimen** [comment]
I have send you the logs from Syncloud -> Settings -> Support.

**Comment by cyberb** [comment]
Logs only show this error:

````
ERROR:  duplicate key value violates unique constraint "lock_key_index"
````

Not sure if it is related to smb.
Could you uninstall amd install nextcloud to see if that helps?

**Comment by szaimen** [comment]
If I try to upload somenthing to my smb-share via nextcloud it just says: "unknown error occured".
I reinstalled nextcloud but the error happens again.

**Comment by cyberb** [comment]
Could you try uploading and send logs again?

**Comment by szaimen** [comment]
The mail has been sent.

**Comment by cyberb** [comment]
Smb error:
````
Exception":"Icewind\\SMB\\Exception\\InvalidArgumentException","Message":"Invalid request for \/Download%20%281%29.jpg (InvalidArgumentException)","Code":22,
````

Could try also setting max to SMB2

As it helped someone here:

**Comment by cyberb** [comment]
Smb error:
````
Exception":"Icewind\\SMB\\Exception\\InvalidArgumentException","Message":"Invalid request for \/Download%20%281%29.jpg (InvalidArgumentException)","Code":22,
````

Could try also setting max to SMB2

As it helped someone here:

https://help.nextcloud.com/t/smb-external-storage-stops-working-solved/37927/2

**Comment by szaimen** [comment]
Yeah, I tried that but nothing changed.
I have sent you the logs again.

**Comment by cyberb** [comment]
Can you do the same using smbclient tool?
Probably it has nothing to do with nextcloud and all we need is a new version of smbclient.

**Comment by szaimen** [comment]
Do you mean mounting this network share with the cifs-utils?

I installed it, created _/media/folder_ and added the following entry to _/etc/fstab_:

_//windows-pc/networkshare /media/folder cifs vers=3.0,username=windowsusername,password=windowspassword,iocharset=utf8,file_mode=0777,dir_mode=0777 0 0_

Afterwards I added _/media/folder_ to my Nextcloud as external storage. 
Now everything works as expected.

**Comment by cyberb** [comment]
Here is how to run occ: https://github.com/syncloud/platform/wiki/Nextcloud

**Comment by szaimen** [comment]
Thank you!
So to sum up and probably close the ticket:

I think, that Nextclouds external storage SMB Plugin is using natively the cifs-unix-extensions. 
However Windows Servers do not support this extensions as it is described in the first sentence here: https://wiki.ubuntuusers.de/Samba_Client_cifs/#Simulation-von-Rechten-ohne-cifs-UNIX-Erweiterungen
So I cannot use the inbuilt SMB-Plugin when I want to write to a Windows-SMB2/3-Share.
For connecting to Linux SMB2/3 shares (with disabled SMB1) editing the /etc/samba/smb.conf file should work.
