### ISSUE TITLE
Apps -> Add repair button

### ISSUE THREAD

**Issue by szaimen** [syncloud/platform#380]
Please add a button to each app to repair them if they are not working. 
The same would be nice for the whole server, e.g. for situations when the nginx webserver is not working.

**Comment by cyberb** [comment]
Could you explain what exactly repair should do?

We have app backup/restore feature coming soon, is that what you actially want?
https://github.com/syncloud/platform/issues/381

**Comment by cyberb** [comment]
Reopen of backup is not what you are looking for.
