### ISSUE TITLE
Beagle bone black

### ISSUE THREAD

**Issue by aaronxyzee** [syncloud/platform#382]
Hi Syncloud
I have been trying to flash a beagle bone black, with no success.  I have down loaded the the BBB image from your site,  copied it to an sd card and inserted into the device. Do I need to hold down the tiny power button? Do the lights flash when the BBB is being flashed? 

Also what is the address used to ssh into the syncloud device?

Thanks for any help
Aaron
Aaron
When F

**Comment by cyberb** [comment]
You need to take power cable off and on again.
Sd card will not automatically write itself to internal memory.
Can you take a pocture of what you see on tv using hdmi cable.

**Comment by aaronxyzee** [comment]
Thanks for reply.
Do you mean that the BBB does not get 'flashed'? Does it run live from the the sd card?

I do not have an hdmi lead so I need to be able to ssh into it, what is the address to use ? And is it possible to make a vnc connection?

**Comment by cyberb** [comment]
What I mean is that Syncloid image written to sd card will actually run from sd card.

BBB has internal nand memory or something and other BBB specofic images will copy themselves from sd card to imternal memory on first boot (we will not do that).

IP address for your device you will have to get from your router's web page.

**Comment by aaronxyzee** [comment]
No. It's not working.  I have copied the image 3 times and turned it on and off many more times, but it is no good.  Does the BBB need its own operating system as well the syncloud disk?

**Comment by cyberb** [comment]
No.
Are you downloading this one: https://github.com/syncloud/platform/releases/download/18.11/syncloud-beagleboneblack-18.11.img.xz

Strange, another user confirmed it is working: https://github.com/syncloud/platform/issues/362

You need to get an hdmi cable to see what is wrong so I can help you.

**Comment by cyberb** [comment]
Coildnyou try this one juat in case: http://artifact.syncloud.org/image/syncloud-beagleboneblack-18.12.img.xz

They must be the same.

**Comment by aaronxyzee** [comment]
I will try the download link from the last message.
I still have the Angstrom O/S on the BBB, Is this okay or should it be the Debian image?
Under angstrom I can vnc into the desktop, and connect via ssh. is this not enough?
When I put the Syncloud disk in I cannot conect at all and the android app finds nothing.
I Know it is probaly my stupidity, but I would like to try your system out
Thanks for help so far
Aaron

**Comment by aaronxyzee** [comment]
No difference with the last image. Sorry

**Comment by cyberb** [comment]
Are you using etcher to write the image to sd cars on a PC?

**Comment by aaronxyzee** [comment]
Yes, I use etcher on ubuntu laptop

**Comment by cyberb** [comment]
Can you get an hdmi cable to see what is wrong?

**Comment by aaronxyzee** [comment]
So, I have now  an hdmi lead. I have attached BBB to tv screen, added the scyncloud sd card and turned on power and there is nothing on the screen, there are no boot messages or anything. When I remove scyncloud sd card and reboot I get the Angstrom boot screen.

**Comment by cyberb** [comment]
Could you try this:

Step #0.F: Boot your board off of the SD card

Insert SD card into your (powered-down) board, hold down the USER/BOOT button (if using Black) and apply power, either by the USB cable or 5V adapter.

http://beagleboard.org/getting-started#update

**Comment by aaronxyzee** [comment]
So, I have now  an hdmi lead. I have attached BBB to tv screen, added the scyncloud sd card and turned on power and there is nothing on the screen, there are no boot messages or anything. When I remove scyncloud sd card and reboot I get the Angstrom boot screen.

**Comment by aaronxyzee** [comment]
Syncloud card inserted, boot button pressed and bbb powered up and I get nothing. Some lights flash for a second  and then nothing, and nothing appears on the android app....a big fat nothing muffin.

**Comment by cyberb** [comment]
Dis you hold down the USER/BOOT button?

**Comment by aaronxyzee** [comment]
yes i held it down for about a minuit.

**Comment by cyberb** [comment]
Can you successfully boot any of these images usong sd card?

https://beagleboard.org/latest-images

**Comment by aaronxyzee** [comment]
No.  I am having a lot of problems trying to flash the device with anything other than Angstrom .
It is giving me such a head acke

**Comment by cyberb** [comment]
Do you know what exact revision of beagle bone you have?

**Comment by cyberb** [comment]
Have you tried different sd cards?
Do you have verify mode enabled in etcher?

**Comment by aaronxyzee** [comment]
Hi cyberb
So, I have realized that my beaglebone is a bit old and only has a 2gb eMMC thing.  This is the reason I couldn't flash a debian O/S. Could this be the reason that Syncloud wont work. Or can I run it straight from the Micro sd card?

**Comment by cyberb** [comment]
You need to check what your model cam do, but thought you should be able to boot directly from sd card when holding USER button during the boot.

**Comment by cyberb** [comment]
Should we close this issue?
