### ISSUE TITLE
How to know that system components are up to date ?

### ISSUE THREAD

**Issue by raphraph** [syncloud/platform#384]
I was wondering how one (who does not have great knowledge in adminsys) can check that the device on which syncloud is running is up to date in terms of security ?

For example I see that my device (which runs a Syncloud image) is using the latest version of openssh available for Debian (6.7 which is actually quite old, 2014...).
I can do similar checks for other components.

My point is, Syncloud can be updated to latest version with newest security updates, but I do not know if my whole device is.
Would it make sense to have a dedicated page in the Syncloud admin panel listing the different components and their versions, or labels showing if they are up to date or not ?

**Comment by cyberb** [comment]
We do not have such a page.
We try to minimize OS shared dependencies so all the apps contain all the deps with them using snap package format.
As a result we do not really have a lot of things on OS side to care about.

There are few things like kernel, systemd, openssh and few others which we do not update on existing installs unless you write new image.

Over time we will include more into the main platform app.

Currently you have apt (which we will disable in future which can give you list of versions.

**Comment by raphraph** [comment]
Thanks for the clarifications.

Could Syncloud users know in detail what are the "few things" that he should care about on its own concerning his device ?
Furthermore how one can know that the OS shared dependencies versions are compatible with the platform ?

**Comment by cyberb** [comment]
Here is the list of OS tools/shared libraries we do not update on the device:
https://github.com/syncloud/rootfs/blob/master/bootstrap/bootstrap.sh#L66

You can use apt tool to check their versions.

Platform app as well as all the other Syncloud apps do not really have any other OS dependencies.

**Comment by cyberb** [comment]
I do not think we can do anything here.
Feel free to reopen if you have concrete suggestions.
