### ISSUE TITLE
How to change the root password after installation ?

### ISSUE THREAD

**Issue by HerrBender** [syncloud/platform#385]
Hello everybody,
A couple days ago I successfully installed syncloud on my Ordroid HC2.
It still work pretty well. But until yet I can´t find a way to change the root password.

For me it´s look like a big Problme, because you only need the DNS Adress of your syncloud.
Than everyboday is able to login to your syncloud with the default Login Characters.
**Login: root, password: syncloud**.
(https://github.com/syncloud/platform/wiki#ssh)

If my reasoning is wrong please correct me.
Thank you for your help :).

Have a nice day.
Herr Bender

**Comment by cyberb** [comment]
Did you activate your device?
Activation allows you to set your personal device password and that will change root password.

**Comment by HerrBender** [comment]
Yes I activate my device.
But I there was no form or window where I can change the password.
It it possible to simple deactivate and then activate my device again?

**Comment by cyberb** [comment]
Activation form contains device logn and password fields did you enter your desired login password there.
root/syncloud is only there for non activated device.
You can always reactivate your device

**Comment by HerrBender** [comment]
Oh yea it work thank you very much. 
The Problem was that I enter in the Activation form root/syncloud anstead of my own user/password.

**Comment by marxistvegan** [comment]
> Activation form contains device logn and password fields, did you enter your desired login password there.
> 
> root/syncloud is only there for non activated device.
> 
> You can always reactivate your device from settings Activation (you must be in your local lan)

This would be a helpful FAQ, does reactivating it with the same domain reset any existing installed applications?

**Comment by cyberb** [comment]
No.
It will probably reset your certificate for some time.

**Comment by marxistvegan** [comment]
> No.
> It will probably reset your certificate for some time.

So at this point when one wants to change the password it is by re-activating the account?

**Comment by cyberb** [comment]
Yes, untill users app is ready.
https://github.com/syncloud/platform/issues/148
