### ISSUE TITLE
Wi-Fi iOS doesn’t work

### ISSUE THREAD

**Issue by dani-77** [syncloud/platform#386]
All worked fine until the 18.12 version; I don’t think the problem is with the iOS version because I have and older iPhone with version 9.# and it doesn’t work as well.

**Comment by cyberb** [comment]
Are you saying that with latest version (

**Comment by dani-77** [comment]
Not for me, at least; I noticed it in the version 18.12, but the 18.12.2 is not working as well.

**Comment by cyberb** [comment]
Could you tell me which versions of iOS did you try?

**Comment by dani-77** [comment]
Tested the 18.12.2 version of the app on iOS 12.2 and iOS 9.3.5; in none works.

**Comment by dani-77** [comment]
Tested the 18.12.2 version of the app on iOS 12.2 and iOS 9.3.5; in none works.

No dia 12/04/2019, às 17:36, Boris Rybalkin <notifications@github.com> escreveu:

**Comment by cyberb** [comment]
Do you have external mode enabled?
Can you access your device from local network by dns and by local ip?

**Comment by dani-77** [comment]
Local ip and DNS works great; app, nope!
Not in external mode; internal only for security reasons.

**Comment by cyberb** [comment]
Yes, it is not working, just checked.
Give me some time fo fix it.

**Comment by cyberb** [comment]
Strange simulator works fine, just the real device.
I made few changes, could you test on real device?
https://github.com/syncloud/ios/releases/tag/19.04

**Comment by dani-77** [comment]
Hello @cyberb .
I can, but you have to guide me; my iPhone is not "open" (jailbraked) - does this method of installation works?
Regards

**Comment by cyberb** [comment]
I think you should be able to unzip app file and copy it to your phone using iTunes.

https://forums.developer.apple.com/thread/106125

They are talking about .ipa but I have an .app file, should be similar thing.

I do not have an iphone at the moment to try this.

**Comment by dani-77** [comment]
I’ll try it; the way alexfromhome describes it, I believe, I tried, but I’ll look again later.

No dia 17/04/2019, às 12:26, Boris Rybalkin <notifications@github.com> escreveu:

**Comment by dani-77** [comment]
Hello, I tried and I couldn’t make it work.

I tried this method
https://www.funkyspacemonkey.com/howto-convert-iphone-apps-app-ipa

And saw this video
https://www.youtube.com/watch?v=dcmu5vHvV50

I’ll try to read a few more tomorrow.

**Comment by dani-77** [comment]
Hello,
I'll try to install syncloud App with cydia impactor, but only Sunday or Monday; I'm Out for Easter.

**Comment by dani-77** [comment]
I’m too dumb for this; I can’t install it. Sorry @cyberb

**Comment by cyberb** [comment]
No problem, I am trying to fix it.

**Comment by cyberb** [comment]
Unfortunately I do not have any Mac so I am offering a £20 to anyone who can fix this problem.
Issue has to be tested on a real iPhone with a Syncloud VM.

**Comment by cyberb** [comment]
To test WiFi discovery:
1. Install VirtualBox
2. Download VirtualBox (vdi) disk https://github.com/syncloud/platform/releases/download/20.06/syncloud-amd64-20.06.vdi.xz
3. Unzip
4. Create VM based on Debian x64
5. Use existing virtual hard drive and select extracted vdi file
6. Make device available on the same WiFi network as iPhone: Settings -> Network -> Adapter 1: Attach to "Bridged Adapter"
7. Start VM

After a minute or so you should see a login prompt, that means device is running and you can test discovery:
1. On iPhone
2. Login to Syncloud Domain
3. User: teamcity@syncloud.it
4. Password: password
5. Discover new devices
6. You should see after some time your VM in the list.

If you do not see your VM that means either discovery is not working or VM is not on the same WiFi network as your phone.
Check your router to see that there is a new device IP from VirtualBox VM.

**Comment by cyberb** [comment]
Should be fixed and available in app store, please reopen if does not work.
