### ISSUE TITLE
Device not visible with ASUS RT-AC86U router

### ISSUE THREAD

**Issue by AllanBChristensen** [syncloud/platform#388]
When connecting the OHC1 to my ASUS RT-AC86U router, the device is not visible to the android ap, nor can I see it in the router list of connected devices, although  I can see that the cable connection is fine. 

The router is running AiMesh in AiMesh Router mode with an older router, ASUS RT-AC68U, serving as an AiMesh Node. If I connect the OHC1 to the connection point rather than directly to the router, it becomes visible.

This is the definition of Ai Mesh Router Mode which does not make the device visible:
--
AiMesh  Router mode is a traditional mode with AiMesh functionality, which  connects to the Internet via PPPoE, DHCP, PPTP, L2TP, or Static IP and  shares the wireless network to LAN clients or devices. In this mode,  NAT, firewall, and DHCP server are enabled by default. UPnP and Dynamic  DNS are supported for SOHO and home users. Select this mode if you are a  first-time user or you are not currently using any wired/wireless  routers.You can add AiMesh nodes to form an AiMesh WiFi system to provide extra WiFi coverage.
--

Link to description of AiMesh: https://www.asus.com/us/AiMesh/

**Comment by cyberb** [comment]
I guess you need to make sure you are connecting to correct lan port and not wan.
Other than this I cannot really help, especially that it works on another router. We do not really do any special logic for connections.

Probably you will have to talk to Asus support or do some google research: 
https://www.google.com/search?q=ASUS+RT-AC86U+wired+clients

**Comment by cyberb** [comment]
Do you have any news on this?

**Comment by cyberb** [comment]
I assume this is not an issue anymore, reopen if you have more info.
