### ISSUE TITLE
Odroid N2 support

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#391]
Test image is available here: http://artifact.syncloud.org/image/syncloud-odroid-n2-19.02.img.xz

Anyone who has this device please test and let me know if it works.

**Comment by chegeiser** [comment]
I just loaded in on my N2 and it booted up fine and I installed Nextcloud and Notes just fine. 

I was not able to get my old Nextcloud and Notes files to transfer over by restoring from a backup using the new backup feature. Not sure I this is what the backup/restore is meant to be able to do.

**Comment by cyberb** [comment]
Can you open another issue for backup problem and I can help you on that, in theory it should work like that.

Should we close this N2 issue?

**Comment by chegeiser** [comment]
Yes, seems this can be closed. 

I've opened the other issue as a new issue (#394).
