### ISSUE TITLE
Admin login does not work on Gogs

### ISSUE THREAD

**Issue by generein** [syncloud/platform#393]
I have installed Gogs and I am trying to log in with device credentials ('admin' + pwd). I receive a "Username or password is not correct" error.

Logs say the following:

> 2019/05/23 07:04:34 [TRACE] Doing: MirrorUpdate
> 2019/05/23 07:04:34 [ERROR] [...ogs/models/mirror.go:295 MirrorUpdate()] MirrorUpdate: dial unix /var/snap/gogs/common/database/.s.PGSQL.5433: connect: no such file or directory
> 2019/05/23 07:14:34 [TRACE] Doing: MirrorUpdate
> 2019/05/23 07:24:34 [TRACE] Doing: MirrorUpdate
> 2019/05/23 07:34:34 [TRACE] Doing: MirrorUpdate
> 2019/05/23 07:44:34 [TRACE] Doing: DeleteOldRepositoryArchives
> 2019/05/23 07:44:34 [TRACE] Doing: MirrorUpdate
> 2019/05/23 07:44:34 [TRACE] Doing: GitFsck
> 2019/05/23 07:44:34 [TRACE] Doing: CheckRepoStats
> 2019/05/23 07:46:25 [TRACE] Session ID: (snip)
> 2019/05/23 07:46:25 [TRACE] CSRF Token: (snip)
> 2019/05/23 07:46:25 [TRACE] Session ID: (snip)
> 2019/05/23 07:46:25 [TRACE] CSRF Token: (snip)
> 2019/05/23 07:46:25 [TRACE] Template: user/auth/login
> 2019/05/23 07:47:18 [TRACE] Session ID: (snip)
> 2019/05/23 07:47:18 [TRACE] CSRF Token: (snip)
> 2019/05/23 07:47:18 [TRACE] Session ID: (snip)
> 2019/05/23 07:47:18 [TRACE] CSRF Token: (snip)
> 2019/05/23 07:47:18 [TRACE] Template: user/auth/login
> 2019/05/23 07:49:10 [TRACE] Session ID: (snip)
> 2019/05/23 07:49:10 [TRACE] CSRF Token: (snip)
> 2019/05/23 07:49:10 [TRACE] LDAP: Dialing with security protocol '0' without verifying: false
> 2019/05/23 07:49:10 [TRACE] LDAP will bind directly via UserDN template: cn=%s,ou=users,dc=syncloud,dc=org
> 2019/05/23 07:49:10 [TRACE] Binding with userDN: cn=admin,ou=users,dc=syncloud,dc=org
> 2019/05/23 07:49:10 [TRACE] Bound successfully with userDN: cn=admin,ou=users,dc=syncloud,dc=org
> 2019/05/23 07:49:10 [TRACE] Fetching attributes 'cn', 'cn', '', 'mail', '' with filter '(&(objectclass=inetOrgPerson)(uid=admin))' and base 'cn=admin,ou=users,dc=syncloud,dc=org'
> 2019/05/23 07:49:10 [TRACE] Checking admin with filter '(objectClass=inetOrgPerson)' and base 'cn=admin,ou=users,dc=syncloud,dc=org'
> 2019/05/23 07:49:10 [ WARN] Failed to login 'admin' via 'syncloud': name is reserved [name: admin]
> 2019/05/23 07:49:10 [TRACE] Template: user/auth/login

**Comment by cyberb** [comment]
Unfortunately you cannot use admin login and this is a limitation of gogs:
https://github.com/gogs/gogs/issues/4831

You can reactivate your device with different login :(

**Comment by generein** [comment]
Is it possible to change the activation login after activation, i.e. change the LDAP record?

**Comment by cyberb** [comment]
Yes: setting - activation.
You should be inside your local network to do that.
