### ISSUE TITLE
Syncloud Backup - Can't restore on new build

### ISSUE THREAD

**Issue by chegeiser** [syncloud/platform#394]
I was not able to get my old Nextcloud and Notes files to transfer over by restoring from a backup using the new backup feature. This was a fresh install of Syncloud that I plugged the old HD into, enabled the external drive, and then used the restore feature. I still could not access the old data from the original Nextcloud and Notes install that are on this HD.

**Comment by cyberb** [comment]
Can you send us logs (Settings - Support) after the backup restore attempt?

**Comment by chegeiser** [comment]
I'll have to start with a fresh run - I am running the old Pi system right now. A couple questions so I'm sure I am using the Backup feature correctly:
Per the directions in the wiki:

> Currently you can backup app settings from App page and restore an app using Settings - Backup page.
> 
> Backup is stored on a device file storage which located at /data/platform/backup
> 
> Device file storage (/data) is located either on an internal disk or on an external disk (if it was activated in Settings - Storage)

So this means?
1. Backup the current system (Raspberry Pi)
2. Boot from fresh image on new device (Odroid N2)
3. Activate the new device
4. Activate the external disk on the new device so the backup is available
5. Restore from the backup on the external disk
6. All data from the original device is now available on the new device

**Comment by cyberb** [comment]
Yes, it should work like this.

**Comment by chegeiser** [comment]
Just installed form image, activated to my custom domain, activated external disk, updated system and installer, and restored from backup. No luck - there was a little popup in the top right of the screen that said the restore was finished but no apps are available. I've sent logs.

I also rebooted and checked - still no apps that were installed on the original system.

**Comment by cyberb** [comment]
Sorry, you need to install apps first. Backup does not contain app itself

**Comment by cyberb** [comment]
We should add a warning when restoring backup of not installed app.

**Comment by chegeiser** [comment]
That worked. Install app, then restore backup.

But there is another problem that may be related. Once I restored my Nextcloud backup I cannot install other apps. I can choose Install (Diaspora and Syncthing tried) and it shows that it is installing - then after a short period it goes back to just showing the Install option and the app is not installed.

Logs sent.

**Comment by cyberb** [comment]
Could you install one more time wait few minutes and send logs right after that?

**Comment by chegeiser** [comment]
Install from image, then install apps, then logs? Or also install from backup after image>apps?

**Comment by cyberb** [comment]
I mean whatever you have right now, you cannot install new apps right?
I just cannot see anything related to app install error.
If you install an app which fails to install and send logs right aeay I will probably see something useful in them.

**Comment by chegeiser** [comment]
Done. Just tried to install File Browser - it appeared to be installing, then didn't. Logs sent.

**Comment by chegeiser** [comment]
Same thing with Syncthing. Logs sent.

Pic attached showing Syncthing installing, then it's back to the default page with the Install button.
![Syncthing](https://user-images.githubusercontent.com/17602493/59799328-f97e5080-9298-11e9-9393-eec11165b0a5.jpg)
![Syncthing after install attempt](https://user-images.githubusercontent.com/17602493/59799437-31859380-9299-11e9-9ff8-216421c91552.jpg)

**Comment by cyberb** [comment]
You have only 700m left on your sd card (boot disk) which is 3g.
You need to extend it to take all 16g from settings - storage.
Try that to see if it helps.

**Comment by chegeiser** [comment]
I expanded the file system and tried to install Diaspora. Still no luck. Logs sent.

Also, when I tried to re-boot from the Syncloud boot menu it re-booted. But my apps were not available. They didn’t show up in the apps section. I had to shut down, unplug the device, plug it back in and re-boot which restored the apps. Still no Diaspora.

**Comment by cyberb** [comment]
Cannyou run the following command uaing ssh on the device and post the output:

    snap install diaspora

**Comment by chegeiser** [comment]
I get this error:

> error: cannot perform the following tasks:
> - Mount snap "diaspora" (180924) (exit status 127)

**Comment by cyberb** [comment]
This may be an sd card issue.
Can you try all this a new sd card?
Do not forget to extend it first.

**Comment by chegeiser** [comment]
Here are screenshots showing that Nextcloud shows up as installed when I select it from the App Center, but then in Apps it is missing - no apps at all in Apps though I had Nextcloud and Notes running prior to a restart.
![syncloud apps](https://user-images.githubusercontent.com/17602493/59873971-090da000-9352-11e9-8a0a-ae6aea80e9ed.jpg)
![image](https://user-images.githubusercontent.com/17602493/59874031-2e021300-9352-11e9-972d-49de90cb014a.png)

**Comment by chegeiser** [comment]
I'll try a new SD card (eMMC).
Thanks!

**Comment by chegeiser** [comment]
I just installed from a new SD card - same result. Logs sent right after trying to install Diaspora.

**Comment by cyberb** [comment]
Ok, could you check settings - updates and upgrade installer if there is an update?

I have just pushed an updated installer with timeout fix which may or may not fix the problem.

**Comment by chegeiser** [comment]
That seemed to get the installer to work correctly. I installed a fresh image and then expanded the filesystem, then updated, then added two apps, restored backups and added more apps. That all worked with Diaspora, and File explorer - but Syncthing and Gogs will not install. Logs sent.

But after about 6 hours the SSL cert still hasn't gone through on my custom domain. Every other time I've done this the https site has been up and running with a trusted cert within 15-60 minutes. Any idea if any other changes were made that could have impacted the certificate handling?

**Comment by cyberb** [comment]
I think you are hittinh the rate limit because of testing.

Logs says:
    There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains

It should be 5 or 50 per week: https://letsencrypt.org/docs/rate-limits/

**Comment by cyberb** [comment]
Gogs is actually broken at the moment, I am fixong it.
Syncthing I will check.
Certificate should not affect installation.

**Comment by chegeiser** [comment]
hmmm... 20 hours later and the certificate still is invalid.

**Comment by cyberb** [comment]
I guess your cerrificate is OK now?
Gogs is fixed also, please install again.
Syncthing is being fixed and will be ready in couple of days.

**Comment by cyberb** [comment]
Syncthing is also fixed now, sorry for the inconvenience.
Could you check?

**Comment by chegeiser** [comment]
Syncthing is now working. All seems to work: backups, restoring from backup, Syncthing, GOGS, Nextcloud, Notes, File browser, Diaspora.
