### ISSUE TITLE
Odroid H2 support

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#399]
It's in stock https://www.hardkernel.com/shop/odroid-h2/

2 x SATA 3.0

Maybe you could offer it in your shop with to hard drives...
https://www.hardkernel.com/shop/odroid-h2-case-1/

**Comment by cyberb** [comment]
Odroid H2 is actually Intel based so it should be already supported by our amd64 image.

For the shop I am not sure, there are so many Intel based devices which look so much better than this.
