### ISSUE TITLE
Device issues notification

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#4]
_From @cyberb on February 14, 2015 0:36_

After receiving several disk issues emails I think we need some form of health check on a device. I would start with adding simple notification message on device main web ui.
For example "Disk error, more info" plus advice "restart device, format disk, send reports to support ..."

_Copied from original issue: syncloud-old/server#1_

**Comment by cyberb** [comment]
As we have "send logs" it should be enough for now
