### ISSUE TITLE
Backup (RAID) to a friend's Syncloud

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#402]
Just an idea: To store all the data on a friend's Syncloud (select via domain) as backup automatically. Has to be accepeted by the other Syncloud owner. You get only the amount of storage you allow him as well. You can only read out data with your account. Advantage: backup on other physical location.

**Comment by cyberb** [comment]
This is kind of supported by Syncthing except it does not support http(s) as a transport protocol so you need to open its port.
