### ISSUE TITLE
Ideas UI development

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#403]
For me it's a nice experience to look into someone others code and a chance to learn and I understand now a bit more how it works, at least for the UI...

I think it's hard to find a cut, which features should be implemented and which should be an app. E.g. you added the syncthing but also a backup tab in the UI. I would do the cut here. I had the following ideas and I'm not upset, if you don't take them:

(1) If you are as User in the "settings" part, you might want to make changes under several "tabs" so you have to open the menu several times. Therefore I added a settings menu bar only for settings sides...
(2) Under shutdown I did a stand-by option (which is not working yet) maybe we/you can at Wake-on-LAN? to save energy...
(3) Under support I solved issue #333. Also you maybe want to easily know what the problem is, therefore the describe field (not implemented in script yet). 
(4) Maybe the user want to can solve the problem by himself, which would waste less your time, therefore the help yourself part. Also you need a "new system" (email) to view logs, so here they are hidden to not destroy your easy UI, but you have the option directly to read them (no import log file yet).
(5) Support is not one direction, therefore the contribute part.
(6) by adding this, margin of css col2 classes is very small, thats why I added a border to "isolate" different features. I added this to all setting features, that they look the same.
(7) I tried to take the syncloud.org translation method to the platform. Should appear to the right of the shutdown button. Not working yet, maybe because there is no json file yet.
(8) I had actually no idea what the backup feature is for unless I read the Docs. So I added some clarification. Also you have to download the tar.gz files on your PC/external HDD (because that's then the backup). If I click on the files, nothing is happening, so there should be an option to download single files. On the other side it would be nice to have the option to download all files in one step (which needs double zip, which is ok, and then link to this one zip file).
(9) I added an Information that it's also possible to backup the system, but it's to complicated to describe it there, so I linked to the docs...
(10) What I would like to know, are the files (my data) e.g. stored in nextcloud, also in this zip files? This is unclear for me. Or do I need to make backups of my data out of each app again? Because you say backup of settings...
(11) Also, I haven't found the possibility the install apps from zip files. How can I restore my data?
(12) System and Security tabs are just an idea. I aggree to implement this is extern apps. However, I would implement some basic information to let the user know, that there is an opption. Maybe a "non-IT" person whould not care about maleware, if you don't have a hint. Anyway this point is discussable and just my oppinion...
(13) Anyway, it would be nice to have a monitoring, malware protection app, and maybe there is something to see, which computers (IPs) are accessing my device at the moment, to see spy attacks as "non-IT" person...
(14) Then I tried to at some more information to the apps: licence, url website, url opensource code, and description. (didn't work yet because the data is loaded by js, have to understand more...)

That's what I thought. Let me know your opinion...
Issue #359

**Comment by klmhsb42** [comment]
To (8) and I had at the beginning no idea where to create zip files (create backup), a hint, that you have to go to each app page, would be nice and maybe also a "backup all" button.

**Comment by klmhsb42** [comment]
To (3) what I don't get is why don't send the logs per default to support and send copy to myself. A simple user could maybe not understand what's in the logs, so maybe the user doesn't care about it and just want to have support...

**Comment by cyberb** [comment]
I guess you want to concentrate on UI improvements. 
Do you have any experience/interest in backend? As you can see may of those issues require backend support and it is always better to add a complete  feature and you would have a higher chance of merging them.

If you can do both UI and backend which is really the only way to complete most of the features I would start with #333.

If you only want to do UI (js,html,css) that limits your options a lot, but you can still select one and create an issue so we can discuss in more details.
As to UI you should know that we are a "mobile first shop" that is also why simplicity of UI is of a top priority.

Translation is a little bit controversial topic as it needs a lot of maintenance which we cannot provide especially for a much more dynamically changing project like platform comparing to syncloud.org which is not changed very often. We do not have resources to maintain all the languages every time we add a feature as a result translations will be always half done and will just annoy people. On the other side I understand that we technically should be able to add can add translations with the switch and warning like experimental feature in settings.

**Comment by klmhsb42** [comment]
I could also try to add apps, but I still couldn't open any app yet because of issue #331

**Comment by cyberb** [comment]
What exactly is not working? #331 is not a problem it is about more info on IP version while all the needed info to get your device available externally is here https://github.com/syncloud/platform/wiki/External-access

**Comment by klmhsb42** [comment]
ok. I've dual-stack lite and can only access via ipv6. I cannot access domain [name].sycnloud.it from privat network. Page is not found error. 

enabling external access doesn't work. upnp is activated in router, but device is not able to map. I enabled ports for device in router. Manual mapping doesen't work, time out error (oops... page). Don't know what I'm doing wrong. Maybe you could create a router/software list in the wiki and make a doc for each e.g. fritz.box what/where exactly to change in router settings software? 

Access from privat network would be fine for me to start. I guess, I need external access to access per domain? Is there any possibility to access e.g. nextcloud without domain?

**Comment by klmhsb42** [comment]
Also my private network is still ipv4, I think. Could this be a problem and if I would set up a ipv6-only privat network, would that help?

**Comment by cyberb** [comment]
Sorry, for ipv6 external access page is useless and should not be used.
Make you private network ipv6 then you should be able to access from both public and private network without external access page.

**Comment by klmhsb42** [comment]
I can access syncloud with _https://[ipv6]/index.html_ and _https://ipv4/index.html_ but not with the domain _https://name.syncloud.it_ (I need ipv6)

I think the problem is, that my _Internal Address_ under _https://www.syncloud.it/user.html_ is ipv**4** which is taken when I use the domain 

Is it possible to change the mapped _Internal Address_ to ipv**6** or to choose ipv**6**, if I would activate my device again?

**Comment by klmhsb42** [comment]
ok, if I take the right (public?) ipv**6** for https://[ipv6]/index.html it's automatically ON _external access_ but under https://www.syncloud.it/user.html _external access_ it's also mapped as ipv**4**

**Comment by klmhsb42** [comment]
Maybe you could implement a method to check, if it's _dual stack_ or _dual stack lite_ and if it's _DS lite_ to take then automatically ipv6 for the dyndns server...

**Comment by cyberb** [comment]
Yes, should not be difficult, https://github.com/syncloud/platform/issues/407
