### ISSUE TITLE
Restart/shutdown problem on VM

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#404]
User reported that restart and shutdown are not working on a VM.

**Comment by trevorprinn** [comment]
I'm seeing this too. The javascript error is
ReferenceError: dropdown is not defined

**Comment by cyberb** [comment]
@trevorprinn do you still have this problem?

**Comment by trevorprinn** [comment]
Yes. This is when clicking on the Shutdown link. The error on Firefox has a little more info
```
ReferenceError: dropdown is not defined index.html:1:1
    onclick https://tprinn.syncloud.it/index.html:1
```

**Comment by cyberb** [comment]
Did it actually shutdown?
If it did, I do not expect UI to work properly after that :)

**Comment by trevorprinn** [comment]
No. It doesn't shut down. Clicking the link does nothing.

**Comment by cyberb** [comment]
Could you crtl + f5 the page, then try shutdown, then send us logs from the settings please?

**Comment by trevorprinn** [comment]
Interesting. I just tried it from an android tablet using the DuckDuckGo browser (on the same LAN) and that did work, so I suspect a problem with my PC. I've had a few weird problems like this with Chrome at work (similar messages about various things being undefined) and fixed them by uninstalling and reinstalling Chrome. I've just tried that and it's not made a difference. Also, I've been getting the same problem with Firefox (on the same PC).

I've sent you the logs, as requested.

**Comment by cyberb** [comment]
Could you restart firwfox with disabled plugins and try again?
Also do you have another pc to try?
There is nothing wrong in the logs, seems to be browser or pc problem.

**Comment by trevorprinn** [comment]
I've tried it with FF with disabled plugins and also using both Edge and Chrome from another PC. Same result from all of them - the undefined dropdown. Very puzzling.

**Comment by cyberb** [comment]
Sorry it took me some time, but the problem was in mobile mode and I was checking on desktop.
It should be fixe now in latest platform version, please update and check again.

**Comment by cyberb** [comment]
Should be fixed, reopen if not.
