### ISSUE TITLE
Files App - Can read files after logout

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#415]
If I apply the url to files in browser (at least firefox) after logout from files app, I can still read them. Folders are protected.

**Comment by klmhsb42** [comment]
Or are they just getting downloaded?

**Comment by cyberb** [comment]
This must be just a browser cache, which in theory we can disable.
Try ctrl+f5 to check that.

**Comment by cyberb** [comment]
Should we close this?

**Comment by klmhsb42** [comment]
Yes, it's the cache. To disable it would be nice, because if you access with a public PC anybody can read them.

**Comment by cyberb** [comment]
Please upgrade, we should have cache disabled now.
Also you should use private tab in public places!
Reopen if not fixed.
