### ISSUE TITLE
Some apps can't be reached again after power failure

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#418]
After hard disconnection (~4 days) from power (without shutdown), some apps can't be reached over URL.
Case for _nextcloud_ and _users_ app.
Redirection to e.g. https://nextcloud.name.syncloud.it/apps/files/ to `Internal Server Error` page.

**Comment by cyberb** [comment]
You need to send logs to support or yourself to check what is failing.

**Comment by cyberb** [comment]
You actually helped me to fix this long standing bug!
Could you update users?

**Comment by cyberb** [comment]
Nextcloud is also updated.

**Comment by klmhsb42** [comment]
Whatever I've done, I'm happy to help. User works again. Nextcloud still same error. Send logs.

**Comment by cyberb** [comment]
What version of nextcloud do you have now?

**Comment by klmhsb42** [comment]
Installed version: 1909118

**Comment by cyberb** [comment]
https://github.com/syncloud/platform/issues/419
