### ISSUE TITLE
More partnerships with other manufacturers

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#420]
Besides a decentralized internet, it would be nice to support the idea of decentralized manufacturing. Therefore, it needs partnerships between those companies. Maybe you could be the pioneer and link to other companies products to cover a whole foss universe and maybe to ask them, if they could link to your products and to eachother. 

**Existing partnerships:**
Nextcloud: https://nextcloud.com/devices/
Helios4: https://kobol.io/helios4/

**Nice-to-have partnerships:**
_Products (link eachother):_
Purism: https://puri.sm/ (Smartphone, Laptops, Tablet)
Mycroft: https://mycroft.ai/ (Assistant)
OSMC: https://osmc.tv/ (TV box)
Turris: https://www.turris.cz/en/omnia/ (Router)

_Software - No product available (link eachother):_
Asteroidos: https://asteroidos.org/ (Smartwatch OS)

_Software developers - link to yours:_
Kodi: https://kodi.tv/ (if issue #345 is done)
And all other apps which you offer. 

_Hardware developers - link to yours:_
All hardware companies, from which you sell hardware

**Comment by cyberb** [comment]
Yes, but there is no need for an open issue for that.
Things conatantly happen in that area slowly.
