### ISSUE TITLE
Odroid U3+ image problem

### ISSUE THREAD

**Issue by maichai** [syncloud/platform#422]
I used Balena Etcher to write the Odroid U3 image (syncloud-odroid-u3-19.08.img) to a micro SD card for an Odroid U3+.

I can successfully boot from the SD card (connected to HDMI I can see the boot console), but the ethernet interface does not seem to get initialized. At least the LEDs of the ethernet port are not flashing, and it does not pull an IP from the DHCP server.

**Comment by cyberb** [comment]
Have just rebuilt latest image, could you try:
http://artifact.syncloud.org/image/syncloud-odroid-u3-19.10.img.xz

**Comment by maichai** [comment]
Thank you, I imaged it, but the problem unfortunately remains.
I will check with a "known good" image on the weekend, to make sure the hardware did not break at some point in time.

**Comment by maichai** [comment]
I found the last image for that platform at the maker's web page:
https://wiki.odroid.com/old_product/odroid-x_u_q/odroid_u3/u3_release_linux_ubuntu

This image boots and also initializes the NIC properly, and the machine can be reached via network. 
I would probably be good to base the Syncloud image off the image you will find at this URL.

**Comment by cyberb** [comment]
Sure, here is the new image:
http://artifact.syncloud.org/image/syncloud-odroid-u3-19.10.img.xz

**Comment by maichai** [comment]
Thank you so much, it boot fine and the intialization page comes up. I have not gone further yet, but it probably good to replace the current download image for odroid U3 with this new one.

Lets keep this thread open until I have tested more.

**Comment by maichai** [comment]
The machine has a random mac after each power cycle. I don't think that is what it did years ago. That makes it hard to assign a fixed IP, which is needed for the Port mappings on the firewall... Any ideas? (Dont get me wrong, this is not a topic of the Syncloud system, it seems to be a thing of the hardware...)

**Comment by cyberb** [comment]
There is some info here:
https://forum.odroid.com/viewtopic.php?t=3384

Do you have this file?
````
cat /etc/smsc95xx_mac_addr
````

Do you have this module loaded?

````
lsmod smsc95xx
````

**Comment by maichai** [comment]
smsc95xx is loaded but /etc/smsc95xx_mac_addr does not exist

**Comment by maichai** [comment]
Apart from that small issue, the image seems to work fine so far. I think we can close this ticket. If something else comes up I will open a new ticket.
