### ISSUE TITLE
Odroid U3 image: Update renders the system dysfucntional  

### ISSUE THREAD

**Issue by maichai** [syncloud/platform#424]
After using the the update function in the admin UI the systems shows under App Center and Apps: "Oooops, We are sorry, but something went really wrong"

I guess I need to re-image the SD Card?

Any idea why this happens and how to fix it?

**Comment by cyberb** [comment]
Can you access settings page to send logs from support?
If not could you follow this instruction to give us more details: https://github.com/syncloud/platform/wiki/Report-problems
I would like to see what is wrong before you reimage it.

**Comment by maichai** [comment]
I pressed the button for log upload, it spinned forver but never finished. So I reimaged the machine already.
