### ISSUE TITLE
Collabora Online Developer Edition

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#426]
Investigate Collabora Live.
https://www.collaboraoffice.com/code/

**Comment by klmhsb42** [comment]
There is an (unstable) server app for nextcloud https://apps.nextcloud.com/apps/richdocumentscode

It still makes sense to implement this as own app, but could be interesting to support, too.

**Comment by SebastGG** [comment]
has some one tried the collabora built in code server nextcloud app? Is this working ?
![grafik](https://user-images.githubusercontent.com/59542884/101541613-fce02d00-39a1-11eb-88c8-983d4b46af78.png)
on my Odroid hc1 its not possible to activate it

**Comment by cyberb** [comment]
You can try on a PC (x64) with Virtual Box and our image, that should be the same as Syncloud S device.

**Comment by SebastGG** [comment]
i've tried it with x64 and got this error:
![grafik](https://user-images.githubusercontent.com/59542884/102009931-061f2000-3d3b-11eb-8db6-f9791bf8df28.png)
The App says please see (https://www.collaboraoffice.com/online/connecting-collabora-online-built-in-code-server-with-nginx/)
Are we using a nginx server and can someone point me to this file?

**Comment by SebastGG** [comment]
It seems that i found the config file which has to be changed:
https://github.com/syncloud/nextcloud/blob/master/config/nginx.conf
but i do't find it in the filesystem.. does someone know where?

**Comment by cyberb** [comment]
/var/snap/nextcloud/current/config/nginx.conf

It is reset on every uodate

**Comment by SebastGG** [comment]
for every nextcloud update? Or System update?
for now, i will give it try

**Comment by cyberb** [comment]
Nextcloud update.
Feel free tu publish a pull request with any useful change.

**Comment by SebastGG** [comment]
so, i tried to it with the changed config file but nothing happens, still the same error

**Comment by cyberb** [comment]
Canmot translate a screenshot.
What is the error message you are trying to fix?
What is the fix you are trying to test?

**Comment by SebastGG** [comment]
sorry. here in my words in english
- the error says could not establish conection to collabora server, maybe wrong configuration of webserver
- clich here to connect collabora server with nginx

the problem is , that the collabora app cannot connect to the built in code server. i did the changes in the config file as described in the Link (https://www.collaboraoffice.com/online/connecting-collabora-online-built-in-code-server-with-nginx/) but the error is still there.

**Comment by cyberb** [comment]
Why do you think there is any collabora server running?

**Comment by klmhsb42** [comment]
For _Collabora Online - Built-in CODE Server (ARM64)_ I get
`App "richdocumentscode_arm64" cannot be installed because appinfo file cannot be read. ` it might be related to this issue https://github.com/CollaboraOnline/richdocumentscode/issues/66

**Comment by cyberb** [comment]
Finally gave a proper look at all this.

1. "Nextcloud Built-in CODE Server app" is no go.

    It wants command line install only as it is too big and needs fontconfig to be installed separately on the box. Not good for Syncloud user experience.

3. Own server (added to Nextcloud app)

    I tried packaging a Collabora Online into our Nextcloud app with that version you just need to install Nextcloud Office app and set it to use "Use your own server" and set URL to the same as nextcloud itself (ex https://nextcloud.device). I was able to edit various text and calc documents.
    This is done and working on a branch but requires additional 500m to download also complicates Nextcloud packaging.

4. Independent app

    I will repackage it as a separate app and it will be available for x64 and maybe arm64. Arm is not supported by Collabora. That way users can decide if they need online office edit features as it requires additional 500m to download. The rest should be the same install Collabora, Nextcloud with Nextcloud Office and set it to use https://collabora.device. 

Another thing it is not clear how to only allow editing from Nextcloud and not from random Internet users but maybe I should not worry about for now. Also not clear if Collabora has its own web ui and if there is an Ldap authentication there.

**Comment by cyberb** [comment]
Independent app is almost ready, Nextcloud can edit files. Will release soon. Collabora admin UI is not functioning yet (will be fixed later) but is not required for Nextcloud editing features.

**Comment by cyberb** [comment]
Collabora is released, https://github.com/syncloud/platform/wiki/Collabora
