### ISSUE TITLE
Nextcloud apps not working after upgrade

### ISSUE THREAD

**Issue by trevorprinn** [syncloud/platform#430]
I've just upgraded Nextcloud to 19103078 (16.0.5) and now the web interfaces for the extra apps I had installed no longer work. These are Contacts, Calendar, Polls and Passwords. The Contacts and Calendars still seem to be working OK (I can create, edit and delete calendar items in Thunderbird and they synch to other devices, for example), but the web interfaces are either blank or, in the case of Calendar, what looks like a failed attempt to run something like angular.

I'm seeing Javascript errors such as
`Content Security Policy: The page's settings blocked the loading of a resource at chrome-extension://75d8c347-bf25-4772-9c0a-a7a48df345be/fonts/GothamSSm-Book.woff ("font-src").`
on Firefox and Chrome shows a load of 404 errors (perhaps the same errors reported differently).

There are also warnings such as
`Loading failed for the <script> with source “https://nextcloud.tprinn.syncloud.it/extra-apps/calendar/js/public/app.min.js?v=f5a3783b-0”. calendar:44:1`

**Comment by shiremail** [comment]
I deleted the app and also reinstalled the whole OS one the sd card. Doesn't work. The app is broken and can't even be installed fresh on the system.

**Comment by cyberb** [comment]
Could you check contents of this file:
/var/snap/nextcloud/current/nextcloud/config/config.php

Path for extra-apps should be pointing at: /var/snap/nextcloud/[version]/extra-apps

This is wrong value:  /var/snap/nextcloud/common/extra-apps

Simple fix is to change it to : /var/snap/nextcloud/current/extra-apps

I will publish an updated version soon.

**Comment by shiremail** [comment]
It worked somehow. But it needed a few tries for the installation.

**Comment by marxistvegan** [comment]
> Could you check contents of this file:
> /var/snap/nextcloud/current/nextcloud/config/config.php
> 
> Path for extra-apps should be pointing at: /var/snap/nextcloud/[version]/extra-apps
> 
> This is wrong value: /var/snap/nextcloud/common/extra-apps
> 
> Simple fix is to change it to : /var/snap/nextcloud/current/extra-apps
> 
> I will publish an updated version soon.

I am seeing this 

` 'apps_paths' => array(
        array(
                'path'=> '/snap/nextcloud/current/nextcloud/apps',
                'url' => '/apps',
                'writable' => false,
        ),
        array(
                'path'=> '/var/snap/nextcloud/19103078/extra-apps',
                'url' => '/extra-apps',
                'writable' => true,
        ),
`

**Comment by cyberb** [comment]
@marxistvegan Could you execute these commands:

````
snap run nextcloud.occ config:system:get apps_paths 1 path
````

````
ls -la /var/snap/nextcloud/current
````

**Comment by marxistvegan** [comment]
Yep 

> ```
> snap run nextcloud.occ config:system:get apps_paths 1 path
> ```
> ```
> ls -la /var/snap/nextcloud/current
> ```
```

root@syncloud:~# snap run nextcloud.occ config:system:get apps_paths 1 path
/var/snap/nextcloud/common/extra-apps
root@syncloud:~# ls -la /var/snap/nextcloud/current
lrwxrwxrwx 1 root root 8 Nov  7 22:58 /var/snap/nextcloud/current -> 19103078
root@syncloud:~# 

```

**Comment by cyberb** [comment]
Try this workaround:

````
snap run nextcloud.occ config:system:set apps_paths 1 path --value="/var/snap/nextcloud/current/extra-apps"
````

**Comment by trevorprinn** [comment]
That's sorted it for me. Thanks.
(I'll leave it to you to close the issue when it's working for everyone).

**Comment by marxistvegan** [comment]
Likewise it resolved it, it did a app update in the beginning when I visited the site, and disabled some but then updated the right click app and then they were enabled on the next visit.

**Comment by cyberb** [comment]
Update released.
