### ISSUE TITLE
OwnTracks - location sharing

### ISSUE THREAD

**Issue by DrMantisTobbogan** [syncloud/platform#431]
I think it would be great if a location sharing app could be added. [OwnTracks ](https://github.com/owntracks)is open source and seems to be actively maintained. It also has [support ](https://owntracks.org/booklet/guide/clients/)for both HTTP and MQTT protocols if that makes things easier to implement.

**Comment by cyberb** [comment]
Seems not active or dead

**Comment by cyberb** [comment]
Done
