### ISSUE TITLE
[mail] How to add more users

### ISSUE THREAD

**Issue by SebastGG** [syncloud/platform#437]
I have a question how to add more users/email adresses to the mail server. I've added all my users with the users app. At the nextcloud side the users are available/accessable but at the mailserver not.

**Comment by cyberb** [comment]
What kind of error do you see if you try to login to mail web?
Can you send logs to support from settings - support page?

**Comment by SebastGG** [comment]
for me the question is, the user credentials schould be for all apps the same? If this is correct, then something is wrong.
Error - the login failed
logs are on the way

**Comment by cyberb** [comment]
Yes all apps get the same user credentials.
No logs yet, do not forget to include support checkbox.

**Comment by SebastGG** [comment]
logs are sent

**Comment by cyberb** [comment]
Did you enter lowercase username and UID to be the same?

**Comment by SebastGG** [comment]
What i did is, to fill the fields in the users app and created new users. The name and first name are different to the UID which is a syntesis of all given names!

What i see when i compare all users: The admin user created during the activation/installation of the users app has not filled all fields in the users app. The UID is the same as the Name and the first name field is empty.

So do i have to modify, after creating an new user, this to the same look as the admin user?

**Comment by cyberb** [comment]
Sorry for the confusion, you need to use "Display Name" as your username.
It will be renamed to User Name soon

**Comment by SebastGG** [comment]
![grafik](https://user-images.githubusercontent.com/59542884/72104296-69ceeb00-332b-11ea-8570-0d8a9c979251.png)
So if i add the user "Test". What are the credentials for the apps?

Username: Test Test
Passw: ********

![grafik](https://user-images.githubusercontent.com/59542884/72104412-a4d11e80-332b-11ea-93f0-0c7a7150725e.png)

Login fails

**Comment by SebastGG** [comment]
The Nextcloud App uses the UID as the Username

**Comment by cyberb** [comment]
In Users app you should set:
````
Display Name: test
````
In Mail you should use:
````
User: test
````

**Comment by SebastGG** [comment]
allright. After modifying the display name, as descibed, i can login to all users.
Thanks

**Comment by cyberb** [comment]
I must say it is a mess, we should not use Display Name as user name. I should fix Mail to use UID and rename UID to Username.
For now if you keep Display Name (Username) same as UID you should be safe when this is fixed.

**Comment by cyberb** [comment]
For now I have made a change to Users app to show User name and copy its value to UID.
