### ISSUE TITLE
PHPVirtualBox

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#439]
https://github.com/phpvirtualbox/phpvirtualbox

I've virtualbox running on my home server with Syncloud VM and another Server as VM. Would be nice to have syncloud server as host of virtualbox to avoid an additional OS (needed as host now) to save hardware capacity.

**Comment by cyberb** [comment]
You can install Syncloud as OS on your host just boot from the image, did you try?

**Comment by cyberb** [comment]
This is too much dev oriented for Syncloud users, closing this for now.
For devs already have plain OS, VirtualBox and docker.
