### ISSUE TITLE
ISP blocks lower end ports

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#44]
Sometimes ISPs block popular ports like 80, 443...
Probably insider should check if mapped port is actually accessible.

**Comment by cyberb** [comment]
This cannot be done without outsider :) (redirect service) we can ask it to ping services.

This may be a potential security hole as hackers may register not their servers add 1-10000 services and then ping them, so we become a port scanner.

**Comment by vsapronov** [comment]
We need to do this as a part of web-based UPnP Router check. We can easily avoid port scanning problem, if we check address:port only when right domain token is provided.
