### ISSUE TITLE
Syncloud as router

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#442]
Just another idea with lower priority: It would be nice to use Syncloud as router (all-in-one) with e.g. http://www.banana-pi.org/r2.html device. All settings which you have to do in the extern router today could be done by default which would make it way easier to setup. Also people don't have to spend money twice. Using https://openwrt.org/

**Comment by klmhsb42** [comment]
Or https://www.turris.cz/en/omnia/ as device

**Comment by cyberb** [comment]
OpenWRT seems to be a good candidate.
Many router software projects still rely on FreeBSD like pfSense/OPNSense whic we cannot use.
And all of them try to be OS distros themselves which is fine but we will have to spend some time repackaging as an app.

**Comment by cyberb** [comment]
https://en.m.wikipedia.org/wiki/Comparison_of_router_software_projects

**Comment by cyberb** [comment]
Also apart from standard network features routing, filtering, port mapping they add additional feature like VPN which does not make sense for Syncloud as they are independent apps.
So ideally I would look for a router app which would cover minimal set of features.
For now I guess anything will work to remove the need to have a real router.
I guess you cannot phisically remove a router because they many times combine modems

**Comment by cyberb** [comment]
Such routers/modems will have to stay in bridge mode.

**Comment by cyberb** [comment]
Someone actually tried to create OpenWRT snap:https://github.com/asac/openwrt-snap

**Comment by cyberb** [comment]
Another thing, do you even need a router for IPv6?

**Comment by klmhsb42** [comment]
Interesting question. What if you have DS or DSlite, don't you need it to access _IPv4 only_ websites? Or is this NAT by the ISP? But yes, otherwise you need only an _simple_ app with which you can organize your privat network (name resolution of home devices and DNS Rebind Protection). BTW, [this](https://github.com/syncloud/platform/wiki/External-access#ipv6-port-sharing) ipv6-port-sharing entry in your wiki was my misstake. You don't need it.

OpenWRT app would be a nice start and would be still useful as it will take time that all people are moving to IPv6...

**Comment by klmhsb42** [comment]
I assume that the devices get their IPv6 directly from the ISP and not from the router? Would be nice to have an app which would give devices _ipv6 privacy extensions_

**Comment by klmhsb42** [comment]
Something like a IoT device manager. E.g. this https://thinger.io/

**Comment by klmhsb42** [comment]
Simple _modem interface app_ would be also nice.

**Comment by klmhsb42** [comment]
You can remove the _ipv6-port-sharing entry_ in the wiki and close this issue

**Comment by cyberb** [comment]
Great, done.
