### ISSUE TITLE
asterisk app

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#446]
VoIP server https://www.asterisk.org/

**Comment by cyberb** [comment]
Actually I spent months in this one few years ago. Tried to create VoIP server to use with SIP compatible phone clients. It is much more complex than mail app which took months to understand and configure.
So I gave up and then I tried Nextcloud Talk and I must say they did a great job and I use it to talk to my relatives regulary.
So in terms of complete out of the box simple to use VoIP client like WhatsApp I think it is impossible without some well maintained open source solution on top of asterisk. Asterisk is too low and has complex configuration and at the time there was no good opensource mobile/desktop client 

If you want to provide just Asterisk itself for admins to configure I do not see the point it being a Syncloud app, what can be easier than apt install asterisk or probably even snap install asterisk on a regular Ubuntu.

**Comment by klmhsb42** [comment]
Yes you are right. Asterisk is too complex. It's just that I have VoIP phone numbers from my cable provider and my router has options to set up phones. Would be nice to have a simple app to manage and connect. Also to use it with VoIP client on smartphone. Nextcloud talk is great but there is no option to make landline phone calls. It just an idea with low priority...

**Comment by klmhsb42** [comment]
Also Syncloud customers could be also business customers and use it for their small business/store
