### ISSUE TITLE
Nextcloud upgrade (SD card issue)

### ISSUE THREAD

**Issue by tfhmd1** [syncloud/platform#448]
Hi, I have a problem upgrading the nextcloud app.

Installed version: 19111297
Available version: 200109121

It does not seem to want to upgrade - it is showing 'upgrading' and the wheel is spinning. It eventually stops and remains with the existing version. All other apps still upgrade without problem

**Comment by cyberb** [comment]
You are using an old version at the moment the only way to upgrade is to execute few commands obln the device. Here is the instruction: https://github.com/syncloud/platform/wiki/Nextcloud#upgrade-to-a-specific-version
You need to upgrade to 15 then to 17 and then back to stable.

**Comment by tfhmd1** [comment]
Sorry for the basic question, but how/where do I find the OCC?

**Comment by cyberb** [comment]
You do not really need to use OCC command. All you need is to run the following set of commands using ssh:

````
wget apps.syncloud.org/apps/nextcloud_19102646_$(dpkg --print-architecture).snap

snap install nextcloud_19102646_$(dpkg --print-architecture).snap --devmode

wget apps.syncloud.org/apps/nextcloud_19111297_$(dpkg --print-architecture).snap

snap install nextcloud_19111297_$(dpkg --print-architecture).snap --devmode

snap refresh nextcloud --amend
````

**Comment by cyberb** [comment]
SSH info: https://github.com/syncloud/platform/wiki/SSH

**Comment by tfhmd1** [comment]
Hi Boris,

I'm not sure if you are getting my emails - I tried what you suggested. 
It hasn't worked - should I just remove and reinstall?

Thanks,

Tom

**Comment by cyberb** [comment]
Yes, that should also work, but it will clear all the settings like calendars, contacts.

**Comment by tfhmd1** [comment]
Ah yes, that is not ideal.

I'll try again - it does download the new updates. I followed your 
instructions exactly - at the end it says:

Run configure hook of "nextcloud" snap if present

*The Installed version:*200109121


I think I need to give one more command to configure the hook, otherwise 
it reverts back to the old version.

Thanks,

Tom

**Comment by cyberb** [comment]
Sorry, you are actually on a version which should upgrade using UI fine.
Could you send one more email with logs so I can check, must be something else then.
Did you buy your device or built yourself?
Which device do your have?

**Comment by tfhmd1** [comment]
I was upgrading the OS and didn't let it finish.

Now, I am not able to connect at all to syncloud - there is a blank 
screen on my browser except:


  This site can’t be reached

*192.168.100.4*refused to connect.

Try:

  * Checking the connection
  * Checking the proxy and the firewall
    <chrome-error://chromewebdata/#buttons>

ERR_CONNECTION_REFUSED


I have tried to restart both the server and router but no luck.

**Comment by cyberb** [comment]
How exactly you were upgrading OS?

**Comment by tfhmd1** [comment]
I was upgrading by clicking the upgrade button in the settings.

**Comment by cyberb** [comment]
From your logs you have SD card issue:
````
mmcblk1: error -110 transferring data, sector 5209881, nr 256, cmd response 0x900, card status 0x0
````
How did you build the device, did you buy or built yourself?
Is it HC1?
If you built yourself you need to follow this instruction and use SATA SSD disk for Syncloud:
https://github.com/syncloud/platform/wiki/Boot-from-SATA

**Comment by tfhmd1** [comment]
Yes, It is the HC1, built by myself. I had only had the OS on the SD 
card as I didn't know that there was a USB option.

Question - if I install a fresh version of Syncloud on the SD and USB, 
will I have lost all my settings for the nextcloud already on the system?

Secondly, to follow the instructions, I need to run Putty?

Thanks

**Comment by cyberb** [comment]
It is not usb, it is SATA connection.
You will lose settings unless you do a backup first, but your settings are probably lost already as SD fails.
If you write both and boot then yes you need Putty to make SATA disk your boot disk.

**Comment by tfhmd1** [comment]
I got this message on the command:

'lsblk' is not recognized as an internal or external command,
operable program or batch file.

I decided to proceed with just an SD boot at the moment. Is it possible 
to boot with the SATA SSD disk once I solve the above issue?

**Comment by cyberb** [comment]
Yes, fixed the instruction, you need to install few tools:
https://github.com/syncloud/platform/wiki/Boot-from-SATA#on-device

**Comment by tfhmd1** [comment]
I don't seem to be able to use Putty to access the syncloud - I've tried 
root and syncloud  and my own syncloud username and password. Neither 
combination is working.

**Comment by cyberb** [comment]
For Putty (SSH) you always need to use "root" as user.
Default password is "syncloud".
If you activate device, password will be set to activation password.

**Comment by tfhmd1** [comment]
OK, this is the output I got:


NAME        FSTYPE   LABEL UUID MOUNTPOINT
sdb
`-sdb1      ext4           97c88af2-1145-43ea-bbbe-de32b1d9388e
mmcblk1
|-mmcblk1p1 vfat     boot  52AA-6867
`-mmcblk1p2 ext4
loop0       squashfs /snap/platform/1
sda
|-sda2      ext4           e139ce78-9841-40fe-8823-96a304a09859 /
`-sda1      vfat     boot  52AA-6867

If this is ok, can I now remove both the SD and the USB and reboot?

**Comment by cyberb** [comment]
Unfortunately SD card has to be inserted to boot the device but it will not be used as an internal disk for OS files (rootfs) so chances of it being corrupted are very low and even if it happenes you can replace it without losing anything.

USB, do you mean SATA disk or actually you have external USB attached and nothing inside attached to SATA?

**Comment by tfhmd1** [comment]
That's ok - the main thing is that the SD card failure (which seems to 
be very regular occurrence) does not end up causing bigger issues. The 
whole idea of the server is that it should be reliable, so your work 
around is extremely positive. Not sure why Hardkernel haven't thought to 
do something like this.

I installed the OS on the SATA using the USB (as per your intructions 
on: https://github.com/syncloud/platform/wiki/Boot-from-SATA#on-device)

Also I have the OS on the SD. When I remove the USB and just left the SD 
in place it doesn't boot at all. I've just put the USB back in, and 
rebooted and on Putty validated and got the following:


NAME        FSTYPE   LABEL UUID MOUNTPOINT
sdb
`-sdb1      ext4           97c88af2-1145-43ea-bbbe-de32b1d9388e
mmcblk1
|-mmcblk1p1 vfat     boot  52AA-6867
`-mmcblk1p2 ext4
loop0       squashfs /snap/platform/1
sda
|-sda2      ext4           e139ce78-9841-40fe-8823-96a304a09859 /
`-sda1      vfat     boot  52AA-6867

I've also just sent you a log report.

I presume it is booting from the USB instead of the SATA. Can you 
confirm? Is there another command I need to do in order to switch the OS 
to the SATA?

**Comment by tfhmd1** [comment]
In addition to the below - I should add that I have an SSD attached to 
the SATA. Currently now, I have the SD and USB attached as it does not 
boot with just the SD in there.

Can I now start adding apps or is there anything else to do first?
Thanks.

**Comment by tfhmd1** [comment]
On the external activation - it says In case of custom domain name 
external access page should not be used.

What should I do in this case? It is not allowing me to have external 
router access - I can put only 443 and 79 (80 is not currently available 
until I change my provider in a couple of weeks).

**Comment by cyberb** [comment]
Put USB disk away for now.
Write image to SD and SSD (using USB/SATA adapter)
Attach both and boot.
Reset boot flag on SD and reboot.
Does it work?

**Comment by cyberb** [comment]
Do you have custom domain name?
Something other than [user].syncloud.it

**Comment by tfhmd1** [comment]
Ah, now I understand. I'll try flashing the SATA tomorrow and following 
the steps again. I'll let you know if it works.

**Comment by tfhmd1** [comment]
Yes, I have a custom domain name. I have activated it previously and it 
worked ok with activating again. Just this problem with the external ports.

**Comment by cyberb** [comment]
Most likely you just need to create port mappings. 
https://github.com/syncloud/platform/wiki/Custom-domain

If you have no port 80 mapping you will not have a https certificate.
https://github.com/syncloud/platform/wiki/Browser-warning-(certificate-problem)

**Comment by tfhmd1** [comment]
I finally read properly what you had asked - I now installed the OS on 
the SSD using the SATA adapter, attached both and booted.

I have installed Nextcloud, but it seems that the nextcloud is 
installing on the SD and not the SSD - here is what I am getting from PUTTY:


NAME        FSTYPE   LABEL UUID MOUNTPOINT
loop1       squashfs /snap/platform/1
mmcblk1
|-mmcblk1p1 vfat     boot  52AA-6867
`-mmcblk1p2 ext4
loop0       squashfs /snap/nextcloud/
sda
|-sda2      ext4           e139ce78-9841-40fe-8823-96a304a09859 /
`-sda1      vfat     boot  52AA-6867

**Comment by cyberb** [comment]
No, it is actually not on SD (mmcblk). It is just a little bit confusing output, it uses loop device which mounts the app from /snap/... Anything under / is SATA disk (/dev/sda2)

**Comment by tfhmd1** [comment]
Something has gone very wrong - I'm wondering whether to just reformat 
both the SD and SATA and and start all again. Is this the best solution?

**Comment by cyberb** [comment]
Sure

**Comment by tfhmd1** [comment]
I have reformatted and flashed both the SATA and SD. I have installed 
the SD and SATA and activated the syncloud.

Then I ran:

|sudo tune2fs -U clear /dev/mmcblk1p2|


The reply was:
The UUID may only be changed when the filesystem is unmounted.

I then ran the check:

root@syncloud:~# lsblk -f
NAME        FSTYPE   LABEL UUID MOUNTPOINT
mmcblk1
|-mmcblk1p1 vfat     boot  52AA-6867
`-mmcblk1p2 ext4           e139ce78-9841-40fe-8823-96a304a09859 /
loop0       squashfs /snap/platform/1
sda
|-sda2      ext4           e139ce78-9841-40fe-8823-96a304a09859
`-sda1      vfat     boot  52AA-6867

Is everything fine? I won't install any apps until I know that the 
system is booting from the SATA.

**Comment by cyberb** [comment]
The correct order is this:
1. Flash both
2. Boot
4. Run tune2fs clean
5. Reboot
6. Run lsblk
7. Activate and install apps.

**Comment by tfhmd1** [comment]
I've done all that - I'm now uploading files to the server - it is 
running very slowly (200kb/s average). I'm starting to think that I'm 
uploading to the 32GB SD card instead of the 1tb SSD - is there a way to 
check this?

Here is my report from running lsblk:

NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop1         7:1    0 123.1M  1 loop /snap/nextcloud/200109121
mmcblk1     179:0    0  28.8G  0 disk
|-mmcblk1p1 179:1    0   128M  0 part
`-mmcblk1p2 179:2    0  28.7G  0 part /
loop2         7:2    0 529.4M  1 loop /snap/rocketchat/190609478
loop0         7:0    0  53.8M  1 loop /snap/platform/19112983
sda           8:0    0 931.5G  0 disk
|-sda2        8:2    0     3G  0 part
`-sda1        8:1    0   128M  0 part
loop3         7:3    0  54.6M  1 loop /snap/platform/200119157

I just send a log also.

**Comment by tfhmd1** [comment]
I'm still uploading files which is going very slowly - I wonder if it is 
possible to see which disk is filling up with data - I suspect it is the 
SD rather than the SATA. I've attached a screenshot of the storage page.

**Comment by cyberb** [comment]
> The UUID may only be changed when the filesystem is unmounted.

Really sorry I forgot that it is not possible to reset UUID on a mounted device.
You actually need to do it on a Linux PC/device which is not running on it at the same time. Docs are reverted.

**Comment by tfhmd1** [comment]
Ok, so I need to format both SD card and SSD again, install OS on SD 
first and run that without the SSD installed?

Meanwhile I install OS on the SSD and then install both of them together?

If I want to revert to just booting from the SD for now, what does that 
require me to do?

**Comment by cyberb** [comment]
> Ok, so I need to format both SD card and SSD again, install OS on SD
first and run that without the SSD installed?

No, sorry it is all confusing that is why people buy pre-configured devices :)
Odroid always boots from SD regardless of SATA (SSD) being attached or not. So current solution to force Odroid to use SATA (SSD) as root file system is to clear UUID from SD card file system. The only problem is that you can do it only when you are not running in this SD so this has to be done on the other PC. You can do it on the same device only if you boot on another SD and attach this SD using USB adapter for example.

> If I want to revert to just booting from the SD for now, what does that
require me to do?

This is default mode and does not require anything, just use the SD with the image.
SATA (SSD) in this mode can be used as an external storage using Storage page. External storage stores files generated by apps while apps themselves and OS stays on SD card which not very good.

Sorry I used SATA and SSD interchangeably and meant SATA disk.

**Comment by tfhmd1** [comment]
Apologies for causing so much hassle with this. The reason I had used my 
own device was that I wanted to use my own domain name. I'm happy to pay 
for support in setting up.

I'm just going to reformat the SATA and try again. As this is a 
temporary solution until the Helios 64 is shipped, I'm hoping that the 
SD will survive that long.

Thanks for your help and the great Syncloud!

**Comment by cyberb** [comment]
I think I can actually provide a separate image for HC SD card to simplify things.

**Comment by tfhmd1** [comment]
That's great. Can I continue to use the server as it is at the moment or 
should I wait to install everything from scratch?

**Comment by cyberb** [comment]
You can continue, I will let you know here when it is ready and you decide what to do :)

**Comment by cyberb** [comment]
I have released the new type of image for Odroid HC with SATA disk.
Image for SD card: https://github.com/syncloud/platform/releases/download/20.01/syncloud-odroid-xu3and4-boot-20.01.img.xz
Image for SATA disk: https://github.com/syncloud/platform/releases/download/20.01/syncloud-odroid-xu3and4-20.01.img.xz
Could you try?

**Comment by tfhmd1** [comment]
Certainly! I'll come back later today after I installed it

On 2 February 2020 16:39:11 EET, Boris Rybalkin <notifications@github.com> wrote:
>I have released the new type of image for Odroid HC with SATA disk.
>Image for SD card:
>https://github.com/syncloud/platform/releases/download/20.01/syncloud-odroid-xu3and4-boot-20.01.img.xz
>Image for SATA disk:
>https://github.com/syncloud/platform/releases/download/20.01/syncloud-odroid-xu3and4-20.01.img.xz
>Could you try?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/syncloud/platform/issues/448#issuecomment-581141773

-- Sent from /e/ Mail

**Comment by tfhmd1** [comment]
I am able to boot but the storage drive is not showing. Perhaps I have 
not formatted it correctly before installing the OS?

See attached.

**Comment by cyberb** [comment]
Which drive (SATA)?
Not showing where (Storage)?

That is the idea, now SATA disk has became you main disk and you cannot also attach it as a storage. If you want additional storage you can attach USB disk.

Just to confirm, what 'lsblk -f' shows?

**Comment by tfhmd1** [comment]
Here is what it is showing:


NAME        FSTYPE   LABEL UUID MOUNTPOINT
mmcblk1
|-mmcblk1p1 vfat     boot  52AA-6867
`-mmcblk1p2 ext4
loop0       squashfs /snap/platform/2
sda
|-sda2      ext4           e139ce78-9841-40fe-8823-96a304a09859 /
`-sda1      vfat     boot  52AA-6867

I just pressed 'extend' on the storage page and the boot disk went from 
3G to 931G - so it must be now booting from the SATA - I'll just try to 
install nextcloud and see if I can get it to work - it is looking promising.

**Comment by cyberb** [comment]
Yes, extend is still needed as etcher cannot really do it for you as far as I know.
Otherwise it is all good.

**Comment by tfhmd1** [comment]
Unfortunately it all stopped working after I installed nextcloud. It was 
synchronising but didn't get very far before it started to go slow and 
then this screen occurred.

**Comment by cyberb** [comment]
What screen?
Can you send logs?

**Comment by caroyston** [comment]
Hi Cyberb,
I have a similar build using the Odriod H1. I used the 2 images you uploaded and flashed the MicroSD and SSD respectively. Did the Activation and ran extend and SynCloud storage shows 120gig :-D
Next I installed Nextcloud from the apps, logged in and Everything looks great. Then I checked  System Disk. I only show 2.72gig on sda2. As this is a brand new install I can mess with it without losses.   Any ideas?

root@syncloud:~# lsblk -f
NAME        FSTYPE   LABEL UUID  MOUNTPOINT
loop1       squashfs       /snap/nextcloud/
mmcblk1
|-mmcblk1p1 vfat     boot  52AA-6867
`-mmcblk1p2 ext4
loop0       squashfs       /snap/platform/2
sda
|-sda2      ext4  e139ce78-9841-40fe-8823-96a304a09859 /
`-sda1      vfat     boot  52AA-6867

![Capture](https://user-images.githubusercontent.com/47074485/73906081-7d03a680-4856-11ea-9353-bc181da11ae5.JPG)

**Comment by cyberb** [comment]
Could you run:
````
df -h
````

**Comment by tfhmd1** [comment]
Filesystem      Size  Used Avail Use% Mounted on
udev            930M     0  930M   0% /dev
tmpfs           200M   18M  183M   9% /run
/dev/sda2       2.9G  2.9G     0 100% /
tmpfs           998M     0  998M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           998M     0  998M   0% /sys/fs/cgroup
/dev/loop0       56M   56M     0 100% /snap/platform/200130176
/dev/loop1      124M  124M     0 100% /snap/nextcloud/200109121

I rebooted - I was able to click a send logs button - not sure if it worked.

**Comment by caroyston** [comment]
sure:
root@syncloud:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            930M     0  930M   0% /dev
tmpfs           200M   22M  179M  11% /run
/dev/sda2       2.9G  1.2G  1.7G  41% /
tmpfs           998M  8.0K  998M   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           998M     0  998M   0% /sys/fs/cgroup
/dev/loop0       56M   56M     0 100% /snap/platform/200130176
/dev/loop1      124M  124M     0 100% /snap/nextcloud/200109121
root@syncloud:~#

Wow, so the 120gig drive is only 2% partitioned?

**Comment by cyberb** [comment]
This should show you the real size of the disk:
````
lsblk
````

Expand boot in Settings - Storage should fix that. Strange it went back if you already did that. Could you ry again?

**Comment by tfhmd1** [comment]
Hi, I ran lsblk:


NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop1         7:1    0 123.1M  1 loop /snap/nextcloud/200109121
mmcblk1     179:0    0  28.8G  0 disk
|-mmcblk1p1 179:1    0   128M  0 part
`-mmcblk1p2 179:2    0     3G  0 part
loop0         7:0    0    56M  1 loop /snap/platform/200130176
sda           8:0    0 931.5G  0 disk
|-sda2        8:2    0 931.4G  0 part /
`-sda1        8:1    0   128M  0 part

Do I need to also run 3. 'tune2fs clean' ?

Nothing has changed so far - I still have the same screen.

 1. Flash both
 2. Boot
 3. Run tune2fs clean
 4. Reboot
 5. Run lsblk
 6. Activate and install apps.

**Comment by cyberb** [comment]
> Do I need to also run 3. 'tune2fs clean' ? 

No, the new way is to simply write two corresponding images to SD and SATA disk. tune2fs is not needed anymore.
Can you extend boot disk from Settings - Storage screen?

**Comment by tfhmd1** [comment]
Nope - I rebooted and still I get the white screen. I input my username 
and password to no avail.

Should I reinstall the images again?

**Comment by cyberb** [comment]
Ok, probably Nextcloud or files took all the space. Did you expand before installing or not?
I have changed the doc to mention the expand.
Simplest thing is to flash again both images, then expand and reboot. Make sure you have correct size on storage page and then install apps.

**Comment by tfhmd1** [comment]
I've just installed again and expanded the storage before installing any 
software.

A problem I am encountering is with Nextcloud which is saying there is 
no space. When I run lsbk I get:

NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop1         7:1    0    56M  1 loop /snap/platform/200130176
mmcblk1     179:0    0  28.8G  0 disk
|-mmcblk1p1 179:1    0   128M  0 part
`-mmcblk1p2 179:2    0     3G  0 part
loop2         7:2    0  93.2M  1 loop /snap/pihole/191023246
loop0         7:0    0 529.4M  1 loop /snap/rocketchat/190609478
sda           8:0    0 931.5G  0 disk
|-sda2        8:2    0 931.4G  0 part /
`-sda1        8:1    0   128M  0 part
loop3         7:3    0 123.1M  1 loop /snap/nextcloud/200109121

Is there any way to allow the programs to use as much space as they need?

**Comment by cyberb** [comment]
Could you run this:
````
df -h
````

**Comment by tfhmd1** [comment]
yes, it gives this:


Filesystem      Size  Used Avail Use% Mounted on
udev            930M     0  930M   0% /dev
tmpfs           200M  9.5M  191M   5% /run
/dev/sda2       2.9G  2.8G     0 100% /
tmpfs           998M   40K  998M   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           998M     0  998M   0% /sys/fs/cgroup
/dev/loop0      530M  530M     0 100% /snap/rocketchat/190609478
/dev/loop1       56M   56M     0 100% /snap/platform/200130176
/dev/loop2       94M   94M     0 100% /snap/pihole/191023246
/dev/loop3      124M  124M     0 100% /snap/nextcloud/200109121

**Comment by cyberb** [comment]
I see, run this:
````
/snap/platform/current/bin/resize-sd-partition.sh
````
And then df again.

**Comment by tfhmd1** [comment]
Thanks - it seems to have worked - I'll let you know for sure once 
everything has sync'd later on. Here is what it said when I ran it:

Command (m for help):

Command (m for help):
Disk /dev/sda: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 33553920 bytes
Disklabel type: dos
Disk identifier: 0x3cedfd53

Device     Boot  Start        End    Sectors   Size Id Type
/dev/sda1         2048     264191     262144   128M  c W95 FAT32 (LBA)
/dev/sda2       264193 1953525167 1953260975 931.4G 83 Linux

Partition 3 does not start on physical sector boundary.


Command (m for help): Partition number (1,2, default 2):
Partition 2 has been deleted.

Command (m for help): Disk /dev/sda: 931.5 GiB, 1000204886016 bytes, 
1953525168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 33553920 bytes
Disklabel type: dos
Disk identifier: 0x3cedfd53

Device     Boot Start    End Sectors  Size Id Type
/dev/sda1        2048 264191  262144  128M  c W95 FAT32 (LBA)


Command (m for help): Partition type
    p   primary (1 primary, 0 extended, 3 free)
    e   extended (container for logical partitions)
Select (default p): Partition number (2-4, default 2): First sector 
(264192-1953525167, default 327675): Last sector, +sectors or 
+size{K,M,G,T,P} (264193-1953525167, default 1953525167):
Created a new partition 2 of type 'Linux' and of size 931.4 GiB.

Command (m for help): Disk /dev/sda: 931.5 GiB, 1000204886016 bytes, 
1953525168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 33553920 bytes
Disklabel type: dos
Disk identifier: 0x3cedfd53

Device     Boot  Start        End    Sectors   Size Id Type
/dev/sda1         2048     264191     262144   128M  c W95 FAT32 (LBA)
/dev/sda2       264193 1953525167 1953260975 931.4G 83 Linux

Partition 3 does not start on physical sector boundary.


Command (m for help):
The partition table has been altered.
Calling ioctl() to re-read partition table.
Re-reading the partition table failed.: Device or resource busy

The kernel still uses the old table. The new table will be used at the 
next reboot or after you run partprobe(8) or kpartx(8).

resize2fs 1.42.12 (29-Aug-2014)
The filesystem is already 244157621 (4k) blocks long.  Nothing to do!

**Comment by tfhmd1** [comment]
Just to say that everything is working. Thank you very much for all your 
effort to sort out the problem.

**Comment by cyberb** [comment]
No problem, closing this, if you have more problems please open new one.
