### ISSUE TITLE
Bitwarden

### ISSUE THREAD

**Issue by tfhmd1** [syncloud/platform#449]
https://bitwarden.com/

This open source self hosted password vault would be very useful!

**Comment by cyberb** [comment]
1. It is written on dotnet hence Microsoft tools which every time I touch it on Linux is not 100% the same as on Windows. Especially on our arm 32 boards.
2. SQL Server dependency. Not sure how is this a free tool. Definitely not open source.
3. Also looks like they are very docker oriented. Should not be difficult to remove that requirement in theory as we do not use docker but instead snapd.

So for me while this is actually cool project I think it is no go at the moment. Unless someone is willing to maintain it.

**Comment by chexxor** [comment]
There is an unofficial server implementation written in Rust which people use, which might be new knowledge for you and might change your opinion.

https://github.com/dani-garcia/bitwarden_rs

**Comment by cyberb** [comment]
This looks much better!

**Comment by shiremail** [comment]
An implementation would be great.

**Comment by tfhmd1** [comment]
Is this still a possibility?

**Comment by cyberb** [comment]
Yes, we are running out of resources.
Do you want to give it a go?
https://github.com/syncloud/platform/wiki/App-porting-guide

**Comment by cyberb** [comment]
released, check app store

**Comment by shiremail** [comment]
Thank you very much. Works great so far….
