### ISSUE TITLE
Remove old packages from PyPi

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#45]

**Comment by vsapronov** [comment]
I'll rename this task. For prod in 0.9 we are already on S3. Although we need to clean PyPi from 0.8 apps after 0.9 release. We are still using PyPi during build, so it would be nice to keep it clean. These are libraries we are deploying to PyPi: convertible, syncloud-app, coin, travis-tools.

**Comment by vsapronov** [comment]
I have removed almost all packages from PyPi. These only left: coin, convertible, syncloud-app, travis-tools.
Keep this in mind if something will break unexpectedly any time soon...
