### ISSUE TITLE
[Users] App access permissions

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#453]
Would be nice to have the option to enable/disable access to an app for each user

**Comment by klmhsb42** [comment]
and to be able create groups for this https://ldapwiki.com/wiki/LDAP%20Group

**Comment by klmhsb42** [comment]
#557

**Comment by cyberb** [comment]
Groups are available now in latest users app.

**Comment by cyberb** [comment]
Why do you need this?

**Comment by klmhsb42** [comment]
Well, I personally don't. But let's say if you want to run syncloud in a small business (premium), you might want to create users that can login into e.g. nextcloud app but e.g. not gitlab app (because they have a certain role in the company). You can close this or add issue labels like "add feature" and "add premium feature". 

I thought about that a simple django app https://django-auth-ldap.readthedocs.io/en/latest/ could be also an option as frontend #620 and to manage users like app access. Anyway, I don't have resources to support you right now, so you can close it for now. Maybe I will come back to this :)

**Comment by cyberb** [comment]
Yeah let's close this for now, there are a lot of interesting and usefull things to do right now and not to worry about what may happen in future, as it may not happen at all :)
