### ISSUE TITLE
[diaspora] user managment

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#457]
I've seen that diaspora people don't want to implement LDAP in near future. It would be nice to have script which creates at least an admin user (same as Syncloud admin) by installation and set this user as diaspora admin like [here](https://wiki.diasporafoundation.org/FAQ_for_pod_maintainers#What_are_roles_and_how_do_I_use_them.3F_.2F_Make_yourself_an_admin_or_assign_moderators) described so that an admin panel appears. It would be nice to deactivate user registration by [default ](https://docs.bitnami.com/oci/apps/diaspora/configuration/disable-registrations/) as everybody can register. Not sure if users can be created by admin panel.

**Comment by cyberb** [comment]
I would concentrate on adding Mastadon instead for now: https://github.com/syncloud/platform/issues/292

**Comment by cyberb** [comment]
Mastodon took over I think for now.
