### ISSUE TITLE
[Shop] selling raspberry pi sd card storage

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#459]
Just, another idea. Sorry, if I'm confusing. You could offer option to select more storage on micro SD card for the Syncloud R (and C) as main storage (128,256,512) as they are getting cheaper...

**Comment by cyberb** [comment]
I do not think we should grow RPi options as it is coming very close to Syncloud H(Odroid HC1) price where you can have much better SSD disk with space options as you mentioned.
