### ISSUE TITLE
Custom domain name zone amangement

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#461]
We should be able to offer users to manage custom DNS zones (example.com) the same way we manage [user].syncloud.it
So device can update all needed records like:
1. A for IPv4 address changes
2. AAAA for IPv6 even if it is changing.
3. SPF/DKIM for mail support
4. Wildcard support
5. DNS based certificate issue to remove the need for port 80.

**Comment by chegeiser** [comment]
Is there a timeline for wildcard support?

**Comment by cyberb** [comment]
No, but this is top priority at the moment.

**Comment by cyberb** [comment]
DNS based certificate validation is tracked under a separate issue: https://github.com/syncloud/platform/issues/601
The rest is done and is part of the premium plan (DNS management is not free for us)

**Comment by cyberb** [comment]
To see new premium plan update your system from Settings - Updates then reactivate your device from Settings - Activation.
No change to existing activation options, free and custom are still there.
