### ISSUE TITLE
translate github wiki

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#463]
would nice to have a translation for github wiki. I don't know what would be the best way. To setup indepentend docs website and to integrate content automatically for english in that? Or is there github plugin/language interface? You could maintain russian and I the german part...

**Comment by klmhsb42** [comment]
or you create new repo on github an make it as html or office file or whatever is the best or both so that people can open links directly in those files

**Comment by klmhsb42** [comment]
what do you think about this? https://github.com/klmhsb42/wiki-translate

you can keep the original wiki (en) and just other languages are there

**Comment by cyberb** [comment]
I guess we could migrate wiki to a separate repo, but the problem with that is how to actually view/navigate. I think wiki viewer is much better than code viewer on github (no sidebar, link navigation). The only good thing is PR feature wich is missing on wiki (by the way wiki has its own repo for pushing and pulling just no PRs).

So while I think regular code repo for docs is a must for PRs but then you have to setup some CI (travis/gh actions) to actually compile the docs into some nice looking doc framework.

Rocket.Chat does this (https://github.com/RocketChat/docs -> https://docs.rocket.chat ) but they do not have any translation. So this last bit got me thinking if they do not have do we need as docs are more for developers who usually can understand tech english. It is like creating bug request in different languages, no one does this.

**Comment by klmhsb42** [comment]
Sounds interesting and good to know. But I actually didn't want to make it to complicated/putting to much work into it. I would keep the original English wiki and link at the bottom (as a footer) all languages for respective page (in the translation repo). A navigation can be set in index.md and each should have a home/nav button. Sorry if I missed that...

**Comment by klmhsb42** [comment]
I could create all page templates for all languages in my repo (except English). And later you can add links in the original wiki. Translations can be added successive. Would be nice if you fork it first so I can set the actual URLs which would be a lot. I will maybe write a small script to generate templates...

**Comment by cyberb** [comment]
You want me to fork klmhsb42/wiki-translate to syncloud/docs?

**Comment by klmhsb42** [comment]
yes, but I want you to fork it to a repo to which I can make pull requests. 

If syncloud/docs doesn't has this option then syncloud/wiki-translate or you can download and reupload if you don't like the wording, I don't mind...

**Comment by cyberb** [comment]
made you an admin on https://github.com/syncloud/docs

**Comment by klmhsb42** [comment]
Thanks. Just added files for a first start. I will probably add german translation. If everything is done, you can use [footers](https://github.com/syncloud/docs/blob/master/templates/footer.md) in future to reference in the english wiki (https://github.com/syncloud/platform/wiki).
