### ISSUE TITLE
Nextcloud upgrade failing.

### ISSUE THREAD

**Issue by Rohukas** [syncloud/platform#467]
Hello,
I'm having a issue similar to #448 

My device: odroid-xu3and4 wi th 120gb ssd

When upgrading nextcloud from 19111297 to 200109121 it just fails after a while and stays at 19111297.

I then ran the commands suggested in #448 
`
wget apps.syncloud.org/apps/nextcloud_19102646_$(dpkg --print-architecture).snap

snap install nextcloud_19102646_$(dpkg --print-architecture).snap --devmode

wget apps.syncloud.org/apps/nextcloud_19111297_$(dpkg --print-architecture).snap

snap install nextcloud_19111297_$(dpkg --print-architecture).snap --devmode

snap refresh nextcloud --amend
`
After running the last command to update to 200109121 I am getting the following errors:
`
root@odroid-xu3and4:~# snap install nextcloud_19111297_$(dpkg --print-architectu                                                                                                                            re).snap --devmode
nextcloud 19111297 installed
Snap nextcloud is no longer tracking stable.
root@odroid-xu3and4:~# snap refresh nextcloud --amend
Copy snap "nextcloud" data                                                     .                                                                                                                            Copy snap "nextcloud" data                                                     O                                                                                                                            Run configure hook of "nextcloud" snap if present                              o                                                                                                                            error: cannot perform the following tasks:
- Run configure hook of "nextcloud" snap if present (run hook "configure":
-----
2020-02-02 13:00:53,192 - nextcloud_config - INFO - setting value: datadirectory                                                                                                                             = /opt/disk/external/nextcloud
2020-02-02 13:00:54,741 - nextcloud_config - INFO - setting datadirectory = /opt                                                                                                                            /disk/external/nextcloud
2020-02-02 13:00:56,157 - nextcloud_occ - INFO - Nextcloud or one of the apps re                                                                                                                            quire upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
  - installed: true
  - version: 17.0.2.1
  - versionstring: 17.0.2
  - edition:
2020-02-02 13:01:02,456 - nextcloud_occ - INFO - Nextcloud or one of the apps re                                                                                                                            quire upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode enabled
 Starting ...
    0/0 [>---------------------------]   0%2020-02-02 13:05:03,703 - nextcloud_o                                                                                                                            cc - INFO - Nextcloud or one of the apps require upgrade - only a limited number                                                                                                                             of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Disabled incompatible app: audioplayer
Disabled incompatible app: calendar
Disabled incompatible app: files_mindmap
Disabled incompatible app: files_texteditor
Disabled incompatible app: groupfolders
Disabled incompatible app: keeweb
Disabled incompatible app: notes
Disabled incompatible app: unsplash
Updating <accessibility> ...
Updated <accessibility> to 1.3.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.7.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 1.6.0
Updating <files_rightclick> ...
Updated <files_rightclick> to 0.14.2
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.6.0
Updating <gallery> ...
Updated <gallery> to 18.4.0
Updating <logreader> ...
Updated <logreader> to 2.2.0
Updating <password_policy> ...
Updated <password_policy> to 1.7.0
Updating <privacy> ...
Updated <privacy> to 1.1.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.7.0
Updating <recommendations> ...
Updated <recommendations> to 0.5.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.7.0
Updating <support> ...
Updated <support> to 1.0.1
Updating <survey_client> ...
Updated <survey_client> to 1.5.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.6.0
Updating <viewer> ...
Updated <viewer> to 1.2.0
Updating <federation> ...
Updated <federation> to 1.7.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.5.0
Updating <oauth2> ...
Updated <oauth2> to 1.5.0
Updating <user_ldap> ...
Updated <user_ldap> to 1.7.0
Updating <files> ...
Updated <files> to 1.12.0
Updating <activity> ...
Updated <activity> to 2.10.1
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.0.0
Updating <dav> ...
Fix broken values of calendar objects

Updated <dav> to 1.13.0
Updating <files_sharing> ...
Updated <files_sharing> to 1.9.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.7.0
Updating <files_versions> ...
Updated <files_versions> to 1.10.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.7.0
Updating <workflowengine> ...
Updated <workflowengine> to 1.7.0
Updating <comments> ...
Updated <comments> to 1.7.0
Updating <firstrunwizard> ...
Updated <firstrunwizard> to 2.6.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.6.0
Updating <notifications> ...
Updated <notifications> to 2.5.0
Updating <systemtags> ...
Updated <systemtags> to 1.7.0
Updating <theming> ...
Updated <theming> to 1.8.0
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore
Checking for update of app files in appstore
Checked for update of app "files" in appstore
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app files_rightclick in appstore
Update app files_rightclick from appstore
Checked for update of app "files_rightclick" in appstore
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore
Checking for update of app gallery in appstore
Checked for update of app "gallery" in appstore
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore
Checking for update of app privacy in appstore
Checked for update of app "privacy" in appstore
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore
Checking for update of app recommendations in appstore
Checked for update of app "recommendations" in appstore
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore
Checking for update of app support in appstore
Checked for update of app "support" in appstore
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in appstore
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore
Checking for update of app user_ldap in appstore
Checked for update of app "user_ldap" in appstore
Checking for update of app viewer in appstore
Checked for update of app "viewer" in appstore
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore
Checking for update of app audioplayer in appstore
Checked for update of app "audioplayer" in appstore

Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore
Checking for update of app files_mindmap in appstore
Checked for update of app "files_mindmap" in appstore
Checking for update of app files_texteditor in appstore
Checked for update of app "files_texteditor" in appstore
Checking for update of app groupfolders in appstore
Checked for update of app "groupfolders" in appstore
Checking for update of app keeweb in appstore
Checked for update of app "keeweb" in appstore
Checking for update of app notes in appstore
Checked for update of app "notes" in appstore
Checking for update of app unsplash in appstore
Checked for update of app "unsplash" in appstore
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level
2020-02-02 13:05:04,800 - nextcloud_occ - INFO - Nextcloud or one of the apps re                                                                                                                            quire upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode disabled
2020-02-02 13:05:07,148 - nextcloud_occ - INFO - Nextcloud or one of the apps re                                                                                                                            quire upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Check indices of the share table.
Check indices of the filecache table.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Done.

  There are no commands defined in the "ldap" namespace.

2020-02-02 13:05:10,626 - nextcloud_occ - ERROR - occ error: Nextcloud or one of                                                                                                                             the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Traceback (most recent call last):
  File "/snap/nextcloud/200109121/meta/hooks/configure", line 7, in <module>
    Installer().configure()
  File "/snap/nextcloud/200109121/hooks/installer.py", line 112, in configure
    self.occ.run('ldap:set-config s01 ldapEmailAttribute mail')
  File "/snap/nextcloud/200109121/hooks/octools.py", line 19, in run
    raise e
subprocess.CalledProcessError: Command '/snap/nextcloud/current/bin/occ-runner l                                                                                                                            dap:set-config s01 ldapEmailAttribute mail' returned non-zero exit status 1
-----)

`

Another thing to mention is how my current version of nextcloud has pretty much just broken down.
The page has no styling being loaded and the icon has just dissapeared from the apps menu.
![nostyle](https://user-images.githubusercontent.com/32801664/73608933-7bb94c00-45c0-11ea-9b96-a30569012e07.png)
![noimageaswell](https://user-images.githubusercontent.com/32801664/73608941-97bced80-45c0-11ea-8af8-ec4e255b35b8.png)

**Comment by Rohukas** [comment]
Update:
Removed the previous nextcloud installation by pressing the remove button.
Pressed install again.
All working now.

**Comment by cyberb** [comment]
Remove always work but not always convenient as you lose settings.
The usual reasons are:
1. You missed two major app updates (Nextcloud only). Solution is to check for updates and apply them.
2. SD card is broken none of the apps can be updated. Solution is to not use SD card on production devices.
