### ISSUE TITLE
Internal mode for device

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#47]
Exposing device on Internet should be optional. Small server at home with zero-scripting for setup is good enough to be offered as a product. It also will help users with crappy routers.

**Comment by vsapronov** [comment]
Have we discussed the following? Internal mode might be the only one during activation. Then the "Make available from Internet" checkbox will be somewhere in admin web. At that point we can do really full router check by trying end-to-end connection between device and syncloud.it server.

I see following benefits:
As already discussed user can use device even if router is a crap.
Activation experience will be 99% success. It will require only working multicast on router for bonjour.
Router check will be 100% real and no need to implement it for each native platform.
We can provide better error reporting for UPnP, public IP, etc issues from syncloud device.

**Comment by cyberb** [comment]
Really like it. Should we remove redirect login from the app as well?
It will be part of web DNS admin and we will not pass it to activation.

Interesting thing, what is activation then?
No insider.
No internal ssh as we will use rest or even web.
Just saving device master login password to be used by platform and all apps :)

**Comment by cyberb** [comment]
I bet I can guarantee saving login/password to a file even with 100% success rate :)

**Comment by vsapronov** [comment]
I think domain selection is also part of activation. Even if device is
visible only in wi-fi it is still cool to type boris.syncloud.it and get to
your device. Much better then 192.168....

**Comment by cyberb** [comment]
Right I am mixing two things:
1. DNS needs public address from ISP for the router
2. Device web needs UPnP on the router.

I think it makes no sense to use public ip without UPnP.

So you are saying in case we have no UPnP we still can make DNS resolve to local IP?

I think we can do it, if redirect can detect that.

**Comment by vsapronov** [comment]
Yes. One boolean field in /domain/update request. Depends on this flag we
either map to public or to internal address in DNS.

**Comment by vsapronov** [comment]
Redirect is ready for this now. There's map_local_address boolean flag in /domain/update request. If the flag is true then DNS will map domain to local_ip, otherwise (as before) to ip. The flag is not required to make latest redirect backward compatible.
