### ISSUE TITLE
mount syncloud root directory

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#470]
I would like to mount the Syncloud root directory on file manager nautlius under debian. Should that already work? I don't get an error message (nothings happens).

sftp://root@example.syncloud.it

**Comment by cyberb** [comment]
Yes it is possible.
You are probably going theought the router and it blocks port 22 (SSH).
Can you SSH to your device using the same domain name?

**Comment by klmhsb42** [comment]
ssh works

**Comment by klmhsb42** [comment]
I will test it with open port 22

**Comment by klmhsb42** [comment]
It was not the port. I got it working with:
terminal:
`sshfs root@example.syncloud.it: /any/directory/on/client -o allow_other`
to unmount:
`umount /any/directory/on/client`

**Comment by klmhsb42** [comment]
Then open `/any/directory/on/client` in file explorer

**Comment by klmhsb42** [comment]
Do you want to add this to "SSH" wiki entry and close it?

**Comment by klmhsb42** [comment]
new problem: folders inside snap folder are empty. there is only .rnd file

**Comment by klmhsb42** [comment]
same with ssh

how can I see files like in https://files.example.syncloud.it/

**Comment by klmhsb42** [comment]
ok, with ssh `cd ..`

how can I mount this?

**Comment by klmhsb42** [comment]
ok it's:

`sshfs root@example.syncloud.it:'/' /any/directory/on/client -o allow_other`

**Comment by klmhsb42** [comment]
You can add to wiki under "SSH":

To mount Syncloud root folder on linux client via sshfs:
Create folder on your client:
`mkdir /any/directory/on/client`
Mount ./root/ folder with:
`sshfs root@example.syncloud.it: /any/directory/on/client -o allow_other`
Mount Syncloud root with:
`sshfs root@example.syncloud.it:'/' /any/directory/on/client -o allow_other`
Unmount with:
`umount /any/directory/on/client`

**Comment by cyberb** [comment]
I did not know this myself :)
I usually use GUI tool like krusader (two panel file manager) and type on one side something like sftp://user@device.syncloud.it and copy files.
I think your approach is very low level for a regular Syncloud user and they do not even know what mount is (at least I hope so)

**Comment by klmhsb42** [comment]
Or to https://github.com/syncloud/platform/wiki/Remote-file-access

**Comment by cyberb** [comment]
Done: https://github.com/syncloud/platform/wiki/Remote-file-access#mount-a-dir-on-linux
