### ISSUE TITLE
Odriod H1 NextCloud not working with expanded SSD drive

### ISSUE THREAD

**Issue by caroyston** [syncloud/platform#471]
Hi Guys

I have built using a new Odriod H1.
I used the 2 images Boris recently uploaded and flashed the MicroSD and SSD respectively.
Did the Activation and ran expand and SynCloud storage shows 120gig :-D
Next I installed Nextcloud from the apps, logged in and Everything looks great.
Then I checked System in Nextcloud, the Disk. I only show 2.72gig on sda2.
![Capture](https://user-images.githubusercontent.com/47074485/74078896-f0d3b980-49e4-11ea-9934-029eaa9e9da9.JPG)
btw this is the second clean install I have done with the same results.

Here is some drive info from my SSH session.

root@syncloud:~# lsblk -f

NAME        FSTYPE   LABEL UUID  MOUNTPOINT
loop1       squashfs       /snap/nextcloud/
mmcblk1
|-mmcblk1p1 vfat     boot  52AA-6867
`-mmcblk1p2 ext4
loop0       squashfs       /snap/platform/2
sda
|-sda2      ext4  e139ce78-9841-40fe-8823-96a304a09859 /
`-sda1      vfat     boot  52AA-6867
###################################################################

(parted) print all

Model: JMicron Generic (scsi)
Disk /dev/sda: 128GB
Sector size (logical/physical): 512B/4096B
Partition Table: msdos
Disk Flags:

Number  Start   End    Size   Type     File system  Flags
 1      1049kB  135MB  134MB  primary  fat16        lba
 2      135MB   128GB  128GB  primary  ext4

Model: SD SD16G (sd/mmc)
Disk /dev/mmcblk1: 15.5GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags:

Number  Start   End     Size    Type     File system  Flags
 1      1049kB  135MB   134MB   primary  fat16        lba
 2      135MB   3356MB  3221MB  primary  ext4
####################################################################

Tail of fdisk -l
 
 Device         Boot  Start     End Sectors  Size Id Type
/dev/mmcblk1p1        2048  264191  262144  128M  c W95 FAT32 (LBA)
/dev/mmcblk1p2      264193 6555647 6291455    3G 83 Linux

Disk /dev/sda: 119.2 GiB, 128035676160 bytes, 250069680 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 33553920 bytes
Disklabel type: dos
Disk identifier: 0x3cedfd53

Device     Boot  Start       End   Sectors   Size Id Type
/dev/sda1         2048    264191    262144   128M  c W95 FAT32 (LBA)
/dev/sda2       264193 250069679 249805487 119.1G 83 Linux

**Comment by cyberb** [comment]
Nextcloud shows correct disk (sda).
Online resize probably does not refresh size info correctly, not sure where Nextcloud takes it, try running:
````
df -h
````

If it shows correct free space.
Then just reboot it should refresh all the caches.

**Comment by caroyston** [comment]
Thanks for the quick reply Boris,

drive space is 2.9G, no 128G to be seen anywhere.
btw Wordpress also only sees 3G

Syncloud reports 119G
![Capture1](https://user-images.githubusercontent.com/47074485/74092356-6daf7380-4a77-11ea-84c3-b102dbde8017.JPG)

Here is the df -h
root@syncloud:/etc# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            930M     0  930M   0% /dev
tmpfs           200M   22M  179M  11% /run
/dev/sda2       2.9G  1.6G  1.2G  59% /
tmpfs           998M  8.0K  998M   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           998M     0  998M   0% /sys/fs/cgroup
/dev/loop0       56M   56M     0 100% /snap/platform/200130176
/dev/loop1      124M  124M     0 100% /snap/nextcloud/200109121
/dev/loop2       25M   25M     0 100% /snap/files/19120650
/dev/loop3      297M  297M     0 100% /snap/wordpress/190703179
root@syncloud:/etc#

**Comment by cyberb** [comment]
Could you run:
````
parted /dev/sda2 unit % print free --script --machine
````

**Comment by cyberb** [comment]
Extend should have run this command, but something happened like partition was extended but file system was not.
Run dmesg to see if you have any errors on this disk.
You can run manually extend one more time to see what happenes.
````
/snap/platform/current/bin/resize-sd-partition.sh
````

**Comment by caroyston** [comment]
Manually running resize-sd-partition.sh worked.
I now see the whole SSD drive. :-D

Thank you. 

root@syncloud:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            930M     0  930M   0% /dev
tmpfs           200M  5.5M  195M   3% /run
/dev/sda2       118G  1.7G  111G   2% /
tmpfs           998M  8.0K  998M   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           998M     0  998M   0% /sys/fs/cgroup
/dev/loop0       25M   25M     0 100% /snap/files/19120650
/dev/loop1      297M  297M     0 100% /snap/wordpress/190703179
/dev/loop2       56M   56M     0 100% /snap/platform/200130176
/dev/loop3      124M  124M     0 100% /snap/nextcloud/200109121
root@syncloud:~#
