### ISSUE TITLE
[shop] selling WiFi dongle

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#473]
Would be nice to offer WiFi/Bluetooth combo dongle in the shop and in best case one type which works for all offered Syncloud devices.

https://www.raspberrypi.org/forums/viewtopic.php?t=27678

**Comment by klmhsb42** [comment]
#472

**Comment by klmhsb42** [comment]
WiFi might be sufficient, no need for Bluetooth

**Comment by cyberb** [comment]
Sorry no resources at the moment
