### ISSUE TITLE
Nextcloud Hub version 18 upgrade

### ISSUE THREAD

**Issue by aaxios1** [syncloud/platform#476]
Just wondering when Nextcloud 18 will be available on Syncloud.  The document server and additional apps in Nextcloud 18 are of interest.

**Comment by cyberb** [comment]
Updated to 18.0.1 please check.

**Comment by aaxios1** [comment]
Thank You.






Randolph M. Merl

rmerl@aaxios.com<mailto:rmerl@aaxios.com>

215 840-2189 (C)

267 545-7400 (O)

610 726-1464 (F)






The information contained in this electronic mail transmission is intended solely for the addressee(s) named above.  If you are not an addressee, or responsible for delivering this transmission to an addressee, you have received this transmission in error and you are strictly prohibited from reading or disclosing it.  The information contained in this transmission is highly confidential and may be subject to legally enforceable privileges. Unless you are an addressee, or associated with an addressee for delivery purposes, you may violate these privileges and subject yourself to liability if you do anything with this transmission other than immediately contact us by telephone at 267 545-7400 and delete this transmission.  Thank you.


________________________________
