### ISSUE TITLE
Getting Error Trying to update Wordpress from within Wordpress - it shows there is an update.

### ISSUE THREAD

**Issue by aaxios1** [syncloud/platform#477]
Downloading update from https://downloads.wordpress.org/release/wordpress-5.3.2-new-bundled.zip…

The authenticity of wordpress-5.3.2-new-bundled.zip could not be verified as no signature was found.

Unpacking the update…

The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions.: wp-admin/includes/update-core.php

Installation Failed

**Comment by cyberb** [comment]
Update has been released, please update the app.

**Comment by aaxios1** [comment]
Thank you

Randolph M. Merl
rmerl@aaxios.com
215 840-2189 (C)
267 545-7400 (O)
610 726-1464 (F)
The information contained in this electronic mail transmission is intended solely for the addressee(s) named above. If you are not an addressee, or responsible for delivering this transmission to an addressee, you have received this transmission in error and you are strictly prohibited from reading or disclosing it. The information contained in this transmission is highly confidential and may be subject to legally enforceable privileges. Unless you are an addressee, or associated with an addressee for delivery purposes, you may violate these privileges and subject yourself to liability if you do anything with this transmission other than immediately contact us by telephone at 267 545-7400 and delete this transmission. Thank you.
________________________________
