### ISSUE TITLE
 Let's Encrypt certificate authority code 2020.02.29 CAA Rechecking Bug

### ISSUE THREAD

**Issue by GitHub-user121** [syncloud/platform#478]
Could you please help me to renew my certificate, after this bug 
https://community.letsencrypt.org/t/2020-02-29-caa-rechecking-bug/114591
my certificate are not valid.

Thanks

**Comment by sttrebo** [comment]
here's a website that let's you check to see if your certificate is valid.  no idea if it's accurate or not.  just throwing this out there...
https://checkhost.unboundtest.com/

got this reference from https://arstechnica.com/

**Comment by cyberb** [comment]
Run these two commands on the device:
```
cp --remove-destination /var/snap/platform/common/config/tls/default.crt /var/snap/platform/common/syncloud.crt
```
```
cp --remove-destination /var/snap/platform/common/config/tls/default.key /var/snap/platform/common/syncloud.key
```

And wait for 5 mins.

**Comment by cyberb** [comment]
@GitHub-user121 did it help?

**Comment by GitHub-user121** [comment]
Thanks @cyberb , the issue is fixed :)
