### ISSUE TITLE
How can I install ONLYOFFICE for nextcloud?

### ISSUE THREAD

**Issue by RTM80** [syncloud/platform#479]
Hello Snyclouds,
I installed ONLYOFFICE via the "+App"-function in my nextcloud Account. But Office documents are still not opened in the browser.
I'm sorry if I ask this stupid question (I'm still a beginner) - but how do I have to install ONLYOFFICE correctly to use it?
Thank you very much!
Ruben

**Comment by cyberb** [comment]
Not yet implemented, duplicate: https://github.com/syncloud/platform/issues/474

**Comment by klmhsb42** [comment]
This is now offered by nextcloud v23, not onlyoffice directly but their own implementation/system
