### ISSUE TITLE
Router check on web UI

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#48]
We need to move router check from phone to web UI. This will allow us to do real check and will give us this feature for all platforms.

**Comment by cyberb** [comment]
we have external/internal mode button which works ok

**Comment by vsapronov** [comment]
Mode switch is good, but don't we want to check if external mode is working (and if it's not working then check why? UPNP failure,  no public external address or something else). We keep doing it over email almost with every user who has issues.

**Comment by cyberb** [comment]
No we do it on server and we log things, send log should be enough, we will continue to log more every time we ask user or we can even send him new platform version and ask them to try again.

**Comment by vsapronov** [comment]
OK, sounds fair

On Sat, Sep 19, 2015 at 6:13 PM, Boris Rybalkin <notifications@github.com>
wrote:

> No we do it on server and we log things, send log should be enough, we
> will continue to log more every time we ask user or we can even send him
> new platform version and ask them to try again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/48#issuecomment-141710855>.
>



-- 

Vladimir Sapronov
