### ISSUE TITLE
Unable to modify Pi-hole upstream DNS servers

### ISSUE THREAD

**Issue by NoRge308** [syncloud/platform#482]
Hi,

I'm a new user of syncloud.
I've install my nextcloud instance without problem but with pi-hole i'm unable to change upstream DNS servers. When i go to webgui to change paramaters i've got this error :

API Error: Invalid setting value

I'm logged in webgui with admin account.

Thx for help and sorry for me poor english ^^

**Comment by cyberb** [comment]
Right, rust web app we are using is not supported anymore so we will have to upgrade to a c based backend.
Current workaround is to edit this file manually on the box:
```
/var/snap/pihole/common/etc/pihole/setupVars.conf
```
And restart pi-hole:
```
snap restart pihole
```
Then logout and login into the UI to see the change.

**Comment by NoRge308** [comment]
Ok it seems to work, at least in the settings of the webgui the dns that I modified are indicated!

I put in the setupVars.conf file:
9.9.9.9
149.112.112.112
2620:fe::fe
2620:fe::9

But after a few hours of use I see that pihole actually uses the dns that I indicated in the static ip config of my odroid. Namely 1.1.1.1

Why?

**Comment by cyberb** [comment]
Is it pihole or other services on the box like snapd. Or even other apps like Nextcloud.
They would not know about pihole running on the same box, for that you need another box purely for pihole.

**Comment by NoRge308** [comment]
Actually I have NextCloud running on the same odroid but I don't understand ?
Ok for the other instances running on the same box, I understand that they are not protected by pi-hole but for the rest of the network?

**Comment by cyberb** [comment]
The rest of the network should be protected if you set your router primary DNS to point at your pihole IP

**Comment by NoRge308** [comment]
This is what I did, the dns of my router points to the ip of odroid.
I have the impression that all requests from the network are handled by pi-hole now.

But what I still cannot grasp is that pi-hole does not take into account the dns that I indicate in its config but that it takes the dns that I indicated in the ip config of odroid.

**Comment by cyberb** [comment]
Do you need static ip config?

**Comment by NoRge308** [comment]
Yes but I would have preferred to leave it in dynamic to manage everything from the router. Because if I leave the ip dynamic, after 24 hours, when renewing the DHCP lease, the syncloud no longer has internet access. As the router indicates the syncloud ip as in dns the dchp assigns its own IP as DNS :-/

**Comment by cyberb** [comment]
Latest Pi-hole is released with dns fixes and other improvements.
