### ISSUE TITLE
Nextcloud Talk - Camera & Microphone not working

### ISSUE THREAD

**Issue by SebastGG** [syncloud/platform#483]
Hi at all,

i've just installed nextcloud talk. After installation of the app i tried to make some test video calls. Firefox/Edge Broweser recognized that the camera and microphone should used for the call, but the nextcloud app shows an error. So camera and microphone are not available!

Has someone else the same problem?

Cheers Sebastian

![grafik](https://user-images.githubusercontent.com/59542884/77207160-f569b280-6af8-11ea-8faf-ea2244d67c33.png)

**Comment by cyberb** [comment]
Do you have a valid certificate on your domain name?

**Comment by SebastGG** [comment]
yes.
in the meantime i've tried it via the android app. With the app the video call is possible.

**Comment by cyberb** [comment]
Can you test your browsers here for camera/mic issues?
https://test.webrtc.org/

**Comment by cyberb** [comment]
Also this issue mentions Windows 10 camera disabled in settings:
https://help.nextcloud.com/t/talks-problem-camera-and-microphone-not-working/46199

> On Windows 10 you need to enable general app camera and microphone access from settings > privacy as well. Even the browser might not be listed with a dedicated switch/toggle, the general toggle above needs to be enabled for desktop browsers to use them.

**Comment by SebastGG** [comment]
Allright, i've tested it and now it works! Thanks a lot! 
What i still miss is to make video calls with people outside of my local Lan. I read something about turn server, etc. Maybe thats the problem?
What i tried, is to connect my mobile phone via the mobile network over the open vpn app into my local lan. After doing this, the video call is working.

cheers Sebastian

**Comment by cyberb** [comment]
@SebastGG is this still a problem?
You may want to get some help from Nextcloud community and if there is some mis-configuration on Syncloud side we can fix it.

**Comment by SebastGG** [comment]
Hi,
for me its fine now. Using nextcloud talk with some friends, i've used the vpn to give everybody access to my local lan. 

But as far as i can see, when i want nextcloud talk without the vpn, i need to have an installed TURN server. (https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794)

Under preferences Nextcloud talk only the preconfigured STUN server is listed. 
![grafik](https://user-images.githubusercontent.com/59542884/85879491-c2f7e180-b7da-11ea-9562-eef8bd6bf347.png)

Is this right?

**Comment by cyberb** [comment]
We do not have a turn server installed yet, you can try installing one and let us know if that helped.
We can have one on the device, does it require one additional external port open? It is not convenient for people who do not know any IT, probably only mass IPv6 can help here.

**Comment by cyberb** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you have more info.
Thank you!
