### ISSUE TITLE
Asus Tinkerboard sd card image is broken

### ISSUE THREAD

**Issue by jmwilkes76** [syncloud/platform#486]
i tried using syncloud with my asus tinkerboard. i messed with it a few 
times, trying different sd cards, different downloads of the OS, 
different power cord.. different card readers.. nothing. i figured out how to access the 
tinkerboard over ssh and did some poking around and found out that the 
snap package for syncloud is labeled "broken". was wanting to bring this 
to somebody's attention in hopes of it getting i fixed. any help of the 
matter will be greatly appreciated.

**Comment by cyberb** [comment]
Could you run this command:
```
zcat /proc/config.gz | grep SQUASHFS
```

**Comment by jmwilkes76** [comment]
CONFIG_SQUASHFS=y
CONFIG_SQUASHFS_DECOMP_SINGLE=y
# CONFIG_SQUASHFS_DECOMP_MULTI is not set
# CONFIG_SQUASHFS_DECOMP_MULTI_PERCPU is not set
# CONFIG_SQUASHFS_XATTR is not set
CONFIG_SQUASHFS_ZLIB=y
# CONFIG_SQUASHFS_LZ4 is not set
CONFIG_SQUASHFS_LZO=y
# CONFIG_SQUASHFS_XZ is not set
# CONFIG_SQUASHFS_ZSTD is not set
# CONFIG_SQUASHFS_4K_DEVBLK_SIZE is not set
# CONFIG_SQUASHFS_EMBEDDED is not set
CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE=3

**Comment by jmwilkes76** [comment]
CONFIG_SQUASHFS=y
CONFIG_SQUASHFS_DECOMP_SINGLE=y
# CONFIG_SQUASHFS_DECOMP_MULTI is not set
# CONFIG_SQUASHFS_DECOMP_MULTI_PERCPU is not set
# CONFIG_SQUASHFS_XATTR is not set
CONFIG_SQUASHFS_ZLIB=y
# CONFIG_SQUASHFS_LZ4 is not set
CONFIG_SQUASHFS_LZO=y
# CONFIG_SQUASHFS_XZ is not set
# CONFIG_SQUASHFS_ZSTD is not set
# CONFIG_SQUASHFS_4K_DEVBLK_SIZE is not set
# CONFIG_SQUASHFS_EMBEDDED is not set
CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE=3

**Comment by jmwilkes76** [comment]
CONFIG_SQUASHFS=y
CONFIG_SQUASHFS_DECOMP_SINGLE=y
# CONFIG_SQUASHFS_DECOMP_MULTI is not set
# CONFIG_SQUASHFS_DECOMP_MULTI_PERCPU is not set
# CONFIG_SQUASHFS_XATTR is not set
CONFIG_SQUASHFS_ZLIB=y
# CONFIG_SQUASHFS_LZ4 is not set
CONFIG_SQUASHFS_LZO=y
# CONFIG_SQUASHFS_XZ is not set
# CONFIG_SQUASHFS_ZSTD is not set
# CONFIG_SQUASHFS_4K_DEVBLK_SIZE is not set
# CONFIG_SQUASHFS_EMBEDDED is not set
CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE=3

**Comment by cyberb** [comment]
This explains why snap is not working we need these flags enabled in kernel, could you download and run the same command on this latest image from armbian:
https://dl.armbian.com/tinkerboard/archive/Armbian_20.02.7_Tinkerboard_bionic_legacy_4.4.213_desktop.7z

**Comment by jmwilkes76** [comment]
CONFIG_SQUASHFS=y
CONFIG_SQUASHFS_DECOMP_SINGLE=y
# CONFIG_SQUASHFS_DECOMP_MULTI is not set
# CONFIG_SQUASHFS_DECOMP_MULTI_PERCPU is not set
# CONFIG_SQUASHFS_XATTR is not set
CONFIG_SQUASHFS_ZLIB=y
CONFIG_SQUASHFS_LZ4=y
CONFIG_SQUASHFS_LZO=y
CONFIG_SQUASHFS_XZ=y
CONFIG_SQUASHFS_ZSTD=y
# CONFIG_SQUASHFS_4K_DEVBLK_SIZE is not set
# CONFIG_SQUASHFS_EMBEDDED is not set
CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE=3

**Comment by cyberb** [comment]
Here is the new image, could you try:
https://github.com/syncloud/platform/releases/download/untagged-c3b5b8e9ffe50a63b63f/syncloud-tinker-jessie-20.04.img.xz

**Comment by cyberb** [comment]
Sorry here is the proper RC: https://github.com/syncloud/platform/releases/download/20.04-rc1/syncloud-tinker-jessie-20.04.img.xz

**Comment by jmwilkes76** [comment]
i just tried it, and it doesn't work either..

**Comment by cyberb** [comment]
What is the error?

**Comment by cyberb** [comment]
Sorry, used the wrong base image, rebuilt.
Could you download again: https://github.com/syncloud/platform/releases/download/20.04-rc1/syncloud-tinker-jessie-20.04.img.xz

**Comment by jmwilkes76** [comment]
that last image you posted seems to be working properly.. thank you for getting it squared away.

**Comment by jmwilkes76** [comment]
unable to install nextcloud.. no errors it just doesn't install. it acts like it's installing but it never finishes and shows that it's installed.

**Comment by cyberb** [comment]
Could you send logs from support page?

**Comment by jmwilkes76** [comment]
support logs sent..

**Comment by cyberb** [comment]
Just released a fix for Nextcloud for 20.04 images, could you try again?

**Comment by jmwilkes76** [comment]
i sure can. do i need to re-flash my sd card? send me a link or whatever and i'll check it out..

**Comment by jmwilkes76** [comment]
i got it up and running and was able to install nextcloud successfully this time.. so far everything i've fiddled with is working properly.

**Comment by cyberb** [comment]
Should be all working in 20.04.
