### ISSUE TITLE
Linux smartphone Syncloud activation app

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#487]
As there are Linux smartphones like [PINEPHONE](https://store.pine64.org/?product=pinephone-community-edition-ubports-limited-edition-linux-smartphone) and [Librem 5](https://shop.puri.sm/shop/librem-5/) coming up, it might make sense to offer the Syncloud activation app on those devices, too.

**Comment by klmhsb42** [comment]
OpenStore for Ubuntu Touch: https://open-store.io/

**Comment by klmhsb42** [comment]
Probably just a low-priority issue, but just to let you know that I have a pinephone beta device and would be able to test it. I don't have time/knowledge to develop at the moment.

- needs arm build and would be nice to offer this as snap package https://open-store.io/
- and maybe as flatpak https://discover.manjaro.org/ 
- amd64 build would be nice to have to activate the syncloud device from laptop https://snapcraft.io/
- Use GTK or Qt (?). I think there is an issue with GTK4 support on mobian (based on debian bullseye?)
- This could connect Linux smartphone community and syncloud community as they are both freedom enthusiasts (= more syncloud users?)

**Comment by cyberb** [comment]
Mobile app only feature is to find device IP and ooen a browser. for you. So if you have a browser for pinephone then you are fine.
Does pinephone support Android apps?
The bigger problem is actually having all the client apps like Nextcloud, RocketChat ...

**Comment by klmhsb42** [comment]
For myself, I can deal with the workaround. For the browser you need to know the IP first. Android apps can't be run drirectly on the Linux OS but in Anbox. However, it didn't work for me on mobian yet. 

I think Syncloud mobile app is very convenient and maybe there are similar GUI utilities on Linux which could be forked and simplified. Just out of curiosity: How do you detect the IPs of the syncloud devices only and not just of all devices in the network?

Mail, files, contacts, xmpp, matrix clients work so far I guess. Direct apps like nextcloud talk are not there. Telegram works pretty reliably. You can save urls like sub.device.syncloud.it as web app.

**Comment by cyberb** [comment]
> Just out of curiosity: How do you detect the IPs of the syncloud devices only and not just of all devices in the network?

Each Suncloud device runs an avahi daemon which uses mdns (zeroconf, bonjour) to announce itself, so any mdsn client can do it. https://www.avahi.org/

**Comment by klmhsb42** [comment]
I'm using ubuntu touch on a volla phone as my daily driver since months now and I started to port apps using qml (I've a basic understanding). I started to play around to create a frame for a potential syncloud app inspired by your android version. How would it be possible to authenticate against syncloud.it and to get a token? Is there an API? I've seen it would be also possible via the webinterface https://stackoverflow.com/questions/58921220/qt5-qml-automatic-authentication-username-and-password-with-on-a-third-party-de

**Comment by cyberb** [comment]
If you are trying to port Syncloud Android app to Ubuntu Phone you probably just need to do what app does:
https://github.com/syncloud/android/blob/master/syncloud/src/main/java/org/syncloud/android/core/redirect/RedirectService.kt#L22

I would just port as is to whatever UI framework phone uses (qml, java script, snap)

**Comment by klmhsb42** [comment]
> I would just port as is to whatever UI framework phone uses (qml, java script, snap)

looks like you would have to pack a java compiler with it

I have the following thing, but it returns the following after inserting my credentials

_qml: code: 500
qml: {"success":false,"message":"unable to get a user"}_

```
function makeRequest()
    {
    var fetch={};
    fetch["some"]="requestcontent";
    var postData = JSON.stringify(fetch);
    var doc = new XMLHttpRequest();
    doc.onreadystatechange = function() {
        if (doc.readyState == doc.DONE) {

            console.debug("code: " + doc.status);
            var serverResponse = doc.responseText;
            console.log(serverResponse);

            var result = JSON.parse(serverResponse);
            
        }
    }

    var user=username.text
    var pass=password.text


    doc.open("POST", "https://api.syncloud.it/user");
    doc.setRequestHeader('Content-type', 'application/json');
    doc.setRequestHeader( 'Authorization', 'Basic ' + user+':'+pass);
    //doc.setRequestHeader( 'Authorization', 'Basic ' + Qt.btoa( user + ':' + pass ) )

    doc.withCredentials = true;


    doc.send(postData);
    }
```

**Comment by klmhsb42** [comment]
sounds like it can't get the user string from `'Basic ' + user+':'+pass`

**Comment by cyberb** [comment]
> looks like you would have to pack a java compiler with it

No, I mean port the logic as to whatever panguage it is.

>    doc.setRequestHeader( 'Authorization', 'Basic ' + user+':'+pass);

This is wrong because this not what is happening in android, we just post json for this class:

```
class UserCredentials(
    val email: String,
    val password: String
)
```
Which translates to this json:

```
{
    "email": "user@examole.com",
    "password": "secret"
)

**Comment by klmhsb42** [comment]
I can login successfully. I just uploaded my current stuff https://github.com/klmhsb42/syncloud-ub-touch so anybody can follow updates...

**Comment by klmhsb42** [comment]
If this app works, it can also be build for ubuntu desktop in future easily, I guess...

**Comment by cyberb** [comment]
great!
do you have any screenshots (I have no running ubuntu touch at the moment)?
also do you want to add any CI (travis, gh actions ...) so each commit produces a package for testing/publishing?
do you want me to create a repo under syncloud for you like syncloud/ubuntu-touch?

**Comment by cyberb** [comment]
and of cause unit tests? :)

**Comment by klmhsb42** [comment]
> do you have any screenshots

done (see my repo .rmd file)

> I have no running ubuntu touch at the moment

you can also build on desktop, and in a convenient way using qtcreator (see my repo .rmd file)

> do you want to add any CI (travis, gh actions ...)

> and of cause unit tests? :)

never worked with that/heard about it, but sounds interesting ;)

> do you want me to create a repo under syncloud for you like syncloud/ubuntu-touch?

yes, would be nice

**Comment by klmhsb42** [comment]
right now I get the json from server and can read it with the console log. Next step would be to save it and to display the output in the UI and to refresh it. 

> Each Suncloud device runs an avahi daemon which uses mdns (zeroconf, bonjour) to announce itself, so any mdns client can do it. https://www.avahi.org/

If this is implemented, the app can be published I guess

**Comment by cyberb** [comment]
https://github.com/syncloud/ubuntu-touch
You have maintainer permissions, that means you can push directly.

**Comment by cyberb** [comment]
I guess no progress on ununtu touch means we can remove it for now to reduce confusion.
