### ISSUE TITLE
Disable external access of IPv6 connection

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#490]
Just another idea (with lower priority), which would be nice to have: Would be great to be able to disable external access of syncloud device which is connected through IPv6 by a button in the web UI. Do you think there is a way to do that? So, that you can still access it by the domain, but only from private network? I don't know, how it is for IPv4, can you normally access by the domain, when you disable external access?

**Comment by klmhsb42** [comment]
For example, a function could redirect the domain to an empty page, if not in privat network.

**Comment by klmhsb42** [comment]
Or just use privat ipv4 and switch of ipv6? #505 however, public ip is required to access by domain right? Maybe use local hostname, also to access apps?

**Comment by cyberb** [comment]
You can disable IPv6 domain now on access page. It will not disable access by ipv6 address if you know it of cause.
Reopen if you need more
