### ISSUE TITLE
Froxlor app

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#493]
nginx server config web ui

https://github.com/Froxlor/Froxlor
https://froxlor.org/

**Comment by klmhsb42** [comment]
could be useful to config syncloud nginx server

**Comment by cyberb** [comment]
Which nginx server would you want to configure? Every app has its own.

**Comment by klmhsb42** [comment]
I thought of the platform. But, it's probably unnecessary...

**Comment by cyberb** [comment]
Yes, does not make sense, users you cannot really change it without running full set of tests which are part of the build.
