### ISSUE TITLE
Drone CI build server app

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#498]
Would it make sense to have this as an app on device to provide custom developed apps?

**Comment by cyberb** [comment]
Usually you have one build server for a repo and Syncloud already has one.
I think it is a good idea to have a drone server in general for users willing to create build pipelines for their source repositories like Gogs which is already available on Syncloud. In that case if you push Syncloud app code to your repo then of cause you can automate the build using your own Drone CI. If you do not like to run manually drone exec locally.

**Comment by cyberb** [comment]
I think this too early, currently we do not even have a lot of people who are willing to make code changes and thise who are happy to use github PRs.
