### ISSUE TITLE
[docs] App ideas

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#501]
This is an interesting source about possible apps.

https://github.com/awesome-selfhosted/awesome-selfhosted

**Comment by klmhsb42** [comment]
You could add this link to the github wiki...

**Comment by klmhsb42** [comment]
Syncloud is already in that list. 👍

**Comment by klmhsb42** [comment]
Might be interesting, too:
https://github.com/n1trux/awesome-sysadmin
from
https://www.reddit.com/r/selfhosted/wiki/index

**Comment by cyberb** [comment]
I do not think it is an issue "app ideas" and how do we fix it? :)
I would rather create an issue per app and only if you really want it and ready to use. No point to create hundred app requests with no one interested in them and no one to implement.
At this point what I am not looking for just number of apps, what we need is a very useful set of apps for people to choose from.
If you want we can create a wiki page for app ideas.

**Comment by klmhsb42** [comment]
> No point to create hundred app requests with no one interested in them and no one to implement.

Right, so I thought would be nice to have a hint in the wiki that people don't need to summarize via issues...

**Comment by cyberb** [comment]
Move to discussion please
