### ISSUE TITLE
certificate retrieval - refresh button

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#504]
I don't have certificate problem yet, but could you tell, why it's taking hours and isn't there a way to speed it up like sending some request during activation? (just simply asked)

**Comment by klmhsb42** [comment]
Ok, I reactivated and it was directly there. I didn't open ports 80/443 first time. Maybe it's needed, as I activate it with private IPv4?

**Comment by cyberb** [comment]
Let's Encrypt only need port 80 to be open to issue a certificate.
Also we are running certificate job every 5 mins, so up to 5 mins delay.
There is another way to get certificates using DNS (no port 80 needed) which should be simpler for users of syncloud.it (#360)

**Comment by klmhsb42** [comment]
Thanks for the information...

**Comment by klmhsb42** [comment]
> Let's Encrypt only need port 80 to be open to issue a certificate.

Problem of current workflow is, you open port 80 after activation. I have the feeling, if I do it like that, I don't get certificate (even after hours).

If I open ports in the router manually and reactive Syncloud device in Syncloud UI, I get it in a few seconds (to minutes).

**Comment by cyberb** [comment]
Closing this as we are not using http ports for certificate renewal it is dns based now. Device does not even have to be publicly accessible anymore.
