### ISSUE TITLE
Downgrade Installer Version

### ISSUE THREAD

**Issue by shiremail** [syncloud/platform#512]
Hi,

a few days ago the system started to inform me about a new version of the Installer. This seems to be an older version. Is this a bug?

Bye

![Screenshot_20200527-124145_Chrome](https://user-images.githubusercontent.com/57576378/83010753-0a8f2000-a019-11ea-8b0d-6ad8d7e0a53d.png)

**Comment by cyberb** [comment]
This not a bug. Installer was downgraded a day after release when it was found that it cannot install certain apps.
Did you upgrade it few days before?
Do you experience any issues?
You may want to downgrade for now, while we investigate the issue with latest version.
I can keep this issue open to track status of  latest installer issue.

**Comment by shiremail** [comment]
I updated a few days ago. The file browser could not be installed. It works now with the downgraded installer.

**Comment by sttrebo** [comment]
How do i downgrade the installer?

**Comment by cyberb** [comment]
@sttrebo just push upgrade button.
