### ISSUE TITLE
Syncloud OS HDD

### ISSUE THREAD

**Issue by dani-77** [syncloud/platform#514]
Hello Boris,

would you like to incorporate, copy/edit to your wiki this?

https://github.com/dani-77/Syncloud.OS-HDD

Best regards,

**Comment by cyberb** [comment]
Our main image instruction covers info how to write disk image using Etcher to any media. Media can be any hard/ssd disk attached using USB/SATA.
I have added an info page for x64 Syncloud OS image and referenced it from our images wiki: https://github.com/syncloud/platform/wiki/PC.
Let me know if you think it should include more info.

**Comment by dani-77** [comment]
I understand your point of view; keep it simple! It is far more simple attaching a Drive with an USB cable and flash the image directly than the way I described; It works, but it is not that simple nor direct.
The page added to the wiki is enough Boris.

**Comment by cyberb** [comment]
I  really would like to understand what is not simple or direct.
You can use usb/sata connected disk to write an image on one pc using Etcher and then attach this disk directly to SATA on another PC and boot it.
I see you are mentioning dd command which is good but Etcher is simpler and cross platform.
Is this not how you do it?

**Comment by dani-77** [comment]
You missed the point or translation; I admitted that your way is far more simple than mine! dd command is perfect, but it is more complex than using etcher (and it's not cross platform). Keep it simple, the page you added to wiki is perfect.
Regards
