### ISSUE TITLE
device IP address

### ISSUE THREAD

**Issue by sttrebo** [syncloud/platform#526]
seems that whenever I power down and restart my device, a new internal IP address is used.  not a huge inconvenience, but it does make the manual port settings on my router/firewall a bit more of a challenge as they are tied to the IP address for the device.  is there a way to reserve a static internal IP address or some other way to get it to not change the IP address upon power up?

**Comment by cyberb** [comment]
It should be actually static, what image/board are you using?

**Comment by sttrebo** [comment]
odroid-hc1

    On Friday, July 24, 2020, 1:19:17 AM PDT, Boris Rybalkin <notifications@github.com> wrote:  
 
 


It should be actually static, what image/board are you using?

**Comment by cyberb** [comment]
Can you run this command:
```
ip -br link show eth0

**Comment by cyberb** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you have more info.
Thank you!
