### ISSUE TITLE
Nextcloud update issue

### ISSUE THREAD

**Issue by generein** [syncloud/platform#528]
Hello,

When I try to upgrade the Nextcloud app from 19111297 to 200414143 in the platform interface, it does not appear to work. Going via ssh gives me the following error:

`root@odroid-c2:~# snap refresh nextcloud --channel=master`
`error: cannot perform the following tasks:`
`- Download snap "nextcloud" (200719160) from channel "master/stable" (received an unexpected http response code (404) when trying to download http://apps.syncloud.org/apps/nextcloud_200719160_armhf.snap)`

**Comment by cyberb** [comment]
You need to follow this instruction: https://github.com/syncloud/platform/wiki/Nextcloud#upgrade-to-a-specific-version
In your case you need to do two steps: "Version 17" and "Go back to stable"

**Comment by generein** [comment]
Thank you! Tried that but... The upgrade to a specific version seems to go well, until this ldap related error:
```

nextcloud_occ - ERROR - occ error: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Traceback (most recent call last):
  File "/snap/nextcloud/x1/meta/hooks/configure", line 7, in <module>
    Installer().configure()
  File "/snap/nextcloud/x1/hooks/installer.py", line 112, in configure
    self.occ.run('ldap:set-config s01 ldapEmailAttribute mail')
  File "/snap/nextcloud/x1/hooks/octools.py", line 19, in run
    raise e
subprocess.CalledProcessError: Command '/snap/nextcloud/current/bin/occ-runner ldap:set-config s01 ldapEmailAttribute mail' returned non-zero exit status 1
-----)
```

The command to go back to stable results in:
```Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
(...)
nextcloud_installer - WARNING - unable to upgrade
```

The Syncloud app interface still shows me on 19111297; from the Nextcloud web interface it seems I am now on Nextcloud 16.05 rather than 17.

**Comment by cyberb** [comment]
Do you have any Nextcloud apps which require update?
Could try updating/removing those apps and retry this again:
```
wget apps.syncloud.org/apps/nextcloud_200109121_$(dpkg --print-architecture).snap

snap install nextcloud_200109121_$(dpkg --print-architecture).snap --devmode

**Comment by cyberb** [comment]
Another option is to remove Nexctoud and install again, but you will lose various settings (not files)

**Comment by generein** [comment]
> Do you have any Nextcloud apps which require update?
> Could try updating/removing those apps and retry this again:
Yes, that resolved it, thank you.

'snap run nextcloud.occ app:update --all'
