### ISSUE TITLE
TLS 1.3 Not Working

### ISSUE THREAD

**Issue by DarkCoocky** [syncloud/platform#531]
With the last modifications, I noticed while testing my server with SSL Labs that TLS 1.3 is not working.

I'm thinking about the certificate that, according to Google should be renewed manually to make TLS 1.3 working. But I didn't find the command to force the certificate renewal with certbot.
(source : https://libre-software.net/tls-nginx/#tls)

**Comment by cyberb** [comment]
Have modifications made it worse?
Or it was never working?

**Comment by cyberb** [comment]
I think we need OpenSSL v1.1.1 or greater for that, but we have  1.0.2g
https://github.com/syncloud/3rdparty/blob/master/nginx/build.sh#L17

**Comment by DarkCoocky** [comment]
That never worked.

You sure? When I tried it was the version 1.1.1 d

**Comment by cyberb** [comment]
Just pushed an upgrade to nginx

**Comment by DarkCoocky** [comment]
I'll test your modifications soon.
But as I turned off again my server by mistake it won't be before Friday :)

**Comment by cyberb** [comment]
Fix is released, update system from updates, should be at least 200723422.
Firefox and ssl labs (A+) show TLS 1.3
