### ISSUE TITLE
Wordpress update 5.5

### ISSUE THREAD

**Issue by marxistvegan** [syncloud/platform#537]
Wondering when we might see that update, some plugins I would like to use like Jetpack are not able to be installed at the moment.

**Comment by cyberb** [comment]
Can you test the new version using the following command on the device?
```
snap refresh wordpress --channel=master
```

**Comment by marxistvegan** [comment]
> Can you test the new version using the following command on the device?
> 
> ```
> snap refresh wordpress --channel=master
> ```

Tried it, it ran in terminal without error, but the website does not reflect the update. I also have another issue, that i will create related to logins.

**Comment by cyberb** [comment]
sorry, it is in our rc channel:

```
snap refresh wordpress --channel=rc
```

**Comment by cyberb** [comment]
released
