### ISSUE TITLE
OpenVPN app installation impossible

### ISSUE THREAD

**Issue by DarkCoocky** [syncloud/platform#539]
I tried to install the OpenVPN from apps Store and from CLI. Each time i try the app cannot be installed.
I don't have any error on website interface, on CLI I have 

`error : cannot perform the following tasks :
- Start "openvpn" (200507119) services ([start snap.openvpn.nginx.service snap.openvpn.web.service snap.openvpn.server.service] failed with exit status 1 : Job for snap.openvpn.service.failed because the control process exited with error code.
See "systemctl status snap.openvpn.server.service" and "journalctl -xe" for details`

**Comment by cyberb** [comment]
Can you send us logs?
or send them first to yourself and check shat is the error?
also you can try running `journalctl -xe`

**Comment by DarkCoocky** [comment]
You mean sending logs through Web UI? 
I'm gonna retry the command you wrote and copy paste the output in a file. Just wait until I come home :)

**Comment by cyberb** [comment]
> You mean sending logs through Web UI?
Yes, it collects various logs in one email, you can use it with "support" unchecked to not share it with us.

**Comment by DarkCoocky** [comment]
I sent the logs for you.
I don't know if there are the things we're looking for because it's been almost 2hrs since the last problem with openVPN.

**Comment by DarkCoocky** [comment]
Here's the output of journalctl that i put into a txt.
[journalctl.txt](https://github.com/syncloud/platform/files/5203384/journalctl.txt)

**Comment by cyberb** [comment]
This must be the problem:
```

**Comment by cyberb** [comment]
Are you running on docker?

**Comment by DarkCoocky** [comment]
I think that's the problem too
I'm running syncloud on Raspberry Pi 3 B+

**Comment by cyberb** [comment]
```
iptables --version
```
Are you on latest image?

**Comment by DarkCoocky** [comment]
iptables v.1.8.2

**Comment by cyberb** [comment]
```
cat /etc/os-release
```

**Comment by DarkCoocky** [comment]
PRETTY_NAME="Debian GNU/linux 10 (buster)"
NAME="Debian GNU/linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by cyberb** [comment]
Must be these install commands:
```
    if ! iptables -t nat -C POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; then
        iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
    fi
```

**Comment by cyberb** [comment]
could you try running each?

**Comment by DarkCoocky** [comment]
> 
> 
> Must be these install commands:
> 
> ```
>     if ! iptables -t nat -C POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; then
>         iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
>     fi
> ```

Are you sure of the syntax ?
Got an error on second line and the first changes the character at beginning of the line from # to >

**Comment by cyberb** [comment]
Yes, try these independently:
```
iptables -t nat -C POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```

**Comment by DarkCoocky** [comment]
The system tells me for each that chain MASQUERADE doesn't exist. (You can see it in the screenshot)
![CommandResult](https://user-images.githubusercontent.com/68286576/92882059-da289180-f40f-11ea-9c21-d909a87b103e.png)

**Comment by cyberb** [comment]
try this:
```
grep MASQ /boot/config-*
```
my output:
```
CONFIG_NFT_MASQ=m
CONFIG_NF_NAT_MASQUERADE_IPV4=y
CONFIG_NFT_MASQ_IPV4=m
CONFIG_IP_NF_TARGET_MASQUERADE=m
CONFIG_NFT_MASQ_IPV6=m
CONFIG_NF_NAT_MASQUERADE_IPV6=y
CONFIG_IP6_NF_TARGET_MASQUERADE=m
```

**Comment by DarkCoocky** [comment]
Output :

`grep : /boot/config-*: No such file or directory`

**Comment by cyberb** [comment]
try 
```
grep MASQ /proc/config
```
or 
```
zcat /proc/config.gz | grep MASQ 
```
also
```
ls /proc/config*
```

**Comment by DarkCoocky** [comment]
Still nothing no file or directory
![image](https://user-images.githubusercontent.com/68286576/92923224-6306f380-f437-11ea-9a91-5de8bb6870cc.png)

**Comment by cyberb** [comment]
ok, this this
```
modprobe configs
```
and then 
```
zcat /proc/config.gz | grep MASQ 
```

**Comment by DarkCoocky** [comment]
`CONFIG_NF_NAT_MASQUERADE_IPV4=m`
`CONFIG_IP_NF_TARGET_MASQUERADE=m`
`CONFIG_NF_NAT_MASQUERADE_IPV6=m`
`CONFIG_IP6_NF_TARGET_MASQUERADE=m``

**Comment by cyberb** [comment]
@thomasschaeferm you helped us with openvpn in past, did you test on RPi3 B+? did you have to do anything special apart from installing stock Syncloud image, like upgrading kernel of something?

**Comment by cyberb** [comment]
@DarkCoocky can you try PRi 4 image as they should be backward compatible: https://github.com/syncloud/platform/releases/download/20.06/syncloud-raspberrypi4-20.06.img.xz

**Comment by thomasschaeferm** [comment]
I own only a raspberry pi  2 and 4. I never tested with raspberry pi 3. ( I tested also x86_64)

**Comment by cyberb** [comment]
> I own only a raspberry pi 2
Ok, have you tested on RPi 2 with stock image and openvpn works?

**Comment by cyberb** [comment]
Actually I just tested rpi3 on both v3 and v4 images and I can confirm that openvpn does not work on image rpi3 and works on image for rpi4.
I am not sure if we even need to maintain separate image for rpi3, I will remove it.

**Comment by thomasschaeferm** [comment]
I run rpi2 with opensuse and a self compiled open vpn(2.5 beta4) with my own config scripts. Raspberry 4 with 64 bit is just my test device for everything, mostly idle at the moment. 
If you want, that I test some things then I would start from scratch with a different sd-card and the images you provide.

**Comment by DarkCoocky** [comment]
> 
> 
> @DarkCoocky can you try PRi 4 image as they should be backward compatible: https://github.com/syncloud/platform/releases/download/20.06/syncloud-raspberrypi4-20.06.img.xz

I'll try this but, about the migration process, are the users exported ? Because I've got nextcloud running and you don't mention in the wiki if all the information about the users are stored on the external drive.

**Comment by cyberb** [comment]
Files are stored on external disk (if external disk is not activated files will be lost after migration)

For users and other settings uou need to do a backup of nextcloud app before the migration and make sure it is on the latest version.

After migration you need to install Nextcloud and restore the backup.

If user accounts were created in Users app then they will have to be recreated, but Nextcloud backup will still keep all the info about them.

I eill update our wiki.

**Comment by cyberb** [comment]
Updated: https://github.com/syncloud/platform/wiki/Device-migration

**Comment by cyberb** [comment]
reopen if it does not work.

**Comment by DarkCoocky** [comment]
Did the migration, everything works (and that's already great news lol). And OpenVPN is installed successfully.
Thank you for your help :)
