### ISSUE TITLE
Odroid XU4s 

### ISSUE THREAD

**Issue by knappvoraus** [syncloud/platform#540]
didn´t get a connection via SSH to update new nextcloud-release, so I re-installed Nextcloud at the device.
Worked well some weeks, but now:
Odroid XU4S (Syncloud H) just with red and blue light, no hartbeat, no connection, no disc traffic.
µSD seems to be OK.
No idea how to debug it...

**Comment by cyberb** [comment]
No green light on the board?
Are you using external disk?
Can you power off/on?
How did you check SD card?
Try another sd card and write this image to it (this is the same image you have): https://github.com/syncloud/platform/releases/download/20.06/syncloud-odroid-xu3and4-sd-20.06.img.xz

**Comment by knappvoraus** [comment]
new µSD, Image flashed with Balena Etcher: Heartbeat is back! My router identifies device as 10.0.0.9 , but still not reachable, either by old devicve name or as "new" device.
![grafik](https://user-images.githubusercontent.com/71258444/93087026-49b0b200-f698-11ea-8c78-3a2022b9f45e.png)

**Comment by cyberb** [comment]
can you open browser at: http://10.0.0.9

**Comment by knappvoraus** [comment]
unfortunately not 
:-|

**Comment by cyberb** [comment]
can you try to use Putty (SSH) to connect to it?

**Comment by knappvoraus** [comment]
PuTTY´s responsig (Login,...) but I never get a connetion because of invalid passwd/login!?!. because of that I did a re-instllation of nextcloud last time

**Comment by cyberb** [comment]
try "root" as login and your device password you used to activate the device.

**Comment by knappvoraus** [comment]
no luck. is ist posible to reset device to delivers status, e.g. by formatig SSD? Data are safe.

**Comment by cyberb** [comment]
yes, you just need to write this (non-sd) image: https://github.com/syncloud/platform/releases/download/20.06/syncloud-odroid-xu3and4-20.06.img.xz
with usb to sata adapter for example
