### ISSUE TITLE
Wordpress unable to login

### ISSUE THREAD

**Issue by marxistvegan** [syncloud/platform#541]
Hey all,

This has happened a few times and I have not found a successful resolution. Namely after initial install wordpress allows me to login with the same user and password as I have used via LDAP. But now after a day I am unable to successfully login again. Wondering if anyone else has run into this or found a resolution?

**Comment by cyberb** [comment]
What error exacly do you see?
Have you changed any LDAP settings or anything else?
Can you login to any other app with the same user?
What kind of device do you have?
You can send logs from settings to help us investigate the error.

**Comment by marxistvegan** [comment]
> What error exacly do you see?
I receive an "Unknown error"

> Have you changed any LDAP settings or anything else?
I have not changed the LDAP settings at all

> Can you login to any other app with the same user?
I can log into all other apps including nextcloud and the main site, as well as users and pi-hole without error.

> What kind of device do you have?
I repurposed laptop. 

> You can send logs from settings to help us investigate the error. 
Logs are sent now.

**Comment by cyberb** [comment]
> But now after a day I am unable to successfully login again

Does it then allow you to login again or you have to reinstall it?

Can you make few failing attempta and then send logs again?
I cannot really see the login error, it may be a browser issue, can you try to login from different devices?

**Comment by cyberb** [comment]
Also do you have wordpres file manager plugin installed?
In the logs there is an attempt to use it but it ia not found:

```
2020/09/11 14:44:47 [error] 9362#0: *364 FastCGI sent in stderr: "Unable to open primary script: /snap/wordpress/current/wordpress/wp-content/plugins/wp-file-manager/lib/php/connector.minimal.php (No such file or directory)
```

**Comment by marxistvegan** [comment]
Just did a 3 different attempts to log in to the site and then I sent the logs. 

No luck what so ever in logging into wordpress with the same credentials

I do not recall adding that, what I may have added was Jetpack, but I did not use that as my login method.

**Comment by cyberb** [comment]
log says your ldap bind dn is invalid from wordpress:
```
Sep 22 09:21:39 syncloud slapd[27585]: conn=87759 op=0 do_bind: invalid dn (***)
```

While I guess nextcloud is correct:
```
Sep 22 09:20:58 syncloud slapd[27585]: conn=87758 op=0 BIND dn="dc=syncloud,dc=org" method=128
```

Can you reinstall wordpress and login, will it work? If yes can you send logs for sucesfull login?

**Comment by marxistvegan** [comment]
I reinstalled and it seems to be working at the moment, I resent the logs after logging in and out and after adding the jetpack plugin since that was something in the last one.

**Comment by cyberb** [comment]
Reopen if you get this problem again.

**Comment by marxistvegan** [comment]
Ran into this again today, it seems to be after I add Jetpack, this might need to be tested by others to see if they run into the same problem

**Comment by cyberb** [comment]
Make a few login attempts and send logs.

**Comment by marxistvegan** [comment]
Sent new logs today

**Comment by cyberb** [comment]
Did you upgrade system?
If yes, try to do ctrl + f5 and then send logs again and include support.
