### ISSUE TITLE
status of the device after Shutdown

### ISSUE THREAD

**Issue by SebastGG** [syncloud/platform#542]
Hello all,

i have a simple question. What is the status of the device after pressing the Shutdown Button?

After Shutdown of the device, what is the status? Is the device still listening for user actions? Or is the device powered off and can only restarted by plugging the power cabel off and on? 

cheers Sebastian

My device (Odroid HC1)

**Comment by cyberb** [comment]
This should switch your device off similar to taking the power off. Can be started only by taking the power cable off and on.
