### ISSUE TITLE
raspberry Pi 4 : start4.elf not compatible

### ISSUE THREAD

**Issue by pirboazo** [syncloud/platform#545]
Hi 
I download monday 5 10.2020,  the file syncloud-raspberrypi4-20.06.img.xz . 

This morning after resolved severa problems during the last week , start my card  and i receive on screen this message

![IMG_20201012_100242](https://user-images.githubusercontent.com/1702929/95724371-962ae580-0c76-11eb-9b1c-85e1f7156302.jpg)

A diff between my download and a file file download today shown no diff.

Regards.
Pierre

**Comment by cyberb** [comment]
Did you try to flash it again?

>  resolved several problems

What exactly did you do?

**Comment by pirboazo** [comment]
It was not problem with raspiberry , but with my internet connection.
As i want use a custom domain , i need to append a new Fix IP .

This raspi4 is new, so try with an old card...

**Comment by cyberb** [comment]
Is there anything we can help you with?

**Comment by pirboazo** [comment]
Hello , I think your img have a problem with new raspi4.
For me it's good I have active on older card .

And it works fine.

**Comment by cyberb** [comment]
What do you mean by older card?
Are you saying our latest image does not work on Raspberry Pi 4 with 8G of RAM but is working on Raspberry Pi 4 with 4G of RAM?

**Comment by pirboazo** [comment]
Yes, i think that.

**Comment by cyberb** [comment]
Could you try the new image based on latest raspberry pi os image:
https://github.com/syncloud/platform/releases/download/20.10-rc1/syncloud-raspberrypi-20.06.img.xz

**Comment by pirboazo** [comment]
OK i shall test tomorow , i don't have card now.
I give a status tomorow afternoon.
regards

**Comment by pirboazo** [comment]
Hello Boris

this new image work fine.
![pboizot@Pib-Nixos: ~_126](https://user-images.githubusercontent.com/1702929/96017181-f625b580-0e49-11eb-8bef-9d9c1264f2b8.png)

Best regards
Pierre

**Comment by cyberb** [comment]
Updated our download links.
Thanks for letting us know!
