### ISSUE TITLE
Fail2ban for ssh 

### ISSUE THREAD

**Issue by DarkCoocky** [syncloud/platform#548]
I was thinking about the issue for the root user #538 . 
Maybe we could keep this user but instead add a fail2ban to avoid bruteforce through ssh in a first time and then maybe expand it to protect all the apps running on the server  ?

**Comment by cyberb** [comment]
I think this is a good tool to have. Probably as an independent app first.

**Comment by DarkCoocky** [comment]
Sounds great so that people can control what apps are protected with this system.

**Comment by cyberb** [comment]
Interesting variant: https://github.com/crowdsecurity/crowdsec

I do like tools written in go as they give you a single binary with no crazy runtime dependencies (unlike py/js/ru/java/c#...), fast and quick to compile if you want to patch it

**Comment by Frontrider** [comment]
> I do like tools written in go as they give you a single binary with no crazy runtime dependencies (unlike py/js/ru/java/c#...), fast and quick to compile if you want to patch it

Offtopic: Remove java/jvm from that list, as that statement is [not exactly true](https://www.graalvm.org/native-image/). Not trivial, but also not difficult. Unlike c# which is just getting that feature.

Ontopic: I checked crowdsec once, yes that might be a good one.

**Comment by cyberb** [comment]
Well java Native Image sounds good on paper, but I have not seen a single popular service on github (plenty on php :))

**Comment by Frontrider** [comment]
> Well java Native Image sounds good on paper, but I have not seen a single popular service on github (plenty on php :))

Meh. It is quite big in closed source at least.

**Comment by cyberb** [comment]
Crowdsec is ready in the store.
It contains basic level detection configured (nginx, dovecot/postfix, ssh) plus webui to see the alerts/decisions.
No bouncers yet so decisions are not executed yet, we will gather some stats before adding bouncers like firewall rules later.
Feel free to open specific issues on it.
