### ISSUE TITLE
PHP version warning for Nextcloud Password app

### ISSUE THREAD

**Issue by marxistvegan** [syncloud/platform#552]
Hey all,
 Noticed this warning and realize I cannot figure out which version of php is currently running tried
`apt list --installed | grep php`
and came up with nothing.

Here is a screen shot of the warning it get. Just want to know if this is an issue or not

![Screenshot_2020-11-07 Apps - Dialectica cloud](https://user-images.githubusercontent.com/6064303/98445586-668cc300-20e6-11eb-8b2e-816a09b97bd7.png)

**Comment by cyberb** [comment]
Syncloud is using snap packaging and not apt (while it is available). That means all dependencies like php are coming with the app itself for maximum isolation between apps (one app cannot break another app by using the same dependency)
To check Nextcloud PHP you can go to Nextcloud -> Settings -> System
Current PHP version is 7.3.19
Just updated to the latest 7.4.12: https://github.com/syncloud/3rdparty/blob/master/php7/build.sh#L19
Will let you know if it builds ok and publish a new version of Nextcloud with it.

**Comment by cyberb** [comment]
Nextcloud is on PHP 7.4 now, please update
