### ISSUE TITLE
Rocket chat upgrade

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#555]
Rocket Chat uses Mongo which is not supported on ARM 32bit, last version is 3.2 (https://jira.mongodb.org/browse/DOCS-5815)
Last version of Rocket.Chat on arm32 Syncloud devices is 1.1.1 (https://github.com/RocketChat/Rocket.Chat/releases/tag/1.1.0)
Starting with version 3.0.0 RocketChat dropped Mongo 3.2 support (https://github.com/RocketChat/Rocket.Chat/releases/tag/2.4.13)

At the moment we do not separate versions between architectures and have one for both arm32 and amd64.
For now we can upgrade only on amd64.
That requires a change in snaps.

Going forward we should introduce arm64 builds (which is RPi for example) and probably stop arm32.

**Comment by SebastGG** [comment]
Hi,
i have problems with connecting my desktop client with the rocket chat instance at the syncloud. Is this because the current rocket chat server version is too old? Current Version is 1.1.1

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1863

**Comment by cyberb** [comment]
@SebastGG what error do you get in the client log?

**Comment by SebastGG** [comment]
when i set the server url of my rocket chat i get the error "no valid server found at the url"

where are the logs available?

**Comment by cyberb** [comment]
Not sure, I am using mobile app and it is fine.
Can you access url you trying to use?
Does it work in abrowser so you can see a working rocket chat?
Also what server device are you using?

**Comment by SebastGG** [comment]
mobile and web browser works fine, everything works as aspected
I think that the desktop client (windws) in combination with the server version is the problem!?

**Comment by SebastGG** [comment]
Hi Boris,

i have some questions. I'm using odroid HC1 with syncloud. After some 
struggeling at the beginning now everything woks well and stable.
But now i realized, that the odroid hc1 can not use the nextcloud only 
office app and the collabora built in server app as well. For me its 
quite difficult to set up an second server to bring the ability to my 
nextcloud, and as far as i can see i need for that a arm64 or X64 board.

When in buy a new device, for example the shuttle NC10U, then everything 
works out of the box with syncloud. Or do you recommend something else 
less expensive?

thanks in advance, Sebastian


Am 29.11.2020 16:57 schrieb Boris Rybalkin:

**Comment by cyberb** [comment]
> When in buy a new device, for example the shuttle NC10U, then everything
works out of the box with syncloud

Is this a question or a statement?
I have not tried only office myself yet.
Please create a separate issue or use this one for only office questions: https://github.com/syncloud/platform/issues/474

**Comment by SebastGG** [comment]
sorry for this, wrong issue

**Comment by cyberb** [comment]
Rocket Chat is slowly coming to x64 but currently this issue stops us from making a proper package:
https://stackoverflow.com/questions/65256105/dynamic-linker-direct-call-segmentation-fault-when-running-an-app-compiled-whith

**Comment by cyberb** [comment]
64 bit version is out on master channel so if you have Syncloud S or any supported 64 bit device you can give it a try:

```
snap refresh rocketchat --channel=master
```

Next step will be to change snap to support architecture independent versioning.
Also migrate Raspberry Pi to a 64 bit image.

**Comment by cyberb** [comment]
v4.2.2 is in the store with x64 and arm64 support
