### ISSUE TITLE
External Storage / Nextcloud

### ISSUE THREAD

**Issue by shiremail** [syncloud/platform#559]
Hello,

I use a "syncloud H" with an external SSD. After reinstalling the system I noticed that all the syncted nextcloud data is located on the internal SD card and not on the external SSD.

The external SSD is mounted. It shows up under /opt/disk/external. Bt all my data is stored unter /opt/disk/internal/...

How can I solve this?

Bye.

**Comment by cyberb** [comment]
1. Are you saying that you activated an external disk in Settings - Storage and then started to sync the data to Nextcloud but in the end it appeared still under /opt/disk/internal? (should not happen)

2. Or this is more just to ask how to copy files?
You can always `cp -r /opt/disk/internal/* /opt/disk/external/`
Then you need to re-activate external disk in settings so all apps are notified about the disk change.
Also for Nextcloud you need to scan existing files:
https://github.com/syncloud/platform/wiki/Nextcloud#file-scan

**Comment by cyberb** [comment]
reopen if it does not work as expected.
