### ISSUE TITLE
Redirect doesn't return parameters messages from activate

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#56]
Try to activate with domain name that is already taken. Parameters messages should be populated with error about domain field.

**Comment by cyberb** [comment]
just faced that error, a bit annoying :)

**Comment by cyberb** [comment]
Looks like platform server side got the right exception, but android activation form does not show it

**Comment by vsapronov** [comment]
Nope, I debugged it on Android side. JSON returned to Android app doesn't
have parameters_messages.

On Wednesday, September 16, 2015, Boris Rybalkin <notifications@github.com>
wrote:

> Looks like platform server side got the right exception, but android
> activation form does not show it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/56#issuecomment-140925159>.
>


-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
That is what I am saying, platform got the error, but it does not send it to android probably. At least redirect is fine.

 root@cubietruck:~# less /opt/data/platform/log/rest_internal.log

2015-09-16 23:16:41,371 - util - ERROR - {
  "message": "There's a error in parameters", 
  "parameters_messages": [
    {
      "messages": [
        "User domain name is already in use"
      ], 
      "parameter": "user_domain"
    }
  ], 
  "success": false
}
