### ISSUE TITLE
wordpress 5.6 update

### ISSUE THREAD

**Issue by marxistvegan** [syncloud/platform#560]
similar to last time, happy to test too

**Comment by cyberb** [comment]
The best way forward is to create a pull request with new version change: https://github.com/syncloud/wordpress/blob/master/build.sh#L15
Could you do this?

**Comment by marxistvegan** [comment]
I could try, I am a bit rusty on the layout of platform, but are all things under the snap directory or where do I edit this?

**Comment by cyberb** [comment]
All you need to do:
1. Fork https://github.com/syncloud/wordpress
2. Change `WORDPRESS_VERSION` in build.sh 
3. Commit and push the change
4. Create a pull request.

**Comment by marxistvegan** [comment]
commit and push part is where I am not sure in terms of steps in relation to snap, a little help there if possible

**Comment by cyberb** [comment]
Ok, steps I mentioned are about changing the source code. When you change it and publish a pull request (a way of telling "take my changes") our build server (something which converts source code to a snap package)automatically produces a snap package and runs some tests.
If all good I will publish a snap package to a master channel for testing.
If testing is good I promote the package to stable channel for everyone to use.

**Comment by cyberb** [comment]
You can try GitHub Desktop if you are new to git: https://desktop.github.com
I have not tried it myself :)

**Comment by cyberb** [comment]
Also I think you can do all this just uaong github website, they have a fork button, an edit button and a create pull request button :)

**Comment by cyberb** [comment]
released, please update

**Comment by marxistvegan** [comment]
Thanks, sorry I was not able to be more helpful in the testing, i am way too rusty to do pull requests but could test candidates via ssh. The update did work!
However the old issue of not able to log in happened again but that was before the update. I sent a new log just now and will update #541
