### ISSUE TITLE
“The directory is unavailable, please check the logs or contact the administrator”

### ISSUE THREAD

**Issue by ik0api** [syncloud/platform#561]
Hello.
I've just sent a report regarding my Syncloud Nextcloud installation, which works perfectly except for the following message which now appears when I try to access the "deleted" directory:

“The directory is unavailable, please check the logs or contact the administrator”

The behaviour is exactly the same as described here:
https://help.nextcloud.com/t/problem-with-deleted-files/64978

I don't know how to apply the suggested fix, having a limited knowledge of Linux and lot of fear to damage my installation.

Thanks and regards.

**Comment by cyberb** [comment]
Have you tried to cleanup the trash?
https://github.com/syncloud/platform/wiki/Nextcloud#trash-cleanup

Did you have files bigger than 2GB?
Which device are you using?

**Comment by ik0api** [comment]
Answers below

Il giorno dom 3 gen 2021 alle ore 16:58 Boris Rybalkin <
notifications@github.com> ha scritto:

> Have you tried to cleanup the trash?
> https://github.com/syncloud/platform/wiki/Nextcloud#trash-cleanup
>
Did it, now I have no errors but my files are gone (they were in trashbin
before)
No major problem, although I would have preferred to keep them

Did you have files bigger than 2GB?
>
No, but my drive is EXT4 12Tb formatted at 64bit (you might remember my
issue with 2Tb formats)

> Which device are you using?
>
RPI4 4Gb RAM

Thank you for help! I love Syncloud!

Marco

**Comment by cyberb** [comment]
> I would have preferred to keep them

Sorry for that

> files bigger than 2GB? No

Strange, I thought the issue is about having big deleted files (> 2^32 bytes)
Can you delete a small file and check if you can see it?

**Comment by ik0api** [comment]
Yes, "Deleted files" now works properly, I find a
few files deleted on purpose.
Would have been a way to fix the problem without losing the deleted
files?
Thank you for the great work and care.
Marco


At 23:31 03/01/2021, Boris Rybalkin wrote:


I would have preferred to keep them

Sorry for that



files bigger than 2GB? No

Strange, I thought the issue is about having big deleted files (>
2^32 bytes)
Can you delete a small file and check if you can see it?
­
You are receiving this because you authored the thread.
Reply to this email directly,

view it on GitHub, or

unsubscribe.

**Comment by cyberb** [comment]
If the reason was a big file (that is the issue in the link you posted) then the only way to solve this Nextcloud issue is to use a 64 bit device (Syncloud S or any other IntelAMD x64)
I the issue is something else we need logs next time it happens.

Also please try not to reply to the issue by email and comment directly.

**Comment by ik0api** [comment]
OK, I'm totally sure I didn't upload any files >2Tb, so the behaviour remains unexplained to me. I'll monitor and report in case of new issues.
Thank you for the precious and prompt help.

**Comment by cyberb** [comment]
2GB not TB

**Comment by ik0api** [comment]
Sorry, my mistype: I'm totally sure I didn't upload any files >2Gb

**Comment by ik0api** [comment]
Hello Boris.
Sorry to bother you, I don't know if these issues are worth opening a
ticket.

*1* - I keep having the errors regarding the deleted files (see
correspondence below).
I did the trash-cleanout for the 3rd time but I fear to lose something
important in the future... is there a way to solve it forever?

*2* - For the 1st time in 1,5 years I repeatedly get this email message
from Letsencrypt:

From: Let's Encrypt Expiry Bot ***@***.***>
Subject: Let's Encrypt certificate expiration notice for domain "
diaspora.marmon.syncloud.it" (and 14 more)
To: ***@***.***

Hello,

Your certificate (or certificates) for the names listed below will expire
in 10 days (on 24 May 21 14:53 +0000). Please make sure to renew your
certificate before then, or visitors to your web site will encounter errors.

We recommend renewing certificates automatically when they have a third of
their total lifetime left. For Let's Encrypt's current 90-day certificates,
that means renewing 30 days before expiration. See
https://letsencrypt.org/docs/integration-guide/ for details.

diaspora.marmon.syncloud.it

I restarted the system a couple of times but they continue.

*3* - When I go to Settings - Resume (or what it is in English) I get these
errore since upgrade to 21.0 (sorry for Italian but I don't have the
English version):

Sono presenti degli avvisi relativi alla tua configurazione.

   - Nel database mancano alcune chiavi primarie. Poiché l'aggiunta di
   chiavi primarie su tabelle grandi può richiedere del tempo, non sono state
   aggiunte automaticamente. Eseguendo *"occ db:add-missing-primary-keys"*,
   quelle chiavi mancanti possono essere aggiunte manualmente mentre l'istanza
   è in esecuzione.
      - Chiave primaria mancante nella tabella "oc_federated_reshares".
      - Chiave primaria mancante nella tabella
      "oc_systemtag_object_mapping".
      - Chiave primaria mancante nella tabella "oc_comments_read_markers".
      - Chiave primaria mancante nella tabella "oc_collres_resources".
      - Chiave primaria mancante nella tabella "oc_collres_accesscache".
      - Chiave primaria mancante nella tabella "oc_filecache_extended".
   - Alcune colonne del database non sono state convertite in big int.
   Poiché la modifica dei tipi di colonna può richiedere del tempo, non sono
   state modificate automaticamente. Eseguendo "occ
   db:convert-filecache-bigint", le modifiche in corso saranno applicate
   manualmente. L'operazione deve essere eseguita mentre l'istanza non è in
   linea. Per ulteriori dettagli, leggi la relativa pagina di documentazione
   <https://docs.nextcloud.com/server/20/go.php?to=admin-bigint-conversion>.
      - federated_reshares.share_id
      - share_external.id
      - share_external.parent

I entered the system on RPI4 via Putty and tried to execute * "occ
db:add-missing-primary-keys" *but it isn't accepted by RPI4.

What can I do?

II appreciate your continuous support!

Ciao!

Marco




Il giorno dom 3 gen 2021 alle ore 16:58 Boris Rybalkin <
***@***.***> ha scritto:

**Comment by cyberb** [comment]
>  I keep having the errors regarding the deleted files (see
correspondence below).
I did the trash-cleanout for the 3rd time but I fear to lose something
important in the future... is there a way to solve it forever?

We really need to know what files are there causing the issue and a especially what is their size. I think we need to introduce a pure 64 bit RPI image for that. https://github.com/syncloud/platform/issues/587

> For the 1st time in 1,5 years I repeatedly get this email message
from Letsencrypt

This is a known issue, when we add a new app to the store devices get a new certificate as we have to list all domains in it explicitly. https://github.com/syncloud/platform/issues/461

> When I go to Settings - Resume 

Not sure what do mean. Could you pleas ask this question at our forum: https://syncloud.discourse.group I would happy to help.

> I entered the system on RPI4 via Putty and tried to execute * "occ
db:add-missing-primary-keys" *but it isn't accepted by RPI4.

https://github.com/syncloud/platform/wiki/Nextcloud#command-line-tool-occ

Please ask questions first at our forum as a separate topics as it is easier to track and migrate to issues if needed.
