### ISSUE TITLE
Lost access to Standard Notes

### ISSUE THREAD

**Issue by trevorprinn** [syncloud/platform#562]
I've been using Standard Notes on my server for quite a while with no problems until now. This morning I started the Standard Notes desktop app on a Windows 10 machine, and it said there was an upgrade and it wanted to upgrade the encryption (something like that, I didn't make a note of the message), which I let it do. I can't now login on any platform. On ones where I was logged in already it insists I log out, and then the login fails. The message is "Invalid email or password". I'm certain the password wasn't changed by me.

If I try to use strict sign in on the desktop app I get the message
"Strict Sign In has refused the server's sign-in parameters. The latest account version is 004, but the server is reporting a version of 003 for your account. If you'd like to proceed with sign in anyway, please disable Strict Sign In and try again."
Disabling strict sign in goes back to giving the "Invalid email or password" message.

**Comment by cyberb** [comment]
Can you access your notes from a browser or a mobile app?

**Comment by trevorprinn** [comment]
I've tried browsers and the Android app, and they won't let me log in either.

(Incidentally, I have a backup, so I haven't lost my notes).

**Comment by cyberb** [comment]
What error message do you get in the browser?

**Comment by trevorprinn** [comment]
When I use the browser I get "Invalid email or password." regardless of whether I use strict sign in or not.
I'm entering the Sync Server Domain as https://notes.myserver.syncloud.it/api

**Comment by cyberb** [comment]
Sync Server Domain should be just api.

**Comment by trevorprinn** [comment]
Sorry, I should have been clearer. I tried both api and the full address in the browser, and it made no difference. I used the full address in the desktop app.

**Comment by cyberb** [comment]
If just api syill does not work, probably something happened to notes app.
Can you send logs?

**Comment by trevorprinn** [comment]
I think I have. I've gone to the support page, switched on Send a copy to support, and pressed Send Logs.

**Comment by cyberb** [comment]
Log just says authentication is not valid.
Can you register another user and see if that works?

**Comment by trevorprinn** [comment]
I created a new user using the browser, and that seems to work. I can't get it to import my backup, though.

I've tried to open the new account using the desktop app, and that fails to open it. It shows a dialogue headed "Waiting for Key" with the text "This note is awaiting its encryption key to be ready. Please wait for syncing to complete for this note to be decrypted.", and nothing further seems to happen.

**Comment by cyberb** [comment]
what kind of backup do you have, Syncloud backup?
what happens when you try to restore a backup?

**Comment by trevorprinn** [comment]
It's the automatic notes backup.

I'm going nuts trying to work out what's it doing. It's behaving differently (worse) on the machine where I let the Desktop app do the encryption upgrade, and I think that's what's broken it. I can't load any backups on that machine at all. On another machine, I can load a backup when not logged in. (This is all using the browser - the desktop app no longer works anywhere).

On one machine all the backups have an auth_params section, and I can load these in by entering the password, but on the other machine (the one with the later data on, where I allowed the desktop app to update the encryption) they have no auth_params section, and have a '"version": "004"' entry instead.

I can't afford to spend much more time on this. I suspect the problem is that the Standard Notes people have updated the encryption on their servers, and later forced the desktop app to update to that encryption, which has messed up the account on my server, preventing anything from accessing it, and also destroying my backups on the machine where the update was done. I'm just going to have to recover the data from my backups on the machine where I didn't do the encryption update, and use something else (either load it onto the cloud Standard Notes server, or import it into Joplin, or something).

**Comment by cyberb** [comment]
Yes, that is probably what is happening.
Just checked their their updates, did not see any braking change notice, but what we can do is upgrade Syncloud app to the latest version to see it that helps with the new desktop app.
I personally use only Android and web app (daily) and have no issues. Web app is always compatible with the server unless some other client breaks the data itself I guess.

**Comment by cyberb** [comment]
Please migrate to the new `Standard Notes` app from the store. You can have both apps and export/import data from one to another.
Existing `Notes` will be removed soon, but if you have it installed it will stay untill uninstalled.
