### ISSUE TITLE
Support Odroid HC4

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#566]
https://odroid.in/ubuntu_20.04lts/c4-hc4/ubuntu-20.04-4.9-minimal-odroid-c4-hc4-20201212.img.xz

**Comment by cyberb** [comment]
Here is the image for testing: https://github.com/syncloud/platform/releases/download/21.01/syncloud-odroid-hc4-21.01.img.xz
Reopen if does not work.

**Comment by simoneburalli** [comment]
hi team,
just flashed Syncloud into a brand new HC4. The boot is ok. I have found only a problem: shutdown -h now does not carry out any effect. On the Rasp Pi4 the same command triggers a real shutdown with a list of services that stop.
This is crucial because I don't know the effects on Syncloud system after a "hot" shutdown and, first of all, HC4 contains 2 hard drives and I don't think it's a good idea to switch the system off with disk running. Any comments? Thanks a lot for great support

**Comment by cyberb** [comment]
As I understand `shutdown` calls systemd so it does a proper stop of all the services.

> shutdown -h now does not carry out any effect

That is probably because our uwsgi service does not have a proper shutdown event handler so it waits for 30 seconds before the shutdown (times 2 probably), try waiting for a minute or two.

**Comment by simoneburalli** [comment]
YES! You are right: proper shutdown and disks stops. Also with Rasp Pi4 I had to wait for a couple of minutes, the only difference is that with HC4 the console does not give any message, only a blinking cursor while with Rasp the user gets several colorful messages for any message. Anyway, being that I'm gonna perform the shutdown remotely from now on, I'm not interested in what happens console-wise. Thanks a lot.

**Comment by simoneburalli** [comment]
I have followed the guide to use a `mdadm `for RAID1. Everything flowed smoothly except for the last `sudo initramfs-update -u` that gave this output:
`update-initramfs: Generating /boot/initrd.img-4.9.236-63
W: Couldn´t identify type of root file system for fsck hook `

Could it be an issue for the next boot? Thank you very much
p.s.: the RAID 1 is still syncing: about 6 hrs to the end. Is this the reason why I see this?

![image](https://user-images.githubusercontent.com/11993963/105766134-a632b080-5f59-11eb-8929-08758db20228.png)

**Comment by cyberb** [comment]
First of all this is not correct issue for raid problems (this is much better https://github.com/syncloud/platform/issues/570).
Here is the instruction to follow: https://github.com/syncloud/platform/wiki/Multiple-Disks
You should unmount the disk first.
