### ISSUE TITLE
Is it possible to install non syncloud apps to syncloud?

### ISSUE THREAD

**Issue by Drasila** [syncloud/platform#568]
I want to use my syncloud server to leech torrents 24/7. I was thinking of installing a torrent client and controlling it via ssh, is that possible? I'm afraid of trying and then interfering with other apps so I want to be sure I can do this first. If not possible I will get a second arm board for that.

**Comment by cyberb** [comment]
It is possible as all Syncloud apps are isolated in /snap and /var/snap dirs. Generally it is safe to install apt packages, just make sure you do not remove snapd and not use ports 80 and 443.
If you do not know what snap and apt means probably you should not try this on Syncloud device.

**Comment by Drasila** [comment]
Thank you for the clarification.
