### ISSUE TITLE
Syncloud and Bitdefender

### ISSUE THREAD

**Issue by 2boot** [syncloud/platform#569]
Hope this is the correct place to post this issue
Both https://www.syncloud.it/login and https://[username].syncloud.it are prevented to be loaded automatically  in browser. Example jpg 
![2b](https://user-images.githubusercontent.com/42319802/105176089-a9bed580-5b1c-11eb-8a0a-0653734aa1c1.JPG)
added

**Comment by cyberb** [comment]
https://www.syncloud.it this is strange.
it would be great to know what exactly it thinks the issue is.
For the device domain name, one potential issue is that https certificate is not yet retrieved, what other browsers say (Firefox, Chrome)?
Does it have a real certificate?

**Comment by 2boot** [comment]
Sorry it has taken so long to reply, I have wiped and reloaded ubuntu on my laptop partly due to above indication and a (unknown at the time) failing wifi card which I believed were down to a virus. I also wiped the (pi and connected ssd) (pi/ssd), I reset my router and started again recording each and every step. That said when using mobile phone Android logging into (pi/ssd)192.168.1.227/login I have to accept the warning (as per your video) to continue. **Understood!**
On Edge https://192.168.1.227/login I get the above screenshot whilst going via https://www.syncloud.it/login no warning is generated.
On Firefox  https://192.168.1.227/login I get a SIMILAR screenshot whilst going via https://www.syncloud.it/login no warning is generated. These warnings appear more serious than the Android versions.
**So I am thinking it is mostly normal. 

I do not know where to look for a CERTIFICATE.** Please advise

A full day so I will continue with Apps tomorrow.

**RECOMMENDATIONS**
1) Inform persons activating that they MUST wait for a confirmation email and respond to that email BEFORE touching the eg Raspberrypi 192.168.1.217 at the top of the Android screen to further activate.
2) Inform persons that the information they type into DEVICE CREDENTIALS on the Android screen that will be the "password" **that will be used with the user "root".** (As yet I have not found a use for the "name" placed in the box above that "password"). 

Thank you for your time

**Comment by 2boot** [comment]
The certificate which Firefox complains about is advised as follows
![Screenshot from 2021-01-22 07-53-28](https://user-images.githubusercontent.com/42319802/105463578-2f12c900-5c88-11eb-98b0-04e1c3f093c1.png)
The certificate itself can viewed by proceeding to https://chase.syncloud.it
Thanks

**Comment by cyberb** [comment]
This means you do not have a real certificate, it can be automatically obtained if external access is enabled, see more info: https://github.com/syncloud/platform/wiki/Browser-warning-(certificate-problem)

**Comment by 2boot** [comment]
Thanks, I had just got to that point myself by performing external access from settings (as first time I have logged in) I then turned wifi off on Android and using edge browser - no Android complaints. 
As I wiped the laptop yesterday, installed nordvpn on laptop, then using vpn externally to (pi/ssd) by chase.syncloud.it in Firefox - no Firefox complaints.

LOCALLY
Whilst NOT connected to vpn Firefox **no Firefox complaints** with https://chase.syncloud.it/login
Whilst NOT connected to vpn Firefox **COMPLAINS** with https://192.168.1.227

**Comment by 2boot** [comment]
Just to finalise and close this issue. The final certificate is now available on my chase.syncloud.it home server.
In my above post I said that Firefox complains when locally connecting to https://192.168.1.227 (the server address). This becomes obvious when viewing the certificate.
![Screenshot from 2021-01-23 09-02-49](https://user-images.githubusercontent.com/42319802/105574675-f5ac8d00-5d5d-11eb-9696-601f54da4e5d.png)
Many thanks for your assistance.
