### ISSUE TITLE
Support hosts with public IP

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#57]
Amazon EC2 servers for example...
What if syncloud is running on a server with public ip. DDNS doesn't hurt. However local_ip will be external ip in reality, local_port is external too...

**Comment by cyberb** [comment]
So is it not working as is?
Or this is more about "lets make it proper"?

**Comment by vsapronov** [comment]
I'm yet to try, but few things don't make much sense. Device will show that
it's in internal mode, while it's accessible from Internet. There are could
be more issues besides mentioned.

On Wednesday, August 26, 2015, Boris Rybalkin <notifications@github.com>
wrote:

> So is it not working as is?
> Or this is more about "lets make it proper"?
> On Aug 26, 2015 13:59, "Vladimir Sapronov" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Amazon EC2 servers for example...
> > What if syncloud is running on a server with public ip. DDNS doesn't
> hurt.
> > However local_ip will be external ip in reality, local_port is external
> > too...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/syncloud/platform/issues/57>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/57#issuecomment-135023468>.
>


-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
This is possible as we have access page.
1. Disable UPnP.
2. Enter machine IP (or enter 0 for auto detection)
3. Enter port 80/443
4. Enable external access
Save

Device will still be available on both http and https.
