### ISSUE TITLE
Raid1 as storage not possible

### ISSUE THREAD

**Issue by racer2220** [syncloud/platform#570]
Hello together,
I have created a RAID 1 on my RPI2 using MDADM on my two 2TB HDDs (with external power).
Unfortunately I cannot activate the RAID as storage. I see it in the settings and I can activate both HDDs itself, but I can just format the RAID.
Is this a known Issue and are there any workarounds?

Thanks so far!

**Comment by cyberb** [comment]
Could you send logs to support from Settings - Support?
So we can check why raid is not being accepted?

**Comment by racer2220** [comment]
Yes, Done

**Comment by cyberb** [comment]
1. Could you post a screenshot of what you see on the Storage UI?
2. Output of the: `lsblk -Pp -o NAME,SIZE,TYPE,MOUNTPOINT,PARTTYPE,FSTYPE,MODEL`

**Comment by cyberb** [comment]
Here is the current status of raid support: https://github.com/syncloud/platform/wiki/Multiple-Disks

**Comment by cyberb** [comment]
@racer2220 It would be great if you can reply to your support report and tell us that this is the problem, we get many device reports :)
If I found correctly you have your raid mounted which is the problem, please unmount and check the instruction above.

**Comment by simoneburalli** [comment]
Hi Boris,
I can confirm that in case you have configured the RAID correctly according to the [guide ](https://github.com/syncloud/platform/wiki/Multiple-Disks), perform `sudo umount /dev/md0` and then activate the RAID from it Syncloud web interface **worked for me**. Thanks

![image](https://user-images.githubusercontent.com/11993963/105912818-51139f00-602c-11eb-97da-fdae141385d4.png)

p.s. I'm really sorry for having commented on #566

**Comment by cyberb** [comment]
Closing this as RAID support is covered by this issue: https://github.com/syncloud/platform/issues/571
