### ISSUE TITLE
Update failure (Nextcloud Bookmarks)

### ISSUE THREAD

**Issue by sttrebo** [syncloud/platform#572]
got a update notification for nextcloud bookmarks.  went ahead and ran the update but it errored out.  now whenever I try and get into Nextcloud, I get this:
![image](https://user-images.githubusercontent.com/2676482/105911203-ca84a080-5fde-11eb-8560-0f653663bb73.png)

if i run the update again, i get this log:

Update to 20.0.4
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT "b"."id" FROM "oc_bookmarks" "b" LEFT JOIN "oc_bookmarks_tree" "t" ON b.id = t.id AND ? WHERE "t"."id" IS NULL' with params ["bookmark"]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type boolean: "bookmark"

Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: Not a mysql database -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Repair step: Deduplicate shared bookmark folders
Repair info: Removed 0 duplicate shares
Repair step: Remove superfluous shared bookmark folders
Repair info: Removed 0 superfluous shares
Repair step: Remove orphaned bookmark shares
Repair info: Removed 0 orphaned shares
Repair info: Removed 0 orphaned public links
Repair step: Remove orphaned bookmark tree items
Repair info: Removed 0 orphaned bookmarks entries
Repair info: Removed 0 orphaned folders entries
Repair info: Removed 0 orphaned children entries
Repair info: Removed 0 orphaned bookmark folders

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT "b"."id" FROM "oc_bookmarks" "b" LEFT JOIN "oc_bookmarks_tree" "t" ON b.id = t.id AND ? WHERE "t"."id" IS NULL' with params ["bookmark"]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type boolean: "bookmark"

any ideas?

**Comment by cyberb** [comment]
Seems to be a bug in Bookmarks and looks like they released a fix 11 hours ago, try again :(
https://github.com/nextcloud/bookmarks/issues/1388

**Comment by sttrebo** [comment]
still the same problem.  is there a way i can remove the Bookmarks app manually (or a command line update instead of the automated update)so I can at least get my Nextcloud back up and running?

**Comment by cyberb** [comment]
You can try one of these:
```
snap run nextcloud.occ app:update bookmarks
snap run nextcloud.occ app:disable bookmarks
snap run nextcloud.occ app:remove bookmarks
snap run nextcloud.occ app:list
```

**Comment by sttrebo** [comment]
snap run nextcloud.occ app:update bookmarks 
did it.  thanks for the help..
