### ISSUE TITLE
Nextcloud file upload terribly slow over LAN

### ISSUE THREAD

**Issue by simoneburalli** [syncloud/platform#573]
About 6 hrs for 40 GB and about 6000 files (all RAW photos). In my opinion it is too slow, almost unusable. Any idea to start from to understand what's wrong with the system configuration? Nextcloud has a slow responsiveness also in web interface to navigate dashboard, applications, etc. 
Any help will be appreciated a lot.
Thanks in advance

![image](https://user-images.githubusercontent.com/11993963/106055829-36096380-60ee-11eb-8fb4-c679060e3819.png)

**Comment by cyberb** [comment]
What is the device (cpu)?
How much RAM (total/available)?

**Comment by cyberb** [comment]
PHP is not the fastest language on the planet, so you need more resources.
If you have a lot files to transfer, one option is to copy directly to disk (attach) or to use sftp (to /data/nextcloud/[user]/files) and then let Nextcloud know about it: https://github.com/syncloud/platform/wiki/Nextcloud#file-scan

**Comment by simoneburalli** [comment]
> What is the device (cpu)?
> How much RAM (total/available)?

It's an Odtoid HC4 (8GB RAM, if I well remember) with 2 HDD's in RAID1. 
I'll try sftp. Thanks a lot
