### ISSUE TITLE
Snapd is not running

### ISSUE THREAD

**Issue by sttrebo** [syncloud/platform#574]
Been getting this error when I go thru synvloud and check for updates.  Is it me or the site?

Syncloud
Updates
Check for updates
System:
Installer:
×
Error
('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

**Comment by cyberb** [comment]
Does it happen all the time?
Could you send logs if it happenes again?

**Comment by sttrebo** [comment]
![image](https://user-images.githubusercontent.com/2676482/106363092-4468a280-62db-11eb-9569-b460fcb6a2d2.png)
 yes, everytime.  currently using the Brave browser, but it also happens on MS Edge.

just sent the logs.

**Comment by cyberb** [comment]
I think local app store (snapd) is no running (died?), can you reboot and check again?
Also you are running many apps on the device, that is ok, but how much RAM do you have it may be not enough?

**Comment by sttrebo** [comment]
when i select 'restart' or 'shutdown' i get a server error.  is there another safe way to restart the box?  i haven't added any new apps recently but maybe the recent nextcloud update broke something?

**Comment by sttrebo** [comment]
ok, seems even with the server error, the box shutdown anyway.  just restarted it but still the same problem.

**Comment by cyberb** [comment]
You can only uninstall apps with snapd running
```
systemctl start snapd
```
If that does not help try stopping the apps first:
```
systemctl stop snap.nextcloud*
```

**Comment by sttrebo** [comment]
hi-thanks, i ended up re-flashing and starting over from square one with a new sub-domain.  so i'm back up and running.
1 thing i found looking thru the logs, i'm not sure is a problem or not, but my NAS (WDMyCloud) was internally configured to be mapping ports 80 and 443.  i believe that was set a long time ago (several years) when this unit was setup as a WebDAV server.  Since I'm not using it as such I deleted those mappings.  Could that have been a part of my problems in the past?
thankssteve
    On Saturday, February 6, 2021, 01:58:55 AM PST, Boris Rybalkin <notifications@github.com> wrote:  
 
 


You can only uninstall apps with snapd running
systemctl start snapd

If that does not help try stopping the apps first:
systemctl stop snap.nextcloud*

**Comment by cyberb** [comment]
Please consider non-issue related questions at 
https://syncloud.discourse.group
