### ISSUE TITLE
Read external syncloud hard drive with windows laptop

### ISSUE THREAD

**Issue by RTM80** [syncloud/platform#575]
Hello everyone,
I use Nextcloud via an connected external hard drive. Unfortunately, Nextcloud keeps causing problems, so I'm afraid for my data. Is there a way to transfer the data (without Nextcloud) to my Windows laptop? If I connect the hard drive directly to the laptop and it cannot be read. Probably because it has a different file system.
So is there a trick for laymen? 
Thank you!
Josh

**Comment by cyberb** [comment]
Please use our community discussion forum at https://syncloud.discourse.group

There are two options:
1. Install Syncthing app on Syncloud device and on Windows and choose what to sync/copy.
2. Attach disk to Windows and use ext4 filesystem reading apps: https://superuser.com/questions/37512/how-to-read-ext4-partitions-on-windows
