### ISSUE TITLE
Remove services table in redirect

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#58]
We don't need list of services on redirect. Syncloud device web can show them if needed but we don't need them to map domain to address since we are using single port mapping on a router...

**Comment by vsapronov** [comment]
I guess services table is used for new domain-per-service schema. So , let's leave it?

**Comment by cyberb** [comment]
DNS is wildcard, so I think we do not need it.

As I remember we have used services to show app links, but right now redirect serves two purposes:
1. Device DNS: device.syncloud.it and *.device.syncloud.it
2. Link to device web UI (http/https): device.syncloud.it:web_port

Even if we add more non http services like SMTP, we still do not need its port info on redirect.

**Comment by vsapronov** [comment]
I see. Let's start removing services from redirect then. My plan:
1. Introduce web_port column on domain table
2. Start populating this column on domain_update call
3. Move all logic that relies on services table to new web_port column
4. Delete services table
