### ISSUE TITLE
Running non-syncloud applications breaks syncloud?

### ISSUE THREAD

**Issue by Penguinjumper** [syncloud/platform#580]
So I mentioned this is #563 but I think it went unnoticed because the issue had already been closed.

I hope this is the right way of posting/asking this:

Maybe as a temporary workaround for the outdated Pihole in the AppCenter: I tried installing pihole via ssh and "curl -sSL https://install.pi-hole.net | bash"

For pihole, this worked, but it seems this broke something within syncloud, as I couldn't reach it's web ui or my nextcloud anymore.

(Since I'm a rookie with this stuff, I had to 'factory reset' the whole thing, because I really needed my nextcloud up and running.)

Anything I overlooked? Or is it just not possible to install other applications next to the "official" syncloud ones?

**Comment by cyberb** [comment]
It is possible, you just need to know what exactly installer does and eaht ports take.
For example we are running nginx webserver om port 80/443 if pihole starts on the same ports before us then you cannot access any syncloud app web.
The problem if I start investing how to do it it would be easier just to upgrade pi-hole.
Believe me it should be coming soon.
Follow this: https://github.com/syncloud/platform/issues/578

**Comment by Penguinjumper** [comment]
Ok, thanks a lot for your effort.
