### ISSUE TITLE
Elaborate on operation status while showing busy spinner

### ISSUE THREAD

**Issue by mikini** [syncloud/platform#581]
The current busy spinner indication only relays a boolean status (operation ended or not).

On long running operations performed on less capable platforms the missing indication of operation length and estimated end could potentially be perceived by an eager user (see fx. #579) as an indication that the operation is not progressing as intended.

Adding some indication of progress, like a progress bar with a few steps or a simple textual indication of the current state (download, install, setup, cleaup etc.), would give the impression that waiting a bit more is worth it.

# Current busy spinner
![Screenshot from 2021-03-07 11-00-36](https://user-images.githubusercontent.com/1330166/110236630-270ca100-7f37-11eb-82a3-0ea58b8922f5.png)

**Comment by cyberb** [comment]
Yes, that is exactly what I was thinking about, snapd daemon actually provides all the info already, we just need to wire it to the UI.
Too busy with few apps at the moment (pihole upgrade and bitwarden) pull requests are always welcome.

UI: https://github.com/syncloud/platform/blob/master/www/src/views/App.vue#L222
Backend: https://github.com/syncloud/platform/blob/master/src/syncloud_platform/snap/snap.py#L39
While backend has to migrate from python to go.
So anyone who knows javascript/vue.js and python/go should be able to do that.

**Comment by cyberb** [comment]
Now it should be easy to show on app page current device activity like installing this app or doing something else which prevents ypu from installing this app right now and a link to Status page (yet to come)

**Comment by cyberb** [comment]
fixed in the new progress UI changes.
