### ISSUE TITLE
Calibre ebook manager

### ISSUE THREAD

**Issue by raud3rs** [syncloud/platform#585]
Hello, I use calibre for my ebook and comics collection. Caliber has a lot of functions and is also a server which contains a web browser reader and can also be used by other ebook readers. unfortunately i'm not a programmer and i'm not a millionaire depending on your cooperation. 
[CALIBRE](https://calibre-ebook.com/)
Thanks

**Comment by raud3rs** [comment]
all about the server of Calibre App 
https://www.mobileread.com/forums/forumdisplay.php?s=fe212bec8508eda48d0d95a9276250a3&f=277

**Comment by cyberb** [comment]
You would really help us by subscribing for a premium account and you do you do not have to be a millionaire for that :)

**Comment by cyberb** [comment]
https://github.com/janeczku/calibre-web

**Comment by cyberb** [comment]
Ok, this make a perfect next app, unix socket and ldap is there.

**Comment by cyberb** [comment]
Ok, we are almost there, last bit for authentication: https://github.com/janeczku/calibre-web/issues/2795

**Comment by cyberb** [comment]
Calibre web is in the store named Calibre

**Comment by raud3rs** [comment]
![Bildschirmfoto vom 2023-05-31 09-36-51](https://github.com/syncloud/platform/assets/81413554/0325a523-f4f8-46d2-b047-bdeb3e7ff5f9)
