### ISSUE TITLE
HP Microserver G8

### ISSUE THREAD

**Issue by Manoel1023** [syncloud/platform#586]
el servidor no arranca con el USB ni con el HDD

**Comment by cyberb** [comment]
Which image are you using?
Do you have a screen (HDMI) attached?
Could you take a picture of the error on the screen?

**Comment by Manoel1023** [comment]
Hola,  intente con las dos imágenes X64 con un USB  y con 1 HDD y no arranca, el servidor dice que no tiene medios de arranque. La pantalla la tengo por VGA. La foto la subo en cuanto llegue a casa. También tomaré fotos del bios  por si hay alguna configuración mal hecha.

**Comment by cyberb** [comment]
Try writing this image https://github.com/syncloud/platform/releases/download/21.01/syncloud-amd64-uefi-21.01.img.xz to a disk.
Then attach it to SATA and remove all other disks and USB disks.

**Comment by Manoel1023** [comment]
![WhatsApp Image 2021-05-08 at 6 43 01 PM (1)](https://user-images.githubusercontent.com/83729430/117556551-c7626d00-b02f-11eb-9db2-bef7f6e2a819.jpeg)
![WhatsApp Image 2021-05-08 at 6 43 01 PM](https://user-images.githubusercontent.com/83729430/117556552-c7fb0380-b02f-11eb-8b09-935f5863457a.jpeg)
![WhatsApp Image 2021-05-08 at 6 43 02 PM (1)](https://user-images.githubusercontent.com/83729430/117556553-c7fb0380-b02f-11eb-837e-479aaf3071e5.jpeg)
![WhatsApp Image 2021-05-08 at 6 43 02 PM](https://user-images.githubusercontent.com/83729430/117556554-c7fb0380-b02f-11eb-92b0-bdab8c446a1d.jpeg)

Buena noche.

Aún sigo atascado en lo mismo, lo he instalado en un disco SSD  y en HDD paro no arranca. La bios la heconfigurado de los dos modos pero nada.
También lo intente con usb sin obtener resultados.

**Comment by cyberb** [comment]
When Legacy BIOS enabled you need this image https://github.com/syncloud/platform/releases/download/21.01/syncloud-amd64-21.01.img.xz
How did you write image to disk?
Did you use etcher on another PC?
Can you boot any other OS on this PC and disk?

**Comment by Manoel1023** [comment]
Buen día.

ya intenté con la imagen que me pasaste y sigue igual.

El servidor si inicia otros sistemas operativos, le he instalado ububtu server,  Hace poco le instalé Univention Corporate Server core y funcionó bien. le instalado Ubos entre otros. No sé por que no inicia esta imagen

La imagen la pasé con Etcher en otra pc a un Disco Sata de 1tb con un adaptador USB 3.0  a Sata y también lo hice con una memoria USB 3.0 sin obtener resultados positivos.

**Comment by cyberb** [comment]
Do you still have ubuntu disk which worked on this PC?
If yes can tou check which partitions it has?
Trying to understand if it actually supports UEFI.

Also try to enable AHCI support.

**Comment by Manoel1023** [comment]
![image](https://user-images.githubusercontent.com/83729430/117589604-2edff180-b0f0-11eb-87ef-e211a98abd14.png)
Acabo de instalar de Nuevo el ubuntu

**Comment by cyberb** [comment]
Could you run 
```
fdisk -l /dev/sda
```

**Comment by Manoel1023** [comment]
El sistema operativo siempre lo instalo en disco de la bahia 1, para mi siempre ha sido mejor utilizar AHCI no he tenido lios hasta ahora; alguna vez usando legacy no me inició un S.O. y leí que debía pasarlo a AHCI y funcionaría correctamente, Creo fue Proxmox el que molestó un poco, la verdad fue hace tiempo ahora no recuerdo qué S.O.  Esta noche intentaré una vez mas, como  me dices.

**Comment by cyberb** [comment]
Is this still an issue?

**Comment by Manoel1023** [comment]
Hola, 
Mil disculpas, por cuestiones de aislamiento no he podido conectarme constantemente, Finalmente me rendí he instalé debian y docker he podido trabajar así. Lastimosamente no he podido hacer lo que uds tienen el el proyecto con el mismo usuario para todas las aplicaciones.
Realmente solo necesitaba el Nextcloud,pero con docker la imaginación es el límite, Bno yo soy autodidacta en cuestiones de sistemas. Así que tengo muuuuuucho que aprender y leer en las comunidades.

Agradezco mucho el apoyo prestado, más adelante cuando tenga otro equipo intentaré de nuevo, este proyecto me gusta bastante, tuve la oportunidad de probarlo en una máquina virtual.

De nuevo muchas gracias. Pronto regresaré a intentarlo de nuevo

**Comment by cyberb** [comment]
sure, feel free to reopen or create another issue when you are ready.
