### ISSUE TITLE
Plex

### ISSUE THREAD

**Issue by JuanPerezPerez1** [syncloud/platform#588]
Hi. How can i update plex ?. I have tried (snap refresh plex) but it doesn't update to the latest version.

**Comment by cyberb** [comment]
We have not pushed latest version yet, it is building right now. I will let you know when it is available.

**Comment by cyberb** [comment]
version 1.22.3.4523 has been pushed to the store, update from the app page.
reopen if you have any issues

**Comment by JuanPerezPerez1** [comment]
Thank u
