### ISSUE TITLE
RPI 4 --- external storage problem

### ISSUE THREAD

**Issue by Lloir** [syncloud/platform#590]
Unable to enable two external hard drives on RPI 4, both of these are on an externally powered hub. If I enable one the other turns inactive and vice versa....
![Capture](https://user-images.githubusercontent.com/1220697/120926824-549fec80-c6d6-11eb-8553-bd29085d5008.PNG)

**Comment by cyberb** [comment]
Currently multiple disks are not supported on UI, but you can manually create a raid disk: https://github.com/syncloud/platform/wiki/Multiple-Disks#raid

**Comment by cyberb** [comment]
Duplicate of this: https://github.com/syncloud/platform/issues/571
