### ISSUE TITLE
Support for Gnubee PC1 PC2

### ISSUE THREAD

**Issue by salkdmaslkdm** [syncloud/platform#593]
Can you please add support for the GnuBee Nas SingleBoard? Gnubee.org
Should be really the same like the Helios 4 both Open Hardware with nearly the same specs :)

Thanks!

**Comment by cyberb** [comment]
As I understand it is an arm cpu, is there any debian disk image availavlble to download?

**Comment by salkdmaslkdm** [comment]
ja you can download debian on it, on the GitHub page you find it, new kernel in google chat-> links are here gnubee.org

**Comment by cyberb** [comment]
their github repos seems to be dead at https://github.com/gnubee-git
last commit 2019.

**Comment by cyberb** [comment]
For ARM devices we really need a "stock" disk image with one or two partitions which can be written to a disk (or whatever boot storage used in the device) by Etcher or dd.
If stock image does not exist you could create one and publish to your github so we can use it.

**Comment by cyberb** [comment]
as an example for Helios 4 they provide an image here https://www.armbian.com/helios4 so we just take it and convert to Syncloud image.
At the moment we do not have resources to create images from scratch unless you can help us, here is the image creation repo: https://github.com/syncloud/image

**Comment by salkdmaslkdm** [comment]
Of course! on the GitHub page

**Comment by cyberb** [comment]
could you paste OS image url here please? (cannot seem to find it)

**Comment by salkdmaslkdm** [comment]
Here it is:
https://github.com/gnubee-git/gnubee-git.github.io/raw/master/debian/librecmc-ramips-mt7621-gb-pc1-squashfs-sysupgrade_2017-11-28.bin

and the HowTo:
http://gnubee.org/install_debian.html



________________________________
Von: Boris Rybalkin ***@***.***>
Gesendet: Mittwoch, 30. Juni 2021 12:39
An: syncloud/platform ***@***.***>
Cc: salkdmaslkdm ***@***.***>; Author ***@***.***>
Betreff: Re: [syncloud/platform] Support for Gnubee PC1 PC2 (#593)


could you paste OS image url here please? (cannot seem to find it)

**Comment by salkdmaslkdm** [comment]
Here it is:
https://github.com/gnubee-git/gnubee-git.github.io/raw/master/debian/librecmc-ramips-mt7621-gb-pc1-squashfs-sysupgrade_2017-11-28.bin

and the HowTo:
http://gnubee.org/install_debian.html

PS: Sadly no one ever made easy sd card image or images for harddrives to get it to run!

________________________________
Von: KleinStadtKind XVX ***@***.***>
Gesendet: Mittwoch, 30. Juni 2021 12:48
An: syncloud/platform ***@***.***>
Betreff: AW: [syncloud/platform] Support for Gnubee PC1 PC2 (#593)

Here it is:
https://github.com/gnubee-git/gnubee-git.github.io/raw/master/debian/librecmc-ramips-mt7621-gb-pc1-squashfs-sysupgrade_2017-11-28.bin

and the HowTo:
http://gnubee.org/install_debian.html



________________________________
Von: Boris Rybalkin ***@***.***>
Gesendet: Mittwoch, 30. Juni 2021 12:39
An: syncloud/platform ***@***.***>
Cc: salkdmaslkdm ***@***.***>; Author ***@***.***>
Betreff: Re: [syncloud/platform] Support for Gnubee PC1 PC2 (#593)


could you paste OS image url here please? (cannot seem to find it)

**Comment by cyberb** [comment]
> PS: Sadly no one ever made easy sd card image or images for harddrives to get it to run!

Exactly, and we are going to do it either if there is no community support to create an sd card image than board is not popular and we cannot help with that.

Unless you want to do it, closing.

**Comment by cyberb** [comment]
> wait, the problem is that gnubee is using MIPS not ARM? Or is this not so important?
I will find someone who is making iso for you if than syncloud is possible on it!

I do not really know what is it unless I see some disk image with some linux kernel where squash fs support is enabled I cannot really comment.

**Comment by salkdmaslkdm** [comment]
i will do my best to get you an image!!!
