### ISSUE TITLE
Support for the Turris Omnia Router Nas

### ISSUE THREAD

**Issue by salkdmaslkdm** [syncloud/platform#594]
Is it possible to add Support for the Turris Omnia Router?
You can use the Router with OpenWRT also as a Nas Device with drives connected. 
It is possible to use nextcloud with it, but could it be possible to run Syncloud too? add support in dockers or in a box etc?
Would this be possible?

**Comment by cyberb** [comment]
I think this device is not powerful enough to provide a minimum level of user experience for major open source sever apps like Nextcloud or RocketChat not to mention Plex.
For ARM devices currently we have a conversion procedure (https://github.com/syncloud/image) from any "stock" disk image with one or two partitions which can be written to a disk (or whatever boot storage used in the device) by Etcher or dd.
If stock image does not exist you could create one and publish to your github so we can use it.

**Comment by cyberb** [comment]
Reopen if you have a linux image
