### ISSUE TITLE
WebGui error

### ISSUE THREAD

**Issue by sttrebo** [syncloud/platform#596]
getting a webgui error 'connection aborted;'  sent the error logs under personal email.
![Capture](https://user-images.githubusercontent.com/2676482/124806700-d8393d00-df11-11eb-8d36-d1ffaf154212.JPG)

ran this:
journalctl -u snap.platform.backend

got this:
journalctl -u snap.platform.backend
-- Logs begin at Wed 2021-07-07 07:15:04 UTC, end at Wed 2021-07-07 11:54:00 UTC
-- No entries --
lines 1-2/2 (END)

ran this:
systemctl status snap.platform.backend

got this:
systemctl status snap.platform.backend
● snap.platform.backend.service - Service for snap application platform.backend
   Loaded: loaded (/etc/systemd/system/snap.platform.backend.service; enabled; v
   Active: active (running) since Thu 2019-02-14 10:12:03 UTC; 2 years 4 months
 Main PID: 478 (backend)
   Memory: 8.2M
   CGroup: /system.slice/snap.platform.backend.service
           └─478 /snap/platform/210321656/bin/backend /var/snap/platform/common/

Warning: Journal has been rotated since unit was started. Log output is incomple
lines 1-9/9 (END)

**Comment by cyberb** [comment]
can you try:
```
systemctl restart snap.platform.backend
```
And try UI again?

**Comment by sttrebo** [comment]
ran it a couple of times, no response on the putty session to that command and the WebGui still has the same error.

**Comment by cyberb** [comment]
sorry, it was actually snapd from the logs, can you run this:
```
systemctl status snapd
```

**Comment by sttrebo** [comment]
systemctl status snapd
● snapd.service - Snappy daemon
   Loaded: loaded (/lib/systemd/system/snapd.service; enabled; vendor preset: en
   Active: failed (Result: exit-code) since Wed 2021-07-07 01:19:56 UTC; 19h ago
  Process: 1001 ExecStart=/usr/lib/snapd/snapd (code=exited, status=2)
 Main PID: 1001 (code=exited, status=2)

Warning: Journal has been rotated since unit was started. Log output is incomple
lines 1-7/7 (END)

**Comment by cyberb** [comment]
```
systemctl restart snapd
```

**Comment by sttrebo** [comment]
systemctl restart snapd
root@syncloud:~# systemctl status snapd
● snapd.service - Snappy daemon
   Loaded: loaded (/lib/systemd/system/snapd.service; enabled; vendor preset: en
   Active: failed (Result: exit-code) since Thu 2021-07-08 13:24:25 UTC; 1min 24
  Process: 20496 ExecStart=/usr/lib/snapd/snapd (code=exited, status=2)
 Main PID: 20496 (code=exited, status=2)

Jul 08 13:24:25 syncloud systemd[1]: snapd.service: Service RestartSec=100ms exp
Jul 08 13:24:25 syncloud systemd[1]: snapd.service: Scheduled restart job, resta
Jul 08 13:24:25 syncloud systemd[1]: Stopped Snappy daemon.
Jul 08 13:24:25 syncloud systemd[1]: snapd.service: Start request repeated too q
Jul 08 13:24:25 syncloud systemd[1]: snapd.service: Failed with result 'exit-cod
Jul 08 13:24:25 syncloud systemd[1]: Failed to start Snappy daemon.

i'm thinking maybe it's time to reflash/start over and just restore my data.  but since everything else is working fine, might just wait until the Pi4-64 is available then go with that...

**Comment by cyberb** [comment]
```
journalctl -e -u snapd
```

**Comment by sttrebo** [comment]
hi-
thanks, but i ended up starting from scratch to get things cleaned up.  did a fresh install.  when i added in the nextcloud apps that i need (tasks, news, calendar, and several others), nextcloud displayed a banner at the top saying then apps would cause nextcloud to be unstable therefore they could not be installed.  weird, never seen that before.  sorry i didn't capture those messages.  but i think i'll wait for the Pi4-64 version because it sounds like 64bit support is going to become more and more required.  plus it'll give me an easy reason to buy a bigger SSD..

**Comment by cyberb** [comment]
Ok, let's close this then.
