### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by shiremail** [syncloud/platform#604]
Hello,

I get this message in Chrome accessing my syncloud via the internet. I remember that I could skip this message in Chrome. That is no longer possible. Now I only can do it using EGDE.

Any hints?

Bye.

**Comment by cyberb** [comment]
This message means you do not have a valid certificate.
It should not be difficult to have one automatically if you follow this instruction: https://github.com/syncloud/platform/wiki/Browser-warning-(certificate-problem)

**Comment by shiremail** [comment]
That seems to be working. The connection is now encrypted.
