### ISSUE TITLE
Error when trying to load Apps and App Center

### ISSUE THREAD

**Issue by lams007** [syncloud/platform#606]
Hi, I am new to Syncloud I am running it on a raspberry pi 4 with 8Gb of memory I used the image form the web page I think it is the newest the name is syncloud-raspberrypi-21.09.img I have not installed any app I just tried to install the lets encrypt certificated.
Mi main goal is to have a GOGS git server, Nextcloud and wordpress running. 
Earlier today I installed the 3 of them and they were fine but when I tried cloning from my PC the test repository I put on the server the git hub client returned me that I need the certificate. Since I broke the image i think I  made a new install, after many attempts I think I have now the certificate. Since it is a fresh install I was going to install de GOGS git server but when I try to load the app center page on my syncloud i get the error "string indices must be integers"
![image](https://user-images.githubusercontent.com/66234107/137408398-1c4f60ea-c78d-4e05-aa19-2a359767e367.png)

also the same for Apps page
![image](https://user-images.githubusercontent.com/66234107/137408556-e1d4f81b-395d-4880-890d-84108039153c.png)

Settings look to be working fine but inside setting in update I get the exact same error 
![image](https://user-images.githubusercontent.com/66234107/137408614-bcf94409-b573-405d-a7ee-d3e2765344a0.png)

I logged via SSH and made sudo apt update and upgrade so everything should be up to date. After this I restared and I am having the same issue.

Does any one have an idea what could be happening?

**Comment by cyberb** [comment]
Probably you ran out of disk space.
Did you extend the boot disk from Settings - Internal Memory after the install?
Also running apt get is not a good idea as it may break the system and this is not how we bring updates in.

**Comment by cyberb** [comment]
Reopen if not working still.
