### ISSUE TITLE
Redirect does not support http query special simbols in user password

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#607]
Device activation fails when Syncloud Domain Account (not device) user password contains one of query reserved characters (;,/?:@&=+$)

Current workaround until this is fixed is to not use them.

**Comment by AllizomFoxfire** [comment]
Not as far as I can tell. I just downloaded the latest build for Raspberry Pi today, installed it, and get the following:
![Screenshot from 2021-11-01 18-06-45](https://user-images.githubusercontent.com/67071878/139748379-86dd00ac-ed49-40b6-9660-51a1d7bd1e1e.png)

Yes, my password does contain the characters for added complexity.

**Comment by cyberb** [comment]
Images contained incorrect platform version.
This fixed now and images updated.
Could you try downloading a corresponding 21.10 image and test?
