### ISSUE TITLE
Can't upgrade from Version: 210624280 to 211101376

### ISSUE THREAD

**Issue by ik0api** [syncloud/platform#609]
Hello.
I can't upgrade Nextcloud from Version 210624280 to 211101376. Dotted wheel rotates for several minutes, at last the attached UDB disk rattles for a minute and then nothing changes, the upgrade is re-offered like nothing happened.

I've also tried the fix on https://github.com/syncloud/platform/wiki/Nextcloud#upgrade-to-a-specific-version: snap refresh nextcloud --amend

Same results: nothing changes.

![immagine](https://user-images.githubusercontent.com/66923922/141613777-033c3d9a-2e6b-48f6-95d0-adf8433c312c.png)

BTW I have the same problem with email server app, not upgrading from v. 210301142

I have backups of both apps.

I've sent a report from Syncloud.

Question: if I remove the Nextcloud app and reinstall it will I keep files and profiles? I mean, will the users login with old credentials and find their files?

Thank you

Marco

**Comment by cyberb** [comment]
Can you post the output of this command:
```
snap refresh nextcloud
```
If you reinstall nextcloud files should stay as long as you use the same usernames and run file scan after installation: https://github.com/syncloud/platform/wiki/Nextcloud#file-scan
Other settings like calendars/contacts are lost on reinstall.

Mail app, could you create a separate issue and post the output of:
```
snap refresh mail
```

**Comment by ik0api** [comment]
Sure:

root@syncloud:~# snap refresh nextcloud
Mount snap "nextcloud" (211101376)                                                                                                                              Mount snap "nextcloud" (211101376)                                                                                                                              error: cannot perform the following tasks:
- Start snap "nextcloud" (211101376) services ([start snap.nextcloud.php-fpm.service snap.nextcloud.postgresql.service snap.nextcloud.nginx.service] failed with exit status 1: Job for snap.nextcloud.postgresql.service failed. See 'systemctl status snap.nextcloud.postgresql.service' and 'journalctl -xn' for details.
)

**Comment by cyberb** [comment]
Could you send the output of this command right after the upgrade attempt?

    journalctl -n 100 --no-pager

**Comment by ik0api** [comment]
Here is the full sequence::


root@syncloud:~# snap refresh nextcloud
error: cannot perform the following tasks:
- Start snap "nextcloud" (211101376) services ([start snap.nextcloud.postgresql.service snap.nextcloud.nginx.service snap.nextcloud.php-fpm.service] failed with exit status 1: Job for snap.nextcloud.postgresql.service failed. See 'systemctl status snap.nextcloud.postgresql.service' and 'journalctl -xn' for details.
)
root@syncloud:~# journalctl -n 100 --no-pager
-- Logs begin at Thu 1970-01-01 00:00:01 UTC, end at Sun 2021-11-14 20:56:44 UTC. --
Nov 14 20:55:29 syncloud nextcloud.php-fpm[13065]: [NOTICE] [pool www] 'group' directive is ignored when FPM is not running as root
Nov 14 20:55:29 syncloud nextcloud.php-fpm[13169]: [NOTICE] fpm is running, pid 13169
Nov 14 20:55:29 syncloud nextcloud.php-fpm[13169]: [NOTICE] ready to handle connections
Nov 14 20:55:30 syncloud systemd[1]: Started Service for snap application nextcloud.php-fpm.
Nov 14 20:55:30 syncloud systemd[1]: Starting Service for snap application nextcloud.nginx...
Nov 14 20:55:30 syncloud nextcloud.nginx[13188]: waiting for /var/snap/nextcloud/common/web.socket
Nov 14 20:55:31 syncloud nextcloud.nginx[13187]: nginx: [alert] could not open error log file: open() "/snap/nextcloud/211101376/nginx/logs/error.log" failed (30: Read-only file system)
Nov 14 20:55:31 syncloud nextcloud.nginx[13187]: nginx: the configuration file /var/snap/nextcloud/211101376/config/nginx.conf syntax is ok
Nov 14 20:55:31 syncloud nextcloud.nginx[13187]: nginx: configuration file /var/snap/nextcloud/211101376/config/nginx.conf test is successful
Nov 14 20:55:31 syncloud nextcloud.nginx[13187]: nginx: [alert] could not open error log file: open() "/snap/nextcloud/211101376/nginx/logs/error.log" failed (30: Read-only file system)
Nov 14 20:55:31 syncloud systemd[1]: Started Service for snap application nextcloud.nginx.
Nov 14 20:55:31 syncloud systemd[1]: Stopping Service for snap application nextcloud.php-fpm...
Nov 14 20:55:31 syncloud nextcloud.php-fpm[13169]: [NOTICE] Terminating ...
Nov 14 20:55:31 syncloud nextcloud.php-fpm[13169]: [NOTICE] exiting, bye-bye!
Nov 14 20:55:31 syncloud systemd[1]: Stopped Service for snap application nextcloud.php-fpm.
Nov 14 20:55:32 syncloud systemd[1]: Stopping Service for snap application nextcloud.nginx...
Nov 14 20:55:32 syncloud nextcloud.nginx[13224]: nginx: [alert] could not open error log file: open() "/snap/nextcloud/211101376/nginx/logs/error.log" failed (30: Read-only file system)
Nov 14 20:55:32 syncloud nextcloud.nginx[13224]: 2021/11/14 20:55:32 [notice] 13236#0: signal process started
Nov 14 20:55:32 syncloud systemd[1]: Stopped Service for snap application nextcloud.nginx.
Nov 14 20:55:32 syncloud systemd[1]: Stopped Service for snap application nextcloud.postgresql.
Nov 14 20:55:33 syncloud systemd[1]: Reloading.
Nov 14 20:55:34 syncloud systemd[1]: Reloading.
Nov 14 20:55:35 syncloud systemd[1]: Starting Service for snap application nextcloud.php-fpm...
Nov 14 20:55:35 syncloud systemd[1]: Starting Service for snap application nextcloud.postgresql...
Nov 14 20:55:36 syncloud nextcloud.postgres[13312]: [1-1] 2021-11-14 20:55:36.075 GMT [13312] LOG:  listening on Unix socket "/var/snap/nextcloud/current/database/.s.PGSQL.5436"
Nov 14 20:55:36 syncloud nextcloud.postgresql[13295]: 2021-11-14 20:55:36.075 GMT [13312] LOG:  listening on Unix socket "/var/snap/nextcloud/current/database/.s.PGSQL.5436"
Nov 14 20:55:36 syncloud nextcloud.postgres[13312]: [2-1] 2021-11-14 20:55:36.262 GMT [13312] LOG:  ending log output to stderr
Nov 14 20:55:36 syncloud nextcloud.postgres[13312]: [2-2] 2021-11-14 20:55:36.262 GMT [13312] HINT:  Future log output will go to log destination "syslog".
Nov 14 20:55:36 syncloud nextcloud.postgresql[13295]: 2021-11-14 20:55:36.262 GMT [13312] LOG:  ending log output to stderr
Nov 14 20:55:36 syncloud nextcloud.postgresql[13295]: 2021-11-14 20:55:36.262 GMT [13312] HINT:  Future log output will go to log destination "syslog".
Nov 14 20:55:36 syncloud nextcloud.postgres[13313]: [3-1] 2021-11-14 20:55:36.309 GMT [13313] LOG:  database system was shut down at 2021-11-14 20:50:34 GMT
Nov 14 20:55:36 syncloud nextcloud.postgres[13312]: [3-1] 2021-11-14 20:55:36.369 GMT [13312] LOG:  database system is ready to accept connections
Nov 14 20:55:36 syncloud systemd[1]: Started Service for snap application nextcloud.postgresql.
Nov 14 20:55:43 syncloud nextcloud.php-fpm[13320]: [NOTICE] [pool www] 'user' directive is ignored when FPM is not running as root
Nov 14 20:55:43 syncloud nextcloud.php-fpm[13320]: [NOTICE] [pool www] 'group' directive is ignored when FPM is not running as root
Nov 14 20:55:43 syncloud nextcloud.php-fpm[13274]: [NOTICE] [pool www] 'user' directive is ignored when FPM is not running as root
Nov 14 20:55:43 syncloud nextcloud.php-fpm[13274]: [NOTICE] [pool www] 'group' directive is ignored when FPM is not running as root
Nov 14 20:55:43 syncloud nextcloud.php-fpm[13320]: [NOTICE] fpm is running, pid 13320
Nov 14 20:55:43 syncloud nextcloud.php-fpm[13320]: [NOTICE] ready to handle connections
Nov 14 20:55:44 syncloud systemd[1]: Started Service for snap application nextcloud.php-fpm.
Nov 14 20:55:44 syncloud systemd[1]: Starting Service for snap application nextcloud.nginx...
Nov 14 20:55:44 syncloud nextcloud.nginx[13339]: waiting for /var/snap/nextcloud/common/web.socket
Nov 14 20:55:44 syncloud nextcloud.nginx[13338]: nginx: [alert] could not open error log file: open() "/snap/nextcloud/210624280/nginx/logs/error.log" failed (30: Read-only file system)
Nov 14 20:55:45 syncloud nextcloud.nginx[13338]: nginx: the configuration file /var/snap/nextcloud/210624280/config/nginx.conf syntax is ok
Nov 14 20:55:45 syncloud nextcloud.nginx[13338]: nginx: configuration file /var/snap/nextcloud/210624280/config/nginx.conf test is successful
Nov 14 20:55:45 syncloud nextcloud.nginx[13338]: nginx: [alert] could not open error log file: open() "/snap/nextcloud/210624280/nginx/logs/error.log" failed (30: Read-only file system)
Nov 14 20:55:45 syncloud systemd[1]: Started Service for snap application nextcloud.nginx.
Nov 14 20:55:45 syncloud systemd[1]: Unmounted Mount unit for nextcloud.
Nov 14 20:55:46 syncloud systemd[1]: Reloading.
Nov 14 20:55:48 syncloud snapd[461]: 2021/11/14 20:55:48.713892 handlers.go:306: Reported install problem for "nextcloud" as 3d520192-458d-11ec-b95b-fa163e6cac46 OOPSID
Nov 14 20:55:50 syncloud platform.backend[326]: Cron:
Nov 14 20:56:14 syncloud nginx[13371]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:14 +0000] "GET /status.php HTTP/1.1" 200 158 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:14 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:14 +0000] "GET /status.php HTTP/1.1" 200 158 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:17 syncloud nginx[13369]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:17 +0000] "PROPFIND /remote.php/dav/files/Marco/ HTTP/1.1" 207 259 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:17 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:17 +0000] "PROPFIND /remote.php/dav/files/Marco/ HTTP/1.1" 207 259 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:20 syncloud nginx[13369]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:20 +0000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1183 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:20 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:20 +0000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1183 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:20 syncloud nginx[13369]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:20 +0000] "GET /ocs/v2.php/apps/files/api/v1/directEditing?format=json HTTP/1.1" 200 221 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:20 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:20 +0000] "GET /ocs/v2.php/apps/files/api/v1/directEditing?format=json HTTP/1.1" 200 221 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:20 syncloud slapd[792]: conn=1239 fd=10 ACCEPT from IP=127.0.0.1:59556 (IP=127.0.0.1:389)
Nov 14 20:56:20 syncloud slapd[792]: conn=1239 op=0 BIND dn="dc=syncloud,dc=org" method=128
Nov 14 20:56:20 syncloud slapd[792]: conn=1239 op=0 BIND dn="dc=syncloud,dc=org" mech=SIMPLE ssf=0
Nov 14 20:56:20 syncloud slapd[792]: conn=1239 op=0 RESULT tag=97 err=0 text=
Nov 14 20:56:24 syncloud slapd[792]: conn=1239 op=1 SRCH base="cn=syncloud,ou=groups,dc=syncloud,dc=org" scope=0 deref=0 filter="(&(|(objectClass=posixGroup)))"
Nov 14 20:56:24 syncloud slapd[792]: conn=1239 op=1 SRCH attr=1.1
Nov 14 20:56:24 syncloud slapd[792]: conn=1239 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Nov 14 20:56:24 syncloud slapd[792]: conn=1239 op=2 UNBIND
Nov 14 20:56:24 syncloud slapd[792]: conn=1239 fd=10 closed
Nov 14 20:56:24 syncloud nginx[13369]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:24 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 461 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:24 syncloud nginx[697]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:24 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 461 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:25 syncloud nginx[13369]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:25 +0000] "GET /remote.php/dav/avatars/Marco/128.png HTTP/1.1" 200 33021 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:25 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:25 +0000] "GET /remote.php/dav/avatars/Marco/128.png HTTP/1.1" 200 33049 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:25 syncloud nginx[13368]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:25 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:25 syncloud nginx[697]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:25 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:26 syncloud nginx[13369]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:26 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:26 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:26 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:26 syncloud nginx[13368]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:26 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:26 syncloud nginx[697]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:26 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:27 syncloud nginx[13371]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:27 +0000] "PROPFIND /remote.php/dav/files/Marco/Nextcloud%20Progs/ HTTP/1.1" 207 8672 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:27 syncloud nginx[696]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:27 +0000] "PROPFIND /remote.php/dav/files/Marco/Nextcloud%20Progs/ HTTP/1.1" 207 8686 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:31 syncloud nginx[13369]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:31 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=0&limit=50&format=json HTTP/1.1" 200 787 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:31 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:31 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=0&limit=50&format=json HTTP/1.1" 200 787 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:32 syncloud nginx[13370]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:32 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=453095&limit=50&format=json HTTP/1.1" 200 371 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:32 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:32 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=453095&limit=50&format=json HTTP/1.1" 200 371 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:34 syncloud nginx[13371]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:34 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=453045&limit=50&format=json HTTP/1.1" 200 369 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:34 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:34 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=453045&limit=50&format=json HTTP/1.1" 200 369 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:35 syncloud nginx[13370]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:35 +0000] "PROPFIND /remote.php/dav/files/Marco/ HTTP/1.1" 207 1318 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:35 syncloud nginx[697]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:35 +0000] "PROPFIND /remote.php/dav/files/Marco/ HTTP/1.1" 207 1318 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:35 syncloud nginx[13369]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:35 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452995&limit=50&format=json HTTP/1.1" 200 370 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:35 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:35 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452995&limit=50&format=json HTTP/1.1" 200 370 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:37 syncloud nginx[13368]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:37 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452945&limit=50&format=json HTTP/1.1" 200 371 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:37 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:37 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452945&limit=50&format=json HTTP/1.1" 200 371 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:39 syncloud nginx[13368]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:39 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452895&limit=50&format=json HTTP/1.1" 200 371 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:39 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:39 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452895&limit=50&format=json HTTP/1.1" 200 371 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:40 syncloud nginx[13368]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:40 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452845&limit=50&format=json HTTP/1.1" 200 370 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:40 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:40 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452845&limit=50&format=json HTTP/1.1" 200 370 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:43 syncloud nginx[13371]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:43 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452795&limit=50&format=json HTTP/1.1" 200 369 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:43 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:43 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452795&limit=50&format=json HTTP/1.1" 200 369 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:44 syncloud nginx[13369]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:44 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452745&limit=50&format=json HTTP/1.1" 200 371 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
Nov 14 20:56:44 syncloud nginx[695]: syncloud nginx: 79.3.19.198 - Marco [14/Nov/2021:20:56:44 +0000] "GET /ocs/v2.php/apps/activity/api/v2/activity?since=452745&limit=50&format=json HTTP/1.1" 200 371 "-" "Mozilla/5.0 (Windows) mirall/3.3.6stable-Win64 (build 20211028) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
root@syncloud:~#

**Comment by cyberb** [comment]
Could you try one more time?

**Comment by ik0api** [comment]
After a few days of absence I gave a new "upgrade" command via Syncloud interface and the system upgraded to NextCloud 22.2.0 with no errors... a mystery to me...

Thank you anyway

**Comment by cyberb** [comment]
Sorry forgot to mention that it was fixed recently after few more updates in the store.
