### ISSUE TITLE
Offer android app on F-Droid

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#610]
It would be nice to offer the Syncloud android app in the [F-Droid](https://f-droid.org/) store for users of de-googled android OS like [lineageos](https://lineageos.org/). It just has to fit the [policy](https://f-droid.org/en/docs/Inclusion_Policy/). That's [how to do it](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md).

**Comment by cyberb** [comment]
I know it is not fdroid but apk is available to install on any Android device at https://github.com/syncloud/android/releases
Android app is not changing a lot and not really needed if you know the IP of your device.
Will close for now unless someone else wants to maintain fdroid account/deployment.
