### ISSUE TITLE
Reference to Syncloud from app websites

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#611]
One possibility to get more attention would be to ask app devs to refer to syncloud on there website. For a first start I created a bright and dark svg badge. Could you make a section on https://github.com/syncloud/platform/wiki/App-porting-guide and insert there download links /embed them?

https://github.com/syncloud/syncloud.org/pull/45

**Comment by klmhsb42** [comment]
One example would be rocket chat, to ask them to insert a reference https://de.rocket.chat/install

**Comment by klmhsb42** [comment]
Ok it's already there in the docs https://docs.rocket.chat/quick-start/installing-and-updating/paas-deployments/syncloud

**Comment by cyberb** [comment]
Yeah we do it as we port apps. Some of them reject like jellyfin: https://github.com/jellyfin/jellyfin.org/pull/334:
