### ISSUE TITLE
Hint to app contribution

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#612]
How about to make links on the app list how to contribute? Vote could link to a poll in discourse forum. Create to the wiki. Reward would need an own wiki page.

![g34388](https://user-images.githubusercontent.com/44033489/142730383-cc56fbed-7493-4876-aba6-1313b51e16b2.png)

**Comment by cyberb** [comment]
Sure

**Comment by cyberb** [comment]
Feel free to create a PR until then closing as no one is working on it.
