### ISSUE TITLE
App voting

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#613]
As discourse polls can not be edited as I see so far and must be sync. with github issues, maybe issue voting system in general would be interesting. https://vote.biglybt.com/syncloud/platform/ looks easy to use but I don't understand why it's not listing all issues or how to add them...

**Comment by klmhsb42** [comment]
https://vote.biglybt.com/syncloud/platform/app

**Comment by cyberb** [comment]
I guess it is done
