### ISSUE TITLE
Bounty system

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#614]
https://gitpay.me/ looks as it's open source and there is a github app https://github.com/apps/gitpay-me

Would you install such an app in your syncloud repo? I haven't understood yet if 8% fees have to be payed twice, once by the funder and once by the software dev. 16% might be a bit high but it looks well organized...

**Comment by klmhsb42** [comment]
if you install the gitpay-me github app I can make a bounty for testing on an app starting with one you are not focusing on right now like monitoring app https://github.com/syncloud/platform/issues/121

**Comment by cyberb** [comment]
16% is too much :) I am not even sure if someone wants to pay or get paid why would they not just ask on the issue.
Do not get me wrong I love the idea of connecting users and programmers around open source projects with money. 
For now when I need some open source work to be done for money (when I do not want to do it myself)  I just use upwork, 5% for me and usually 10% for devs (https://www.upwork.com/i/how-it-works/freelancer) I think. Amount of developers is impressive, around the world and you get very competitive offers very quickly.

I have imstalled their github app for platform repo. Not sure I understand what to do next.

**Comment by klmhsb42** [comment]
> I am not even sure if someone wants to pay or get paid why would they not just ask on the issue.

Well, it's like a donation. Why would someone donate. But here the donator has even a direct benefit. I just thought it would be also a chance that you could focus on platform issues, support, and the shop - and other devs could add apps. Also this could "bind" new devs as community as they get to know the principles about app creation. That was my initial thought...

About upwork, I don't have much knowledge about this in general anyway, but it sound you are paying per work hour which would be great of course but not really assessable how much it will cost to solve one issue. 

About the costs, isn't it that you have to sum the cut from the money, so 5+10% = 15% that's what upwork is getting? So 15 vs 16 % wouldn't be big difference.

Another idea would be to offer a issue as a product in your shop, where you can select the issue number and then set the number how many times you want to add 5$. It would need a script to publish the current total amount somewhere. Biggest problem would be to attract new devs, but once the community is big enough...

**Comment by cyberb** [comment]
Let's close this for now as nothing I can do, unless you tell me what yo do next. But anyway this is more for discussion https://syncloud.discourse.group/
