### ISSUE TITLE
[docs] translate github wiki

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#615]
1) Can you add links to translations following this https://github.com/syncloud/docs/blob/master/templates/footer.md
2) I thought it would be nice to have this at the end of the app porting guide https://github.com/klmhsb42/wiki-translate/blob/main/requests/app-porting-guide.md
3) I created a manual from the video what you can add if you like https://github.com/klmhsb42/wiki-translate/blob/main/requests/setup.md

**Comment by cyberb** [comment]
> I thought it would be nice to have this at the end of the app porting guide https://github.com/klmhsb42/wiki-translate/blob/main/requests/app-porting-guide.md

done

**Comment by cyberb** [comment]
> I created a manual from the video what you can add if you like https://github.com/klmhsb42/wiki-translate/blob/main/requests/setup.md

done (https://github.com/syncloud/platform/wiki/Setup-(detailed))

**Comment by cyberb** [comment]
> Can you add links to translations following this https://github.com/syncloud/docs/blob/master/templates/footer.md

I can of cause, just a few thoughts before we do that.

I have checked the doc repo and the layout and I have few questions, it looks like a copy of every page translated to another language, so if I want to add, change and even remove content/pages I need to do it 6 times.
I understand that documentation is 90% text so we would need to do translations anyway but there are other things like command line snippets which we do not translate, and structure of cause which I would like to change once.

Should we try to do it more dynamic like github pages which use Jekyl generator automatically generating a website from the templates as soon as you push: https://pages.github.com/
something like syncloud.github.com would be a compromise between a full blown site building framework like react/vue and completely static pages?

**Comment by cyberb** [comment]
probably we should start doing a weekly calls zoom/telegram not sure what is the best one two way/one way.

**Comment by klmhsb42** [comment]
> > Can you add links to translations following this https://github.com/syncloud/docs/blob/master/templates/footer.md
> 
> I can of cause, just a few thoughts before we do that.
> 
> I have checked the doc repo and the layout and I have few questions, it looks like a copy of every page translated to another language, so if I want to add, change and even remove content/pages I need to do it 6 times. I understand that documentation is 90% text so we would need to do translations anyway but there are other things like command line snippets which we do not translate, and structure of cause which I would like to change once.
> 
> Should we try to do it more dynamic like github pages which use Jekyl generator automatically generating a website from the templates as soon as you push: https://pages.github.com/ something like syncloud.github.com would be a compromise between a full blown site building framework like react/vue and completely static pages?

You can decide what's best. I haven't used github pages yet, but how would it keep the structure, by including (md?) files into others or like a dictionary? If dictionary, we could also use the syncloud.org and its json files then (or create a second wiki json file for each language to avoid nesting with webpage content)...

**Comment by cyberb** [comment]
This probably has to move to discussion
