### ISSUE TITLE
[Video conference] Jami

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#617]
Good distributed zoom replacement: https://jami.net/

**Comment by klmhsb42** [comment]
I haven't heard about jami yet, but this looks really powerful. It allows chat/calls without saving data to a server (only on client devices)? So people who don't have syncloud can participate too? And the syncloud app would be for synchronizing, right? That would be really cool to have, as nextcloud talk or rocketchat do not offer this yet I guess...

**Comment by cyberb** [comment]
> So people who don't have syncloud can participate too?

I have not thought about it but probably you are right, the only way to know is to try.

**Comment by klmhsb42** [comment]
I have just tested, works pretty good

**Comment by klmhsb42** [comment]
Syncloud app for backup would be nice if that's possible / even required...

**Comment by klmhsb42** [comment]
Only thing is, you can't create a public conference link as I see, so all people have to be in a group to participate what is maybe not wanted

**Comment by klmhsb42** [comment]
Video calls work even almost on the pinephone :D

**Comment by klmhsb42** [comment]
> Only thing is, you can't create a public conference link as I see, so all people have to be in a group to participate what is maybe not wanted

There is the Rendezvous mode

**Comment by klmhsb42** [comment]
> Syncloud app for backup would be nice if that's possible / even required... 

For backup not really needed as you can just create a .gz file to nextcloud or anywhere

For a public conference you just need a public client/host/user, what is probably incompatible with the idea of syncloud, as it's a server... So the client will host the conference.

Maybe it's sufficient to create a wiki entry for jami or "syncloud conference".

You could also use it instead of telegram for newsletter...

**Comment by cyberb** [comment]
There are so many negative reviews on google play mostly about messaging. I would not mix messages (rocketchat is the best) with voice/video confirence.
So I would be perfectly fine to talk on one platform and chat on another at the same time as it is much easier to find two best products.
Telegram is good for news as it has relatively wide audience at the moment.

There is also jitsi of cause https://github.com/syncloud/platform/issues/481 which has 100 time more downloads on google play (10m) and 50 times more reviews (50k)

Ideally I would have a conference server on Syncloud  device so I do not have worry about keeping all the info on my ohone which I can lose or break (I often do). Also conference links are better to have nice dns names.

Sorry have no time to test both of them at the moment, busy testing dns based wildcard cert https://github.com/syncloud/platform/issues/360

**Comment by cyberb** [comment]
> I haven't heard about jami yet
Wikipedia says `Jami (formerly GNU Ring, SFLphone)` i have actually tried both

**Comment by klmhsb42** [comment]
If jami would offer a web client it would satisfy all wishes... If you want to communicate with all people, most are still using whatsapp, signal, or telegram. If it's self-hosted you have to be their admin and to ask them to move to another app/client, that's possible for a few times but then they might not understand the reason. And today it's already a mess as there are so many messengers. So it would be nice to have something with bridges like matrix. But I don't know if that's good enough for conferences, so messenging might be really another issue. But jami could solve it all...

**Comment by cyberb** [comment]
Just checked Oculus Quest 2 / Bigscreen VR features and I must say VR is the future of the meetings especially in this pandemic period where I cannot even properly travel from UK to EU.
You can create public/private rooms and invite people, you can hear the direction of the voice coming from, you can mute/unmute people, you can show content from the PC (not sure if linux is supported but Proton should be pushing this)
I guess I should create Syncloud room :)
There are actually few other apps like Bigscreen and they are all fighting for the VR meeting space, I assume there will be more cheap headsets like oculus 2 and meeting apps.

**Comment by klmhsb42** [comment]
> There is also jitsi of cause #481 which has 100 time more downloads on google play (10m) and 50 times more reviews (50k)
you can close this
