### ISSUE TITLE
[platform] access rights

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#619]
A user with no admin rights should be able to login into platform but only see installed apps and "open" buttons (not app center, settings, restart,...).

**Comment by klmhsb42** [comment]
#453

**Comment by klmhsb42** [comment]
Or a "request" button in the app center instead of install and an email to the admin

**Comment by klmhsb42** [comment]
#659

**Comment by cyberb** [comment]
I think current logic is good enough. Admins can login and do everything. Non admins cannot login. Simple logic so I can concentrate on other useful features.
