### ISSUE TITLE
iframe user portal app

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#620]
Would be nice to have a user portal bringing all features from different syncloud apps to one place via iframes. The admin just needs something like a function to create/remove a button with url, icon, and name for each feature... 

I haven't found any available software yet...

#497

**Comment by cyberb** [comment]
Can you explain what is use case of such an app?
What is the example?

**Comment by klmhsb42** [comment]
this would be an alternative to what I describe in #619; so the syncloud platform app is an UI to access syncloud for admins and this user portal app could be an UI to access syncloud for users only. This could be useful for larger teams of users...

**Comment by cyberb** [comment]
Let's close this for as this not goint to be implemented in near future, reopen if you actually want to do it.

I just want issues to represent more current problems or app requests, and less of nice to have things which no one is willing to do.
