### ISSUE TITLE
Resilio Sync

### ISSUE THREAD

**Issue by JuanPerezPerez1** [syncloud/platform#632]
Has anyone thought about (Resilio Sync) as another alternative to (syncthing) ?

**Comment by cyberb** [comment]
Looks like it a closed-source solution.
For now we are considering open-source solutions unless there is absolutely no alternative.
If you really want this app in Syncloud store feel free to port it and maintain, we will take it.
https://github.com/syncloud/platform/wiki/App-porting-guide
