### ISSUE TITLE
Nextcloud Update v484 failling

### ISSUE THREAD

**Issue by shiremail** [syncloud/platform#638]
Hello!

Error:

root@syncloud:~# snap refresh nextcloud
error: cannot perform the following tasks:
- Run pre-refresh hook of "nextcloud" snap if present (run hook "pre-refresh":
-----
2022-02-26 19:35:03,397 - database - INFO - postgres executing: snap run nextcloud.pgdumpall -f /var/snap/nextcloud/current/database.dump
pg_dump.bin: [archiver] could not write to output file: No space left on device
pg_dumpall: pg_dump failed on database "nextcloud", exiting
2022-02-26 19:35:04,524 - database - ERROR - postgres error:
Traceback (most recent call last):
  File "/snap/nextcloud/211228447/meta/hooks/pre-refresh", line 7, in <module>
    Installer().pre_refresh()
  File "/snap/nextcloud/211228447/hooks/installer.py", line 90, in pre_refresh
    self.db.backup()
  File "/snap/nextcloud/211228447/hooks/postgres.py", line 52, in backup
    self.run('snap run nextcloud.pgdumpall -f {0}'.format(self.backup_file))
  File "/snap/nextcloud/211228447/hooks/postgres.py", line 62, in run
    raise e
  File "/snap/nextcloud/211228447/hooks/postgres.py", line 58, in run
    output = check_output(cmd, shell=True).decode()
  File "/snap/nextcloud/current/python/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/snap/nextcloud/current/python/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'snap run nextcloud.pgdumpall -f /var/snap/nextcloud/current/database.dump' returned non-zero exit status 1.
-----)

Bye.

**Comment by shiremail** [comment]
32GB SD card with syncloud on it
128 GB SSD

Filesystem      Size  Used Avail Use% Mounted on
udev            929M     0  929M   0% /dev
tmpfs           200M   22M  179M  11% /run
/dev/mmcblk1p2  2.9G  2.3G  482M  83% /
tmpfs           998M   12K  998M   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           998M     0  998M   0% /sys/fs/cgroup
/dev/loop1       85M   85M     0 100% /snap/files/158
/dev/loop0       43M   43M     0 100% /snap/bitwarden/21032862
/dev/loop2       30M   30M     0 100% /snap/files/21030283
/dev/loop3      147M  147M     0 100% /snap/platform/1227
/dev/loop4      431M  431M     0 100% /snap/nextcloud/211228447
/dev/loop5      147M  147M     0 100% /snap/platform/1236
/dev/loop6      147M  147M     0 100% /snap/platform/1264
/dev/sda1       110G   21G   84G  21% /opt/disk/external

I only use bitwarden und nextcloud on my device. Nextcloud data is on the SSD.

**Comment by cyberb** [comment]
What kind of device is this?
Did you build it yourself?
Try 
```
du -hx --max-depth=1 / | sort -h
```

**Comment by shiremail** [comment]
https://shop.syncloud.org/syncloud-h

4.0K    /media
4.0K    /mnt
4.0K    /srv
16K     /lost+found
20K     /opt
28K     /snap
32K     /tmp
44K     /home
2.7M    /etc
70M     /root
89M     /boot
658M    /usr
1.5G    /var
2.3G    /

**Comment by shiremail** [comment]
Any ideas?

**Comment by cyberb** [comment]
Did you anything with disk?
Root filesystem should not be on sdcard.
```
/dev/mmcblk1p2 2.9G 2.3G 482M 83% /
```

Looks like internal disk is used as external disk which is wrong and should be root `/`

You need to copy your files to another disk before you continue!

When you have backed up your files you need to do a factory reset by writing a fresh images to disk and sd card using this instruction:
https://github.com/syncloud/platform/wiki

Make sure you are writing sd image to sd card and disk image to internal disk (using another PC)

More info: https://github.com/syncloud/platform/wiki/Boot-from-SATA

**Comment by shiremail** [comment]
Hm...The board is called ODROID XU4S.

Last time I downloaded the image for XU4 from the wiki page. For the XU4 you only find one file. I used RUFUS to make a bootable image for the SD card and than booted the device. On the GUI I used the settings page to add the SSD. That worked also without any problems. I wonder why it used the storage that way....

**Comment by shiremail** [comment]
The XU4S seems to be the HC1.

**Comment by cyberb** [comment]
Yes this is much better, for external disk you need to use usb disk.

Can you run `lsblk`?

**Comment by cyberb** [comment]
Also did you extend boot disk from Settings - Internal Memory page?

**Comment by shiremail** [comment]
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0         7:0    0 146.9M  1 loop /snap/platform/1264
loop1         7:1    0  84.9M  1 loop /snap/files/158
loop2         7:2    0 434.5M  1 loop /snap/nextcloud/484
loop3         7:3    0  42.9M  1 loop /snap/bitwarden/21032862
sda           8:0    0 111.8G  0 disk
|-sda1        8:1    0   128M  0 part
`-sda2        8:2    0 111.7G  0 part /
mmcblk1     179:0    0  29.7G  0 disk
|-mmcblk1p1 179:1    0   128M  0 part
`-mmcblk1p2 179:2    0    10M  0 part

Under Internal memory it shows:

Boot

Partition 111,7G

Nextcloud installed fine.

Looks like the SD card is now only really used for the kernel do boot the system. The rest is on the SSD.

**Comment by cyberb** [comment]
do you still have a problem?
if yes what is the error now?

**Comment by jamidi99** [comment]
I am also having difficulties upgrading Nextcloud to v484.  My issues seems different though:

root@syncloud:~# snap refresh nextcloud
error: cannot perform the following tasks:
- Run configure hook of "nextcloud" snap if present (run hook "configure": 
-----
2022-03-11 10:41:31,721 - nextcloud_config - INFO - setting value: datadirectory = /opt/disk/external/nextcloud
2022-03-11 10:41:33,069 - nextcloud_config - INFO - setting datadirectory = /opt/disk/external/nextcloud
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2022-03-11 10:41:33,566 - nextcloud_occ - INFO - - installed: true
  - version: 23.0.2.1
  - versionstring: 23.0.2
  - edition: 
  - maintenance: false
  - needsDbUpgrade: true
  - productname: Nextcloud
  - extendedSupport: false
2022-03-11 10:41:33,566 - nextcloud_installer - INFO - status: - installed: true
  - version: 23.0.2.1
  - versionstring: 23.0.2
  - edition: 
  - maintenance: false
  - needsDbUpgrade: true
  - productname: Nextcloud
  - extendedSupport: false
2022-03-11 10:41:33,566 - nextcloud_installer - INFO - upgrading nextcloud
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2022-03-11 10:41:33,880 - nextcloud_occ - INFO - Maintenance mode enabled
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2022-03-11 10:41:34,203 - nextcloud_occ - ERROR - occ error: Setting log level to debug
Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
Maintenance mode is kept active
Resetting log level
2022-03-11 10:41:34,203 - nextcloud_installer - WARNING - unable to upgrade
2022-03-11 10:41:34,203 - nextcloud_installer - WARNING - Setting log level to debug
Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
Maintenance mode is kept active
Resetting log level
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2022-03-11 10:41:34,499 - nextcloud_occ - INFO - Maintenance mode disabled
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2022-03-11 10:41:50,542 - nextcloud_occ - INFO - Check indices of the share table.
Check indices of the filecache table.
Adding additional size index to the filecache table, this can take some time...
Filecache table updated successfully.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Adding properties_pathonly_index index to the oc_properties table, this can take some time...
oc_properties table updated successfully.
Check indices of the oc_jobs table.
Adding job_lastcheck_reserved index to the oc_jobs table, this can take some time...
oc_properties table updated successfully.
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2022-03-11 10:41:51,267 - nextcloud_occ - INFO - Check columns of the comments table.
Done.
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

                                                          
  There are no commands defined in the "ldap" namespace.  
                                                          

2022-03-11 10:41:51,579 - nextcloud_occ - ERROR - occ error:
Traceback (most recent call last):
  File "/snap/nextcloud/484/meta/hooks/configure", line 7, in <module>
    Installer().configure()
  File "/snap/nextcloud/484/hooks/installer.py", line 112, in configure
    self.occ.run('ldap:set-config s01 ldapEmailAttribute mail')
  File "/snap/nextcloud/484/hooks/octools.py", line 19, in run
    raise e
  File "/snap/nextcloud/484/hooks/octools.py", line 13, in run
    output = check_output('{0} {1}'.format(self.occ_runner_path, args), shell=True).decode().strip()
  File "/snap/nextcloud/current/python/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/snap/nextcloud/current/python/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/snap/nextcloud/current/bin/occ-runner ldap:set-config s01 ldapEmailAttribute mail' returned non-zero exit status 1.
-----)
root@syncloud:~#

Any help is greatly appreciated.
Thanks a lot!

**Comment by cyberb** [comment]
@jamidi99 
```
Updates between multiple major versions and downgrades are unsupported.
```
Please use this upgrade procedure if you skipped more than one major update: https://github.com/syncloud/platform/wiki/Nextcloud#cannot-upgrade-from-ui

For questions like this please use https://syncloud.discourse.group/
