### ISSUE TITLE
Opening Office documents on Nextcloud web interface

### ISSUE THREAD

**Issue by zovallo** [syncloud/platform#645]
Nextcloud does not open office documents on web interface. Please note that Collabora online app and Collabora Online - Built-in code server app have been installed.

**Comment by zovallo** [comment]
Nextcloud does not open office documents on web interface. Please note that Collabora online app and Collabora Online - Built-in code server app have been installed.

**Comment by cyberb** [comment]
Something seems to be incorrect with our nextcloud configuration.
Do you get the same message?
`Could not establish connection to the Collabora Online server. This might be due to a missing configuration of your web server`

Posted a question on Nextcloud: https://help.nextcloud.com/t/nextcloud-office-with-built-in-code-server-is-not-working/138092

**Comment by zovallo** [comment]
yes

**Comment by cyberb** [comment]
Ok please follow this issue as will publish some progress there: https://github.com/syncloud/platform/issues/426

**Comment by zovallo** [comment]
Dear Boris
I followed the thread but i did not understand.
Ho did you solved the issue?
How can I edit the office documents online??
Please let me know
best regards
mb

**Comment by cyberb** [comment]
Hi, just give me a day or two and I will release a new app called collabora (and close the other issue), you will be able to install it from Syncloud store and use in Nextcloud. I will publish an instruction (not very complex) on our wiki on how to integrate all three together (Collabora, Nextcloud and Nextcloud Office)

**Comment by cyberb** [comment]
Please try installing Collabora app and check this instruction https://github.com/syncloud/platform/wiki/Collabora

**Comment by zovallo** [comment]
Dear Boris
Attached the video recording of my screen with the procedure you suggested.
As you can see it does not work.
Please have a look.
Awaiting for your comments
Best Regards

**Comment by cyberb** [comment]
Sorry there is no video, do not reply by email just use github url in browser and attach it. Also this is public so to not expose your private device url you can send email to support@syncloud.it

**Comment by cyberb** [comment]
Can you send logs from Settings - Support to support?

**Comment by cyberb** [comment]
One thing I can see is that you are on old version of platform, because of that you get do not get a wildcard https certificate so collabora does not have a valid cert.

Can you upgrade from System - Updates and let me know?

**Comment by zovallo** [comment]
HI
Done exactly as suggested:
System Upgrade, Installer Upgrade, Nextcloud Upgrade.
Collabora Installed BEFORE Nextcloud Office app.
Nextcloud Office app set to: https://Collabora.mydomine.syncloud.i ; Disabled the certificate request
Still does not work
See screenshot attached

**Comment by cyberb** [comment]
@zovallo I see you have a proper wildcard slcertificate now which covers collabora app, do you still not able to edit documents?
If yes could you send logs from Settings - Support?

**Comment by cyberb** [comment]
Reopen if does not work
