### ISSUE TITLE
I cannot create a calendar Invitation with a different email from doamin.syncloud.it

### ISSUE THREAD

**Issue by zovallo** [syncloud/platform#646]
If I send a calendar invitation using a different email from "domani.syncloud.it", the recipient dos not receive it

**Comment by zovallo** [comment]
If I send a calendar invitation using a different email from "domani.syncloud.it", the recipient dos not receive it

**Comment by cyberb** [comment]
Am I right you have a Syncloud Mail app installed and your local users can send email to each other?
Can you try sending email to the that external user from Mail app?
Usually gmail blocks email coming from independent mail servers unless they register their IP (not possibpe for a dynamic IP) and they send you an email explaining that.

**Comment by cyberb** [comment]
Reopen if you are ready to provide more feedback
