### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by JuanPerezPerez1** [syncloud/platform#650]
Hi
Today I have realized that I cannot access from my domain in the local network, which I could before. Also today the system tells me to update to a version 1361 when I am in version 1389. When I do the update it does nothing and keeps asking me to update.

**Comment by cyberb** [comment]
Hi,
For questions/support we have a separate discussion site, please create two threads, one per question at https://syncloud.discourse.group and I will help as soon as you do this.

Github is for code fixes (which may may happen after we discuss your issues)

Thanks
