### ISSUE TITLE
i can’t install Pi-hole

### ISSUE THREAD

**Issue by JuanPerezPerez1** [syncloud/platform#651]
i can’t install Pi-hole. I can install any other app except that. Is there a way to install manually?

**Comment by cyberb** [comment]
Whar error message do you get?
Send logs from Settings - Support.
Also you can try installing using SSH and post the output:
```
snap install pihole
```

**Comment by JuanPerezPerez1** [comment]
I have tried to install it but it does as if it is going to install it and does nothing. I tried through ssh as you told me but I got this error.



error: cannot perform the following tasks:
- Run install hook of "pihole" snap if present (run hook "install":
-----
2022/05/17 19:32:16 open /snap/pihole/210320405/config/platform.cfg: no such file or directory
Traceback (most recent call last):
  File "/snap/pihole/210320405/meta/hooks/install", line 6, in <module>
    installer.Installer().install()
  File "/snap/pihole/210320405/hooks/installer.py", line 56, in install
    self.install_config()
  File "/snap/pihole/210320405/hooks/installer.py", line 48, in install_config
    'ipv4': check_output(['/snap/platform/current/bin/cli', 'ipv4'])
  File "/snap/pihole/current/python/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/snap/platform/current/bin/cli', 'ipv4']' returned non-zero exit status 1

**Comment by JuanPerezPerez1** [comment]
Yes I think I have the latest version (System: 1361) but I still can't install pi-hole

**Comment by cyberb** [comment]
Can you run the command:
```
/snap/platform/current/bin/cli ipv4
```

**Comment by JuanPerezPerez1** [comment]
yes. and then

**Comment by JuanPerezPerez1** [comment]
after executing the command nothing happens and I don't know what to do next

**Comment by cyberb** [comment]
Can you show the output?

**Comment by JuanPerezPerez1** [comment]
10.0.0.26root@syncloud:~#

**Comment by JuanPerezPerez1** [comment]
root@syncloud:~# /snap/platform/current/bin/cli ipv4
10.0.0.26root@syncloud:~#

**Comment by cyberb** [comment]
Ok, can you run these two commands and show the output:
```
/snap/platform/current/bin/cli ipv4

echo $?
```

**Comment by JuanPerezPerez1** [comment]
root@syncloud:~# /snap/platform/current/bin/cli ipv4
10.0.0.26root@syncloud:~# echo $?
0
root@syncloud:~#

**Comment by cyberb** [comment]
Sorry just tested myself and latest version is broken Indeed.
I am in the middle of fixing custom dns feature in pihole, give me a day or two and I will publish the new version asap.

**Comment by cyberb** [comment]
Fixed, please try to install again from the web the usual way.
