### ISSUE TITLE
Instalación en vps (Oracle cloud)

### ISSUE THREAD

**Issue by Manoel1023** [syncloud/platform#653]
Hola, he venido siguiendo hace más de 1 año el proyecto, actualmente lo uso en mi casa! Quisiera saber cómo instalarlo en una instancia de Oracle Cloud me gustaría el correo y la página siempre disponible, adicionalmente, q debo hacer para que al cargar el dominio o la IP cargue directamente el WordPress dónde está alojada la página, y el panel de syncluod se cargue en otro puerto o subdominio? Desde ya muchas gracias 😃 !!

**Comment by cyberb** [comment]
Hi

Could you ask these questions at https://syncloud.discourse.group/ one oer thread please.
I will help you there!
