### ISSUE TITLE
App Users | Prevent users (or groups) from adding/removing apps

### ISSUE THREAD

**Issue by simoneburalli** [syncloud/platform#659]
As a Syncloud admin,
I would like to prevent users (or groups) from adding/removing apps because this is essential for Syncloud security. Thanks

**Comment by cyberb** [comment]
Is it easier to not allow non-admin user to login at all for now? There is nothing useful for non admins anyway.

**Comment by Penguinjumper** [comment]
> Is it easier to not allow non-admin user to login at all for now? There is nothing useful for non admins anyway.

Sounds reasonable enough. Admins can take care of updates (and Auto-Update of apps and Syncloud should sort even that out) and nothing else there should be accessible for non admins I guess.

**Comment by cyberb** [comment]
![IMG_20230210_195547](https://user-images.githubusercontent.com/885528/218185834-b66b4c86-18a7-4593-b9e7-04be83f3f918.jpg)

**Comment by Penguinjumper** [comment]
Great work!
