### ISSUE TITLE
[Device] Adding support for Jetson Nano

### ISSUE THREAD

**Issue by viscropst** [syncloud/platform#668]
Currently Syncloud does not have an Image for Jetson Nano. So I tried the [image building script](https://github.com/syncloud/image), and worked out with some modification with `tools/boot.sh` to solve with the rootfs partation size larger than the image's usable size after boot partation created in sgdisk shows and [base image](https://redirect.armbian.com/jetson-nano/Bullseye_current). If need I'll create a PR to apply this work.

**Comment by cyberb** [comment]
Sure create a PR please
