### ISSUE TITLE
Activate hdd error

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#67]
Hdd activation leads to error page.

**Comment by jpma89** [comment]
Clicking the "Activate" button of a HDD attached causes following log entries in /opt/data/platform/log/uwsgi_public.log:

[pid: 849|app: 0|req: 27/55] 192.168.0.2 () {40 vars in 576 bytes} [Mon Nov  2 21:03:05 2015] GET /owncloud/status.php => generated 233 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 72 bytes (2 switches on core 1)
[pid: 849|app: 0|req: 28/56] 192.168.0.2 () {40 vars in 594 bytes} [Mon Nov  2 21:03:06 2015] GET /owncloud/owncloud/status.php => generated 233 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/platform/lib/Flask-Login-0.2.11/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/opt/app/platform/lib/syncloud-platform-164/syncloud_platform/server/rest/public.py", line 256, in disk_activate
    return jsonify(success=True, disks=Hardware().activate_disk(device, fix_permissions)), 200
TypeError: activate_disk() takes exactly 2 arguments (3 given)
------------------------------------------------------------
[pid: 849|app: 0|req: 29/57] 192.168.0.2 () {46 vars in 1082 bytes} [Mon Nov  2 21:03:06 2015] GET /server/rest/settings/disk_activate?device=%2Fdev%2Fsda1 => generated 66 bytes in 35 msecs (HTTP/1.1 500) 3 headers in 368 bytes (1 switches on core 1)
[pid: 849|app: 0|req: 30/58] 192.168.0.2 () {46 vars in 1084 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/error.html => generated 4794 bytes in 29 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 846|app: 0|req: 11/60] 192.168.0.2 () {44 vars in 1013 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/lib/bootstrap-3.3.1.min.js => generated 35601 bytes in 157 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 0)
[pid: 845|app: 0|req: 10/60] 192.168.0.2 () {44 vars in 1003 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/lib/underscore-min.js => generated 14241 bytes in 156 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 849|app: 0|req: 32/61] 192.168.0.2 () {44 vars in 1030 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/css/lib/font-awesome-4.0.3.css => generated 21658 bytes in 166 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 0)
[pid: 849|app: 0|req: 32/62] 192.168.0.2 () {44 vars in 1032 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/css/lib/bootstrap-3.3.1.min.css => generated 113498 bytes in 219 msecs via sendfile() (HTTP/1.1 200) 8 headers in 619 bytes (0 switches on core 1)
[pid: 840|app: 0|req: 11/63] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/lib/URI.js => generated 27598 bytes in 235 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 840|app: 0|req: 11/64] 192.168.0.2 () {44 vars in 1007 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/lib/jquery-2.1.1.min.js => generated 84245 bytes in 238 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 845|app: 0|req: 11/65] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/android.js => generated 375 bytes in 163 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 0)
[pid: 849|app: 0|req: 34/66] 192.168.0.2 () {44 vars in 979 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/mobile.js => generated 328 bytes in 151 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 0)
[pid: 846|app: 0|req: 13/67] 192.168.0.2 () {44 vars in 1008 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/css/form-center.css => generated 608 bytes in 215 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 0)
[pid: 840|app: 0|req: 12/68] 192.168.0.2 () {44 vars in 1016 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/images/logo-52.png => generated 2898 bytes in 119 msecs via sendfile() (HTTP/1.1 200) 8 headers in 601 bytes (0 switches on core 1)
[pid: 846|app: 0|req: 13/69] 192.168.0.2 () {44 vars in 1004 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/css/main-menu.css => generated 554 bytes in 221 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 849|app: 0|req: 34/70] 192.168.0.2 () {44 vars in 977 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/error.js => generated 215 bytes in 138 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 1)
[pid: 849|app: 0|req: 35/71] 192.168.0.2 () {46 vars in 1002 bytes} [Mon Nov  2 21:03:06 2015] GET /server/rest/user => generated 78 bytes in 18 msecs (HTTP/1.1 200) 3 headers in 349 bytes (1 switches on core 0)
[pid: 849|app: 0|req: 36/72] 192.168.0.2 () {46 vars in 1096 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/css/fonts/glyphicons-halflings-regular.woff => generated 23424 bytes in 31 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)

**Comment by jpma89** [comment]
Clicking the "Activate" button of a HDD attached causes following log entries in /opt/data/platform/log/uwsgi_public.log:



[pid: 849|app: 0|req: 27/55] 192.168.0.2 () {40 vars in 576 bytes} [Mon Nov  2 21:03:05 2015] GET /owncloud/status.php => generated 233 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 72 bytes (2 switches on core 1)
[pid: 849|app: 0|req: 28/56] 192.168.0.2 () {40 vars in 594 bytes} [Mon Nov  2 21:03:06 2015] GET /owncloud/owncloud/status.php => generated 233 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](\**req.view_args)
  File "/opt/app/platform/lib/Flask-Login-0.2.11/flask_login.py", line 758, in decorated_view
    return func(*args, \**kwargs)
  File "/opt/app/platform/lib/syncloud-platform-164/syncloud_platform/server/rest/public.py", line 256, in disk_activate
    return jsonify(success=True, disks=Hardware().activate_disk(device, fix_permissions)), 200
TypeError: activate_disk() takes exactly 2 arguments (3 given)
------------------------------------------------------------
[pid: 849|app: 0|req: 29/57] 192.168.0.2 () {46 vars in 1082 bytes} [Mon Nov  2 21:03:06 2015] GET /server/rest/settings/disk_activate?device=%2Fdev%2Fsda1 => generated 66 bytes in 35 msecs (HTTP/1.1 500) 3 headers in 368 bytes (1 switches on core 1)
[pid: 849|app: 0|req: 30/58] 192.168.0.2 () {46 vars in 1084 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/error.html => generated 4794 bytes in 29 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 846|app: 0|req: 11/60] 192.168.0.2 () {44 vars in 1013 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/lib/bootstrap-3.3.1.min.js => generated 35601 bytes in 157 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 0)
[pid: 845|app: 0|req: 10/60] 192.168.0.2 () {44 vars in 1003 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/lib/underscore-min.js => generated 14241 bytes in 156 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 849|app: 0|req: 32/61] 192.168.0.2 () {44 vars in 1030 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/css/lib/font-awesome-4.0.3.css => generated 21658 bytes in 166 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 0)
[pid: 849|app: 0|req: 32/62] 192.168.0.2 () {44 vars in 1032 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/css/lib/bootstrap-3.3.1.min.css => generated 113498 bytes in 219 msecs via sendfile() (HTTP/1.1 200) 8 headers in 619 bytes (0 switches on core 1)
[pid: 840|app: 0|req: 11/63] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/lib/URI.js => generated 27598 bytes in 235 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 840|app: 0|req: 11/64] 192.168.0.2 () {44 vars in 1007 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/lib/jquery-2.1.1.min.js => generated 84245 bytes in 238 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 845|app: 0|req: 11/65] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/android.js => generated 375 bytes in 163 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 0)
[pid: 849|app: 0|req: 34/66] 192.168.0.2 () {44 vars in 979 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/mobile.js => generated 328 bytes in 151 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 0)
[pid: 846|app: 0|req: 13/67] 192.168.0.2 () {44 vars in 1008 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/css/form-center.css => generated 608 bytes in 215 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 0)
[pid: 840|app: 0|req: 12/68] 192.168.0.2 () {44 vars in 1016 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/images/logo-52.png => generated 2898 bytes in 119 msecs via sendfile() (HTTP/1.1 200) 8 headers in 601 bytes (0 switches on core 1)
[pid: 846|app: 0|req: 13/69] 192.168.0.2 () {44 vars in 1004 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/css/main-menu.css => generated 554 bytes in 221 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 849|app: 0|req: 34/70] 192.168.0.2 () {44 vars in 977 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/js/error.js => generated 215 bytes in 138 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 1)
[pid: 849|app: 0|req: 35/71] 192.168.0.2 () {46 vars in 1002 bytes} [Mon Nov  2 21:03:06 2015] GET /server/rest/user => generated 78 bytes in 18 msecs (HTTP/1.1 200) 3 headers in 349 bytes (1 switches on core 0)
[pid: 849|app: 0|req: 36/72] 192.168.0.2 () {46 vars in 1096 bytes} [Mon Nov  2 21:03:06 2015] GET /server/html/css/fonts/glyphicons-halflings-regular.woff => generated 23424 bytes in 31 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)

**Comment by jpma89** [comment]
Clicking the "Activate" button of an attached USB-HDD causes following log entries in /opt/data/platform/log/nginx_error.log:


2015/11/02 21:25:37 [warn] 873#0: *281 an upstream response is buffered to a temporary file /opt/app/platform/nginx/uwsgi\_temp/4/01/0000000014 while reading upstream, client: 192.168.0.2, server: localhost, request: "GET /server/html/css/lib/bootstrap-3.3.1.min.css HTTP/1.1", upstream: "uwsgi://unix:///opt/app/platform/config/uwsgi/socket/public.wsgi.sock:", host: "192.168.0.13", referrer: "http://192.168.0.13/server/html/error.html"
2015/11/02 21:25:37 [warn] 873#0: *275 an upstream response is buffered to a temporary file /opt/app/platform/nginx/uwsgi_temp/5/01/0000000015 while reading upstream, client: 192.168.0.2, server: localhost, request: "GET /server/html/js/lib/jquery-2.1.1.min.js HTTP/1.1", upstream: "uwsgi://unix:///opt/app/platform/config/uwsgi/socket/public.wsgi.sock:", host: "192.168.0.13", referrer: "http://192.168.0.13/server/html/error.html"

**Comment by jpma89** [comment]
There seem to be no changes written to /opt/data/platform/log/rest_public.log

**Comment by cyberb** [comment]
Platform v165 should have this fixed (Syncloud v1.0 release)

**Comment by jpma89** [comment]
Seems to work now :+1:
