### ISSUE TITLE
Camera security software

### ISSUE THREAD

**Issue by ktatar156** [syncloud/platform#670]
Please consider adding any Open Source Camera Security Software, e.g. iSpy, ZoneMinder or similar.

**Comment by ktatar156** [comment]
Hello @cyberb :)
I'd love to see this software on Syncloud! :)

**Comment by cyberb** [comment]
I mean would you like to try packaging it for us?
Or you would rather wait for someone else to do it?

**Comment by cyberb** [comment]
We have this guide: https://github.com/syncloud/platform/wiki/App-porting-guide

I guess Nextcloud is the best candidate for copying.
You can create PRs against this repo:
https://github.com/syncloud/zoneminder

**Comment by cyberb** [comment]
Frigate is another option: https://github.com/blakeblackshear/frigate
Pytnon and react. No authentication system.

**Comment by cyberb** [comment]
Shinobi: https://gitlab.com/Shinobi-Systems/Shinobi
Has ldap support, nodejs, mariadb.

**Comment by cyberb** [comment]
Viseron: https://github.com/roflcoopter/viseron
No ldap, nodejs

**Comment by cyberb** [comment]
Moonfire: https://github.com/scottlamb/moonfire-nvr
Rust (really low on resources), no authentication support.

**Comment by cyberb** [comment]
Frigate was selected and published, file individual issues if needed.
