### ISSUE TITLE
[docs] add "API" page to docs

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#671]
Would be good to have an doc entry for the syncloud.it API, something like this:

# API

### POST Request

To access the REST API Endpoint of syncloud.it

the url is `https://api.syncloud.it/user`

the content-type is `application/json`

the required data is

```
{
    "email": "user@example.com",
    "password": "secret"
}
```
### Server Response

You will get a list of the activated devices in JSON format.

**Comment by klmhsb42** [comment]
I guess there is no API for the platform app (yet), right?

**Comment by cyberb** [comment]
This is not really a true public api for people to use, this api between device and dns. It evolves over time and documentation will get outdated and will add more confusion. Of cause if we get 100s of developers doing platform development then yes, now there is no need.

Why do you need it?
