### ISSUE TITLE
Bitwarden Update?

### ISSUE THREAD

**Issue by shiremail** [syncloud/platform#681]
Will there be a new update for Bitwarden in the near future? There are a few interessting changes as of late (argon2id).

**Comment by cyberb** [comment]
Just to let you know we are using vaultearden backend implementation, will upgrade from v1.25.0 to v.1.28.1.

**Comment by shiremail** [comment]
Thanks.

**Comment by cyberb** [comment]
v1.28.1 is has been pushed to the store
