### ISSUE TITLE
Shairport sync request.

### ISSUE THREAD

**Issue by blowuppp** [syncloud/platform#682]
Hi, it was recommended that a 'request for app' was created here ;

In our instance of Syncloud it would be useful to have 'shairport sync' available - thus save using a dedicated machine for audio playback.

**Comment by cyberb** [comment]
Is it this one? https://github.com/mikebrady/shairport-sync

Never used it myself, how dow it work?
Do you expect after installing this app to instantly atart playing your airplay through the audio out jack?
Do you expect to make any config changes (ideally no)?
Is there any webui to configure it (it is ok if none is needed)?

**Comment by cyberb** [comment]
Ok, shairpot app is in the store, tested on rpi and it played music through headphone jack right after install from iphone using airplay (spotify) also from adnroid using airmusic trial test app.
If you have any issues please open a separate ticket.

**Comment by blowuppp** [comment]
Dear Mr Boris, please accept my sincere apology for missing your kind
responses, only excuse is Syncloud is SO SOLID that we spend less time with
computers (but more time dealing with a dementia stricken mother) these
days 👍

Many, many thank yous for making up the SharePort addition ... it is
working perfectly , my Syncloud is now one extra client for our mishmash of
SharePort Pis fed by Airfoil <https://rogueamoeba.com/airfoil/mac/> audio
server <https://rogueamoeba.com/airfoil/mac/>.

We aspired to a full linux (Sonos like multi room synced audio) solution using
snapcast server and clients
<https://magpi.raspberrypi.com/articles/build-a-multi-room-audio-system-with-raspberry-pi>
but never manage a solid system. My hunch is that your skills could make
something that works ... im not asking though ... you already seem to be
the busiest and most conscientious man in the software industry , bought
you a couple of beers using the donate feature :-)

yours with deep appreciation
Mark Cookman

**Comment by cyberb** [comment]
Thank you for the kind words!
I have read the instruction you mentioned about Mopidy, Snapcast. While I could probably package them as independent apps, looks like you will need a bit of a command line config still to do after the install. It has to be given some thought how to make it more user friendly. Feel free open issues.
