### ISSUE TITLE
Update Adlists on Pi-Hole

### ISSUE THREAD

**Issue by LepusMaximus** [syncloud/platform#684]
i am new to syncloud and have a new installation.
I installed the pi-hole from the app store and added new adlists. 
Now how do I get these adlists to download and apply. 
In the web interface tools->update gravity to use unfortunately does not work.
Is there a command to do this? thank you.

**Comment by cyberb** [comment]
Right, let me fix that, meanwhile could you try this command:

```
/snap/pihole/current/bin/gravity.sh
```

**Comment by LepusMaximus** [comment]
Thank you. That worked!
