### ISSUE TITLE
Can't use SD card slot for storage on BeagleBoneBlack after copying system to EMMC

### ISSUE THREAD

**Issue by Dan2077** [syncloud/platform#685]
As per title, after running `/original/opt/scripts/tools/eMMC/init-eMMC-flasher-v3.sh` and then rebooting from the EMMC, insterting an sd card formatted as FAT32 or ext4, doesn't show up as an expandable storage option.

**Comment by cyberb** [comment]
Pushed a fix, could you update system from.settings and let me know if you can use ad card as storage.
By the way I would recommend using external usb disk instead..

**Comment by Dan2077** [comment]
That has done the trick. Avoiding using the USB port on the BBB to avoid the system from freezing. https://e2e.ti.com/support/processors-group/processors/f/processors-forum/308549/am335x-usb-babble-interrupt

**Comment by cyberb** [comment]
> Avoiding using the USB port on the BBB to avoid the system from freezing

right, makes sense!
