### ISSUE TITLE
Nextcloud accessing from local IP

### ISSUE THREAD

**Issue by idefy** [syncloud/platform#687]
First sync with a lot of data is VERY slow using the nextcloud.nnn.syncloud.it. I did not find a way in the documentation to allow to connect directly with internal IP address to speed things up.
Is there a way to configure the client with internal IP ?

**Comment by cyberb** [comment]
Hi,

Have you enabled external access?
In external mode we set dns name to public IP on the router so you can access from the Internet but at the same time when you are inside the Lan traffic still goes through the router back to lan.
Is the speed comparable with the internet speed or even slower?
Is there any QOS enabked on the router?
Also I know some routers cannot route traffic at lan speeds.

If this is a PC which is constantly inside LAN you can override DNS in hosts file https://en.m.wikipedia.org/wiki/Hosts_(file)
```
local_ip nextcloud.nnn.syncloud.it
```

**Comment by idefy** [comment]
Thank you for the response.
I tried both with external access enabled or not and did not see any difference in speed.
I switch to using commandline (scp -rp ) rather than NC UI so I can have more visible details: The max speed I am seeing is a little lower than 26MB/s on big files. My internet speed is 500Mb/s so way lower. 
Syncloud is on a Raspberry Pi 4 B.
QoS is turned off on my router. It's an Asus RT-AC66U B1. NAT acceleration is on auto on which enables CTF (Cut Through Forwarding) 
Each RJ45 port is 1Gbps and both PC and PI are connected directly on it.
I did not think of overriding the DNS, I did it, when I ping nextcloud.nnn.syncloud.it it does show the local ip, but I did not see a gain in speed.
I know it's not a disk limit, I copied the data from one disk to the next directly when both are connected on the PI and it was fast. 
I turned back on the NC UI to sync again, but I see the max speed is 0.5Mbps according to windows task manager
Not too sure what is happening.

**Comment by cyberb** [comment]
Ok, is upload/download or both?
You can test download of a file excluding nextcloud but still using the rest of syncloud by installing files app and downloading some file to compare.

**Comment by idefy** [comment]
Actually, after closing the NC UI, all of a sudden it went up to 160Mbps, but varies most of the time between 50Mbps and 100Mbps.
It seems the UI for some reason slows everything down while it remains open. Still not super high speed, but better than before.

**Comment by cyberb** [comment]
27.0.1 is out.
Also you can always see what browser is doing by opening a network tab in dev tools if you think it is related. I know sometimes when I open images it will start generating previews on demand at it may take some time and server resources on a big collection.
Otherwise I would close this issue as it is not clear if we can fix it, feel free to discuss things at https://syncloud.discourse.group/
