### ISSUE TITLE
Migrate to internal memory button

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#69]
Some board like beagle bone, have internal memory, we may help them using it.

**Comment by jpma89** [comment]
Maybe this might help:

http://www.crashcourse.ca/wiki/index.php/BBB_software_update_process

**Comment by cyberb** [comment]
Not enough resources at the moment.

**Comment by cyberb** [comment]
Some work has been done to improve that.
Run script: /opt/app/platform/bin/copy_to_emmc.sh

Source: https://github.com/syncloud/platform/blob/master/bin/copy_to_emmc.sh
Settings button will be added later.

**Comment by cyberb** [comment]
I’m closing this issue because it has been inactive for a few months.
Please reopen if you have more info.
Thank you!
