### ISSUE TITLE
Nextcloud v711 installed -> Update to v706 proposed

### ISSUE THREAD

**Issue by shiremail** [syncloud/platform#691]
Hello together,

![IMG_1187](https://github.com/syncloud/platform/assets/57576378/10dc515d-7682-492f-9b77-781a4368610d)

'Upgrade' does nothing...

Bye.

**Comment by cyberb** [comment]
Yeah, sorry I had to downgrade Nextcloud on arm32 as latest version did not work properly for some users but if you already installed it it will not go back.

Are you on arm32?
Do you have any issues currently?

**Comment by shiremail** [comment]
I just noticed it. Nextcloud runs just fine. I use an older ODROID board which I bought thru your shop a few years ago ( so I guess arm32).

**Comment by cyberb** [comment]
If all is ok, I would leave as is until you get a better device.
