### ISSUE TITLE
Need a good workaround to install in esxi

### ISSUE THREAD

**Issue by ratatouillex** [syncloud/platform#693]
Hello,
we have failed to install from img.xz in esxi. 
we were trying to convert img.xz to .iso with no success.

Finally, we have managed to get it install in VirtualBox and then export ova and import it in ESXi. 
But it's very slow in ESXi.

Probably supporting ESXI officially will be a good idea. otherwise, Need a good workaround to install in ESXI.

Thanks!

**Comment by cyberb** [comment]
When you slow, do you know what exactly is slow, like high cpu usage, slow network or disk?

**Comment by ratatouillex** [comment]
Ok. I'm uninstalled Syncloud.
If you confirm that how i installed it in ESXi is correct, I will reinstall it and try again and investigate the CPU ram and the disk.

**Comment by cyberb** [comment]
Yes, to me that is one of the valid ways, so I would like to see what exactly is slow (not working).

**Comment by cyberb** [comment]
reopen if not working
