### ISSUE TITLE
Keep owncloud binaries in our S3 storage

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#7]
_From @vsapronov on March 15, 2015 22:5_

We need to keep ownCloud binaries in our S3 storage to control what we are installing into image.

_Copied from original issue: syncloud/owncloud#1_

**Comment by cyberb** [comment]
How could we overlook that :)
"The .tar archive is the classic way of installing ownCloud server."
https://owncloud.org/install/#instructions-server

**Comment by vsapronov** [comment]
Some linuxoids like do to everything "proper" linux way...
