### ISSUE TITLE
USB pendrive is not showing up in hdd list

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#70]

**Comment by jpma89** [comment]
The pendrive is NTFS formatted and can be mounted and written by the Debian version contained in Syncloud image v1.0

**Comment by jpma89** [comment]
When the USB pendrive is connected settings.html runs into an error condition. See /opt/data/platform/log/uwsgi_public.log:


[pid: 493|app: 0|req: 17/52] 192.168.0.2 () {46 vars in 1065 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/settings.html => generated 13528 bytes in 30 msecs via sendfile() (HTTP/1.1 200) 8 headers in 618 bytes (1 switches on core 1)
[pid: 493|app: 0|req: 19/53] 192.168.0.2 () {46 vars in 1084 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/error.html => generated 4794 bytes in 71 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 493|app: 0|req: 20/54] 192.168.0.2 () {44 vars in 1032 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/css/lib/bootstrap-3.3.1.min.css => generated 113498 bytes in 188 msecs via sendfile() (HTTP/1.1 200) 8 headers in 619 bytes (0 switches on core 1)
[pid: 492|app: 0|req: 10/55] 192.168.0.2 () {44 vars in 1030 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/css/lib/font-awesome-4.0.3.css => generated 21658 bytes in 184 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 0)
[pid: 494|app: 0|req: 15/56] 192.168.0.2 () {44 vars in 1007 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/js/lib/jquery-2.1.1.min.js => generated 84245 bytes in 265 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 494|app: 0|req: 16/57] 192.168.0.2 () {44 vars in 1013 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/js/lib/bootstrap-3.3.1.min.js => generated 35601 bytes in 317 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 399|app: 0|req: 15/58] 192.168.0.2 () {44 vars in 1004 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/css/main-menu.css => generated 554 bytes in 369 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 492|app: 0|req: 11/59] 192.168.0.2 () {44 vars in 1008 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/css/form-center.css => generated 608 bytes in 177 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 399|app: 0|req: 16/60] 192.168.0.2 () {44 vars in 1003 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/js/lib/underscore-min.js => generated 14241 bytes in 410 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 493|app: 0|req: 21/61] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/js/lib/URI.js => generated 27598 bytes in 187 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 399|app: 0|req: 16/62] 192.168.0.2 () {44 vars in 977 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/js/error.js => generated 215 bytes in 139 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 17/63] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/js/android.js => generated 375 bytes in 259 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 0)
[pid: 492|app: 0|req: 12/64] 192.168.0.2 () {44 vars in 1016 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/images/logo-52.png => generated 2898 bytes in 133 msecs via sendfile() (HTTP/1.1 200) 8 headers in 601 bytes (0 switches on core 0)
[pid: 494|app: 0|req: 17/65] 192.168.0.2 () {44 vars in 979 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/js/mobile.js => generated 328 bytes in 213 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 1)
[pid: 493|app: 0|req: 22/66] 192.168.0.2 () {46 vars in 1002 bytes} [Mon Nov  2 22:37:04 2015] GET /server/rest/user => generated 78 bytes in 45 msecs (HTTP/1.1 200) 3 headers in 349 bytes (1 switches on core 1)
[pid: 493|app: 0|req: 23/67] 192.168.0.2 () {46 vars in 1096 bytes} [Mon Nov  2 22:37:04 2015] GET /server/html/css/fonts/glyphicons-halflings-regular.woff => generated 23424 bytes in 63 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
Mon Nov  2 22:37:05 2015 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Nov  2 22:37:05 2015 - uwsgi\_response\_writev\_headers\_and\_body\_do(): Broken pipe [core/writer.c line 296] during GET /server/rest/settings/version (192.168.0.2)
IOError: write error
[pid: 493|app: 0|req: 24/68] 192.168.0.2 () {46 vars in 1029 bytes} [Mon Nov  2 22:37:04 2015] GET /server/rest/settings/version => generated 0 bytes in 1526 msecs (HTTP/1.1 200) 3 headers in 0 bytes (0 switches on core 0)
[pid: 493|app: 0|req: 24/69] 192.168.0.2 () {46 vars in 1065 bytes} [Mon Nov  2 22:37:05 2015] GET /server/html/settings.html => generated 13528 bytes in 54 msecs via sendfile() (HTTP/1.1 200) 8 headers in 618 bytes (0 switches on core 1)
[pid: 493|app: 0|req: 26/70] 192.168.0.2 () {46 vars in 1084 bytes} [Mon Nov  2 22:37:05 2015] GET /server/html/error.html => generated 4794 bytes in 63 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 18/71] 192.168.0.2 () {44 vars in 1004 bytes} [Mon Nov  2 22:37:05 2015] GET /server/html/css/main-menu.css => generated 554 bytes in 179 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 0)
[pid: 493|app: 0|req: 27/72] 192.168.0.2 () {44 vars in 1032 bytes} [Mon Nov  2 22:37:05 2015] GET /server/html/css/lib/bootstrap-3.3.1.min.css => generated 113498 bytes in 207 msecs via sendfile() (HTTP/1.1 200) 8 headers in 619 bytes (0 switches on core 1)
[pid: 399|app: 0|req: 18/73] 192.168.0.2 () {44 vars in 1013 bytes} [Mon Nov  2 22:37:05 2015] GET /server/html/js/lib/bootstrap-3.3.1.min.js => generated 35601 bytes in 241 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 0)
[pid: 399|app: 0|req: 18/74] 192.168.0.2 () {44 vars in 1003 bytes} [Mon Nov  2 22:37:05 2015] GET /server/html/js/lib/underscore-min.js => generated 14241 bytes in 263 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 492|app: 0|req: 14/75] 192.168.0.2 () {44 vars in 1007 bytes} [Mon Nov  2 22:37:05 2015] GET /server/html/js/lib/jquery-2.1.1.min.js => generated 84245 bytes in 312 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 492|app: 0|req: 14/76] 192.168.0.2 () {44 vars in 1030 bytes} [Mon Nov  2 22:37:05 2015] GET /server/html/css/lib/font-awesome-4.0.3.css => generated 21658 bytes in 322 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 1)
[pid: 493|app: 0|req: 28/77] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 22:37:06 2015] GET /server/html/js/lib/URI.js => generated 27598 bytes in 224 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 399|app: 0|req: 20/78] 192.168.0.2 () {44 vars in 979 bytes} [Mon Nov  2 22:37:06 2015] GET /server/html/js/mobile.js => generated 328 bytes in 200 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 0)
[pid: 494|app: 0|req: 20/81] 192.168.0.2 () {44 vars in 1008 bytes} [Mon Nov  2 22:37:06 2015] GET /server/html/css/form-center.css => generated 608 bytes in 296 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 20/81] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 22:37:06 2015] GET /server/html/js/android.js => generated 375 bytes in 237 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 0)
[pid: 492|app: 0|req: 15/81] 192.168.0.2 () {44 vars in 1016 bytes} [Mon Nov  2 22:37:06 2015] GET /server/html/images/logo-52.png => generated 2898 bytes in 158 msecs via sendfile() (HTTP/1.1 200) 8 headers in 601 bytes (0 switches on core 0)
[pid: 399|app: 0|req: 20/82] 192.168.0.2 () {44 vars in 977 bytes} [Mon Nov  2 22:37:06 2015] GET /server/html/js/error.js => generated 215 bytes in 172 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 21/83] 192.168.0.2 () {46 vars in 1002 bytes} [Mon Nov  2 22:37:06 2015] GET /server/rest/user => generated 78 bytes in 39 msecs (HTTP/1.1 200) 3 headers in 349 bytes (1 switches on core 1)
[pid: 493|app: 0|req: 29/84] 192.168.0.2 () {46 vars in 1096 bytes} [Mon Nov  2 22:37:06 2015] GET /server/html/css/fonts/glyphicons-halflings-regular.woff => generated 23424 bytes in 63 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
Mon Nov  2 22:37:07 2015 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Nov  2 22:37:07 2015 - uwsgi\_response\_writev\_headers\_and\_body\_do(): Broken pipe [core/writer.c line 296] during GET /server/rest/settings/version (192.168.0.2)
IOError: write error
[pid: 493|app: 0|req: 29/85] 192.168.0.2 () {46 vars in 1029 bytes} [Mon Nov  2 22:37:05 2015] GET /server/rest/settings/version => generated 0 bytes in 1470 msecs (HTTP/1.1 200) 3 headers in 0 bytes (0 switches on core 0)
[pid: 493|app: 0|req: 30/86] 192.168.0.2 () {44 vars in 979 bytes} [Mon Nov  2 22:37:07 2015] GET / => generated 4777 bytes in 37 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 493|app: 0|req: 31/87] 192.168.0.2 () {44 vars in 1010 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/css/lib/bootstrap-3.3.1.min.css => generated 113498 bytes in 180 msecs via sendfile() (HTTP/1.1 200) 8 headers in 619 bytes (0 switches on core 0)
[pid: 494|app: 0|req: 22/88] 192.168.0.2 () {44 vars in 959 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/js/lib/URI.js => generated 27598 bytes in 173 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 0)
[pid: 399|app: 0|req: 22/89] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/js/lib/underscore-min.js => generated 14241 bytes in 190 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 492|app: 0|req: 17/90] 192.168.0.2 () {44 vars in 985 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/js/lib/jquery-2.1.1.min.js => generated 84245 bytes in 256 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 492|app: 0|req: 17/91] 192.168.0.2 () {44 vars in 1008 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/css/lib/font-awesome-4.0.3.css => generated 21658 bytes in 262 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 1)
[pid: 399|app: 0|req: 23/92] 192.168.0.2 () {44 vars in 991 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/js/lib/bootstrap-3.3.1.min.js => generated 35601 bytes in 312 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 0)
[pid: 493|app: 0|req: 33/93] 192.168.0.2 () {44 vars in 986 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/css/form-center.css => generated 608 bytes in 176 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 399|app: 0|req: 24/94] 192.168.0.2 () {44 vars in 959 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/js/android.js => generated 375 bytes in 178 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 24/95] 192.168.0.2 () {44 vars in 982 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/css/main-menu.css => generated 554 bytes in 212 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 24/96] 192.168.0.2 () {44 vars in 955 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/js/error.js => generated 215 bytes in 151 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 0)
[pid: 493|app: 0|req: 33/97] 192.168.0.2 () {44 vars in 957 bytes} [Mon Nov  2 22:37:07 2015] GET /server/html/js/mobile.js => generated 328 bytes in 164 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 0)
[pid: 399|app: 0|req: 24/98] 192.168.0.2 () {44 vars in 994 bytes} [Mon Nov  2 22:37:08 2015] GET /server/html/images/logo-52.png => generated 2898 bytes in 111 msecs via sendfile() (HTTP/1.1 200) 8 headers in 601 bytes (0 switches on core 0)
[pid: 492|app: 0|req: 18/99] 192.168.0.2 () {46 vars in 980 bytes} [Mon Nov  2 22:37:08 2015] GET /server/rest/user => generated 78 bytes in 39 msecs (HTTP/1.1 200) 3 headers in 349 bytes (1 switches on core 0)
[pid: 493|app: 0|req: 34/100] 192.168.0.2 () {46 vars in 1096 bytes} [Mon Nov  2 22:37:08 2015] GET /server/html/css/fonts/glyphicons-halflings-regular.woff => generated 23424 bytes in 54 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 25/101] 192.168.0.2 () {46 vars in 1000 bytes} [Mon Nov  2 22:37:08 2015] GET /server/rest/installed\_apps => generated 219 bytes in 1011 msecs (HTTP/1.1 200) 3 headers in 350 bytes (1 switches on core 1)
[pid: 493|app: 0|req: 35/103] 192.168.0.2 () {44 vars in 1004 bytes} [Mon Nov  2 22:37:09 2015] GET /server/html/images/settings-128.png => generated 3779 bytes in 87 msecs via sendfile() (HTTP/1.1 200) 8 headers in 601 bytes (0 switches on core 0)
[pid: 399|app: 0|req: 25/103] 192.168.0.2 () {44 vars in 1004 bytes} [Mon Nov  2 22:37:09 2015] GET /server/html/images/owncloud-128.png => generated 5703 bytes in 90 msecs via sendfile() (HTTP/1.1 200) 8 headers in 601 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 26/104] 192.168.0.2 () {44 vars in 998 bytes} [Mon Nov  2 22:37:09 2015] GET /server/html/images/store-128.png => generated 2514 bytes in 92 msecs via sendfile() (HTTP/1.1 200) 8 headers in 601 bytes (0 switches on core 0)
[pid: 494|app: 0|req: 27/105] 192.168.0.2 () {46 vars in 1065 bytes} [Mon Nov  2 22:37:09 2015] GET /server/html/settings.html => generated 13528 bytes in 30 msecs via sendfile() (HTTP/1.1 200) 8 headers in 618 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 28/107] 192.168.0.2 () {44 vars in 1016 bytes} [Mon Nov  2 22:37:09 2015] GET /server/html/js/lib/bootstrap-3.3.1.min.js => generated 35601 bytes in 144 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 0)
[pid: 492|app: 0|req: 19/107] 192.168.0.2 () {44 vars in 984 bytes} [Mon Nov  2 22:37:09 2015] GET /server/html/js/lib/URI.js => generated 27598 bytes in 142 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 493|app: 0|req: 37/108] 192.168.0.2 () {44 vars in 1006 bytes} [Mon Nov  2 22:37:09 2015] GET /server/html/js/lib/underscore-min.js => generated 14241 bytes in 211 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 399|app: 0|req: 27/109] 192.168.0.2 () {44 vars in 1033 bytes} [Mon Nov  2 22:37:09 2015] GET /server/html/css/lib/font-awesome-4.0.3.css => generated 21658 bytes in 225 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 0)
[pid: 399|app: 0|req: 27/110] 192.168.0.2 () {44 vars in 1010 bytes} [Mon Nov  2 22:37:09 2015] GET /server/html/js/lib/jquery-2.1.1.min.js => generated 84245 bytes in 200 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 493|app: 0|req: 37/111] 192.168.0.2 () {44 vars in 1035 bytes} [Mon Nov  2 22:37:09 2015] GET /server/html/css/lib/bootstrap-3.3.1.min.css => generated 113498 bytes in 244 msecs via sendfile() (HTTP/1.1 200) 8 headers in 619 bytes (0 switches on core 1)
[pid: 492|app: 0|req: 21/112] 192.168.0.2 () {44 vars in 1011 bytes} [Mon Nov  2 22:37:10 2015] GET /server/html/css/form-center.css => generated 608 bytes in 169 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 0)
[pid: 494|app: 0|req: 30/113] 192.168.0.2 () {44 vars in 1007 bytes} [Mon Nov  2 22:37:10 2015] GET /server/html/css/main-menu.css => generated 554 bytes in 191 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 30/114] 192.168.0.2 () {44 vars in 984 bytes} [Mon Nov  2 22:37:10 2015] GET /server/html/js/android.js => generated 375 bytes in 160 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 0)
[pid: 492|app: 0|req: 21/115] 192.168.0.2 () {44 vars in 982 bytes} [Mon Nov  2 22:37:10 2015] GET /server/html/js/mobile.js => generated 328 bytes in 145 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 1)
[pid: 493|app: 0|req: 39/116] 192.168.0.2 () {44 vars in 980 bytes} [Mon Nov  2 22:37:10 2015] GET /server/html/js/error.js => generated 215 bytes in 137 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 0)
[pid: 493|app: 0|req: 39/117] 192.168.0.2 () {44 vars in 1019 bytes} [Mon Nov  2 22:37:10 2015] GET /server/html/images/logo-52.png => generated 2898 bytes in 128 msecs via sendfile() (HTTP/1.1 200) 8 headers in 601 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 31/118] 192.168.0.2 () {46 vars in 1045 bytes} [Mon Nov  2 22:37:10 2015] GET /server/rest/settings/external\_access => generated 14 bytes in 110 msecs (HTTP/1.1 200) 3 headers in 349 bytes (1 switches on core 1)
[pid: 399|app: 0|req: 29/119] 192.168.0.2 () {46 vars in 1005 bytes} [Mon Nov  2 22:37:10 2015] GET /server/rest/user => generated 78 bytes in 114 msecs (HTTP/1.1 200) 3 headers in 349 bytes (1 switches on core 1)

 \-----------------------------------------------------------

Traceback (most recent call last):
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1475, in full\_dispatch\_request
    rv = self.dispatch\_request()
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1461, in dispatch\_request
    return self.view\_functions\[rule.endpoint]\(\*\*req.view\_args)
  File "/opt/app/platform/lib/Flask-Login-0.2.11/flask\_login.py", line 758, in decorated\_view
    return func(*args, \*\*kwargs)
  File "/opt/app/platform/lib/syncloud-platform-165/syncloud\_platform/server/rest/public.py", line 247, in disks
    return jsonify(success=True, disks=convertible.to\_dict(Hardware().available\_disks())), 200
  File "/opt/app/platform/lib/syncloud-platform-165/syncloud\_platform/tools/hardware.py", line 31, in available\_disks
    key, value = field.split('=', 1)
ValueError: need more than 1 value to unpack

\------------------------------------------------------------

[pid: 493|app: 0|req: 40/120] 192.168.0.2 () {46 vars in 1025 bytes} [Mon Nov  2 22:37:10 2015] GET /server/rest/settings/disks => generated 47 bytes in 605 msecs (HTTP/1.1 500) 3 headers in 368 bytes (1 switches on core 0)
[pid: 493|app: 0|req: 41/121] 192.168.0.2 () {46 vars in 1084 bytes} [Mon Nov  2 22:37:10 2015] GET /server/html/error.html => generated 4794 bytes in 62 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 493|app: 0|req: 42/122] 192.168.0.2 () {44 vars in 1030 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/css/lib/font-awesome-4.0.3.css => generated 21658 bytes in 190 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 0)
[pid: 399|app: 0|req: 30/123] 192.168.0.2 () {44 vars in 1032 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/css/lib/bootstrap-3.3.1.min.css => generated 113498 bytes in 176 msecs via sendfile() (HTTP/1.1 200) 8 headers in 619 bytes (0 switches on core 1)
[pid: 492|app: 0|req: 23/124] 192.168.0.2 () {44 vars in 1004 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/css/main-menu.css => generated 554 bytes in 242 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 0)
[pid: 494|app: 0|req: 33/126] 192.168.0.2 () {44 vars in 1007 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/js/lib/jquery-2.1.1.min.js => generated 84245 bytes in 274 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 0)
[pid: 492|app: 0|req: 23/126] 192.168.0.2 () {44 vars in 1008 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/css/form-center.css => generated 608 bytes in 259 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 34/127] 192.168.0.2 () {44 vars in 1013 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/js/lib/bootstrap-3.3.1.min.js => generated 35601 bytes in 313 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 399|app: 0|req: 31/128] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/js/lib/URI.js => generated 27598 bytes in 209 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 34/129] 192.168.0.2 () {44 vars in 977 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/js/error.js => generated 215 bytes in 186 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 0)
[pid: 493|app: 0|req: 44/130] 192.168.0.2 () {44 vars in 1003 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/js/lib/underscore-min.js => generated 14241 bytes in 296 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
[pid: 493|app: 0|req: 44/131] 192.168.0.2 () {44 vars in 981 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/js/android.js => generated 375 bytes in 239 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 0)
[pid: 492|app: 0|req: 25/132] 192.168.0.2 () {44 vars in 979 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/js/mobile.js => generated 328 bytes in 223 msecs via sendfile() (HTTP/1.1 200) 8 headers in 611 bytes (0 switches on core 0)
[pid: 492|app: 0|req: 25/133] 192.168.0.2 () {44 vars in 1016 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/images/logo-52.png => generated 2898 bytes in 175 msecs via sendfile() (HTTP/1.1 200) 8 headers in 601 bytes (0 switches on core 1)
[pid: 494|app: 0|req: 35/134] 192.168.0.2 () {46 vars in 1002 bytes} [Mon Nov  2 22:37:11 2015] GET /server/rest/user => generated 78 bytes in 40 msecs (HTTP/1.1 200) 3 headers in 349 bytes (1 switches on core 1)
[pid: 493|app: 0|req: 45/135] 192.168.0.2 () {46 vars in 1096 bytes} [Mon Nov  2 22:37:11 2015] GET /server/html/css/fonts/glyphicons-halflings-regular.woff => generated 23424 bytes in 59 msecs via sendfile() (HTTP/1.1 200) 8 headers in 615 bytes (0 switches on core 1)
Mon Nov  2 22:37:12 2015 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Nov  2 22:37:12 2015 - uwsgi\_response\_writev\_headers\_and\_body\_do(): Broken pipe [core/writer.c line 296] during GET /server/rest/settings/version (192.168.0.2)
IOError: write error
[pid: 399|app: 0|req: 31/136] 192.168.0.2 () {46 vars in 1029 bytes} [Mon Nov  2 22:37:10 2015] GET /server/rest/settings/version => generated 0 bytes in 1829 msecs (HTTP/1.1 200) 3 headers in 0 bytes (0 switches on core 0)

**Comment by cyberb** [comment]
What kind of filesystem do you have on that usb stick?
dmesg may give some info.
Also is running fsck on its partitions complains or not?

**Comment by cyberb** [comment]
Sorry, did not see your first comment, I will do some testing on ntfs.
Could you post the output of: 
````
lsblk -Pp -o NAME,SIZE,TYPE,MOUNTPOINT,PARTTYPE,MODEL
````
after inserting the drive?

**Comment by jpma89** [comment]
Here we go:

root@beagleboneblack:~# lsblk -Pp -o NAME,SIZE,TYPE,MOUNTPOINT,PARTTYPE,MODEL
NAME="/dev/sda" SIZE="7.9G" TYPE="disk" MOUNTPOINT="" PARTTYPE="" MODEL="                "
NAME="/dev/sda1" SIZE="7.9G" TYPE="part" MOUNTPOINT="" PARTTYPE="0x7" MODEL=""
NAME="/dev/mmcblk1boot0" SIZE="1M" TYPE="disk" MOUNTPOINT="" PARTTYPE="" MODEL=""
NAME="/dev/mmcblk1boot1" SIZE="1M" TYPE="disk" MOUNTPOINT="" PARTTYPE="" MODEL=""
NAME="/dev/mmcblk0" SIZE="3.7G" TYPE="disk" MOUNTPOINT="" PARTTYPE="" MODEL=""
NAME="/dev/mmcblk0p1" SIZE="96M" TYPE="part" MOUNTPOINT="" PARTTYPE="0xe" MODEL=""
NAME="/dev/mmcblk0p2" SIZE="2G" TYPE="part" MOUNTPOINT="/" PARTTYPE="0x83" MODEL=""
NAME="/dev/mmcblk1" SIZE="1.8G" TYPE="disk" MOUNTPOINT="" PARTTYPE="" MODEL=""
NAME="/dev/mmcblk1p1" SIZE="1.8G" TYPE="part" MOUNTPOINT="" PARTTYPE="0x83" MODEL=""

**Comment by jpma89** [comment]
dmesg when formatted as NTFS:

root@beagleboneblack:~# dmesg | grep usb

[   82.263966] musb-hdrc musb-hdrc.1.auto: otg: usb_otg_kick_fsm: invalid host/gadget device
[   82.393958] usb 1-1: new high-speed USB device number 3 using musb-hdrc
[   82.536049] usb 1-1: device v19b6 p8192 is not supported
[   82.541531] usb 1-1: New USB device found, idVendor=19b6, idProduct=8192
[   82.541545] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   82.541556] usb 1-1: Product: Mass Storage
[   82.541566] usb 1-1: Manufacturer: Generic
[   82.541576] usb 1-1: SerialNumber: C0E08D22
[   82.562662] usb-storage 1-1:1.0: USB Mass Storage device detected
[   82.570213] scsi1 : usb-storage 1-1:1.0

**Comment by jpma89** [comment]
When formatted as EXT4:

root@beagleboneblack:~# dmesg | grep usb

[ 1290.038166] musb-hdrc musb-hdrc.1.auto: otg: usb_otg_kick_fsm: invalid host/gadget device
[ 1290.158133] usb 1-1: new high-speed USB device number 5 using musb-hdrc
[ 1290.300235] usb 1-1: device v19b6 p8192 is not supported
[ 1290.305813] usb 1-1: New USB device found, idVendor=19b6, idProduct=8192
[ 1290.305828] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1290.305840] usb 1-1: Product: Mass Storage
[ 1290.305850] usb 1-1: Manufacturer: Generic
[ 1290.305860] usb 1-1: SerialNumber: C0E08D22
[ 1290.319106] usb-storage 1-1:1.0: USB Mass Storage device detected
[ 1290.325763] scsi3 : usb-storage 1-1:1.0

root@beagleboneblack:~# lsblk -Pp -o NAME,SIZE,TYPE,MOUNTPOINT,PARTTYPE,MODEL

NAME="/dev/sda" SIZE="7.9G" TYPE="disk" MOUNTPOINT="" PARTTYPE="" MODEL="                "
NAME="/dev/sda1" SIZE="7.9G" TYPE="part" MOUNTPOINT="" PARTTYPE="0x83" MODEL=""
NAME="/dev/mmcblk1boot0" SIZE="1M" TYPE="disk" MOUNTPOINT="" PARTTYPE="" MODEL=""
NAME="/dev/mmcblk1boot1" SIZE="1M" TYPE="disk" MOUNTPOINT="" PARTTYPE="" MODEL=""
NAME="/dev/mmcblk0" SIZE="3.7G" TYPE="disk" MOUNTPOINT="" PARTTYPE="" MODEL=""
NAME="/dev/mmcblk0p1" SIZE="96M" TYPE="part" MOUNTPOINT="" PARTTYPE="0xe" MODEL=""
NAME="/dev/mmcblk0p2" SIZE="2G" TYPE="part" MOUNTPOINT="/" PARTTYPE="0x83" MODEL=""
NAME="/dev/mmcblk1" SIZE="1.8G" TYPE="disk" MOUNTPOINT="" PARTTYPE="" MODEL=""
NAME="/dev/mmcblk1p1" SIZE="1.8G" TYPE="part" MOUNTPOINT="" PARTTYPE="0x83" MODEL=""

**Comment by cyberb** [comment]
Should be fixed in v169
