### ISSUE TITLE
Photoprism: filetype .heic not supported

### ISSUE THREAD

**Issue by Morgendorfferr** [syncloud/platform#712]
Newer iPhone export Photos in heic format. Photoprism should support that format (see [Photoprism Doc](https://docs.photoprism.app/developer-guide/media/) but is returning on importation the error

> import: failed to create preview image for ####.heic (file type heic not supported)

The .heic file will be imported into the originals folder but can not be displayed. To reproduce import a .heic file (and no .jpg / .png file with the same name). The error message is shown in the log and errors tab.

On this issue I found an explanation here

[https://github.com/photoprism/photoprism/discussions/4073#discussioncomment-8630228 1](https://github.com/photoprism/photoprism/discussions/4073#discussioncomment-8630228)

which seems to say that in the current version there should be no file /usr/local/bin/heif-convert since this is a depreciated script causing that issue. But I can find this file in my syncloud docker installation under /snap/photoprism/current/photoprism/...

I don’t know if this is truly the reason for my issue - but if Photoprism is not on the current version could you do an update?

**Comment by Morgendorfferr** [comment]
[Github issue](https://github.com/syncloud/platform/issues/712) created

**Comment by Morgendorfferr** [comment]
The error seems to effect all RAW Formats, not only .heic. But for RAW Photos (in my example a .orf file) the Error message is maybe more helpful:

> Error
> import: failed to create preview image for 2024/04/20240404_192156_3272BFD9.orf (+++ dirname /snap/photoprism/current/photoprism/bin/darktable-cli.sh++ cd /snap/photoprism/current/photoprism/bin++ cd ..++ pwd+ DIR=/snap/photoprism/current/photoprism++ echo /snap/photoprism/current/photoprism/lib/x86_64-linux-gnu+ LIBS=/snap/photoprism/current/photoprism/lib/x86_64-linux-gnu++ echo /snap/photoprism/current/photoprism/usr/lib/x86_64-linux-gnu+ LIBS=/snap/photoprism/current/photoprism/lib/x86_64-linux-gnu:/snap/photoprism/current/photoprism/usr/lib/x86_64-linux-gnu++ echo /snap/photoprism/current/photoprism/usr/lib+ LIBS=/snap/photoprism/current/photoprism/lib/x86_64-linux-gnu:/snap/photoprism/current/photoprism/usr/lib/x86_64-linux-gnu:/snap/photoprism/current/photoprism/usr/lib+ /snap/photoprism/current/photoprism/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 --library-path /snap/photoprism/current/photoprism/lib/x86_64-linux-gnu:/snap/photoprism/current/photoprism/usr/lib/x86_64-linux-gnu:/snap/photoprism/current/photoprism/usr/lib /snap/photoprism/current/photoprism/bin/darktable-cli /data/photoprism/photos/originals/2024/04/20240404_192156_3272BFD9.orf /data/photoprism/photos/originals/.photoprism/storage/sidecar/2024/04/20240404_192156_3272BFD9.orf.jpg --apply-custom-presets false --width 7680 --height 7680 --hq true --upscale false --core --library :memory:path lookup '/snap/photoprism/130/photoprism/usr/lib/x86_64-linux-gnu/../share/darktable' fails with: **'No such file or directory‘**)

**Comment by cyberb** [comment]
ok let me check

**Comment by cyberb** [comment]
@Morgendorfferr can you update the app and let me know if it better or not?

**Comment by Morgendorfferr** [comment]
It partially works: .orf works well, .heic still produces the error:

> import: failed to create preview image for 2024/07/20240720_195610_FE28A4FE.heic (file type heic not supported)

**Comment by cyberb** [comment]
Ok let me fix helic support

**Comment by cyberb** [comment]
Pushed new update, can you upgrade and check again please?

**Comment by Morgendorfferr** [comment]
Great! It works, many thanks!
