### ISSUE TITLE
ownCloud cannot enforce HTTPS

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#72]
When activating "Secure (HTTPS)" ownCloud complains that it is being accessed via HTTP even when connecting via HTTPS. The administration option "enforce HTTPS" cannot be clicked.

Symptoms are the same as described here: https://forum.owncloud.org/viewtopic.php?f=26&t=20575

**Comment by cyberb** [comment]
Looks like ownCloud does not detect front nginx https. We always have http between front nginx ownCloud nginx. Probably we have to tell ownCloud its real url by doing url change event the same way as it hdd change event is implemented. I will do some work for this as I need it anyway for diaspora app now.

![owncloud - mozilla firefox_005](https://cloud.githubusercontent.com/assets/885528/10897065/dcb2b1b4-81b5-11e5-9127-c2dcc78c6df8.png)

**Comment by jpma89** [comment]
I just noticed that, this warning (actually no warnings anymore) is not shown when using version 159, after setting HSTS.

![unbenannt](https://cloud.githubusercontent.com/assets/7020468/10902116/9fcdb656-81f9-11e5-831b-849d1087e600.JPG)

![unbenannt2](https://cloud.githubusercontent.com/assets/7020468/10902123/a516d548-81f9-11e5-9c1f-825d86e0e78a.JPG)
