### ISSUE TITLE
Reenabling "Secure (HTTPS)" or "Insecure (HTTP)" shows error message "No port mappers found (NatPmp, UPnP)"

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#73]
/opt/data/platform/log/uwsgi_public.log only sais:

[pid: 493|app: 0|req: 87/269] 192.168.0.2 () {46 vars in 1080 bytes} [Mon Nov  2 22:49:05 2015] GET /server/rest/settings/external_access_enable?mode=https => generated 69 bytes in 107 msecs (HTTP/1.1 200) 3 headers in 349 bytes (2 switches on core 0)
[pid: 493|app: 0|req: 88/270] 192.168.0.2 () {46 vars in 1045 bytes} [Mon Nov  2 22:49:05 2015] GET /server/rest/settings/external_access => generated 14 bytes in 27 msecs (HTTP/1.1 200) 3 headers in 349 bytes (1 switches on core 1)

**Comment by cyberb** [comment]
should be fixed in v173

**Comment by cyberb** [comment]
Still not working properly, I have broken the logic.
Working in it.
