### ISSUE TITLE
Enforce TLS v1.2

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#74]
Enforcing TLS v1.2 for security reasons using "ssl_protocols  TLSv1.2" in  /opt/app/platform/config/nginx/https.conf worked good for me.

Not sure if this will work for all user and shall be the default configuration.

**Comment by cyberb** [comment]
no problem, should be in Platform v167 within 10 minutes.

**Comment by cyberb** [comment]
Looks like we have Redirect (requests) port probing issue because of that, our python does not support TLS > v1.
https://github.com/kennethreitz/requests/issues/171

Rolling back for now, pending Redirect python upgrade.
