### ISSUE TITLE
Accessing ownCloud webinterface via HTTPS results in forwarding to https://localhost:1082

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#76]
With HTTPS enabled, accessing **https://\<my_local_ip\>/owncloud/index.php/apps/files/** or **https://\<my_device_name\>.syncloud.it/owncloud/index.php/apps/files/** results in a forwarding to **https://localhost:1082/owncloud/index.php/apps/files/**

**Comment by jpma89** [comment]
When accessing **https:///owncloud** or **https://.syncloud.it** there is no forwarding.

**Comment by cyberb** [comment]
Platfom v182 and ownCloud v56 should fix that by using domain change events and updating trusted_domains config.

While upgrading I got an error, but reinstall helped.
