### ISSUE TITLE
Activating NTFS USB pendrive not possible

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#77]
Referring to #70 :

USB drive is showing up now, but activating it is not possible and leads to error page.

**rest\_public.log**
 
2015-11-04 23:03:11,322 - hardware - INFO - /opt/app/owncloud/on\_disk\_change.py not found
2015-11-04 23:03:11,330 - systemctl - INFO - checking opt-disk-external.mount
2015-11-04 23:03:11,372 - systemctl - INFO - opt-disk-external.mount: failed
2015-11-04 23:03:12,474 - systemctl - INFO - enabling opt-disk-external.mount
2015-11-04 23:03:12,942 - systemctl - INFO - starting opt-disk-external.mount
2015-11-04 23:03:13,294 - systemctl - ERROR - ● opt-disk-external.mount - External disk
   Loaded: loaded (/lib/systemd/system/opt-disk-external.mount; enabled)
   Active: failed (Result: exit-code) since Wed 2015-11-04 23:03:13 UTC; 77ms ago
    Where: /opt/disk/external
     What: /dev/sda1
  Process: 922 ExecMount=/bin/mount -n /dev/sda1 /opt/disk/external -t fuseblk -o rw,nosuid,nodev,relatime,user\_id=0,group\_id=0,default\_permissions,allow\_other,blksize=4096,uhelper=udisks2 (code=exited, status=32)

Nov 04 23:03:13 beagleboneblack mount[922]: mount: wrong fs type, bad option, bad superblock on /dev/sda1,
Nov 04 23:03:13 beagleboneblack mount[922]: missing codepage or helper program, or other error
Nov 04 23:03:13 beagleboneblack mount[922]: In some cases useful info is found in syslog - try
Nov 04 23:03:13 beagleboneblack mount[922]: dmesg | tail or so.
Nov 04 23:03:13 beagleboneblack systemd[1]: opt-disk-external.mount mount process exited, code=exited status=32
Nov 04 23:03:13 beagleboneblack systemd[1]: Failed to mount External disk.
Nov 04 23:03:13 beagleboneblack systemd[1]: Unit opt-disk-external.mount entered failed state.

**nginx\_error.log**

2015/11/04 23:03:13 [warn] 508#0: *681 an upstream response is buffered to a temporary file /opt/app/platform/nginx/uwsgi\_temp/3/03/0000000033 while reading upstream, client: 192.168.0.2, server: localhost, request: "GET /server/html/css/lib/bootstrap-3.3.1.min.css HTTP/1.1", upstream: "uwsgi://unix:///opt/app/platform/config/uwsgi/socket/public.wsgi.sock:", host: "jpbeaglebone1.syncloud.it", referrer: "https://jpbeaglebone1.syncloud.it/server/html/error.html"
2015/11/04 23:03:13 [warn] 508#0: *695 an upstream response is buffered to a temporary file /opt/app/platform/nginx/uwsgi\_temp/4/03/0000000034 while reading upstream, client: 192.168.0.2, server: localhost, request: "GET /server/html/js/lib/jquery-2.1.1.min.js HTTP/1.1", upstream: "uwsgi://unix:///opt/app/platform/config/uwsgi/socket/public.wsgi.sock:", host: "jpbeaglebone1.syncloud.it", referrer: "https://jpbeaglebone1.syncloud.it/server/html/error.html"

**uwsgi\_public.log**

\------------------------------------------------------------

Traceback (most recent call last):
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1475, in full\_dispatch\_request
    rv = self.dispatch\_request()
  File "/opt/app/platform/lib/Flask-0.10.1/flask/app.py", line 1461, in dispatch\_request
    return self.view\_functions\[rule.endpoint](**req.view\_args)
  File "/opt/app/platform/lib/Flask-Login-0.2.11/flask\_login.py", line 758, in decorated\_view
    return func(*args, **kwargs)
  File "/opt/app/platform/lib/syncloud-platform-170/syncloud\_platform/server/rest/public.py", line 254, in disk\_activate
    return jsonify(success=True, disks=Hardware().activate\_disk(device)), 200
  File "/opt/app/platform/lib/syncloud-platform-170/syncloud\_platform/tools/hardware.py", line 89, in activate\_disk
    systemctl.add\_mount(mount\_entry)
  File "/opt/app/platform/lib/syncloud-platform-170/syncloud\_platform/systemd/systemctl.py", line 70, in add\_mount
    \_\_start(mount\_filename)
  File "/opt/app/platform/lib/syncloud-platform-170/syncloud\_platform/systemd/systemctl.py", line 107, in \_\_start
    raise e
CalledProcessError: Command 'systemctl status opt-disk-external.mount 2>&1' returned non-zero exit status 3

\------------------------------------------------------------

[pid: 393|app: 0|req: 75/216] 192.168.0.2 () {46 vars in 1112 bytes} [Wed Nov  4 23:03:10 2015] GET /server/rest/settings/disk\_activate?device=%2Fdev%2Fsda1 => generated 15 bytes in 2928 msecs (HTTP/1.1 500) 3 headers in 369 bytes (2 switches on core 1)
[pid: 496|app: 0|req: 51/217] 192.168.0.2 () {46 vars in 1114 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/error.html => generated 4794 bytes in 30 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 393|app: 0|req: 77/218] 192.168.0.2 () {44 vars in 1062 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/css/lib/bootstrap-3.3.1.min.css => generated 113498 bytes in 204 msecs via sendfile() (HTTP/1.1 200) 8 headers in 620 bytes (0 switches on core 0)
[pid: 496|app: 0|req: 52/219] 192.168.0.2 () {44 vars in 1060 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/css/lib/font-awesome-4.0.3.css => generated 21658 bytes in 167 msecs via sendfile() (HTTP/1.1 200) 8 headers in 618 bytes (0 switches on core 0)
[pid: 497|app: 0|req: 51/220] 192.168.0.2 () {44 vars in 1037 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/js/lib/jquery-2.1.1.min.js => generated 84245 bytes in 200 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 0)
[pid: 393|app: 0|req: 77/221] 192.168.0.2 () {44 vars in 1034 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/css/main-menu.css => generated 554 bytes in 203 msecs via sendfile() (HTTP/1.1 200) 8 headers in 614 bytes (0 switches on core 1)
[pid: 495|app: 0|req: 44/222] 192.168.0.2 () {44 vars in 1038 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/css/form-center.css => generated 608 bytes in 260 msecs via sendfile() (HTTP/1.1 200) 8 headers in 614 bytes (0 switches on core 1)
[pid: 495|app: 0|req: 44/223] 192.168.0.2 () {44 vars in 1043 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/js/lib/bootstrap-3.3.1.min.js => generated 35601 bytes in 260 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 0)
[pid: 497|app: 0|req: 51/224] 192.168.0.2 () {44 vars in 1033 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/js/lib/underscore-min.js => generated 14241 bytes in 183 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)
[pid: 496|app: 0|req: 54/225] 192.168.0.2 () {44 vars in 1009 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/js/mobile.js => generated 328 bytes in 150 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 0)
[pid: 496|app: 0|req: 54/226] 192.168.0.2 () {44 vars in 1011 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/js/lib/URI.js => generated 27598 bytes in 222 msecs via sendfile() (HTTP/1.1 200) 8 headers in 617 bytes (0 switches on core 1)
[pid: 495|app: 0|req: 45/227] 192.168.0.2 () {44 vars in 1046 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/images/logo-52.png => generated 2898 bytes in 127 msecs via sendfile() (HTTP/1.1 200) 8 headers in 602 bytes (0 switches on core 1)
[pid: 393|app: 0|req: 79/228] 192.168.0.2 () {44 vars in 1011 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/js/android.js => generated 375 bytes in 181 msecs via sendfile() (HTTP/1.1 200) 8 headers in 613 bytes (0 switches on core 0)
[pid: 393|app: 0|req: 79/229] 192.168.0.2 () {44 vars in 1007 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/js/error.js => generated 215 bytes in 152 msecs via sendfile() (HTTP/1.1 200) 8 headers in 612 bytes (0 switches on core 1)
[pid: 393|app: 0|req: 80/230] 192.168.0.2 () {46 vars in 1032 bytes} [Wed Nov  4 23:03:13 2015] GET /server/rest/user => generated 78 bytes in 27 msecs (HTTP/1.1 200) 3 headers in 350 bytes (1 switches on core 0)
[pid: 393|app: 0|req: 81/231] 192.168.0.2 () {46 vars in 1140 bytes} [Wed Nov  4 23:03:13 2015] GET /server/html/css/fonts/glyphicons-halflings-regular.woff => generated 23424 bytes in 30 msecs via sendfile() (HTTP/1.1 200) 8 headers in 616 bytes (0 switches on core 1)

**Comment by jpma89** [comment]
When the pendrive is EXT4 formatted, the error page does not occur.

**Comment by cyberb** [comment]
should be fixed in v175
