### ISSUE TITLE
ownCloud data directory is readable for other users 

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#78]
When running lastest version 185 with an NTFS harddrive, ownCloud says:

Data directory (/data/owncloud) is readable for other users
Please change the permissions to 0770 so that the directory cannot be listed by other users.

**Comment by jpma89** [comment]
The issue appeared after activating an 1.8T USB drive and then rebooting.

**Comment by cyberb** [comment]
This should be fixed in platform v188/ownCloud v61.

**Comment by jpma89** [comment]
Works for me, but already worked with v188/ownCloud v56.
