### ISSUE TITLE
ownCloud configuration checkboxes are not displayed

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#79]
Running v188/owncloud v61:

Checkboxes in ownCloud config are not being displayed. Mouse pointer still changes to hand symbol when hovering over the boxes.

Tested with recent Chrome + Firefox.

![unbenannt](https://cloud.githubusercontent.com/assets/7020468/11195808/3b5bf852-8cb4-11e5-8415-926c1baff4e6.jpg)

**Comment by cyberb** [comment]
Good catch, fixed by https://github.com/syncloud/owncloud/commit/deb6c6fd7890324cced007391e8fcb8200c5ae4f
Will be available in ownCloud v62, in 10 minutes

**Comment by jpma89** [comment]
Fixed after upgrading to ownCloud v62 :+1:
