### ISSUE TITLE
Feature request: Provide possibility to change root PW / unprivileged user PW during activation

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#81]

**Comment by cyberb** [comment]
I think we can change root password from UI.

But we do not have any unprivileged users to change password for. We create non login user per app to isolate them and get less complains from services about running them under root.

I think if you need additional linux users on the device you can always create them using shell and root account.

**Comment by cyberb** [comment]
We can even make ssh authenticate against ldap so it will always be the only admin (activation) account you have to remember.

But even if we do that it will be not completely locked as local network activation is still open.

So if we want to lock device completley we need to disable open reactivation and add some password reminder by email.

**Comment by jpma89** [comment]
For me personally it would be fine to just have the possibility to change root PW from UI.

**Comment by cyberb** [comment]
What about syncing root password with device password user enters on activation?
It is easy to remember one password instead of two.

**Comment by jpma89** [comment]
Even better than having two passwords.

**Comment by cyberb** [comment]
This should be fixed in v219.
You have to reactivate the device to set new root password, either with mobile app or directly by going to local address at home network (192.168.*.*) and clicking on Reactivate menu item.
Reactivation is not possible outside of home network for example using device public domain name as a security measure.

**Comment by jpma89** [comment]
Works fine for me with the latest platform version. Thanks a lot :+1:
