### ISSUE TITLE
Support usb stick as external storage

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#88]
It could be supported the same way as external HDD. Need to be tested. We will need to publish requirements for formatting / filesystem on usb stick.

**Comment by jpma89** [comment]
I already tested this with a cheap 8GB USB stick some weeks ago. If I remember correctly it used to work just like a HDD with NTFS and ext4 with lazy init.

**Comment by vsapronov** [comment]
Nice! Thanks for info! The user asked for it. I'll test it quickly too and respond to the user.
