### ISSUE TITLE
Web admin  shows HTTP: enabled be default

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#91]
By default we do not enable external access at all.
Both HTTP/HTTPS should show disabled.

**Comment by cyberb** [comment]
It is a but confusing, I think we need http/https as two state button. Right now it is three state.
Also I would add explicit on/off external access button.
We have that on config already.

Right now UI shows http because even local ip DNS needs protocol. It kind of says: http local ip access :)

**Comment by vsapronov** [comment]
So there should be 2 toggles: External access ON/OFF. Secure protocol
ON/OFF. Right?

On Fri, Dec 25, 2015 at 3:13 PM, Boris Rybalkin <notifications@github.com>
wrote:

> It is a but confusing, I think we need http/https as two state button.
> Right now it is three state.
> Also I would add explicit on/off external access button.
> We have that on config already.
>
> Right now UI shows http because even local ip DNS needs protocol. It kind
> of says: http local ip access :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/91#issuecomment-167260897>.
>



-- 

Vladimir Sapronov

**Comment by cyberb** [comment]
Yes.
