### ISSUE TITLE
Don't allow upper case domain in iOS

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#96]

**Comment by cyberb** [comment]
Should we also add toLower call inside activate rest call?

**Comment by vsapronov** [comment]
Yes, we need to fix it on both sides

On Sunday, December 27, 2015, Boris Rybalkin <notifications@github.com>
wrote:

> Should we also add toLower call inside activate rest call?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncloud/platform/issues/96#issuecomment-167402868>.
>


-- 

Vladimir Sapronov
